sprite $active_directory [43x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF000000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF0049400FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF001AAA100FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF006AAA700FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF002AAAAA200FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF008AAAAA8000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF003AAAAAAA400FFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0009AAAAAAA9000FFFFFFFFFFFFFF
FFFFFFFFFFFFFF004AAAAAAAAA500FFFFFFFFFFFFFF
FFFFFFFFFFFFFF00AAAAAAAAAAA000FFFFFFFFFFFFF
FFFFFFFFFFFFF006AAAA757AAAA600FFFFFFFFFFFFF
FFFFFFFFFFFF001AAAA30003AAAA100FFFFFFFFFFFF
FFFFFFFFFFFF007AAA6000006AAA700FFFFFFFFFFFF
FFFFFFFFFFF002AAAA3000003AAAA200FFFFFFFFFFF
FFFFFFFFFF0008AAAA4000004AAAA800FFFFFFFFFFF
FFFFFFFFFF004AAAAA9000008AAAAA400FFFFFFFFFF
FFFFFFFFF0009AAAAAA72017AAAAAA9000FFFFFFFFF
FFFFFFFFF005AAAAAA77AAA86AAAAAA500FFFFFFFFF
FFFFFFFF000AAAAAAA21AAA20AAAAAAA000FFFFFFFF
FFFFFFFF006AAAAAA705AAA705AAAAAA700FFFFFFFF
FFFFFFF002AAAAAAA11AAAAA21AAAAAAA100FFFFFFF
FFFFFFF007AAAAAA706AAAAA705AAAAAA800FFFFFFF
FFFFFF003AAAAAAA00AAAAAAA20AAAAAAA200FFFFFF
FFFFF0008AAAAAA707AAAAAAA806AAAAAA900FFFFFF
FFFFF004AAAAAAAA6AAAAAAAAA6AAAAAAAA400FFFFF
FFFF0009AAAA4103AAAAAAAAAAA3014AAAA9000FFFF
FFFF006AAAA400001AAAAAAAAA200003AAAA600FFFF
FFF000AAAAA000000975555578000000AAAAA000FFF
FFF007AAAAA000000930000048000000AAAAA800FFF
FF001AAAAAA100000AA99999AA000001AAAAAA100FF
FF008AAAAAA910006AAAAAAAAA700018AAAAAA8000F
F003AAAAAAAAA659AAAAAAAAAAA966AAAAAAAAA300F
F009AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA900F
F03AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA300
F02AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA200
F00244444444444444444444444444444444444200F
F00000000000000000000000000000000000000000F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ACTIVE_DIRECTORY(_alias) ENTITY(rectangle,black,active_directory,_alias,OFF ACTIVE_DIRECTORY)
!define OFF_ACTIVE_DIRECTORY(_alias,_label) ENTITY(rectangle,black,active_directory,_label,_alias,OFF ACTIVE_DIRECTORY)
!define OFF_ACTIVE_DIRECTORY(_alias,_label,_shape) ENTITY(_shape,black,active_directory,_label,_alias,OFF ACTIVE_DIRECTORY)
!define OFF_ACTIVE_DIRECTORY(_alias,_label,_shape,_color) ENTITY(_shape,_color,active_directory,_label,_alias,OFF ACTIVE_DIRECTORY)
skinparam folderBackgroundColor<<OFF ACTIVE_DIRECTORY>> White