sprite $address_book_policies [42x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF000000000000000000000000000FFFFF
FFFFFFFF000011111111111111111111111000FFFF
FFFFFFFF0029AAAAAAAAAAAAAAAAAAAAA700000FFF
FFFFFFF003AAAAAAAAAAAAAAAAAAAAAA60277300FF
FFFFFFF009AAAAAAAAAAAAAAAAAAAAAA03AAA900FF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAA907AAAA00FF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAA907AAA800FF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAA907AAA200FF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAA907AA400FFF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAA9033000FFFF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAA900000FFFFF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAA900FFFFFFFF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAA900FFFFFFFF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAA900FFFFFFFF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAA900FFFFFFFF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAA900FFFFFFFF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAA900FFFFFFFF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAA900FFFFFFFF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAA900FFFFFFFF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAA900FFFFFFFF
FFFFFFF02AAAAAAAAAAAA1000000052000000000FF
FFFFFFF02AAAAAAAAAAA10455555200355555200FF
FFFFFFF02AAAAAAAAAAA04855555968855555A100F
FFFFFFF02AAAAAAAAAA1085000000A700000096100
FFFF00001444444444405A500A8007400A6009A800
FFF000011111111111105A50098006300A60094800
FF0005AAAAAAAAAAAAA05A50567506306683094800
FF007AAAAAAAAAAAAAA05A50AAA90630AAA7095800
FF01AAAAAAAAAAAAAAA05A50444306304443094800
F003AAAAAAAAAAAAAAA05A50777606317775094800
F002AAAAAAAAAAAAAAA05A50333306303332095800
FF00AAAAAAAAAAAAAAA05A50777606317775094800
FF004AAAAAAAAAAAAAA05A50333206303332094800
FFF002688888888888805A50000006300000096800
FFFF00000000000000005A988888686788888AA800
FFFFF0000000000000003AAAAAAAAAAAAAAAAAA600
FFFFFFFFFFFFFFFFFFF00222222258832222222000
FFFFFFFFFFFFFFFFFFF0000000000000000000000F
FFFFFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ADDRESS_BOOK_POLICIES(_alias) ENTITY(rectangle,black,address_book_policies,_alias,OFF ADDRESS_BOOK_POLICIES)
!define OFF_ADDRESS_BOOK_POLICIES(_alias,_label) ENTITY(rectangle,black,address_book_policies,_label,_alias,OFF ADDRESS_BOOK_POLICIES)
!define OFF_ADDRESS_BOOK_POLICIES(_alias,_label,_shape) ENTITY(_shape,black,address_book_policies,_label,_alias,OFF ADDRESS_BOOK_POLICIES)
!define OFF_ADDRESS_BOOK_POLICIES(_alias,_label,_shape,_color) ENTITY(_shape,_color,address_book_policies,_label,_alias,OFF ADDRESS_BOOK_POLICIES)
skinparam folderBackgroundColor<<OFF ADDRESS_BOOK_POLICIES>> White