sprite $certificate [48x41/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF000000000000000000000000000FFFFFFFF
FFFFFFFFFFFFF000000000000000000000000000FFFFFFFF
FFFFFFFFFFF000A33AAAAAAAAAAAAAAAAAAAAA30FFFFFFFF
FFFFFFFFFF000AA33AAAAAAAAAAAAAAAAAAAAA30FFFFFFFF
FFFFFFFFF000AAA33AAAAAAAAAAAAAAAAAAAAA30FFFFFFFF
FFFFFFFF0009AAA33AAAAAAAAAAAAAAAAAAAAA30FFFFFFFF
FFFFFFF0009AAAA33AAAAAAAAAAAAAAAAAAAAA30FFFFFFFF
FFFFFFF00AAAAAA33AAAAAAAAAAAAAAAAAAAAA30FFFFFFFF
FFFFFF009AAAAAA33AAAAAAAAAAAAA6000003930FFFFFFFF
FFFFFF00444444413AAAAAAAAAAA700367741000FFFFFFFF
FFFFFF00333333336AAAAAAAAAA603AA978AA6000FFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAA804A7100003A800FFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAA02A5029AA601A700FFFFFF
FFFFFF00AAAAAAAAAAAAAAAAA90890590006A03A10FFFFFF
FFFFFF00AAAAAAAAAAAAAAAAA41A20A00000570A50FFFFFF
FFFFFF00AAAAAAAAAAAAAAAAA03A073000000A0790FFFFFF
FFFFFF00AAAAAAAAAAAAAAAAA03A090000000A06A0FFFFFF
FFFFFF00AAAAAAAAAAAAAAAAA13A063000000A0780FFFFFF
FFFFFF00AAAAAAAAAAAAAAAAA41A20A00000660A50FFFFFF
FFFFFF00AAAAAAAAAAAAAAAAA908904A1006903A10FFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAA12A601898502A600FFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAA903A8100005A800FFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAA607AA989AAA200FFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAA40AAAAAAAAAA00FFFFFFF
FFFFFF00666666666666666666606AAAA6AAAAA700FFFFFF
FFFFFF0000000000000000000000AAAAA37AAAAA200FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF006AAAAA01AAAAAA00FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF01AAAAA8009AAAAA700FFFF
FFFFFFFFFFFFFFFFFFFFFFFF007AAAAA5006AAAAAA200FFF
FFFFFFFFFFFFFFFFFFFFFFFF01AAAAAA1000AA80159000FF
FFFFFFFFFFFFFFFFFFFFFFF0031004AA0000AA00000000FF
FFFFFFFFFFFFFFFFFFFFFFFF0000005800F03200FFF00FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0010FF0000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000FF000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_CERTIFICATE(_alias) ENTITY(rectangle,black,certificate,_alias,OFF CERTIFICATE)
!define OFF_CERTIFICATE(_alias,_label) ENTITY(rectangle,black,certificate,_label,_alias,OFF CERTIFICATE)
!define OFF_CERTIFICATE(_alias,_label,_shape) ENTITY(_shape,black,certificate,_label,_alias,OFF CERTIFICATE)
!define OFF_CERTIFICATE(_alias,_label,_shape,_color) ENTITY(_shape,_color,certificate,_label,_alias,OFF CERTIFICATE)
skinparam folderBackgroundColor<<OFF CERTIFICATE>> White