sprite $credentials [47x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF0000000FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00000210000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0007AAAAA9000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF000AAAAAAAAA300FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF000AAAAAAAAAAA200FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF007AAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF01AAAAAAAAAAAAA400FFFFFFFFFFFFFFFF
FFFFFFFFFFFF004AAAAAAAAAAAAA800FFFFFFFFFFFFFFFF
FFFFFFFFFFFF008AAAAAAAAAAAAAA00FFFFFFFFFFFFFFFF
FFFFFFFFFFFF009AAAAAAAAAAAAAA10FFFFFFFFFFFFFFFF
FFFFFFFFFFFF009AAAAAAAAAAAAAA10FFFFFFFFFFFFFFFF
FFFFFFFFFFFF007AAAAAAAAAAAAAA00FFFFFFFFFFFFFFFF
FFFFFFFFFFFF004AAAAAAAAAAAAA800FFFFFFFFFFFFFFFF
FFFFFFFFFFFFF01AAAAAAAAAAAAA300FFFFFFFFFFFFFFFF
FFFFFFFFFFFFF006AAAAAAAAAAA900FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF009AAAAAAAAAA100FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0009AAAAAAAA200FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF0000005AAAAA8000000FFFFFFFFFFFFFFFF
FFFFFFFFFF00000000000000000000000FFFFFFFFFFFFFF
FFFFFFFFF0001AA8000000000002AA5000FFFFFFFFFFFFF
FFFFFFFF0009AAAAA2000000008AAAAA20000FFFFFFFFFF
FFFFFFF002AAAAAAAAA84236AAAAAA5000000000FFFFFFF
FFFFFF001AAAAAAAAAAAAAAAAAAA70017AAA940000FFFFF
FFFFFF008AAAAAAAAAAAAAAAAAA501AAAAAAAAA6000FFFF
FFFFFF00AAAAAAAAAAAAAAAAAA504AAAAAAAAAAAA000FFF
FFFFF001AAAAAAAAAAAAAAAAA803AAAAAAAAAAAAAA00FFF
FFFFF003AAAAAAAAAAAAAAAAA20AAAAAAAAAAA52AA600FF
FFFFF007AAAAAAAAAAAAAAAA806AAAAAAAAAA9005AA00FF
FFFFF009AAAAAAAAAAAAAAAA50AAAAAAAAAAA001AAA500F
FFFFF00AAAAAAAAAAAAAAAAA22AAAAAAAAAA200AAAAA00F
FFFFF00AAAAAAAAAAAAAAAAA14AAAA0AAAA5009AAAAA00F
FFFFF00AAAAAAAAAAAAAAAAA04AAA100AA8006AAAAAA00F
FFFF001AAAAAAAAAAAAAAAAA14AAA9001A002AAAAAAA00F
FFFF001AAAAAAAAAAAAAAAAA31AAAA800000AAAAAAA900F
FFFF003AAAAAAAAAAAAAAAAA509AAAA60009AAAAAAA300F
FFFF00000000000000000000005AAAAA507AAAAAAAA00FF
FFFF000000000000000000000009AAAAA8AAAAAAAA300FF
FFFFFFFFFFFFFFFFFFFFFFFFF001AAAAAAAAAAAAA700FFF
FFFFFFFFFFFFFFFFFFFFFFFFFF001AAAAAAAAAAA6000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF0006AAAAAAAA1000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF0000167740000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_CREDENTIALS(_alias) ENTITY(rectangle,black,credentials,_alias,OFF CREDENTIALS)
!define OFF_CREDENTIALS(_alias,_label) ENTITY(rectangle,black,credentials,_label,_alias,OFF CREDENTIALS)
!define OFF_CREDENTIALS(_alias,_label,_shape) ENTITY(_shape,black,credentials,_label,_alias,OFF CREDENTIALS)
!define OFF_CREDENTIALS(_alias,_label,_shape,_color) ENTITY(_shape,_color,credentials,_label,_alias,OFF CREDENTIALS)
skinparam folderBackgroundColor<<OFF CREDENTIALS>> White