sprite $domain [43x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF000000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF001000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF004AA000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF001AAA600FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF006AAAA200FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF002AAAAA700FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF008AAAAAA300FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF003AAAAAAA800FFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0009AAAAAAAA500FFFFFFFFFFFFFF
FFFFFFFFFFFFFF005AAAAAAAAA9000FFFFFFFFFFFFF
FFFFFFFFFFFFF000AAAAAAAAAAA600FFFFFFFFFFFFF
FFFFFFFFFFFFF007AAAAAAAAAAAA100FFFFFFFFFFFF
FFFFFFFFFFFF001AAAAAAAAAAAAA8000FFFFFFFFFFF
FFFFFFFFFFFF009AAAAAAAAAAAAAA100FFFFFFFFFFF
FFFFFFFFFFF002AAAAAAAAAAAAAAAA000FFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAAAAAAAAA300FFFFFFFFFF
FFFFFFFFFF004AAAAAAAAAAAAAAAAAA000FFFFFFFFF
FFFFFFFFFF01AAAAAAAAAAAAAAAAAAA500FFFFFFFFF
FFFFFFFFF006AAAAAAAAAAAAAAAAAAAA100FFFFFFFF
FFFFFFFF001AAAAAAAAAAAAAAAAAAAAA700FFFFFFFF
FFFFFFFF007AAAAAAAAAAAAAAAAAAAAAA200FFFFFFF
FFFFFFF002AAAAAAAAAAAAAAAAAAAAAAA8000FFFFFF
FFFFFFF009AAAAAAAAAAAAAAAAAAAAAAAA400FFFFFF
FFFFFF004AAAAAAAAAAAAAAAAAAAAAAAAA9000FFFFF
FFFFF000AAAAAAAAAAAAAAAAAAAAAAAAAAA600FFFFF
FFFFF006AAAAAAAAAAAAAAAAAAAAAAAAAAAA000FFFF
FFFF001AAAAAAAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFF007AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA100FFF
FFF002AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA900FFF
FFF009AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA300FF
FF004AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA900FF
FF009AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA500F
F005AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00F
F008AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA30F
F00399999999999999999999999999999999999700F
FF0000000000000000000000000000000000000000F
FF000000000000000000000000000000000000000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DOMAIN(_alias) ENTITY(rectangle,black,domain,_alias,OFF DOMAIN)
!define OFF_DOMAIN(_alias,_label) ENTITY(rectangle,black,domain,_label,_alias,OFF DOMAIN)
!define OFF_DOMAIN(_alias,_label,_shape) ENTITY(_shape,black,domain,_label,_alias,OFF DOMAIN)
!define OFF_DOMAIN(_alias,_label,_shape,_color) ENTITY(_shape,_color,domain,_label,_alias,OFF DOMAIN)
skinparam folderBackgroundColor<<OFF DOMAIN>> White