sprite $irm_protected_message [48x41/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF000000000000000000000000000000000FFFFFFFFF
FFFFFF000000000000000000000000000000000FFFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FFFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FFFFFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFFFFFFFF
FFFFFF0002AAAAAAAAAAAAAAAAAAAAAAAAA4000FFFFFFFFF
FFFFFF008009AAAAAAAAAAAAAAAAAAAAAA10610FFFFFFFFF
FFFFFF00AA106AAAAAAAAAAAAAAAAAAA800AA10FFFFFFFFF
FFFFFF00AAA502AAAAAAAAAAAAAAAAA303AAA10FFFFFFFFF
FFFFFF00AAAA8008AAAAAAAAAAAAA9106AAAA10FFFFFFFFF
FFFFFF00AAAAAA204AAAAAAAAAAA6019AAAAA10FFFFFFFFF
FFFFFF00AAAAAAA601AAAAAAAAA205AAAAAAA10FFFFFFFFF
FFFFFF00AAAAAAAAA007AAAAA9008AAAAAAAA10FFFFFFFFF
FFFFFF00AAAAAAAAAA203AAA501AAAAAAAAAA10FFFFFFFFF
FFFFFF00AAAAAAAAAAA6001004AAAA710000100FFFFFFFFF
FFFFFF00AAAAAAAAAAAA94349AAA6002577630000FFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAA3049AAAAAAA6000FFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAA307AAAAAAAAAA9000FFFFF
FFFFFF00AAAAAAAAAAAAAAAAA707AAAAAAAAAAAAA00FFFFF
FFFFFF00AAAAAAAAAAAAAAAAA03AAAAAAAAAAAAAA800FFFF
FFFFFF00AAAAAAAAAAAAAAAA70AAAAAAAAAAAAAAAA00FFFF
FFFFFF00AAAAAAAAAAAAAAAA01AAAAAAAAAAAAAAAA600FFF
FFFFFF00AAAAAAAAAAAAAAAA04AAA8888888888AAA800FFF
FFFFFF00AAAAAAAAAAAAAAAA06AAA1000000000AAA900FFF
FFFFFF00666666666666666606AAA1000000000AAA900FFF
FFFFFF00000000000000000003AAAAAAAAAAAAAAAA800FFF
FFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAA40FFFF
FFFFFFFFFFFFFFFFFFFFFFFF009AAAAAAAAAAAAAAA00FFFF
FFFFFFFFFFFFFFFFFFFFFFFFF01AAAAAAAAAAAAAA500FFFF
FFFFFFFFFFFFFFFFFFFFFFFFF004AAAAAAAAAAAA800FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF004AAAAAAAAAA700FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF0008AAAAAA9100FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF000024430000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_IRM_PROTECTED_MESSAGE(_alias) ENTITY(rectangle,black,irm_protected_message,_alias,OFF IRM_PROTECTED_MESSAGE)
!define OFF_IRM_PROTECTED_MESSAGE(_alias,_label) ENTITY(rectangle,black,irm_protected_message,_label,_alias,OFF IRM_PROTECTED_MESSAGE)
!define OFF_IRM_PROTECTED_MESSAGE(_alias,_label,_shape) ENTITY(_shape,black,irm_protected_message,_label,_alias,OFF IRM_PROTECTED_MESSAGE)
!define OFF_IRM_PROTECTED_MESSAGE(_alias,_label,_shape,_color) ENTITY(_shape,_color,irm_protected_message,_label,_alias,OFF IRM_PROTECTED_MESSAGE)
skinparam folderBackgroundColor<<OFF IRM_PROTECTED_MESSAGE>> White