sprite $key_permissions_ghosted [27x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF00000000FFFFFFFFF
FFFFFFFF000001100000FFFFFFF
FFFFFFF00023463551000FFFFFF
FFFFFF0005346355354000FFFFF
FFFFFF0054463453553500FFFFF
FFFFF003446332245355200FFFF
FFFFF004463400003553500FFFF
FFFF00246343000045364200FFF
FFFF00364462000043653400FFF
FFFF00544634000135536400FFF
FFFF00346346333355365300FFF
FFFF00363463453553653400FFF
FFFF00344634535535536300FFF
FFFFF004634635535536400FFFF
FFFFF004346355355364300FFFF
FFFFF00046355355364300FFFFF
FFFFFF0003563553553000FFFFF
FFFFFFF00043553553000FFFFFF
FFFFFFFF000553553000FFFFFFF
FFFFFFFFF0063553600FFFFFFFF
FFFFFFFFF0035535500FFFFFFFF
FFFFFFFFF0055355300FFFFFFFF
FFFFFFFFF005355300FFFFFFFFF
FFFFFFFFF003553000FFFFFFFFF
FFFFFFFFF005535200FFFFFFFFF
FFFFFFFFF0053553100FFFFFFFF
FFFFFFFFF0035535410FFFFFFFF
FFFFFFFFF0055355300FFFFFFFF
FFFFFFFFF0053553100FFFFFFFF
FFFFFFFFF003553200FFFFFFFFF
FFFFFFFFF005535300FFFFFFFFF
FFFFFFFFF0053553300FFFFFFFF
FFFFFFFFF00355355000FFFFFFF
FFFFFFFFF0025355200FFFFFFFF
FFFFFFFFFF00255200FFFFFFFFF
FFFFFFFFFF00032000FFFFFFFFF
FFFFFFFFFFF000000FFFFFFFFFF
FFFFFFFFFFFF0000FFFFFFFFFFF
FFFFFFFFFFFFF00FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_KEY_PERMISSIONS_GHOSTED(_alias) ENTITY(rectangle,black,key_permissions_ghosted,_alias,OFF KEY_PERMISSIONS_GHOSTED)
!define OFF_KEY_PERMISSIONS_GHOSTED(_alias,_label) ENTITY(rectangle,black,key_permissions_ghosted,_label,_alias,OFF KEY_PERMISSIONS_GHOSTED)
!define OFF_KEY_PERMISSIONS_GHOSTED(_alias,_label,_shape) ENTITY(_shape,black,key_permissions_ghosted,_label,_alias,OFF KEY_PERMISSIONS_GHOSTED)
!define OFF_KEY_PERMISSIONS_GHOSTED(_alias,_label,_shape,_color) ENTITY(_shape,_color,key_permissions_ghosted,_label,_alias,OFF KEY_PERMISSIONS_GHOSTED)
skinparam folderBackgroundColor<<OFF KEY_PERMISSIONS_GHOSTED>> White