sprite $key_permissions_blue [29x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF000000000FFFFFFFFFF
FFFFFFFFF000012110000FFFFFFFF
FFFFFFFF00169999972000FFFFFFF
FFFFFFF0039999999995000FFFFFF
FFFFFF00399999999999500FFFFFF
FFFFFF019999963599999200FFFFF
FFFFF0059999500029999800FFFFF
FFFFF0099999100009999920FFFFF
FFFFF02999991000099999400FFFF
FFFFF03999996000499999600FFFF
FFFFF03999999757999999600FFFF
FFFFF02999999999999999500FFFF
FFFFF0099999999999999920FFFFF
FFFFF0069999999999999800FFFFF
FFFFF0019999999999999300FFFFF
FFFFFF00499999999999600FFFFFF
FFFFFFF0059999999996000FFFFFF
FFFFFFF000299999993000FFFFFFF
FFFFFFFF0006999998000FFFFFFFF
FFFFFFFFFF0699999800FFFFFFFFF
FFFFFFFFFF0699999800FFFFFFFFF
FFFFFFFFFF0699999600FFFFFFFFF
FFFFFFFFFF069999700FFFFFFFFFF
FFFFFFFFFF06999800FFFFFFFFFFF
FFFFFFFFFF069999000FFFFFFFFFF
FFFFFFFFFF0699999000FFFFFFFFF
FFFFFFFFFF0699999900FFFFFFFFF
FFFFFFFFFF0699999800FFFFFFFFF
FFFFFFFFFF0699998000FFFFFFFFF
FFFFFFFFFF069999000FFFFFFFFFF
FFFFFFFFFF069999300FFFFFFFFFF
FFFFFFFFFF0699999200FFFFFFFFF
FFFFFFFFFF05999999000FFFFFFFF
FFFFFFFFFF0079999200FFFFFFFFF
FFFFFFFFFF000899200FFFFFFFFFF
FFFFFFFFFFF0009200FFFFFFFFFFF
FFFFFFFFFFFF00000FFFFFFFFFFFF
FFFFFFFFFFFFF000FFFFFFFFFFFFF
FFFFFFFFFFFFFF0FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_KEY_PERMISSIONS_BLUE(_alias) ENTITY(rectangle,black,key_permissions_blue,_alias,OFF KEY_PERMISSIONS_BLUE)
!define OFF_KEY_PERMISSIONS_BLUE(_alias,_label) ENTITY(rectangle,black,key_permissions_blue,_label,_alias,OFF KEY_PERMISSIONS_BLUE)
!define OFF_KEY_PERMISSIONS_BLUE(_alias,_label,_shape) ENTITY(_shape,black,key_permissions_blue,_label,_alias,OFF KEY_PERMISSIONS_BLUE)
!define OFF_KEY_PERMISSIONS_BLUE(_alias,_label,_shape,_color) ENTITY(_shape,_color,key_permissions_blue,_label,_alias,OFF KEY_PERMISSIONS_BLUE)
skinparam folderBackgroundColor<<OFF KEY_PERMISSIONS_BLUE>> White