sprite $key_permissions [28x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF000000000FFFFFFFFF
FFFFFFFFF00012210000FFFFFFFF
FFFFFFF00028AAAAA6100FFFFFFF
FFFFFFF005AAAAAAAAA200FFFFFF
FFFFFF006AAAAAAAAAAA200FFFFF
FFFFF002AAAAA647AAAAA00FFFFF
FFFFF009AAAA20007AAAA500FFFF
FFFFF01AAAA900002AAAA900FFFF
FFFFF04AAAAA00002AAAAA00FFFF
FFFF006AAAAA40008AAAAA20FFFF
FFFF006AAAAAA769AAAAAA20FFFF
FFFFF05AAAAAAAAAAAAAAA10FFFF
FFFFF02AAAAAAAAAAAAAAA00FFFF
FFFFF009AAAAAAAAAAAAA600FFFF
FFFFF003AAAAAAAAAAAAA00FFFFF
FFFFFF008AAAAAAAAAAA200FFFFF
FFFFFF0008AAAAAAAAA200FFFFFF
FFFFFFF0004AAAAAAA100FFFFFFF
FFFFFFFF000AAAAAA300FFFFFFFF
FFFFFFFFFF0AAAAAA30FFFFFFFFF
FFFFFFFFFF0AAAAAA30FFFFFFFFF
FFFFFFFFFF0AAAAAA10FFFFFFFFF
FFFFFFFFFF0AAAAA300FFFFFFFFF
FFFFFFFFFF0AAAA400FFFFFFFFFF
FFFFFFFFFF0AAAA8000FFFFFFFFF
FFFFFFFFFF0AAAAA700FFFFFFFFF
FFFFFFFFFF0AAAAAA600FFFFFFFF
FFFFFFFFFF0AAAAAA600FFFFFFFF
FFFFFFFFFF0AAAAA700FFFFFFFFF
FFFFFFFFFF0AAAA8000FFFFFFFFF
FFFFFFFFFF0AAAAA100FFFFFFFFF
FFFFFFFFFF0AAAAA9000FFFFFFFF
FFFFFFFFFF09AAAAA700FFFFFFFF
FFFFFFFFFF00AAAA9000FFFFFFFF
FFFFFFFFFF001AA9000FFFFFFFFF
FFFFFFFFFFF0029100FFFFFFFFFF
FFFFFFFFFFFF00000FFFFFFFFFFF
FFFFFFFFFFFFF000FFFFFFFFFFFF
FFFFFFFFFFFFFF0FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_KEY_PERMISSIONS(_alias) ENTITY(rectangle,black,key_permissions,_alias,OFF KEY_PERMISSIONS)
!define OFF_KEY_PERMISSIONS(_alias,_label) ENTITY(rectangle,black,key_permissions,_label,_alias,OFF KEY_PERMISSIONS)
!define OFF_KEY_PERMISSIONS(_alias,_label,_shape) ENTITY(_shape,black,key_permissions,_label,_alias,OFF KEY_PERMISSIONS)
!define OFF_KEY_PERMISSIONS(_alias,_label,_shape,_color) ENTITY(_shape,_color,key_permissions,_label,_alias,OFF KEY_PERMISSIONS)
skinparam folderBackgroundColor<<OFF KEY_PERMISSIONS>> White