sprite $key_permissions_green [28x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF000000000FFFFFFFFF
FFFFFFFFF00001110000FFFFFFFF
FFFFFFFF0003666664100FFFFFFF
FFFFFFF001666666666200FFFFFF
FFFFFF00166666666666300FFFFF
FFFFFF006666642366666100FFFF
FFFFF0036666300026666500FFFF
FFFFF0056666000005666600FFFF
FFFFF0066666000006666620FFFF
FFFFF0166666400036666630FFFF
FFFFF0166666653466666630FFFF
FFFFF0066666666666666620FFFF
FFFFF0056666666666666610FFFF
FFFFF0046666666666666500FFFF
FFFFFF006666666666666100FFFF
FFFFFF00266666666666300FFFFF
FFFFFFF002666666666300FFFFFF
FFFFFFFF00066666661000FFFFFF
FFFFFFFFF00366666400FFFFFFFF
FFFFFFFFFF036666640FFFFFFFFF
FFFFFFFFFF036666640FFFFFFFFF
FFFFFFFFFF036666630FFFFFFFFF
FFFFFFFFFF036666300FFFFFFFFF
FFFFFFFFFF036664000FFFFFFFFF
FFFFFFFFFF036665000FFFFFFFFF
FFFFFFFFFF0366665000FFFFFFFF
FFFFFFFFFF0366666500FFFFFFFF
FFFFFFFFFF0366666500FFFFFFFF
FFFFFFFFFF0366665000FFFFFFFF
FFFFFFFFFF036665000FFFFFFFFF
FFFFFFFFFF036666100FFFFFFFFF
FFFFFFFFFF0366666100FFFFFFFF
FFFFFFFFFF0266666600FFFFFFFF
FFFFFFFFFF0046666100FFFFFFFF
FFFFFFFFFF000566100FFFFFFFFF
FFFFFFFFFFF0005100FFFFFFFFFF
FFFFFFFFFFFF00000FFFFFFFFFFF
FFFFFFFFFFFFF000FFFFFFFFFFFF
FFFFFFFFFFFFFF0FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_KEY_PERMISSIONS_GREEN(_alias) ENTITY(rectangle,black,key_permissions_green,_alias,OFF KEY_PERMISSIONS_GREEN)
!define OFF_KEY_PERMISSIONS_GREEN(_alias,_label) ENTITY(rectangle,black,key_permissions_green,_label,_alias,OFF KEY_PERMISSIONS_GREEN)
!define OFF_KEY_PERMISSIONS_GREEN(_alias,_label,_shape) ENTITY(_shape,black,key_permissions_green,_label,_alias,OFF KEY_PERMISSIONS_GREEN)
!define OFF_KEY_PERMISSIONS_GREEN(_alias,_label,_shape,_color) ENTITY(_shape,_color,key_permissions_green,_label,_alias,OFF KEY_PERMISSIONS_GREEN)
skinparam folderBackgroundColor<<OFF KEY_PERMISSIONS_GREEN>> White