sprite $lock_protected [38x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFF
FFFFFFFFFFFFF000000000000FFFFFFFFFFFFF
FFFFFFFFFFFF000269AAA830000FFFFFFFFFFF
FFFFFFFFFFF0018AAAAAAAAA4000FFFFFFFFFF
FFFFFFFFFF003AAAAAAAAAAAA8000FFFFFFFFF
FFFFFFFFF002AAAA6200048AAA800FFFFFFFFF
FFFFFFFFF01AAA9100000004AAA500FFFFFFFF
FFFFFFFF006AA9000FFFF0004AAA10FFFFFFFF
FFFFFFFF00AAA200FFFFFFF007AA600FFFFFFF
FFFFFFF004AA700FFFFFFFF001AA900FFFFFFF
FFFFFFF006AA300FFFFFFFFF00AAA10FFFFFFF
FFFFFFF007AA20FFFFFFFFFF008AA20FFFFFFF
FFFFFFF008AA20FFFFFFFFFF007AA20FFFFFFF
FFFFFFF008AA20FFFFFFFFFF007AA20FFFFFFF
FFFFFFF008AA20FFFFFFFFFF007AA20FFFFFFF
FFFFFFF008AA20FFFFFFFFFF007AA20FFFFFFF
FFFFFF0008AA200000000000007AA2000FFFFF
FFFFF0019AAAA9999999999999AAAA600FFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAA500FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF009AAAAAAAAAAAAAAAAAAAAAAA300FFFF
FFFFF0004444444444444444444444200FFFFF
FFFFFF000000000000000000000000000FFFFF
FFFFFFFF00000000000000000000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_LOCK_PROTECTED(_alias) ENTITY(rectangle,black,lock_protected,_alias,OFF LOCK_PROTECTED)
!define OFF_LOCK_PROTECTED(_alias,_label) ENTITY(rectangle,black,lock_protected,_label,_alias,OFF LOCK_PROTECTED)
!define OFF_LOCK_PROTECTED(_alias,_label,_shape) ENTITY(_shape,black,lock_protected,_label,_alias,OFF LOCK_PROTECTED)
!define OFF_LOCK_PROTECTED(_alias,_label,_shape,_color) ENTITY(_shape,_color,lock_protected,_label,_alias,OFF LOCK_PROTECTED)
skinparam folderBackgroundColor<<OFF LOCK_PROTECTED>> White