sprite $lock_with_key_security_blue [42x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00000000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF0002466531000FFFFFFFFFFFFFFFF
FFFFFFFFFFF00039AAAAAAA71000FFFFFFFFFFFFFF
FFFFFFFFFF0007AAAAAAAAAAA500FFFFFFFFFFFFFF
FFFFFFFFFF009AAAA53236AAAA600FFFFFFFFFFFFF
FFFFFFFFF007AAA400000017AAA300FFFFFFFFFFFF
FFFFFFFF003AAA2000FF00006AAA00FFFFFFFFFFFF
FFFFFFFF008AA400FFFFFF0009AA50FFFFFFFFFFFF
FFFFFFFF00AAA00FFFFFFFF001AAA00FFFFFFFFFFF
FFFFFFFF04AA700FFFFFFFFF00AAA00FFFFFFFFFFF
FFFFFFFF06AA30FFFFFFFFFF009AA00FFFFFFFFFFF
FFFFFFFF06AA20FFFFFFFFFFF08AA00FFFFFFFFFFF
FFFFFFFF06AA20FFFFFFFFFFF08AA00FFFFFFFFFFF
FFFFFFFF06AA20FFFFFFFFFFF08AA00FFFFFFFFFFF
FFFFFFFF06AA200000000000008AA00FFFFFFFFFFF
FFFFFF0006AA200000000000008AA0000FFFFFFFFF
FFFFF00048AA655555555555559AA5300FFFFFFFFF
FFFFF008AAAAAAAAAAAAAAAAAAAAAAA40FFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA74000FFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAA810000000FFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAA90069996000FFFF
FFFFF00AAAAAAAAAAAAAAAAAAAA00999999800FFFF
FFFFF00AAAAAAAAAAAAAAAAAAA7089930499500FFF
FFFFF00AAAAAAAAAAAAAAAAAAA2099930499900FFF
FFFFF00AAAAAAAAAAAAAAAAAAA1099999999900FFF
FFFFF00AAAAAAAAAAAAAAAAAAA3099999999900FFF
FFFFF00AAAAAAAAAAAAAAAAAAA8089999999500FFF
FFFFF00AAAAAAAAAAAAAAAAAAAA00999999800FFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAA0079996000FFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAA01999000FFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAA0199900FFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAA0199300FFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAA0199400FFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAA1199930FFFFFF
FFFFF005AAAAAAAAAAAAAAAAAAAAA11998000FFFFF
FFFFFF002333333333333333333330199400FFFFFF
FFFFFF0000000000000000000000001999300FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF00598000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0005000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_LOCK_WITH_KEY_SECURITY_BLUE(_alias) ENTITY(rectangle,black,lock_with_key_security_blue,_alias,OFF LOCK_WITH_KEY_SECURITY_BLUE)
!define OFF_LOCK_WITH_KEY_SECURITY_BLUE(_alias,_label) ENTITY(rectangle,black,lock_with_key_security_blue,_label,_alias,OFF LOCK_WITH_KEY_SECURITY_BLUE)
!define OFF_LOCK_WITH_KEY_SECURITY_BLUE(_alias,_label,_shape) ENTITY(_shape,black,lock_with_key_security_blue,_label,_alias,OFF LOCK_WITH_KEY_SECURITY_BLUE)
!define OFF_LOCK_WITH_KEY_SECURITY_BLUE(_alias,_label,_shape,_color) ENTITY(_shape,_color,lock_with_key_security_blue,_label,_alias,OFF LOCK_WITH_KEY_SECURITY_BLUE)
skinparam folderBackgroundColor<<OFF LOCK_WITH_KEY_SECURITY_BLUE>> White