sprite $lock_with_key_security_ghosted [42x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0000000000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF00002566530000FFFFFFFFFFFFFFFF
FFFFFFFFFFF0005AAAAAAAA6000FFFFFFFFFFFFFFF
FFFFFFFFFF0019AAAAAAAAAAA200FFFFFFFFFFFFFF
FFFFFFFFF001AAAA843348AAAA200FFFFFFFFFFFFF
FFFFFFFFF009AAA200000019AAA00FFFFFFFFFFFFF
FFFFFFFF006AAA0000FF00009AA900FFFFFFFFFFFF
FFFFFFFF00AAA100FFFFFF000AAA00FFFFFFFFFFFF
FFFFFFFF04AA800FFFFFFFF006AA70FFFFFFFFFFFF
FFFFFFF007AA20FFFFFFFFFF00AAA00FFFFFFFFFFF
FFFFFFF008AA10FFFFFFFFFF00AAA00FFFFFFFFFFF
FFFFFFF008AA00FFFFFFFFFF00AAA00FFFFFFFFFFF
FFFFFFF008AA00FFFFFFFFFF00AAA00FFFFFFFFFFF
FFFFFFF008AA00FFFFFFFFFF00AAA00FFFFFFFFFFF
FFFFFFF008AA00000000000000AAA00FFFFFFFFFFF
FFFFFF0008AA00000000000000AAA000FFFFFFFFFF
FFFFF00149AA55555555555555AAA4200FFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAA10FFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAAA61000FFFFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAA600000000FFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAA5013363200FFFFF
FFFFF02AAAAAAAAAAAAAAAAAAA901436446300FFFF
FFFFF02AAAAAAAAAAAAAAAAAAA204360044410FFFF
FFFFF02AAAAAAAAAAAAAAAAAAA0136400346300FFF
FFFFF02AAAAAAAAAAAAAAAAAAA0264363464300FFF
FFFFF02AAAAAAAAAAAAAAAAAAA0043643644300FFF
FFFFF02AAAAAAAAAAAAAAAAAAA303643644610FFFF
FFFFF02AAAAAAAAAAAAAAAAAAAA01436446300FFFF
FFFFF02AAAAAAAAAAAAAAAAAAAA6005446200FFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAA80246300FFFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAA0263300FFFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAA0234000FFFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAA0245100FFFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAA0263400FFFFFF
FFFFF008AAAAAAAAAAAAAAAAAAAAA0234400FFFFFF
FFFFF0002333333333333333333330245100FFFFFF
FFFFFF0000000000000000000000002634000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0035300FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0003000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_LOCK_WITH_KEY_SECURITY_GHOSTED(_alias) ENTITY(rectangle,black,lock_with_key_security_ghosted,_alias,OFF LOCK_WITH_KEY_SECURITY_GHOSTED)
!define OFF_LOCK_WITH_KEY_SECURITY_GHOSTED(_alias,_label) ENTITY(rectangle,black,lock_with_key_security_ghosted,_label,_alias,OFF LOCK_WITH_KEY_SECURITY_GHOSTED)
!define OFF_LOCK_WITH_KEY_SECURITY_GHOSTED(_alias,_label,_shape) ENTITY(_shape,black,lock_with_key_security_ghosted,_label,_alias,OFF LOCK_WITH_KEY_SECURITY_GHOSTED)
!define OFF_LOCK_WITH_KEY_SECURITY_GHOSTED(_alias,_label,_shape,_color) ENTITY(_shape,_color,lock_with_key_security_ghosted,_label,_alias,OFF LOCK_WITH_KEY_SECURITY_GHOSTED)
skinparam folderBackgroundColor<<OFF LOCK_WITH_KEY_SECURITY_GHOSTED>> White