sprite $lock_with_key_security_orange [41x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF00000000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFF00014666420000FFFFFFFFFFFFFFF
FFFFFFFFFFF0017AAAAAAA93000FFFFFFFFFFFFFF
FFFFFFFFFF005AAAAAAAAAAA7000FFFFFFFFFFFFF
FFFFFFFFF006AAAA63235AAAA8000FFFFFFFFFFFF
FFFFFFFF003AAA710000004AAA600FFFFFFFFFFFF
FFFFFFFF00AAA60000FF0003AAA200FFFFFFFFFFF
FFFFFFFF04AA9000FFFFFF005AA700FFFFFFFFFFF
FFFFFFF009AA100FFFFFFF000AAA00FFFFFFFFFFF
FFFFFFF00AAA00FFFFFFFFF007AA20FFFFFFFFFFF
FFFFFFF00AAA00FFFFFFFFF004AA300FFFFFFFFFF
FFFFFFF00AA90FFFFFFFFFFF04AA400FFFFFFFFFF
FFFFFFF00AA90FFFFFFFFFFF04AA400FFFFFFFFFF
FFFFFFF00AA90FFFFFFFFFFF04AA400FFFFFFFFFF
FFFFFFF00AA900000000000004AA400FFFFFFFFFF
FFFFF0000AA900000000000004AA4000FFFFFFFFF
FFFFF0025AAA55555555555557AA7300FFFFFFFFF
FFFF004AAAAAAAAAAAAAAAAAAAAAAA700FFFFFFFF
FFFF006AAAAAAAAAAAAAAAAAAAAAA85000FFFFFFF
FFFF006AAAAAAAAAAAAAAAAAAAA920000000FFFFF
FFFF006AAAAAAAAAAAAAAAAAAAA1058996000FFFF
FFFF006AAAAAAAAAAAAAAAAAAA30799899810FFFF
FFFF006AAAAAAAAAAAAAAAAAA9049950299600FFF
FFFF006AAAAAAAAAAAAAAAAAA7079950199900FFF
FFFF006AAAAAAAAAAAAAAAAAA6089998999910FFF
FFFF006AAAAAAAAAAAAAAAAAA7079999999900FFF
FFFF006AAAAAAAAAAAAAAAAAA9049999999600FFF
FFFF006AAAAAAAAAAAAAAAAAAA30799999800FFFF
FFFF006AAAAAAAAAAAAAAAAAAAA1069997000FFFF
FFFF006AAAAAAAAAAAAAAAAAAAAA20999200FFFFF
FFFF006AAAAAAAAAAAAAAAAAAAAA4099910FFFFFF
FFFF006AAAAAAAAAAAAAAAAAAAAA4099500FFFFFF
FFFF006AAAAAAAAAAAAAAAAAAAAA4099600FFFFFF
FFFF006AAAAAAAAAAAAAAAAAAAAA40999500FFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAA40998100FFFFF
FFFFF001333333333333333333331099600FFFFFF
FFFFFF000000000000000000000000999400FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00398000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF004000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_LOCK_WITH_KEY_SECURITY_ORANGE(_alias) ENTITY(rectangle,black,lock_with_key_security_orange,_alias,OFF LOCK_WITH_KEY_SECURITY_ORANGE)
!define OFF_LOCK_WITH_KEY_SECURITY_ORANGE(_alias,_label) ENTITY(rectangle,black,lock_with_key_security_orange,_label,_alias,OFF LOCK_WITH_KEY_SECURITY_ORANGE)
!define OFF_LOCK_WITH_KEY_SECURITY_ORANGE(_alias,_label,_shape) ENTITY(_shape,black,lock_with_key_security_orange,_label,_alias,OFF LOCK_WITH_KEY_SECURITY_ORANGE)
!define OFF_LOCK_WITH_KEY_SECURITY_ORANGE(_alias,_label,_shape,_color) ENTITY(_shape,_color,lock_with_key_security_orange,_label,_alias,OFF LOCK_WITH_KEY_SECURITY_ORANGE)
skinparam folderBackgroundColor<<OFF LOCK_WITH_KEY_SECURITY_ORANGE>> White