sprite $lock_with_key_security [42x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00000000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFF00002466530000FFFFFFFFFFFFFFFF
FFFFFFFFFFF00049AAAAAAA71000FFFFFFFFFFFFFF
FFFFFFFFFF0008AAAAAAAAAAA400FFFFFFFFFFFFFF
FFFFFFFFF0009AAA953237AAAA400FFFFFFFFFFFFF
FFFFFFFFF008AAA300000018AAA10FFFFFFFFFFFFF
FFFFFFFF004AAA1000FF00007AAA00FFFFFFFFFFFF
FFFFFFFF009AA200FFFFFF0009AA20FFFFFFFFFFFF
FFFFFFFF02AAA00FFFFFFFF003AAA00FFFFFFFFFFF
FFFFFFFF05AA40FFFFFFFFFF00AAA00FFFFFFFFFFF
FFFFFFF007AA10FFFFFFFFFF009AA00FFFFFFFFFFF
FFFFFFF007AA10FFFFFFFFFF009AA00FFFFFFFFFFF
FFFFFFF007AA10FFFFFFFFFF009AA00FFFFFFFFFFF
FFFFFFF007AA10FFFFFFFFFF009AA00FFFFFFFFFFF
FFFFFFF007AA100000000000009AA00FFFFFFFFFFF
FFFFFF0007AA100000000000009AA000FFFFFFFFFF
FFFFF00049AA55555555555555AAA4200FFFFFFFFF
FFFFF009AAAAAAAAAAAAAAAAAAAAAAA20FFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA73000FFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAA700000000FFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAA7018AAA6000FFFF
FFFFF00AAAAAAAAAAAAAAAAAAAA00AAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAAAA50AAA206AA400FFF
FFFFF00AAAAAAAAAAAAAAAAAAA10AAA106AA800FFF
FFFFF00AAAAAAAAAAAAAAAAAAA10AAAA9AAAA00FFF
FFFFF00AAAAAAAAAAAAAAAAAAA10AAAAAAAA800FFF
FFFFF00AAAAAAAAAAAAAAAAAAA50AAAAAAAA400FFF
FFFFF00AAAAAAAAAAAAAAAAAAAA00AAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAAAAA9009AAA500FFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAA901AAA00FFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAA01AA900FFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAA01AA300FFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAA01AA300FFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAA01AAA20FFFFFF
FFFFF007AAAAAAAAAAAAAAAAAAAAA01AA800FFFFFF
FFFFF00023333333333333333333301AA300FFFFFF
FFFFFF0000000000000000000000001AAA200FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF007A7000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0006000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_LOCK_WITH_KEY_SECURITY(_alias) ENTITY(rectangle,black,lock_with_key_security,_alias,OFF LOCK_WITH_KEY_SECURITY)
!define OFF_LOCK_WITH_KEY_SECURITY(_alias,_label) ENTITY(rectangle,black,lock_with_key_security,_label,_alias,OFF LOCK_WITH_KEY_SECURITY)
!define OFF_LOCK_WITH_KEY_SECURITY(_alias,_label,_shape) ENTITY(_shape,black,lock_with_key_security,_label,_alias,OFF LOCK_WITH_KEY_SECURITY)
!define OFF_LOCK_WITH_KEY_SECURITY(_alias,_label,_shape,_color) ENTITY(_shape,_color,lock_with_key_security,_label,_alias,OFF LOCK_WITH_KEY_SECURITY)
skinparam folderBackgroundColor<<OFF LOCK_WITH_KEY_SECURITY>> White