sprite $lock_unprotected [37x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFF
FFFFFFFFFFFFF000001000000FFFFFFFFFFFF
FFFFFFFFFFF000179AAAA83000FFFFFFFFFFF
FFFFFFFFFF0008AAAAAAAAA9100FFFFFFFFFF
FFFFFFFFFF00AAAAAA9AAAAAA200FFFFFFFFF
FFFFFFFFF00AAAA5000002AAAA100FFFFFFFF
FFFFFFFF007AAA1000F00008AAA00FFFFFFFF
FFFFFFFF00AAA100FFFFF0009AA40FFFFFFFF
FFFFFFF006AA600FFFFFFF002AAA00FFFFFFF
FFFFFFF00AAA00FFFFFFFFF009AA00FFFFFFF
FFFFFFF00AA900FFFFFFFFF007AA10FFFFFFF
FFFFFFF00AA900FFFFFFFFFF05AA20FFFFFFF
FFFFFFF00AA900FFFFFFFFFF05AA20FFFFFFF
FFFFFFF0011100FFFFFFFFFF05AA20FFFFFFF
FFFFFFF0000000FFFFFFFFFF05AA20FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF05AA20FFFFFFF
FFFFFF00000000000000000005AA200FFFFFF
FFFFF000000000000000000005AA2000FFFFF
FFFFF007AAAAAAAAAAAAAAAAAAAAA900FFFFF
FFFFF03AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF03AAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF004888888888888888888888600FFFFF
FFFFFF00000000000000000000000000FFFFF
FFFFFFF00000000000000000000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_LOCK_UNPROTECTED(_alias) ENTITY(rectangle,black,lock_unprotected,_alias,OFF LOCK_UNPROTECTED)
!define OFF_LOCK_UNPROTECTED(_alias,_label) ENTITY(rectangle,black,lock_unprotected,_label,_alias,OFF LOCK_UNPROTECTED)
!define OFF_LOCK_UNPROTECTED(_alias,_label,_shape) ENTITY(_shape,black,lock_unprotected,_label,_alias,OFF LOCK_UNPROTECTED)
!define OFF_LOCK_UNPROTECTED(_alias,_label,_shape,_color) ENTITY(_shape,_color,lock_unprotected,_label,_alias,OFF LOCK_UNPROTECTED)
skinparam folderBackgroundColor<<OFF LOCK_UNPROTECTED>> White