sprite $policy [43x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF00000000000000000000000000FFFFF
FFFFFFFFFF000000000000000000000000000000FFF
FFFFFFFFF0015788888888888888888888862000FFF
FFFFFFFF002AAAAAAAAAAAAAAAAAAAAAAA7001100FF
FFFFFFFF00AAAAAAAAAAAAAAAAAAAAAAA902AAA50FF
FFFFFFF004AAAAAAAAAAAAAAAAAAAAAAA509AAA80FF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA41AAAA90FF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA41AAAA50FF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA41AAA900FF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA41AA9000FF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA4021000FFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA400000FFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA40FFFFFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA40FFFFFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA40FFFFFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA40FFFFFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA40FFFFFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA40FFFFFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA40FFFFFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA40FFFFFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA40FFFFFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA40FFFFFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA40FFFFFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA40FFFFFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA40FFFFFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA40FFFFFFFF
FFFFF00002333333333333333337AAAAA40FFFFFFFF
FFFF000111111111111111111000AAAAA40FFFFFFFF
FFF0029AAAAAAAAAAAAAAAAAA104AAAAA40FFFFFFFF
FF001AAAAAAAAAAAAAAAAAAA606AAAAAA40FFFFFFFF
FF009AAAAAAAAAAAAAAAAAAA11AAAAAAA40FFFFFFFF
FF00AAAAAAAAAAAAAAAAAAAA05AAAAAAA40FFFFFFFF
FF00AAAAAAAAAAAAAAAAAAAA06AAAAAAA30FFFFFFFF
FF009AAAAAAAAAAAAAAAAAAA02AAAAAAA00FFFFFFFF
FF003AAAAAAAAAAAAAAAAAAA409AAAAA400FFFFFFFF
FFF003AAAAAAAAAAAAAAAAAAA008AAA400FFFFFFFFF
FFFF000233333333333333333100230000FFFFFFFFF
FFFFF000000000000000000000000000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_POLICY(_alias) ENTITY(rectangle,black,policy,_alias,OFF POLICY)
!define OFF_POLICY(_alias,_label) ENTITY(rectangle,black,policy,_label,_alias,OFF POLICY)
!define OFF_POLICY(_alias,_label,_shape) ENTITY(_shape,black,policy,_label,_alias,OFF POLICY)
!define OFF_POLICY(_alias,_label,_shape,_color) ENTITY(_shape,_color,policy,_label,_alias,OFF POLICY)
skinparam folderBackgroundColor<<OFF POLICY>> White