sprite $protected_voice_mail [48x39/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF000000000000000000000000000000000FFFFFFFF
FFFFFF00011111111111111111111111111111000FFFFFFF
FFFFFF009AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFF02AAAAAA732249AAAAAAAA942249AAAAAA00FFFFFF
FFFFFF02AAAAA20000006AAAAAA50000004AAAAA00FFFFFF
FFFFFF02AAAA2000210009AAAA6000220005AAAA00FFFFFF
FFFFFF02AAA8003AAAA000AAAA002AAAA200AAAA00FFFFFF
FFFFFF02AAA400AAAAA700AAA7009AAAA9007AAA00FFFFFF
FFFFFF02AAA300AAAAA900AAA500AAAAAA005AAA00FFFFFF
FFFFFF02AAA400AAAAA900AAA600AAAAAA006AAA00FFFFFF
FFFFFF02AAA7008AAAA300AAAA004AAAA500789A00FFFFFF
FFFFFF02AAAA1005872001AAAA0003883000000000FFFFFF
FFFFFF02AAAAA00000000011110000000049AA9400FFFFFF
FFFFFF02AAAAAA50000000000000000007AA99AA800FFFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAAA03AA0000AA300FFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAAA08A100000A800FFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAA90AA000000AA00FFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAA90AA000000AA00FFFF
FFFFFF009AAAAAAAAAAAAAAAAAAAAA40AA000000AA00FFFF
FFFFFF00000000000000000000000004AA444444AA400FFF
FFFFFFFF00000000000000000000001AAAAAAAAAAAA10FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF01AAAAAAAAAAAA10FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF01AAAAAAAAAAAA10FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF01AAAAAAAAAAAA10FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF01AAAAAAAAAAAA10FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF01AAAAAAAAAAAA10FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF01AAAAAAAAAAAA10FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF01AAAAAAAAAAAA10FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF01AAAAAAAAAAAA10FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0033333333333300FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000FFFF
}

!define OFF_PROTECTED_VOICE_MAIL(_alias) ENTITY(rectangle,black,protected_voice_mail,_alias,OFF PROTECTED_VOICE_MAIL)
!define OFF_PROTECTED_VOICE_MAIL(_alias,_label) ENTITY(rectangle,black,protected_voice_mail,_label,_alias,OFF PROTECTED_VOICE_MAIL)
!define OFF_PROTECTED_VOICE_MAIL(_alias,_label,_shape) ENTITY(_shape,black,protected_voice_mail,_label,_alias,OFF PROTECTED_VOICE_MAIL)
!define OFF_PROTECTED_VOICE_MAIL(_alias,_label,_shape,_color) ENTITY(_shape,_color,protected_voice_mail,_label,_alias,OFF PROTECTED_VOICE_MAIL)
skinparam folderBackgroundColor<<OFF PROTECTED_VOICE_MAIL>> White