sprite $retention_policy [45x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF0000000000000000000000000000FFFFFFFF
FFFFFFFF000000000000000000000000000000FFFFFFF
FFFFFFF0028AAAAAAAAAAAAAAAAAAAAAA610000FFFFFF
FFFFFF002AAAAAAAAAAAAAAAAAAAAAAA5025630FFFFFF
FFFFFF009AAAAAAAAAAAAAAAAAAAAAAA03AAA800FFFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAAA708AAA900FFFFF
FFFFFF03AAAAAAAAAAAAAAAAAAAAAAA709AAA800FFFFF
FFFFFF04AAAAAAAAAAAAAAAAAAAAAAA709AAA50FFFFFF
FFFFFF04AAAAAAAAAAAAAAAAAAAAAAA709AA700FFFFFF
FFFFFF04AAAAAAAAAAAAAAAAAAAAAAA7089400FFFFFFF
FFFFFF04AAAAAAAAAAAAAAAAAAAAAAA700000FFFFFFFF
FFFFFF04AAAAAAAAAAAAAAAAAAAAAAA700FFFFFFFFFFF
FFFFFF04AAAAAAAAAAAAAAAAAAAAAAA700FFFFFFFFFFF
FFFFFF04AAAAAAAAAAAAAAAAAAAAAAA700FFFFFFFFFFF
FFFFFF04AAAAAAAAAAAAAAAAAAAAAAA700FFFFFFFFFFF
FFFFFF04AAAAAAAAAAAAAAAA7532222100000FFFFFFFF
FFFFFF04AAAAAAAAAAAAA920000000100000000FFFFFF
FFFFFF04AAAAAAAAAAAA700479AA9999AA975000FFFFF
FFFFFF04AAAAAAAAAAAA01A73100000000136A300FFFF
FFFFFF04AAAAAAAAAAAA069000000000000007800FFFF
FFFFFF04AAAAAAAAAAAA04AA743211112246A9700FFFF
FFFFFF04AAAAAAAAAAAA029036789999886405500FFFF
FFFFFF04AAAAAAAAAAAA00A00000000000000630FFFFF
FFFFFF04AAAAAAAAAAAA30A00000000000000820FFFFF
FFFFFF04AAAAAAAAAAAA50A00000344400000A00FFFFF
FFFF000277777777777740A00007AAAA81000A00FFFFF
FF00000000000000000000A0000AA54AA4001900FFFFF
FF004AAAAAAAAAAAAAAAA0820000604AA0002800FFFFF
F008AAAAAAAAAAAAAAAAA06503A9000019503700FFFFF
F03AAAAAAAAAAAAAAAAAA03709AA10007AA04600FFFFF
F09AAAAAAAAAAAAAAAAAA01A09A200011AA0640FFFFFF
F0AAAAAAAAAAAAAAAAAAA10A01A996499A40730FFFFFF
F06AAAAAAAAAAAAAAAAAA30A007AA87AA800910FFFFFF
F00AAAAAAAAAAAAAAAAAA60A000232052000A00FFFFFF
F0029AAAAAAAAAAAAAAAA80A000000000000A00FFFFFF
FF000334444444444444430A400000000003900FFFFFF
FFF000000000000000000008A9531111248A800FFFFFF
FFFFFFFFFFFFFFFFFFFFF0029AAAAAAAAAA9300FFFFFF
FFFFFFFFFFFFFFFFFFFFFF0003789999873000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF00000000000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_RETENTION_POLICY(_alias) ENTITY(rectangle,black,retention_policy,_alias,OFF RETENTION_POLICY)
!define OFF_RETENTION_POLICY(_alias,_label) ENTITY(rectangle,black,retention_policy,_label,_alias,OFF RETENTION_POLICY)
!define OFF_RETENTION_POLICY(_alias,_label,_shape) ENTITY(_shape,black,retention_policy,_label,_alias,OFF RETENTION_POLICY)
!define OFF_RETENTION_POLICY(_alias,_label,_shape,_color) ENTITY(_shape,_color,retention_policy,_label,_alias,OFF RETENTION_POLICY)
skinparam folderBackgroundColor<<OFF RETENTION_POLICY>> White