sprite $role_group [48x41/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF000000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF0000110000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF0005AAAA500FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF007AAAAAA700FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF02AAAAAAAA30FFFFFFFFFFF
FFFFFFFFFFFF000000FFFFFF009AAAAAAAAA00FFFFFFFFFF
FFFFFFFFFFF000010000FFFF00AAAAAAAAAA00FFFFFFFFFF
FFFFFFFFFF005AAAA8000FFF00AAAAAAAAAA00FFFFFFFFFF
FFFFFFFFF007AAAAAA900FFF00AAAAAAAAAA00FFFFFFFFFF
FFFFFFFFF01AAAAAAAA500FFF07AAAAAAAA800FFFFFFFFFF
FFFFFFFF008AAAAAAAAA00FFF00AAAAAAAA00FFFFFFFFFFF
FFFFFFFF009AAAAAAAAA10FFF002AAAAAA300FFFFFFFFFFF
FFFFFFFF00AAAAAAAAAA20F0000005885100000FFFFFFFFF
FFFFFFFF009AAAAAAAAA100007700000000770000FFFFFFF
FFFFFFFF005AAAAAAAA80006AAAA500004AAAA600FFFFFFF
FFFFFFFFF00AAAAAAAA2008AAAAAAAAAAAAAAAA800FFFFFF
FFFFFFFFF000AAAAAA4001AAAAAAAAAAAAAAAAAA30FFFFFF
FFFFFFF0000005997100008AAAAAAAAAAAAAAAAA700FFFFF
FFFFF0000570000000057102AAAAAAAAAAAAAAAA800FFFFF
FFFFF004AAAA5100149AAA600AA7777777777777600FFFFF
FFFF005AAAAAAAAAAAAAAAA902000000000000000000FFFF
FFFF01AAAAAAAAAAAAAAAAAA4029AAAAAAAAAAAAA9200FFF
FFFF03AAAAAAAAAAAAAAAAAAA09AAAAAAAAAAAAAAA600FFF
FFF006AAAAAAAAAAAAAAAAAAA09AAAAA4001AAAAAA600FFF
FFF008AAAAAAAAAAAAAAAAAAA09AAAA503700AAAAA600FFF
FFF00AAAAAAAAAAAAAAAAAAAA09AAAA108A009AAAA600FFF
FFF00AAAAAAAAAAAAAAAAAAAA09AAAA0001008AAAA600FFF
FFF01AAAAAAAAAAAAAAAAAAAA09AAAA400000AAAAA600FFF
FFF02AAAAAAAAAAAAAAAAAAAA09AAAAA20008AAAAA600FFF
FFF000000000000000000000009AAAAAA006AAAAAA600FFF
FFF000000000000000000000009AAAAAA009AAAAAA600FFF
FFFFFFFFFFFFFFFFFFFFFFFFF09AAAAAA02AAAAAAA600FFF
FFFFFFFFFFFFFFFFFFFFFFFFF09AAAAAA005AAAAAA600FFF
FFFFFFFFFFFFFFFFFFFFFFFFF09AAAAAA01AAAAAAA600FFF
FFFFFFFFFFFFFFFFFFFFFFFFF09AAAAAA008AAAAAA600FFF
FFFFFFFFFFFFFFFFFFFFFFFFF09AAAAAA73AAAAAAA600FFF
FFFFFFFFFFFFFFFFFFFFFFFFF04AAAAAAAAAAAAAAA300FFF
FFFFFFFFFFFFFFFFFFFFFFFFF0001111111111111000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ROLE_GROUP(_alias) ENTITY(rectangle,black,role_group,_alias,OFF ROLE_GROUP)
!define OFF_ROLE_GROUP(_alias,_label) ENTITY(rectangle,black,role_group,_label,_alias,OFF ROLE_GROUP)
!define OFF_ROLE_GROUP(_alias,_label,_shape) ENTITY(_shape,black,role_group,_label,_alias,OFF ROLE_GROUP)
!define OFF_ROLE_GROUP(_alias,_label,_shape,_color) ENTITY(_shape,_color,role_group,_label,_alias,OFF ROLE_GROUP)
skinparam folderBackgroundColor<<OFF ROLE_GROUP>> White