sprite $role_assignment_policy [45x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF00000000000000000000000FFFFFFFFFF
FFFFFFFFF0000000000000000000000000000FFFFFFFF
FFFFFFFF000133333333333333333333331000FFFFFFF
FFFFFFF0008AAAAAAAAAAAAAAAAAAAAA9100000FFFFFF
FFFFFFF009AAAAAAAAAAAAAAAAAAAAAA117AA20FFFFFF
FFFFFF003AAAAAAAAAAAAAAAAAAAAAA708AAA50FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAAAAA60AAAA50FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAAAAA60AAAA20FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAAAAA60AAA800FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAAAAA60AA6000FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAAAAA6010000FFFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAAAAA60000FFFFFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFFFF006AAAAAAAAAAAAA1000000000000000000FFFF
FFFFFF006AAAAAAAAAAAA307AAAAAAAAAAAAAA600FFFF
FFFFFF006AAAAAAAAAAAA01AAAAAAAAAAAAAAAA20FFFF
FFFFFF006AAAAAAAAAAAA02AAAAAA5029AAAAAA20FFFF
FFFFFF006AAAAAAAAAAAA02AAAAA201008AAAAA20FFFF
FFFF0000000000000000002AAAA802A802AAAAA20FFFF
FFF00022222222222222202AAAA6007400AAAAA20FFFF
FF003AAAAAAAAAAAAAAAA02AAAA8000001AAAAA20FFFF
F001AAAAAAAAAAAAAAAAA02AAAAA200007AAAAA20FFFF
F008AAAAAAAAAAAAAAAAA02AAAAAA2007AAAAAA20FFFF
F00AAAAAAAAAAAAAAAAAA02AAAAAA500AAAAAAA20FFFF
F009AAAAAAAAAAAAAAAAA02AAAAAA504AAAAAAA20FFFF
F002AAAAAAAAAAAAAAAAA02AAAAAA504AAAAAAA20FFFF
FF005AAAAAAAAAAAAAAAA02AAAAAA501AAAAAAA20FFFF
FF000145555555555555502AAAAAA505AAAAAAA20FFFF
FFF00000000000000000002AAAAAA701AAAAAAA20FFFF
FFFFFF00000000000000002AAAAAAA59AAAAAAA20FFFF
FFFFFFFFFFFFFFFFFFFFF009AAAAAAAAAAAAAA900FFFF
FFFFFFFFFFFFFFFFFFFFF00000000000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFF000000000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ROLE_ASSIGNMENT_POLICY(_alias) ENTITY(rectangle,black,role_assignment_policy,_alias,OFF ROLE_ASSIGNMENT_POLICY)
!define OFF_ROLE_ASSIGNMENT_POLICY(_alias,_label) ENTITY(rectangle,black,role_assignment_policy,_label,_alias,OFF ROLE_ASSIGNMENT_POLICY)
!define OFF_ROLE_ASSIGNMENT_POLICY(_alias,_label,_shape) ENTITY(_shape,black,role_assignment_policy,_label,_alias,OFF ROLE_ASSIGNMENT_POLICY)
!define OFF_ROLE_ASSIGNMENT_POLICY(_alias,_label,_shape,_color) ENTITY(_shape,_color,role_assignment_policy,_label,_alias,OFF ROLE_ASSIGNMENT_POLICY)
skinparam folderBackgroundColor<<OFF ROLE_ASSIGNMENT_POLICY>> White