sprite $security_access_portal [48x43/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000FFFFFF
FFFFFFFFFFFFFFFFF000FFFFFFFFFF000000000000FFFFFF
FFFFFFFFFFFFFF0000000000FFFFF00000258899000FFFFF
FFFFFFFFFFFF00006AAA930000FFF009999999990000FFFF
FFFFFFFFFFF0019AAAAAAAA6000FF0099999999969100FFF
FFFFFFFFFF004AAAAAAAAAAAA100F00999999999697000FF
FFFFFFFFF005AAA9200014AAAA100009993009994638000F
FFFFFFFFF01AAA5000000009AA9000099909999900026000
FFFFFFFF008AA600FFFFF000AAA400099910999900019910
FFFFFFFF01AAA00FFFFFFFF00AA900099993099900029920
FFFFFFF005AA40FFFFFFFFF00AAA10099956099900018400
FFFFFFF006AA00FFFFFFFFFF05AA20099942799912081000
FFFFFFF007AA00FFFFFFFFFF04AA200999999999699000FF
FFFFFFF007AA00FFFFFFFFFF04AA20099999999969300FFF
FFFFFFF007AA00FFFFFFFFFF04AA2009999999992300FFFF
FFFFFFF007AA00000000000004AA200013468999000FFFFF
FFFFFF0007AA00000000000004AA20000000001100FFFFFF
FFFFFF009AAAAAAAAAAAAAAAAAAAA700FF00000000FFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA60FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA80FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA80FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA80FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA80FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA80FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA80FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA80FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA80FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA80FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA80FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA80FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA80FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA80FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA80FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA70FFFFFFFFFFFFFFFF
FFFFF004AAAAAAAAAAAAAAAAAAAAA900FFFFFFFFFFFFFFFF
FFFFFF00000000000000000000000000FFFFFFFFFFFFFFFF
FFFFFFF000000000000000000000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SECURITY_ACCESS_PORTAL(_alias) ENTITY(rectangle,black,security_access_portal,_alias,OFF SECURITY_ACCESS_PORTAL)
!define OFF_SECURITY_ACCESS_PORTAL(_alias,_label) ENTITY(rectangle,black,security_access_portal,_label,_alias,OFF SECURITY_ACCESS_PORTAL)
!define OFF_SECURITY_ACCESS_PORTAL(_alias,_label,_shape) ENTITY(_shape,black,security_access_portal,_label,_alias,OFF SECURITY_ACCESS_PORTAL)
!define OFF_SECURITY_ACCESS_PORTAL(_alias,_label,_shape,_color) ENTITY(_shape,_color,security_access_portal,_label,_alias,OFF SECURITY_ACCESS_PORTAL)
skinparam folderBackgroundColor<<OFF SECURITY_ACCESS_PORTAL>> White