sprite $sharing_policy [44x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF000000000000000000000000000FFFFFFF
FFFFFFFF000000000000000000000000000000FFFFFF
FFFFFFF00037999999999999999999999940000FFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA3013300FFFF
FFFFFF004AAAAAAAAAAAAAAAAAAAAAAA605AAA30FFFF
FFFFFF009AAAAAAAAAAAAAAAAAAAAAAA21AAAA60FFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA23AAAA50FFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA23AAAA10FFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA23AAA600FFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA23AA400FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA200000FFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA2000FFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAA842110000FFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAA8200233310000FFFFFF
FFFFFF00AAAAAAAAAAAAAAAA5005AAAAAA94000FFFFF
FFFFFF00AAAAAAAAAAAAAAA403AAAAAAAAAA9100FFFF
FFFFFF00AAAAAAAAAAAAAA604AAAAAAAA89AAA200FFF
FFFFFF00AAAAAAAAAAAAAA02AAAAA6210008AAA000FF
FFFFFF00AAAAAAAAAAAAA20AAAA800230004AAA800FF
FFFFF000999999999999903AAA902AAA2008AAAA00FF
FFF0000000000000000000AAAA62AAAAA9A71AAA600F
FF00047888888888888830AAA44AAAAAAAA907AA900F
F001AAAAAAAAAAAAAAAA20AA1004AAAAAAAA14AA900F
F00AAAAAAAAAAAAAAAAA20AA0002AAAAAAAA14AA900F
F03AAAAAAAAAAAAAAAAA30AA7008AAAAAAAA06AA900F
F05AAAAAAAAAAAAAAAAA70AAAA05AAAAAAA60AAA700F
F02AAAAAAAAAAAAAAAAAA06AAA607AAA51205AAA20FF
F00AAAAAAAAAAAAAAAAAA00AAAA4038A0003AAA900FF
F002AAAAAAAAAAAAAAAAA805AAAA710A0006AAA200FF
FF00046666666666666666008AAAAA9A835AAA500FFF
FFF00000000000000000000007AAAAAAAAAAA500FFFF
FFFFF00000000000000000000049AAAAAAA82000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFF0002688751000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF00000000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SHARING_POLICY(_alias) ENTITY(rectangle,black,sharing_policy,_alias,OFF SHARING_POLICY)
!define OFF_SHARING_POLICY(_alias,_label) ENTITY(rectangle,black,sharing_policy,_label,_alias,OFF SHARING_POLICY)
!define OFF_SHARING_POLICY(_alias,_label,_shape) ENTITY(_shape,black,sharing_policy,_label,_alias,OFF SHARING_POLICY)
!define OFF_SHARING_POLICY(_alias,_label,_shape,_color) ENTITY(_shape,_color,sharing_policy,_label,_alias,OFF SHARING_POLICY)
skinparam folderBackgroundColor<<OFF SHARING_POLICY>> White