sprite $trusted_application_server [39x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF000000000000000000FFFFFFFFFFFFFF
FFFFFF00011111111111110000FFFFFFFFFFFFF
FFFFFF00AAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFFF05AA80000000000AAA10FFFFFFFFFFFFF
FFFFFF05AA93333333334AAA10FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA10000000FFFFFFF
FFFFFF05AAAAAAAAAAAAAA500256530000FFFFF
FFFFFF05AAAAAAAAAAAAA2049AAAAAA7000FFFF
FFFFFF05AAAAAAAAAAAA108AAAAAAAAAA100FFF
FFFFFF05AAAAAAAAAAA309AAAAAAAAAAAA000FF
FFFFFF05AAAAAAAAAAA06AAAAAAAAAA1AA900FF
FFFFFF05AAA999999920AAAAAAAAAA500AA400F
FFFFFF05AA8000000005AAAAAAAAA8007AA900F
FFFFFF05AAAAAAAAA90AAAAAAAAAA103AAAA00F
FFFFFF05AAAAAAAAA80AAAA28AAA301AAAAA20F
FFFFFF05AAAAAAAAA70AAA5009A7009AAAAA20F
FFFFFF05AA800000000AAAA200A007AAAAAA10F
FFFFFF05AA9777777708AAAA10004AAAAAAA00F
FFFFFF05AAAAAAAAAA12AAAAA001AAAAAAA700F
FFFFFF05AAAAAAAAAA50AAAAA90AAAAAAAA10FF
FFFFFF05AAAAAAAAAAA01AAAAAAAAAAAAA700FF
FFFFFF0011111111111004AAAAAAAAAAA900FFF
FFFFFF00000000000000003AAAAAAAAA700FFFF
FFFFFFFFFFFFFFFFFFFFF00059AAA97100FFFFF
FFFFFFFFFFFFFFFFFFFFFF00000000000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF0000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_TRUSTED_APPLICATION_SERVER(_alias) ENTITY(rectangle,black,trusted_application_server,_alias,OFF TRUSTED_APPLICATION_SERVER)
!define OFF_TRUSTED_APPLICATION_SERVER(_alias,_label) ENTITY(rectangle,black,trusted_application_server,_label,_alias,OFF TRUSTED_APPLICATION_SERVER)
!define OFF_TRUSTED_APPLICATION_SERVER(_alias,_label,_shape) ENTITY(_shape,black,trusted_application_server,_label,_alias,OFF TRUSTED_APPLICATION_SERVER)
!define OFF_TRUSTED_APPLICATION_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,trusted_application_server,_label,_alias,OFF TRUSTED_APPLICATION_SERVER)
skinparam folderBackgroundColor<<OFF TRUSTED_APPLICATION_SERVER>> White