sprite $um_mailbox_policy [45x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF0000000000000000000000FFFFFFFFFFF
FFFFFFFFF000000000000000000000000000FFFFFFFFF
FFFFFFFF00047888888888888888888884000FFFFFFFF
FFFFFFFF00AAAAAAAAAAAAAAAAAAAAAA100000FFFFFFF
FFFFFFF00AAAAAAAAAAAAAAAAAAAAAA409AA80FFFFFFF
FFFFFFF00AAAAAAAAAAAAAAAAAAAAAA05AAAA0FFFFFFF
FFFFFFF04AAAAAAAAAAAAAAAAAAAAAA07AAAA0FFFFFFF
FFFFFFF04AAAAAAAAAAAAAAAAAAAAAA07AAA40FFFFFFF
FFFFFFF04AAAAAAAAAAAAAAAAAAAAAA07AA800FFFFFFF
FFFFFFF04AAAAAAAAAAAAAAAAAAAAAA057300FFFFFFFF
FFFFFFF04AAAAAAAAAAAAAAAAAAAAAA00000FFFFFFFFF
FFFFFFF04AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFFF04AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFFF04AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFFF04AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFFF04AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFFF04AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFFF04AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFFF04AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFFF04AAAAAAAAAA930015100000000000000FFFFF
FFFFFFF04AAAAAAAAAA016630366666666666610FFFFF
FFFFFFF04AAAAAAAAAA0AAAA19AAAAAAAAAAAA70FFFFF
FFFFFFF04AAAAAAAAAA0AAAA19A822222222AA70FFFFF
FFFFFFF04AAAAAAAAAA0AAAA19A800000000AA70FFFFF
FFFF0000000000000000AAAA19A800000000AA70FFFFF
FFF00001111111111110AAAA09A811111111AA70FFFFF
FF0019AAAAAAAAAAAAA0AAAA09AAAAAAAAAAAA70FFFFF
FF009AAAAAAAAAAAAAA09AAA09AA77A78A78AA70FFFFF
FF02AAAAAAAAAAAAAAA09AAA09AA00A01902AA70FFFFF
FF04AAAAAAAAAAAAAAA09AAA09AAAAAAAAAAAA70FFFFF
FF02AAAAAAAAAAAAAAA0AAAA09AA01A02902AA70FFFFF
FF009AAAAAAAAAAAAAA0AAAA09AA77A78A78AA70FFFFF
FF001AAAAAAAAAAAAAA0AAAA09AA33A34A35AA70FFFFF
FFF00001111111111110AAAA19AA00A01A02AA70FFFFF
FFFFF000000000000000AAAA19AAAAAAAAAAAA70FFFFF
FFFFFFFFFFFFFFFFFFF08AAA08AAAAAAAAAAAA60FFFFF
FFFFFFFFFFFFFFFFFFF001100011111111111100FFFFF
FFFFFFFFFFFFFFFFFFF000000000000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_UM_MAILBOX_POLICY(_alias) ENTITY(rectangle,black,um_mailbox_policy,_alias,OFF UM_MAILBOX_POLICY)
!define OFF_UM_MAILBOX_POLICY(_alias,_label) ENTITY(rectangle,black,um_mailbox_policy,_label,_alias,OFF UM_MAILBOX_POLICY)
!define OFF_UM_MAILBOX_POLICY(_alias,_label,_shape) ENTITY(_shape,black,um_mailbox_policy,_label,_alias,OFF UM_MAILBOX_POLICY)
!define OFF_UM_MAILBOX_POLICY(_alias,_label,_shape,_color) ENTITY(_shape,_color,um_mailbox_policy,_label,_alias,OFF UM_MAILBOX_POLICY)
skinparam folderBackgroundColor<<OFF UM_MAILBOX_POLICY>> White