sprite $universal_security_group [48x40/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF000000000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF007AAA7000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAA900FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF008AAAAAAA600FFFFFFFFFF
FFFFFFFFFFFFF0000000FFFFF00AAAAAAAAA00FFFFFFFFFF
FFFFFFFFFFFF000131000FFFF02AAAAAAAAA10FFFFFFFFFF
FFFFFFFFFFF0029AAA9000FFF02AAAAAAAAA20FFFFFFFFFF
FFFFFFFFFFF01AAAAAAA00FFF00AAAAAAAAA10FFFFFFFFFF
FFFFFFFFFF00AAAAAAAA700FF00AAAAAAAA900FFFFFFFFFF
FFFFFFFFFF00AAAAAAAAA00FFF02AAAAAAA200FFFFFFFFFF
FFFFFFFFFF03AAAAAAAAA00FF0003AAAAA3000FFFFFFFFFF
FFFFFFFFFF03AAAAAAAAA000000000353000000FFFFFFFFF
FFFFFFFFFF00AAAAAAAAA00006A800000009A4000FFFFFFF
FFFFFFFFFF00AAAAAAAA7002AAAAA63237AAAAA100FFFFFF
FFFFFFFFFFF02AAAAAAA000AAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFFFFF0002AAAA90004AAAAAAAAAAAAAAAAA40FFFFFF
FFFFFFFF0000000010000001AAAAAAAAAAAAAAAA600FFFFF
FFFFFF0002AAA2000003AA8108AAAA8558AAAAAA800FFFFF
FFFFFF006AAAAA9767AAAAAA30AA70011007AAAAA00FFFFF
FFFFFF02AAAAAAAAAAAAAAAAA06605AAAA407AAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAA2005A922AA30AAAA10FFFFF
FFFFF00AAAAAAAAAAAAAAAAAA600A800009A07AAA20FFFFF
FFFFF00AAAAAAAAAAAAAAAAAA801A300003A1133300FFFFF
FFFFF00AAAAAAAAAAAAAAAAAAA02A200002A1000000FFFFF
FFFFF01AAAAAAAAAAAAAAAAAA902A200002A100000FFFFFF
FFFFF02AAAAAAAAAAAAAAAAAA219A988889506AA300FFFFF
FFFFF04AAAAAAAAAAAAAAAAAA17AAAAAAAA05A26A10FFFFF
FFFFF0000000000000000000007AAAAAAAA08A89A40FFFFF
FFFFF0000000000000000000007AAAAAAAA06AAAA20FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF07AAAAAAAA40AAA700FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF07AAAAAAAAA20A900FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF07AAAAAAAAA60A500FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF07AAAAAAAAA60A800FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF03AAAAAAAAA60A500FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF0000000000000A900FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF0000000000001100FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFF
}

!define OFF_UNIVERSAL_SECURITY_GROUP(_alias) ENTITY(rectangle,black,universal_security_group,_alias,OFF UNIVERSAL_SECURITY_GROUP)
!define OFF_UNIVERSAL_SECURITY_GROUP(_alias,_label) ENTITY(rectangle,black,universal_security_group,_label,_alias,OFF UNIVERSAL_SECURITY_GROUP)
!define OFF_UNIVERSAL_SECURITY_GROUP(_alias,_label,_shape) ENTITY(_shape,black,universal_security_group,_label,_alias,OFF UNIVERSAL_SECURITY_GROUP)
!define OFF_UNIVERSAL_SECURITY_GROUP(_alias,_label,_shape,_color) ENTITY(_shape,_color,universal_security_group,_label,_alias,OFF UNIVERSAL_SECURITY_GROUP)
skinparam folderBackgroundColor<<OFF UNIVERSAL_SECURITY_GROUP>> White