sprite $3rd_party_call_center_solution [46x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF0000000000000FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF000002345543100000FFFFFFFFFFFFFFFFFFFFF
FFFFFF00015AAAAAAAAA941000FFFFFFFFFFFFFFFFFFFF
FFFFF0005AAAAAAAAAAAAAA5000FFFFFFFFFFFFFFFFFFF
FFFF0008AAA7321111238AAA8000FFFFFFFFFFFFFFFFFF
FFF0008AA71000000000027AA7000FFFFFFFFFFFFFFFFF
FF0008AA50000FFFFF000006AA6000FFFFFFFFFFFFFFFF
FF002AA5000FFFFFFFFFF0007AA100FFFFFFFFFFFFFFFF
FF00AA8000FFFFFFFFFFFF0009A800FFFFFFFFFFFFFFFF
F003AA200FFFFFFFFFFFFFF004AA100FFFFFFFFFFFFFFF
F007AA00FFFFFFFFFFFFFFFF00AA500FFFFFFFFFFFFFFF
F00AA500FFFFFFFFFFFFFFFF006AA00FFFFFFFFFFFFFFF
F02AA100FFFFFFFFFFFFFFFF003AA10FFFFFFFFFFFFFFF
F03AA00FFFFFFFFFFFFFFFFFF02AA20FFFFFFFFFFFFFFF
F05AA000000FFFFFFFFFF000001AA20FFFFFFFFFFFFFFF
F05AA000000FFFFFFFFFF000001AA30FFFFFFFFFFFFFFF
F06AA0146100FFFFFFFF0026301AA30FFFFFFFFFFFFFFF
F06AA5AAA800FFFFFFFF008AA93AA30FFFFFFFFFFFFFFF
F06AAAAAAA00FFFFFFFF00AAAAAAA30FFFFFFFFFFFFFFF
F06AAAAAAA00FFFFFFFF00AAAAAAA30FFFFFFFFFFFFFFF
F06AAAAAAA00FFFFFFFF00AAAAAAA30FFFFFFFFFFFFFFF
F05AAAAAAA00FFFFFFFF00AAAAAAA30FFFFFFFFFFFFFFF
F019AAAAAA00FFFFFFFF00AAAAAA810FFFFFFFFFFFFFFF
F003AAAAAA00FFFFFFFF00AAAAA9000FFFFFFFFFFFFFFF
F003AAAAAA00FFFFFFFF00AA510000000000000000000F
FF02A7AAAA00FFFFFFFF00A80155555555555555555100
FF02A07AA800FFFFFFFF009109AAAAAAAAAAAAAAAAA800
FF02A0027100FFFFFFFF00200AAAAAAAAAAAAAAAAAAA00
FF01A0000000FFFFFFFF00000AAAAAAAAAAAAAAAAAAA00
FF00A100000FFFFFFFFFF0000AAAAAAAAAAAAAAAAAAA00
FF008600FFFFFFFFFFFFFFF00AAAA97679AAAAAAAAAA00
FF003A00FFFFFFFFFFFFFFF00AAAA200009AAAA5AAAA00
FF000A300FF0000000000FF00AAAA79910593842AAAA00
FFF004A200000000000000F00AAAAAAA30693884AAAA00
FFF0006A41028AAAAAA810000AAAAA6401995A53AAAA00
FFFF0003AAAAAAAAAAAA80000AAAA90004AAAAAAAAAA00
FFFFF0000238AAAAAAAA60000AAAAA98304AAAAAAAAA00
FFFFFF0000004555555300000AAAAAAAA02AAAAAAAAA00
FFFFFFFFFF000000000000F00AAAA588203AAAAAAAAA00
FFFFFFFFFFFF00000000FFF00AAAA000009AAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFF00AAAA9888AAAAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFF004AAAAAAAAAAAAAAAAA300
FFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000
FFFFFFFFFFFFFFFFFFFFFFFF000000000000000000000F
}

!define OFF_3RD_PARTY_CALL_CENTER_SOLUTION(_alias) ENTITY(rectangle,black,3rd_party_call_center_solution,_alias,OFF 3RD_PARTY_CALL_CENTER_SOLUTION)
!define OFF_3RD_PARTY_CALL_CENTER_SOLUTION(_alias,_label) ENTITY(rectangle,black,3rd_party_call_center_solution,_label,_alias,OFF 3RD_PARTY_CALL_CENTER_SOLUTION)
!define OFF_3RD_PARTY_CALL_CENTER_SOLUTION(_alias,_label,_shape) ENTITY(_shape,black,3rd_party_call_center_solution,_label,_alias,OFF 3RD_PARTY_CALL_CENTER_SOLUTION)
!define OFF_3RD_PARTY_CALL_CENTER_SOLUTION(_alias,_label,_shape,_color) ENTITY(_shape,_color,3rd_party_call_center_solution,_label,_alias,OFF 3RD_PARTY_CALL_CENTER_SOLUTION)
skinparam folderBackgroundColor<<OFF 3RD_PARTY_CALL_CENTER_SOLUTION>> White