sprite $fax_partner [39x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF0000000000000000000000FFFFFFFFFFFFFFF
F001455555555555555553000FFFFFFFFFFFFFF
F01AAAAAAAAAAAAAAAAAAA700FFFFFFFFFFFFFF
F04AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAA999999999999AAAA00FFFFFFFFFFFFFF
F05AAA5000000000000AAAA00FFFFFFFFFFFFFF
F05AAA8666666666666AAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAA61000000000000FFFFF
F05AAAAAAAAAAAAAAAA600000000000000FFFFF
F05AAAAAAAAAAAAAAAA109AAAAAAAAAA10FFFFF
F05AAAAAAAAAAAAAAAA00A000000000A20FFFFF
F05AAAAAAAAAAAAAAAA00A001111100A20FFFFF
F05AAAAAAAAAAAAAAAA00A001111100A20FFFFF
F05AAA744444444444400A006666620A20FFFFF
F05AAA500000000000000A000000000A20000FF
F05AAAAAAAAAA01AA5000A000000000A200000F
F05AAAAAAAAAA04AAA088A888888888A988400F
F05AAAAAAAAAA04AAA0AAAAAAAAAAAAAAAAA300
F05AAA988888804AAA0AAAAAAAAAAAAAAAAA900
F05AAA500000004AAA0AAAAAAAAAAAAAAAAAA00
F05AAA977777704AAA0AAAAAAAAAAAAAAAAAA00
F05AAAAAAAAAA04AAA0AAAAAAAAAAAAAAAAAA00
F05AAAAAAAAAA04AAA0AAA999999999AAAAAA00
F05AAAAAAAAAA04AAA0AAA000000000AAAAAA00
F05AAAAAAAAAA04AAA044A000000000A5444400
F00000000000000673000A000000000A2000000
F00000000000000000000A000000000A20FFFFF
FFFFFFFFFFFFFF00000007AAAAAAAAA900FFFFF
FFFFFFFFFFFFFFFFFFF000000000000000FFFFF
FFFFFFFFFFFFFFFFFFFF0000000000000FFFFFF
}

!define OFF_FAX_PARTNER(_alias) ENTITY(rectangle,black,fax_partner,_alias,OFF FAX_PARTNER)
!define OFF_FAX_PARTNER(_alias,_label) ENTITY(rectangle,black,fax_partner,_label,_alias,OFF FAX_PARTNER)
!define OFF_FAX_PARTNER(_alias,_label,_shape) ENTITY(_shape,black,fax_partner,_label,_alias,OFF FAX_PARTNER)
!define OFF_FAX_PARTNER(_alias,_label,_shape,_color) ENTITY(_shape,_color,fax_partner,_label,_alias,OFF FAX_PARTNER)
skinparam folderBackgroundColor<<OFF FAX_PARTNER>> White