sprite $lync_server_management_tool [48x31/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000FFFFFFF
F0000000000000000000000000000000000246780FFFFFFF
F008999999999999999999999996000699999999000FFFFF
F09AAAAAAAAAAAAAAAAAAAAAAAAA60079999999900000FFF
F0AAAAAAAAAAAAAAAAAAAAAAAAAA9007999999998900000F
F0AAAAAAAAAAAAAAAAAAAAAAAAAA9007995499997A867000
F0AAAAAAAAAAAAAAAAAAAAAAAAAA900799549999A652A900
F0AAAAAA408AAAAAAAAAAAAAAAAA90079954999900000A30
F0AAAAAA0007AAAAAAAAAAAAAAAA90079954999900000A40
F0AAAAAA10006AAAAAAAAAAAAAAA90079954999950006A10
F0AAAAAAA30005AAAAAAAAAAAAAA900799510599A39AA500
F0AAAAAAAA40004AAAAAAAAAAAAA900799999999022A700F
F0AAAAAAAAA50003AAAAAAAAAAAA9007999999990003600F
F0AAAAAAAAAA60001AAAAAAAAAAA9007999999990F0000FF
F0AAAAAAAAAAA60002AAAAAAAAAA9000000357880FFFFFFF
F0AAAAAAAAAAAA20008AAAAAAAAA90F0000000000FFFFFFF
F0AAAAAAAAAAA10006AAAAAAAAAA90FFFFFFF0000FFFFFFF
F0AAAAAAAAAA00008AAAAAAAAAAA90FFFFFFFFFFFFFFFFFF
F0AAAAAAAA800009AAAAAAAAAAAA90FFFFFFFFFFFFFFFFFF
F0AAAAAAA700009AAAAAAAAAAAAA90FFFFFFFFFFFFFFFFFF
F0AAAAAA60000AAAAAAAAAAAAAAA90FFFFFFFFFFFFFFFFFF
F0AAAAAA0002AAA200000009AAAA90FFFFFFFFFFFFFFFFFF
F0AAAAAA004AAAA000000009AAAA90FFFFFFFFFFFFFFFFFF
F0AAAAAAAAAAAAAAAAAAAAAAAAAA90FFFFFFFFFFFFFFFFFF
F0AAAAAAAAAAAAAAAAAAAAAAAAAA90FFFFFFFFFFFFFFFFFF
F0AAAAAAAAAAAAAAAAAAAAAAAAAA90FFFFFFFFFFFFFFFFFF
F0AAAAAAAAAAAAAAAAAAAAAAAAAA90FFFFFFFFFFFFFFFFFF
F08AAAAAAAAAAAAAAAAAAAAAAAAA50FFFFFFFFFFFFFFFFFF
F00566666666666666666666666400FFFFFFFFFFFFFFFFFF
F0000000000000000000000000000FFFFFFFFFFFFFFFFFFF
}

!define OFF_LYNC_SERVER_MANAGEMENT_TOOL(_alias) ENTITY(rectangle,black,lync_server_management_tool,_alias,OFF LYNC_SERVER_MANAGEMENT_TOOL)
!define OFF_LYNC_SERVER_MANAGEMENT_TOOL(_alias,_label) ENTITY(rectangle,black,lync_server_management_tool,_label,_alias,OFF LYNC_SERVER_MANAGEMENT_TOOL)
!define OFF_LYNC_SERVER_MANAGEMENT_TOOL(_alias,_label,_shape) ENTITY(_shape,black,lync_server_management_tool,_label,_alias,OFF LYNC_SERVER_MANAGEMENT_TOOL)
!define OFF_LYNC_SERVER_MANAGEMENT_TOOL(_alias,_label,_shape,_color) ENTITY(_shape,_color,lync_server_management_tool,_label,_alias,OFF LYNC_SERVER_MANAGEMENT_TOOL)
skinparam folderBackgroundColor<<OFF LYNC_SERVER_MANAGEMENT_TOOL>> White