sprite $mail_enabled_public_folder [48x43/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF000000000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF000256666666665100FFFFFFFFF
FFFFFFFFFFFFFFFFFFFF0003AAAAAAAAAAAAA10FFFFFFFFF
FFFFFFFFFFFFFFFFFFF0003AAAAAAAAAAAAAA40FFFFFFFFF
FFFFFFFFFFFFFFFFFF0004AAAAAAAAAAAAAAA50FFFFFFFFF
FFFFFFFFFFFFFFFFF0005AAAAAAAAAAAAAAAA50FFFFFFFFF
FF0000000000000000000000000000000000000FFFFFFFFF
F00133333333333333333333333333333333310FFFFFFFFF
F01AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA50FFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA50FFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA50FFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA50FFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA50FFFFFFFFF
F05AAAAAAA30000000000000000003AAAAAAA50FFFFFFFFF
F05AAAAAAA30000000000000000003AAAAAAA50FFFFFFFFF
F05AAAAAAA300000000000000AAA03AAAAAAA50FFFFFFFFF
F05AAAAAAA300000000000000AAA03AAAAAAA50FFFFFFFFF
F05AAAAAAA300000000000000AAA03AAAAAAA50FFFFFFFFF
F05AAAAAAA30000000000000000003AAAAAAA50FFFFFFFFF
F05AAAAAAA3000000000000000000022222221000000000F
F05AAAAAAA3000AAAAAAA000000000000000000000000000
F05AAAAAAA300000000000000007AAAAAAAAAAAAAAAAA400
F05AAAAAAA30002222222222000AAAAAAAAAAAAAAAAAAA00
F05AAAAAAA3000AAAAAAAAAA000AAAAAAAAAAAAAAAAAAA00
F05AAAAAAA30000000000000000AAAAAAAAAAAAAAAAAAA00
F05AAAAAAA30000000000000000AAAAAAAAAAAAAAAAAAA00
F05AAAAAAA53333333333333300AAAAAAAAAAAAAAAAAAA00
F05AAAAAAAAAAAAAAAAAAAAAA00AAA0003AAAA90004AAA00
F05AAAAAAAAAAAAAAAAAAAAAA00AAA0068AAAA98104AAA00
F05AAAAAAAAAAAAAAAAAAAAAA00AAA0507AAAAA3124AAA00
F05AAAAAAAAAAAAAAAAAAAAAA00AAA48717AAA41947AAA00
F05AAAAAAAAAAAAAAAAAAAAAA00AAAAAA704221AA9AAAA00
F05AAAAAAAAAAAAAAAAAAAAAA00AAAAAAA7000AAAAAAAA00
F00111111111111111111111100AAAAAAA9001AAAAAAAA00
F00000000000000000000000000AAAAAAAA869AAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFFFF006AAAAAAAAAAAAAAAAA400
FFFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000
FFFFFFFFFFFFFFFFFFFFFFFFFF000000000000000000000F
}

!define OFF_MAIL_ENABLED_PUBLIC_FOLDER(_alias) ENTITY(rectangle,black,mail_enabled_public_folder,_alias,OFF MAIL_ENABLED_PUBLIC_FOLDER)
!define OFF_MAIL_ENABLED_PUBLIC_FOLDER(_alias,_label) ENTITY(rectangle,black,mail_enabled_public_folder,_label,_alias,OFF MAIL_ENABLED_PUBLIC_FOLDER)
!define OFF_MAIL_ENABLED_PUBLIC_FOLDER(_alias,_label,_shape) ENTITY(_shape,black,mail_enabled_public_folder,_label,_alias,OFF MAIL_ENABLED_PUBLIC_FOLDER)
!define OFF_MAIL_ENABLED_PUBLIC_FOLDER(_alias,_label,_shape,_color) ENTITY(_shape,_color,mail_enabled_public_folder,_label,_alias,OFF MAIL_ENABLED_PUBLIC_FOLDER)
skinparam folderBackgroundColor<<OFF MAIL_ENABLED_PUBLIC_FOLDER>> White