sprite $push_notification_service [41x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF000000000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF000145530000FFFFFFF
FFFFFFFFFFFFFFFFFFFF00016AAAAAA3000FFFFFF
FFFFFFFFFFFFFFFFFFFF001AAAAAAAAA6000FFFFF
FFFFFFFFFFFFFFFFFFF0009AAAA54AAAA400FFFFF
FF00000000000000000005AAAA102AAAAA000FFFF
F00000000000000000000AAAAA512AAAAA400FFFF
F003AAAAAAAAAAAAAAA20AAAAAA22AAAAA700FFFF
F03AAAAAAAAAAAAAAAA10AAAAAA22AAAAA700FFFF
F06AAAAAAAAAAAAAAAA10AAAAAA22AAAAA700FFFF
F06AAAAAAAAAAAAAAAA40AAAAAA22AAAAA400FFFF
F06AAAAAAAAAAAAAAAA706AAAAA44AAAAA000FFFF
F06AAAAAAAAAAAAAAAAA009AAAAAAAAAA500FFFFF
F06AAAAAAAAAAAAAAAAA802AAAAAAAAA6000FFFFF
F06AAAAAAAAAAAAAAAAAA5017AAAAAA4000FFFFFF
F06AAAAAAAAAAAAAAAAAAA600156630000FFFFFFF
F06AAAAAAAAAAAAAAAAAAAAA30000000FFFFFFFFF
F06AAAAAAAAAAAAAAAAAAAAAAA999200FFFFFFFFF
F06AAAAAAAAAAAAAAAAAAAAAAAAAA200FFFFFFFFF
F06AAAAAAAAAAAAAAAAAAAAAAAAAA200FFFFFFFFF
F06AAAAAAAAAAAAAAAAAAAAAAAAAA200FFFFFFFFF
F06AAAAAAAAAAAAAAAAAAAAA317AA20000FFFFFFF
F06AAAAAAAAAAAAAAAAAA9200008A100000FFFFFF
F06AAAAAAAAAAAAAAAAAA1048902703A6200FFFFF
F06AAAAAAAAAAAAAAAAAA04AAA20009AA900FFFFF
F06AAAAAAAAAAAAAAAAAA10AAA9565AAA600FFFFF
F06AAAAAAAAAAAAAAA55A407AAAAAAAAA200000FF
F06AAAAAAAAAAAAAA2000029AAAAAAAAA6000000F
F06AAAAAAAAAAAAA8056119AA952136AAA6037200
F06AAAAAAAAAAAAA10AAAAAA700000009AAAAA600
F06AAAAAAAAAAAAA05AAAAA7000000001AAAAAA00
F06AAAAAAAAAAAAA028AAAA10000000005AAAA600
F04AAAAAAAAAAAAA6002AA800000000002AA81000
F008AAAAAAAAAAAAAA30AA600000000000AA700FF
F0000000000000000000AA600000000000AA7000F
FF000000000000000003AA900000000002AA80000
FFFF000000000000028AAAA20000000006AAAA600
FFFFFFFFFFFFFFF005AAAAA8000000002AAAAAA10
FFFFFFFFFFFFFFFF00AAAAAA80000001AAAAAA700
FFFFFFFFFFFFFFFF0056109AAA73248AAA601510F
FFFFFFFFFFFFFFFFF0000018AAAAAAAAA6000000F
FFFFFFFFFFFFFFFFF0000005AAAAAAAAA300000FF
FFFFFFFFFFFFFFFFFFFF0009AA9454AAA700FFFFF
FFFFFFFFFFFFFFFFFFFF004AAA20007AAA00FFFFF
FFFFFFFFFFFFFFFFFFFF00027900002A5100FFFFF
FFFFFFFFFFFFFFFFFFFFF0000000F000000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFF0000FF0000FFFFFFFF
}

!define OFF_PUSH_NOTIFICATION_SERVICE(_alias) ENTITY(rectangle,black,push_notification_service,_alias,OFF PUSH_NOTIFICATION_SERVICE)
!define OFF_PUSH_NOTIFICATION_SERVICE(_alias,_label) ENTITY(rectangle,black,push_notification_service,_label,_alias,OFF PUSH_NOTIFICATION_SERVICE)
!define OFF_PUSH_NOTIFICATION_SERVICE(_alias,_label,_shape) ENTITY(_shape,black,push_notification_service,_label,_alias,OFF PUSH_NOTIFICATION_SERVICE)
!define OFF_PUSH_NOTIFICATION_SERVICE(_alias,_label,_shape,_color) ENTITY(_shape,_color,push_notification_service,_label,_alias,OFF PUSH_NOTIFICATION_SERVICE)
skinparam folderBackgroundColor<<OFF PUSH_NOTIFICATION_SERVICE>> White