sprite $site_mailbox [48x44/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF0000000000000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF000466666666664000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFF0006AAAAAAAAAAAA400FFFFFFF
FFFFFFFFFFFFFFFFFFFFF0007AAAAAAAAAAAAAA00FFFFFFF
FFFFFFFFFFFFFFFFFFFF0008AAAAAAAAAAAAAAA00FFFFFFF
FFFFFFFFFFFFFFFFFFF0009AAAAAAAAAAAAAAAA00FFFFFFF
FF000000000000000000000000000000000000000FFFFFFF
F0025555555555555555555555555555555555500FFFFFFF
F02AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
F06AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
F06AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
F06AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
F06AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
F06AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
F06AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
F06AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
F06AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
F06AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
F06AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
F06AAAAAAAAAAAAAAAAAAAAAA70000000000000000000FFF
F06AAAAAAAAAAAAAAAAAAAAAA70111111111111111100FFF
F06AAAAAAAAAAAAAAAAAAAAAA70AAAAAAAAAAAAAAAA00FFF
F06AAAAAAAAAAAAAAAAAAAAAA001000000000000002000FF
F06AAAAAAAAAAAAAAAAAAAAAA006666666666666666600FF
F06AAAAAAAAAAAAAAAAAAAAAA01A666666666666666A00FF
F06AAAAAAAAAAAAAAAAAAAAAA01A000000000002221A00FF
F06AAAAAAAAAAAAAAAAAAAAAA01A00000000000AA71A00FF
F06AAAAAAAAAAAAAAAAAAAAA701A00000000000AA71A00FF
F06AAAAAAAAAAAAAAAAAAAAA408A00000000000AA71A200F
F06AAAAAAAAAAAAAAAAAAAAA21AA000000000000001A600F
F06AAAAAAAAAAAAAAAAAAAAA03AA00AAAAAA8000001AA00F
F06AAAAAAAAAAAAAAAAAAAA706AA000000000000001AA20F
F06AAAAAAAAAAAAAAAAAAAA30AAA00AAAAAAAA10001AA400
F06AAAAAAAAAAAAAAAAAAAA21AAA002222222200001AA600
F024444444444444444444404AAA000000000000001AA900
F000000000000000000000005AAAAAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFF05AAAAAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFF05AAAAAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFF05AAAAAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFF05AAAAAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFF05AAAAAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFF0000000000000000000000000
FFFFFFFFFFFFFFFFFFFFFFF0000000000000000000000000
}

!define OFF_SITE_MAILBOX(_alias) ENTITY(rectangle,black,site_mailbox,_alias,OFF SITE_MAILBOX)
!define OFF_SITE_MAILBOX(_alias,_label) ENTITY(rectangle,black,site_mailbox,_label,_alias,OFF SITE_MAILBOX)
!define OFF_SITE_MAILBOX(_alias,_label,_shape) ENTITY(_shape,black,site_mailbox,_label,_alias,OFF SITE_MAILBOX)
!define OFF_SITE_MAILBOX(_alias,_label,_shape,_color) ENTITY(_shape,_color,site_mailbox,_label,_alias,OFF SITE_MAILBOX)
skinparam folderBackgroundColor<<OFF SITE_MAILBOX>> White