sprite $skype_for_business_room_system [48x31/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00576120000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0072013357200FFFF
FFFFFFFFFFFFFFFFF00000FFFFFFFFF0320000000710FFFF
FFFFFFFFFFFFFFFF0089600FFFFFFFF05101876710800FFF
FFFFFFFFFFFFFFFF07BBB30FFFFFFFF01303800320330FFF
FFFFFFFFFFFFFFF00ABBB60FFFFFFFF00401876300040FFF
FFFFFFFF000FFFFF09BBB50FFFF000F00500026770040FFF
FFFFFFF00000FFF002BBA00FFF0000000703600680060FFF
FFFFFF00ABB10F00210002100007BB2004107887100700FF
FFFFFF04BBB90F06BB879BB2000BBBB000720110000700FF
FFFFFF06BBBB000ABBBBBBB8003BBBB00005743301710FFF
FFFFFF03BBB8000999999999000BBBB0FF00011265100FFF
FFFFF0006A900000000000000004A9000FFF00000000FFFF
FFFF0058000530BBBBBBBBBB5091003900FFFFFFFFFFFFFF
FFFF04BBBBB908BBBBBBBBBBB13BBBBBB0FFFFFFFFFFFFFF
FFFF08BBBBB04BBBBBBBBBBBB908BBBBB10FFFFFFFFFFFFF
FFFF0ABBBB31BBBBBBBBBBBBBB40BBBBB30FFFFFFFFFFFFF
FFF00BBBB709BBBBBBBBBBBBBBB03BBBB50FFFFFFFFFFFFF
FFF00000006BBBBBBBBBBBBBBBB80000000FFFFFFFFFFFFF
FFF0000002BBBBBBBBBBBBBBBBBB2000000FFFFFFFFFFFFF
FFFFFFFF08BBBBBBBBBBBBBBBBBBB0FFFFFFFFFFFFFFFFFF
FFFFFFFF0677777777777777777770FFFFFFFFFFFFFFFFFF
FFFFFFFF0000000000000000000000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_ROOM_SYSTEM(_alias) ENTITY(rectangle,black,skype_for_business_room_system,_alias,OFF SKYPE_FOR_BUSINESS_ROOM_SYSTEM)
!define OFF_SKYPE_FOR_BUSINESS_ROOM_SYSTEM(_alias,_label) ENTITY(rectangle,black,skype_for_business_room_system,_label,_alias,OFF SKYPE_FOR_BUSINESS_ROOM_SYSTEM)
!define OFF_SKYPE_FOR_BUSINESS_ROOM_SYSTEM(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_room_system,_label,_alias,OFF SKYPE_FOR_BUSINESS_ROOM_SYSTEM)
!define OFF_SKYPE_FOR_BUSINESS_ROOM_SYSTEM(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_room_system,_label,_alias,OFF SKYPE_FOR_BUSINESS_ROOM_SYSTEM)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_ROOM_SYSTEM>> White