sprite $skype_for_business_phone_edition [48x33/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000FFFFFFF
FFFFFF00000000000000000000000000F0036311000FFFFF
FFFFF000662000666666666666666610007201347600FFFF
FFFFF02BBBB70BBBBBBBBBBBBBBBBBB00230002102700FFF
FFFFF07BBBBB0BBBAAAAAAAAAAAABBB00400187780150FFF
FFFFF06BBBBB0BBA000000000000ABB00140470040070FFF
FFFFF06BBBBB0BBA000000000000ABB000601787300700FF
FFFFF05BBBBB0BBA000000000000ABB000600004820700FF
FFFFF04BBBBA0BBA000000000000ABB000704600820320FF
FFFFF04BBBBA0BBA222222222222ABB000240677600030FF
FFFFF04BBBB90BBBBBBBBBBBBBBBBBB000055000000610FF
FFFFF04BBBB90BBBBBBBBBBBBBBBBBB00F00267753640FFF
FFFFF03BBBB90BBBB229722A422BBBB00FFF000001000FFF
FFFFF03BBBB90BBBB009600A100BBBB00FFFFF000000FFFF
FFFFF03BBBB90BBBBBBBBBBBBBBBBBB00FFFFFFFFFFFFFFF
FFFFF04BBBB90BBBB009500A000ABBB00FFFFFFFFFFFFFFF
FFFFF04BBBBA0BBBB55A955A756BBBB00FFFFFFFFFFFFFFF
FFFFF04BBBBA0BBBB88A988B888BBBB00FFFFFFFFFFFFFFF
FFFFF05BBBBB0BBBB009500A000ABBB00FFFFFFFFFFFFFFF
FFFFF06BBBBB0BBBB99AA99BA9ABBBB00FFFFFFFFFFFFFFF
FFFFF06BBBBB0BBBBBBBBBBBBBBBBBB00FFFFFFFFFFFFFFF
FFFFF07BBBBB0BBBBBBBBBBBBBBBBBB00FFFFFFFFFFFFFFF
FFFFF04BBBB90BBBBBBBBBBBBBBBBBB00FFFFFFFFFFFFFFF
FFFFF004996003999999999999999940FFFFFFFFFFFFFFFF
FFFFFF00000000000000000000000000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_PHONE_EDITION(_alias) ENTITY(rectangle,black,skype_for_business_phone_edition,_alias,OFF SKYPE_FOR_BUSINESS_PHONE_EDITION)
!define OFF_SKYPE_FOR_BUSINESS_PHONE_EDITION(_alias,_label) ENTITY(rectangle,black,skype_for_business_phone_edition,_label,_alias,OFF SKYPE_FOR_BUSINESS_PHONE_EDITION)
!define OFF_SKYPE_FOR_BUSINESS_PHONE_EDITION(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_phone_edition,_label,_alias,OFF SKYPE_FOR_BUSINESS_PHONE_EDITION)
!define OFF_SKYPE_FOR_BUSINESS_PHONE_EDITION(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_phone_edition,_label,_alias,OFF SKYPE_FOR_BUSINESS_PHONE_EDITION)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_PHONE_EDITION>> White