sprite $skype_for_business_server_management_tool [48x37/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000FFFFFF
FFFFFF00000000000000000000000000001777552000FFFF
FFFFF0059999999999999999999999000160001137200FFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAA00600014300720FFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAA006003845810700FF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAA003107700200500FF
FFFFF00AAAAAA6AAAAAAAAAAAAAAAAA003100787500320FF
FFFFF00AAAAA000AAAAAAAAAAAAAAAA002200004840310FF
FFFFF00AAAAA1001AAAAAAAAAAAAAAA000707600840170FF
FFFFF00AAAAAA2000AAAAAAAAAAAAAA0F0620787600080FF
FFFFF00AAAAAAA2000AAAAAAAAAAAAA0F0073000000250FF
FFFFF00AAAAAAAA30009AAAAAAAAAAA0FF005766413700FF
FFFFF00AAAAAAAAA40009AAAAAAAAAA0FFF0000013200FFF
FFFFF00AAAAAAAAAA50009AAAAAAAAA0FFFFF0000000FFFF
FFFFF00AAAAAAAAAA40009AAAAAAAAA0FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAA2000AAAAAAAAAAA0FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAA1000AAAAAAAAAAAA0FFFFFFFFFFFFFFFF
FFFFF00AAAAAAA0001AAAAAAAAAAAAA0FFFFFFFFFFFFFFFF
FFFFF00AAAAAA0001AAAAAAAAAAAAAA0FFFFFFFFFFFFFFFF
FFFFF00AAAAA0003AA90000003AAAAA0FFFFFFFFFFFFFFFF
FFFFF00AAAAA005AAA60000000AAAAA0FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAA0FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAA0FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAA0FFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAA0FFFFFFFFFFFFFFFF
FFFFF008AAAAAAAAAAAAAAAAAAAAAA20FFFFFFFFFFFFFFFF
FFFFFF00000000000000000000000000FFFFFFFFFFFFFFFF
FFFFFFF00000000000000000000000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_SERVER_MANAGEMENT_TOOL(_alias) ENTITY(rectangle,black,skype_for_business_server_management_tool,_alias,OFF SKYPE_FOR_BUSINESS_SERVER_MANAGEMENT_TOOL)
!define OFF_SKYPE_FOR_BUSINESS_SERVER_MANAGEMENT_TOOL(_alias,_label) ENTITY(rectangle,black,skype_for_business_server_management_tool,_label,_alias,OFF SKYPE_FOR_BUSINESS_SERVER_MANAGEMENT_TOOL)
!define OFF_SKYPE_FOR_BUSINESS_SERVER_MANAGEMENT_TOOL(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_server_management_tool,_label,_alias,OFF SKYPE_FOR_BUSINESS_SERVER_MANAGEMENT_TOOL)
!define OFF_SKYPE_FOR_BUSINESS_SERVER_MANAGEMENT_TOOL(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_server_management_tool,_label,_alias,OFF SKYPE_FOR_BUSINESS_SERVER_MANAGEMENT_TOOL)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_SERVER_MANAGEMENT_TOOL>> White