sprite $skype_for_business_control_panel [48x45/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFF
FFFFFF000000FFFFFFFF00FFF00FFFFF00001000000FFFFF
FFFFFF000000FFFFFF0000FFF0000FFF0077787772000FFF
FFFFFF00BB80FFFFF00110FFF02100F007200000167000FF
FFFFFF00BB80FFFF004B10FFF03A200015000133102700FF
FFFFFF00BB80FFFF01BB10FFF03BA000240048668403500F
FFFFFF00BB80FFF009BB10FFF03BB600060077003500700F
FFFFFF00BB70FFF00BBB10FFF03BBA00070068730000520F
FFFFFF00AB40FFF02BBB100F003BBB10070004778500520F
FFFFFF008B10FFF03BBB910002ABBB20070020005800520F
FFFFFF006B10FFF01BBBBB607BBBBB100530771167001500
FFFFFF006B10FFF00BBBBBBABBBBB9000070178871001600
FFFFFF006B10FFF008BBBBBBBBBBB500F027000000003400
FFFFFF006B10FFFF00ABBBBBBBBB900FF00177433003700F
FFFFFF006B10FFFF002ABBBBBBBA000FFF0001334665000F
FFFFFF006B10FFFFF0019BBBBB8000FFFFF00000000000FF
FFFFFF006B10FFFFFF008BBBBB500FFFFFFFFFFF0000FFFF
FFFFFF006B10FFFFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFFF006B10FFFFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFFF006B10FFFFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFFF006B10FFFFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFFF006B10FFFFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFF0006B100FFFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFF01BBBBA00FFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFF03BBBBA00FFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFF03BBBBA00FFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFF03BBBBA00FFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFF03BBBBA00FFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFF03BBBBA00FFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFF03BBBBA00FFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFF03BBBBA00FFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFF03BBBBA00FFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFF03BBBBA00FFFF008BBBBB50FFFFFFFFFFFFFFFFFFFF
FFFFF03BBBBA00FFFF008B305B50FFFFFFFFFFFFFFFFFFFF
FFFFF03BBBBA00FFFF008B205B40FFFFFFFFFFFFFFFFFFFF
FFFFF03BBBBA00FFFFF03BA8AB00FFFFFFFFFFFFFFFFFFFF
FFFFF02BBBBA00FFFFF005BBA200FFFFFFFFFFFFFFFFFFFF
FFFFF000000000FFFFFF0000000FFFFFFFFFFFFFFFFFFFFF
FFFFFF0000000FFFFFFFFF000FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_CONTROL_PANEL(_alias) ENTITY(rectangle,black,skype_for_business_control_panel,_alias,OFF SKYPE_FOR_BUSINESS_CONTROL_PANEL)
!define OFF_SKYPE_FOR_BUSINESS_CONTROL_PANEL(_alias,_label) ENTITY(rectangle,black,skype_for_business_control_panel,_label,_alias,OFF SKYPE_FOR_BUSINESS_CONTROL_PANEL)
!define OFF_SKYPE_FOR_BUSINESS_CONTROL_PANEL(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_control_panel,_label,_alias,OFF SKYPE_FOR_BUSINESS_CONTROL_PANEL)
!define OFF_SKYPE_FOR_BUSINESS_CONTROL_PANEL(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_control_panel,_label,_alias,OFF SKYPE_FOR_BUSINESS_CONTROL_PANEL)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_CONTROL_PANEL>> White