sprite $tdm_pbx [48x38/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF000000000000000000000000000000000000000000FFFF
F00156666666666666666666666666666666666664000FFF
F019AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
F05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA000FF
F06AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA000FF
F06AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA000FF
F06AAAA000000000000AAAA505AA11AA308A902AAAA000FF
F06AAAA0AAAAAAAAAA0AAAA606AA12AA408A904AAAA000FF
F06AAAA0AAAAAAAAAA0AAAAAAAAAAAAAAAAAAAAAAAA000FF
F06AAAA0AAAAAAAAAA0AAAAAAAAAAAAAAAAAAAAAAAA000FF
F06AAAA0AAAAAAAAAA0AAAA818AA35AA719AA17AAAA000FF
F06AAAA0AAAAAAAAAA0AAAA404AA00AA107A801AAAA000FF
F06AAAA000000000000AAAAA7AAA78AA97AAA79AAAA000FF
F06AAAA444444444444AAAAAAAAAAAAAAAAAAAAAAAA000FF
F06AAAAAAAAAAAAAAAAAAAAAAAA98888888888888880000F
F06AAAAAAAAAAAAAAAAAAAAAAA800000000000000000000F
F06AAAA000000000000AAAAAA90079999999999999998200
F06AAAAAAAAAAAAAAAAAAAAAA708AAAAAAAAAAAAAAAAA900
F06AAAAAAAAAAAAAAAAAAAAAA70AAAAAAAAA49AAAAAAAA00
F06AAAAAAAAAAAAAAAAAAAAAA70AAAAAAAA3009AAAAAAA00
F06AAAAAAAAAAAAAAAAAAAAAA70AAAAAAA41020AAAAAAA00
F06AAAAAAAAAAAAAAAAAAAAAA70AAAAAAA5A0A3AAAAAAA00
F00000000000000000000000000AAAAAAAAA0AAAAAAAAA00
F00000000000000000000000000AAAA55AAA0AAA75AAAA00
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAA904AAAAA706AAAA00
FFFFFFFFFFFFFFFFFFFFFFFFF00AA000005AAA9000008A00
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAA10AAAAA30AAAAA00
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAA20AAA1AAA41AAAA00
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAA0AAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAA7A0A6AAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAA44070AAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAA91008AAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAA908AAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFFFF009AAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFFFFFFFFFFFFF0029AAAAAAAAAAAAAAAA500
FFFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000
FFFFFFFFFFFFFFFFFFFFFFFFFF000000000000000000000F
}

!define OFF_TDM_PBX(_alias) ENTITY(rectangle,black,tdm_pbx,_alias,OFF TDM_PBX)
!define OFF_TDM_PBX(_alias,_label) ENTITY(rectangle,black,tdm_pbx,_label,_alias,OFF TDM_PBX)
!define OFF_TDM_PBX(_alias,_label,_shape) ENTITY(_shape,black,tdm_pbx,_label,_alias,OFF TDM_PBX)
!define OFF_TDM_PBX(_alias,_label,_shape,_color) ENTITY(_shape,_color,tdm_pbx,_label,_alias,OFF TDM_PBX)
skinparam folderBackgroundColor<<OFF TDM_PBX>> White