sprite $voice_mail_preview_partner [40x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF0000000000000000000000FFFFFFFFFFFFFFFF
F001455555555555555553000FFFFFFFFFFFFFFF
F01AAAAAAAAAAAAAAAAAAA600FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAA999999999999AAAA00FFFFFFFFFFFFFFF
F05AAA5000000000000AAAA00FFFFFFFFFFFFFFF
F05AAA8666666666666AAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
F05AAAAAAAAAAAAA99999990000000000000000F
F05AAAAAAAAAAA8000000000000000000000000F
F05AAA7444444410566666666666666666666200
F05AAA5000000002AAAAAAAAAAAAAAAAAAAAAA00
F05AAAAAAAAAAA02AAAAAAAAAAAAAAAAAAAAAA00
F05AAAAAAAAAAA02AAAA5238AAAAAA7227AAAA00
F05AAAAAAAAAAA02AA8100005AAAA300003AAA00
F05AAA9888888802AA20263008AA50155005AA00
F05AAA5000000002A901AAA404AA008AA701AA00
F05AAA9777777702A702AAA703AA00AAAA01AA00
F05AAAAAAAAAAA02A9009AA206AA106AA502AA00
F05AAAAAAAAAAA02AA300310057720022007AA00
F05AAAAAAAAAAA02AAA3000000000000006AAA00
F05AAAAAAAAAAA02AAAA87666666666679AAAA00
F000000000000002AAAAAAAAAAAAAAAAAAAAAA00
F000000000000002AAAAAAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFF01AAAAAAAAAAAAAAAAAAAAA500
FFFFFFFFFFFFFF00000000000000000000000000
FFFFFFFFFFFFFFF000000000000000000000000F
}

!define OFF_VOICE_MAIL_PREVIEW_PARTNER(_alias) ENTITY(rectangle,black,voice_mail_preview_partner,_alias,OFF VOICE_MAIL_PREVIEW_PARTNER)
!define OFF_VOICE_MAIL_PREVIEW_PARTNER(_alias,_label) ENTITY(rectangle,black,voice_mail_preview_partner,_label,_alias,OFF VOICE_MAIL_PREVIEW_PARTNER)
!define OFF_VOICE_MAIL_PREVIEW_PARTNER(_alias,_label,_shape) ENTITY(_shape,black,voice_mail_preview_partner,_label,_alias,OFF VOICE_MAIL_PREVIEW_PARTNER)
!define OFF_VOICE_MAIL_PREVIEW_PARTNER(_alias,_label,_shape,_color) ENTITY(_shape,_color,voice_mail_preview_partner,_label,_alias,OFF VOICE_MAIL_PREVIEW_PARTNER)
skinparam folderBackgroundColor<<OFF VOICE_MAIL_PREVIEW_PARTNER>> White