sprite $voip_gateway [48x17/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF000000000000000000000000000000000000000000000F
F0001333333333333333333333333333333333333332000F
F004AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7000
F019AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA500
F01AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA800
F01AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA800
F01AAAAAAA959AAAA67AAAA75AAAA959AAAA57AAAAAAA800
F01AAAAAAA201AAA700AAAA006AAA202AAA600AAAAAAA800
F01AAAAAAA716AAA913AAAA419AAA717AAA914AAAAAAA800
F01AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA800
F01AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA800
F01AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA800
F01AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA800
F01AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA700
F00000000000000000000000000000000000000000000000
F00000000000000000000000000000000000000000000000
}

!define OFF_VOIP_GATEWAY(_alias) ENTITY(rectangle,black,voip_gateway,_alias,OFF VOIP_GATEWAY)
!define OFF_VOIP_GATEWAY(_alias,_label) ENTITY(rectangle,black,voip_gateway,_label,_alias,OFF VOIP_GATEWAY)
!define OFF_VOIP_GATEWAY(_alias,_label,_shape) ENTITY(_shape,black,voip_gateway,_label,_alias,OFF VOIP_GATEWAY)
!define OFF_VOIP_GATEWAY(_alias,_label,_shape,_color) ENTITY(_shape,_color,voip_gateway,_label,_alias,OFF VOIP_GATEWAY)
skinparam folderBackgroundColor<<OFF VOIP_GATEWAY>> White