sprite $watcher_node [44x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF000010000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF000005A810000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF00003AAAAA60000FFFFFFFFFFFFFFFFF
FFFFFFFFFFF00028AAAAAAA940000FFFFFFFFFFFFFFF
FFFFFFFF000016AAAAAAAAAAA830000FFFFFFFFFFFFF
FFFFFFF00004AAAAAAAAAAAAAAA610000FFFFFFFFFFF
FFFFFF0001AAAAAAAAAAAAAAAAAAA50000FFFFFFFFFF
FFFF00018AAAAAAAAAAAAAAAAAAAAA930000FFFFFFFF
FF00005AAAAAAAAAAAAAAAAAAAAAAAAA720000FFFFFF
F0003AAAAAAAAAAAAAAAAAAAAAAAAAAAAA50000FFFFF
F0003AAAAAAAAAAAAAAAAAAAAAAAAAAAAA70000FFFFF
F020016AAAAAAAAAAAAAAAAAAAAAAAAA8200400FFFFF
F05940027AAAAAAAAAAAAAAAAAAAAA940028A00FFFFF
F05AA820039AAAAAAAAAAAAAAAAAA60016AAA00FFFFF
F05AAAA70005AAAAAAAAAAAAAAA90004AAAAA00FFFFF
F05AAAAAA50017AAAAAAAAAAA930029AAAAAA00FFFFF
F05AAAAAAA830038AAAAAAAA50017AAAAAAAA00FFFFF
F05AAAAAAAAA71005AAAAA81004AAAAAAAAAA00FFFFF
F05AAAAAAAAAAA50007A91002AAAAAAAAAAAA00FFFFF
F05AAAAAAAAAAAA940010018AAAAAAAAAAAAA00FFFFF
F05AAAAAAAAAAAAAA72016AAAAAAAAAAAAAAA00FFFFF
F05AAAAAAAAAAAAAAAA04AAAAAAAAAAAAAAAA00FFFFF
F05AAAAAAAAAAAAAAAA04AAAAAAAAAAAAAAAA00FFFFF
F05AAAAAAAAAAAAAAAA04AAAAAAAAAAAAAAAA00FFFFF
F05AAAAAAAAAAAAAAAA04AAAAAAAAAAAAAAAA00FFFFF
F05AAAAAAAAAAAAAAAA04AAAAAAAAAAAAAAAA00FFFFF
F05AAAAAAAAAAAAAAAA04AAAAAAAAAAAAAAAA00FFFFF
F05AAAAAAAAAAAAAAAA04AAAAAAAAAAAAAAAA00FFFFF
F05AAAAAAAAAAAAAAAA04AAAAAAAAAAAAAAAA00FFFFF
F05AAAAAAAAAAAAAAAA04AAAAAAAAAAAAAAAA00FFFFF
F05AAAAAAAAAAAAAAAA04AAAAAAAAAAAAAAAA00FFFFF
F0029AAAAAAAAAAAAAA04AAAAAAAAAAAAAA5000FFFFF
F00004AAAAAAAAAAAAA01226AAAAAAAAA710000FFFFF
FFF00017AAAAAAAAAAA001106AAAAAA9300010000FFF
FFFF00001AAAAAAAAA005AA11AAAAA400005AA100FFF
FFFFFF00003AAAAA9105A38509AA6100000A379100FF
FFFFFFF000016AA9205A50220000000000040099100F
FFFFFFFFFF00018204A92222222222222222224A9000
FFFFFFFFFFF000003AAAAA99AAAAAAAAAAA99AAAA800
FFFFFFFFFFFF00003AA7000001AA41AA5000002AA700
FFFFFFFFFFFFFF0003A50000006A006A2000000AA000
FFFFFFFFFFFFFFF000A800000089003A3000002A4000
FFFFFFFFFFFFFFFF003A710005A2000AA30003A9000F
FFFFFFFFFFFFFFFF00026888972000005898884000FF
FFFFFFFFFFFFFFFFF000000000000F000000000000FF
FFFFFFFFFFFFFFFFFFF000000000FFF000000000FFFF
}

!define OFF_WATCHER_NODE(_alias) ENTITY(rectangle,black,watcher_node,_alias,OFF WATCHER_NODE)
!define OFF_WATCHER_NODE(_alias,_label) ENTITY(rectangle,black,watcher_node,_label,_alias,OFF WATCHER_NODE)
!define OFF_WATCHER_NODE(_alias,_label,_shape) ENTITY(_shape,black,watcher_node,_label,_alias,OFF WATCHER_NODE)
!define OFF_WATCHER_NODE(_alias,_label,_shape,_color) ENTITY(_shape,_color,watcher_node,_label,_alias,OFF WATCHER_NODE)
skinparam folderBackgroundColor<<OFF WATCHER_NODE>> White