sprite $active_directory_federation_services_server_ghosted [37x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF00000000000000000FFFFFFFFFFFFF
FFFFFF0000000000000000000FFFFFFFFFFFF
FFFFF003AAAAAAAAAAAAAAA500FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAA65555555555AAA00FFFFFFFFFFF
FFFFF00AAA20000000001AAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA0000FFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA0000FFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAA403500FFFFFFFF
FFFFF00AAAAAAAAAAAAAAAA0265100FFFFFFF
FFFFF00AAAAAAAAAAAAAAA30653500FFFFFFF
FFFFF00AAAAAAAAAAAAAAA035365200FFFFFF
FFFFF00AAAAAAAAAAAAAA3053443500FFFFFF
FFFFF00AAA8888888888703320034200FFFFF
FFFFF00AAA1000000000003500013500FFFFF
FFFFF00AAAAAAAAAAAA70255311364200FFFF
FFFFF00AAAAAAAAAAAA21553043143500FFFF
FFFFF00AAAAAAAAAAA7045331350364200FFF
FFFFF00AAA2000000001535036531435000FF
FFFFF00AAA5444444204353165351364200FF
FFFFF00AAAAAAAAAA0135225535432246000F
FFFFF00AAAAAAAAA60351003223210034300F
FFFFF00AAAAAAAAA015510033223100246100
FFFFF00444444443055352255354322464400
FFFFF00000000000153553553553643644600
FFFFF00000000000022222222222222222200
FFFFFFFFFFFFFFF0000000000000000000000
FFFFFFFFFFFFFFFF0000000000000000000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GHOSTED(_alias) ENTITY(rectangle,black,active_directory_federation_services_server_ghosted,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GHOSTED)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GHOSTED(_alias,_label) ENTITY(rectangle,black,active_directory_federation_services_server_ghosted,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GHOSTED)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GHOSTED(_alias,_label,_shape) ENTITY(_shape,black,active_directory_federation_services_server_ghosted,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GHOSTED)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GHOSTED(_alias,_label,_shape,_color) ENTITY(_shape,_color,active_directory_federation_services_server_ghosted,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GHOSTED)
skinparam folderBackgroundColor<<OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GHOSTED>> White