sprite $active_directory_federation_services_server_blue [38x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF000000000000000000FFFFFFFFFFFFF
FFFFFF00000000000000000000FFFFFFFFFFFF
FFFFFF008AAAAAAAAAAAAAAA300FFFFFFFFFFF
FFFFF005AAAAAAAAAAAAAAAA900FFFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF006AAA55555555557AAA00FFFFFFFFFFF
FFFFF006AA900000000003AAA00FFFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA0000FFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAA80000FFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAA119500FFFFFFFF
FFFFF006AAAAAAAAAAAAAAA80699100FFFFFFF
FFFFF006AAAAAAAAAAAAAAA01999600FFFFFFF
FFFFF006AAAAAAAAAAAAAA7089999100FFFFFF
FFFFF006AAAAAAAAAAAAAA0299679700FFFFFF
FFFFF006AAA8888888888509910079200FFFFF
FFFFF006AA90000000000029900069800FFFFF
FFFFF006AAAAAAAAAAAA40999612999300FFFF
FFFFF006AAAAAAAAAAAA04998195499900FFFF
FFFFF006AAAAAAAAAAA2099944990899400FFF
FFFFF006AA90000000005998099954999000FF
FFFFF006AA94444444009993599990899500FF
FFFFF006AAAAAAAAA80797359999973599100F
FFFFF006AAAAAAAAA10990007444710079600F
FFFFF006AAAAAAAA7089900075557100799100
FFFFF002444444440199972599999725999800
FFFFF000000000000899999999999999999900
FFFFF000000000000233333333333333333300
FFFFFFFFFFFFFFFF0000000000000000000000
FFFFFFFFFFFFFFFFF0000000000000000000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_BLUE(_alias) ENTITY(rectangle,black,active_directory_federation_services_server_blue,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_BLUE)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_BLUE(_alias,_label) ENTITY(rectangle,black,active_directory_federation_services_server_blue,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_BLUE)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_BLUE(_alias,_label,_shape) ENTITY(_shape,black,active_directory_federation_services_server_blue,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_BLUE)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_BLUE(_alias,_label,_shape,_color) ENTITY(_shape,_color,active_directory_federation_services_server_blue,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_BLUE)
skinparam folderBackgroundColor<<OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_BLUE>> White