sprite $active_directory_federation_services_server_green [37x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF00000000000000000FFFFFFFFFFFFF
FFFFF00000000000000000000FFFFFFFFFFFF
FFFFF004AAAAAAAAAAAAAAA400FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF01AAA65555555556AAA00FFFFFFFFFFF
FFFFF01AAA20000000001AAA00FFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA0000FFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA0000FFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAA306500FFFFFFFF
FFFFF01AAAAAAAAAAAAAAAA0366100FFFFFFF
FFFFF01AAAAAAAAAAAAAAA20666500FFFFFFF
FFFFF01AAAAAAAAAAAAAA9046666100FFFFFF
FFFFF01AAAAAAAAAAAAAA2066446500FFFFFF
FFFFF01AAA8888888888704610036200FFFFF
FFFFF01AAA1000000000006600026500FFFFF
FFFFF01AAAAAAAAAAAA70466511566300FFFF
FFFFF01AAAAAAAAAAAA11666065166500FFFF
FFFFF01AAAAAAAAAAA7046631660566300FFF
FFFFF01AAA2000000001666056641666000FF
FFFFF01AAA5444444205663266660566300FF
FFFFF01AAAAAAAAAA0265226666652366100F
FFFFF01AAAAAAAAA50561004333310046400F
FFFFF01AAAAAAAAA026610043333100366100
FFFFF00444444442056652266666523666500
FFFFF00000000000266666666666666666600
FFFFF00000000000022222222222222222200
FFFFFFFFFFFFFFF0000000000000000000000
FFFFFFFFFFFFFFFF0000000000000000000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GREEN(_alias) ENTITY(rectangle,black,active_directory_federation_services_server_green,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GREEN)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GREEN(_alias,_label) ENTITY(rectangle,black,active_directory_federation_services_server_green,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GREEN)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GREEN(_alias,_label,_shape) ENTITY(_shape,black,active_directory_federation_services_server_green,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GREEN)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GREEN(_alias,_label,_shape,_color) ENTITY(_shape,_color,active_directory_federation_services_server_green,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GREEN)
skinparam folderBackgroundColor<<OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_GREEN>> White