sprite $active_directory_federation_services_server_orange [37x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF000000000000000000FFFFFFFFFFFFF
FFFFF00000000000000000000FFFFFFFFFFFF
FFFFF005AAAAAAAAAAAAAAA400FFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF02AAA65555555556AAA00FFFFFFFFFFF
FFFFF02AAA10000000001AAA00FFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA0000FFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAA90000FFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAA309600FFFFFFFF
FFFFF02AAAAAAAAAAAAAAA90499100FFFFFFF
FFFFF02AAAAAAAAAAAAAAA20999700FFFFFFF
FFFFF02AAAAAAAAAAAAAA9059999200FFFFFF
FFFFF02AAAAAAAAAAAAAA1198669700FFFFFF
FFFFF02AAA8888888888706930059300FFFFF
FFFFF02AAA1000000000019910049800FFFFF
FFFFF02AAAAAAAAAAAA70799712899300FFFF
FFFFF02AAAAAAAAAAAA019981863998000FFF
FFFFF02AAAAAAAAAAA6089952980799400FFF
FFFFF02AAA1000000002998089952999000FF
FFFFF02AAA5444444009995399991799500FF
FFFFF02AAAAAAAAAA0398348999973499100F
FFFFF02AAAAAAAAA30990005444620069600F
FFFFF02AAAAAAAAA059900055556100699100
FFFFF01444444441099982499999724999700
FFFFF00000000000599999999999999999900
FFFFF00000000000133333333333333333300
FFFFFFFFFFFFFFF0000000000000000000000
FFFFFFFFFFFFFFFF0000000000000000000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_ORANGE(_alias) ENTITY(rectangle,black,active_directory_federation_services_server_orange,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_ORANGE)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_ORANGE(_alias,_label) ENTITY(rectangle,black,active_directory_federation_services_server_orange,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_ORANGE)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_ORANGE(_alias,_label,_shape) ENTITY(_shape,black,active_directory_federation_services_server_orange,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_ORANGE)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_ORANGE(_alias,_label,_shape,_color) ENTITY(_shape,_color,active_directory_federation_services_server_orange,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_ORANGE)
skinparam folderBackgroundColor<<OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER_ORANGE>> White