sprite $active_directory_federation_services_server [37x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF00000000000000000FFFFFFFFFFFFF
FFFFFF0000000000000000000FFFFFFFFFFFF
FFFFF002AAAAAAAAAAAAAAA500FFFFFFFFFFF
FFFFF009AAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAA65555555555AAA00FFFFFFFFFFF
FFFFF00AAA20000000000AAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA0000FFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA0000FFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAA40A900FFFFFFFF
FFFFF00AAAAAAAAAAAAAAAA04AA200FFFFFFF
FFFFF00AAAAAAAAAAAAAAA40AAA900FFFFFFF
FFFFF00AAAAAAAAAAAAAAA05AAAA400FFFFFF
FFFFF00AAAAAAAAAAAAAA30AA77A900FFFFFF
FFFFF00AAA8888888888706A4005A500FFFFF
FFFFF00AAA200000000000AA2003AA00FFFFF
FFFFF00AAAAAAAAAAAA807AA9129AA500FFFF
FFFFF00AAAAAAAAAAAA21AAA0A92AAA000FFF
FFFFF00AAAAAAAAAAA807AA81AA18AA600FFF
FFFFF00AAA2000000002AAA19AA82AAA100FF
FFFFF00AAA6444444208AA72AAAA18AA700FF
FFFFF00AAAAAAAAAA12AA44AAAAA945AA100F
FFFFF00AAAAAAAAA708A300655562006A800F
FFFFF00AAAAAAAAA03AA300665562006AA200
FFFFF0044444444309AAA44AAAAA935AAA900
FFFFF000000000002AAAAAAAAAAAAAAAAAA10
FFFFF00000000000044444444444444444300
FFFFFFFFFFFFFFF0000000000000000000000
FFFFFFFFFFFFFFFF0000000000000000000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER(_alias) ENTITY(rectangle,black,active_directory_federation_services_server,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER(_alias,_label) ENTITY(rectangle,black,active_directory_federation_services_server,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER(_alias,_label,_shape) ENTITY(_shape,black,active_directory_federation_services_server,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,active_directory_federation_services_server,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER)
skinparam folderBackgroundColor<<OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_SERVER>> White