sprite $active_directory_federation_services_proxy [40x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFF
FFFFFF0000000000000000000005200FFFFFFFFF
FFFFFF001111111111111110000AA00FFFFFFFFF
FFFFF005AAAAAAAAAAAAAAA9008AA500FFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA11AAAA00FFFFFFFF
FFFFF00AAAAAAAAAAAAAAAA609A13A600FFFFFFF
FFFFF00AAAAAAAAAAAAAAAA12A700AA00FFFFFFF
FFFFF00AAA52222222222A509AA23AA700FFFFFF
FFFFF00AAA52222222222903AA3A75AA100FFFFF
FFFFF00AAAAAAAAAAAAAA409AA1AA1AA700FFFFF
FFFFF00AAAAAAAAAAAAA904AA29AA74AA200FFFF
FFFFF00AAAAAAAAAAAAA40AA46AAAA55A800FFFF
FFFFF00AAAAAAAAAAAA905A3005337006A300FFF
FFFFF00AAAAAAAAAAAA30AA5019999008A900FFF
FFFFF00AAAAAAAAAAA906AAA9AAAAAA9AAA300FF
FFFFF00AAAAAAAAAAA90377777777777777200FF
FFFFF00AAAAAAAAAAAA400000000000000000FFF
FFFFF00AAAAAAAAAAAAAAAAA300000000000FFFF
FFFFF00AAAAAAAAAAAAAA977200FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAA9000000FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAA00AA400FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAA009A4000000000FFFFFFF
FFFFF00AAAAAAAAAAA109A50000000000FFFFFFF
FFFFF00AAAAAAAAAA108AAAAAAAAAA900FFFFFFF
FFFFF00AAAAAAAAAA209AAAAAAAAAA800FFFFFFF
FFFFF00AAAAAAAAAAA109A40000000000FFFFFFF
FFFFF00AAAAAAAAAAAA109A4000000000FFFFFFF
FFFFF00AAA655555555401993001AA200FFFFFFF
FFFFF00AAA3111111111000000002AA100FFFFFF
FFFFF00AAAAAAAAAAAAA0000000003AA100FFFFF
FFFFF00AAAAAAAAAAAAA05AAAAAAAAAA9100FFFF
FFFFF00AAAA9999999990499999999AA8000FFFF
FFFFF00AAA30000000000000000004A9000FFFFF
FFFFF00AAA8777777777677720004A9000FFFFFF
FFFFF00AAAAAAAAAAAAAAAAA400399100FFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA40000000FFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA4000000FFFFFFFFF
FFFFF0022222222222222222000FFFFFFFFFFFFF
FFFFF0000000000000000000000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_PROXY(_alias) ENTITY(rectangle,black,active_directory_federation_services_proxy,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_PROXY)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_PROXY(_alias,_label) ENTITY(rectangle,black,active_directory_federation_services_proxy,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_PROXY)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_PROXY(_alias,_label,_shape) ENTITY(_shape,black,active_directory_federation_services_proxy,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_PROXY)
!define OFF_ACTIVE_DIRECTORY_FEDERATION_SERVICES_PROXY(_alias,_label,_shape,_color) ENTITY(_shape,_color,active_directory_federation_services_proxy,_label,_alias,OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_PROXY)
skinparam folderBackgroundColor<<OFF ACTIVE_DIRECTORY_FEDERATION_SERVICES_PROXY>> White