sprite $certificate_authority [39x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF0000000000000000FFFFFFFFFFFFFFF
FFFFFF00000000000000000000FFFFFFFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAA966666666668AAA00FFFFFFFFFFFF
FFFFF00AAA600000000005AAA00FFFFFFFFFFFF
FFFFF00AAAA9999999999AAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAA9999900000000000FFF
FFFFF00AAAAAAAAAAAA80000000000000000FFF
FFFFF00AAAAAAAAAAA901336666666666620FFF
FFFFF00AAAAAAAAAA901A55AAAAAAAAAAA30FFF
FFFFF00AAAAAAAAA900AA55AAAAAAAAAAA30FFF
FFFFF00AAA95555500AAA55AAAAAAA988930FFF
FFFFF00AAA7000000255525AAAAAA3022010FFF
FFFFF00AAAAAAAAA0244448AAAAA12966930FFF
FFFFF00AAAAAAAAA04AAAAAAAAA6181551820FF
FFFFF00AAAAAAAAA04AAAAAAAAA09060060A0FF
FFFFF00AAA60000004AAAAAAAAA0A300003A0FF
FFFFF00AAA84444404AAAAAAAAA0A100001A0FF
FFFFF00AAAAAAAAA04AAAAAAAAA1618228170FF
FFFFF00AAAAAAAAA04AAAAAAAAAA092112A00FF
FFFFF00AAAAAAAAA04AAAAAAAAAA13AAAA900FF
FFFFF008888888880388888888880AAA9AA30FF
FFFFF000000000000000000000004AA92AAA00F
FFFFFFFFFFFFFFFFFFFFFFFFFF00AAA30AAA900
FFFFFFFFFFFFFFFFFFFFFFFFFF0587A00880000
FFFFFFFFFFFFFFFFFFFFFFFFFF000070010000F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF000F00FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_CERTIFICATE_AUTHORITY(_alias) ENTITY(rectangle,black,certificate_authority,_alias,OFF CERTIFICATE_AUTHORITY)
!define OFF_CERTIFICATE_AUTHORITY(_alias,_label) ENTITY(rectangle,black,certificate_authority,_label,_alias,OFF CERTIFICATE_AUTHORITY)
!define OFF_CERTIFICATE_AUTHORITY(_alias,_label,_shape) ENTITY(_shape,black,certificate_authority,_label,_alias,OFF CERTIFICATE_AUTHORITY)
!define OFF_CERTIFICATE_AUTHORITY(_alias,_label,_shape,_color) ENTITY(_shape,_color,certificate_authority,_label,_alias,OFF CERTIFICATE_AUTHORITY)
skinparam folderBackgroundColor<<OFF CERTIFICATE_AUTHORITY>> White