sprite $cluster_server [42x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF000000000000FFFF0000000000000FFFFFF
FFFFF0000000000000000F000000000000000FFFFF
FFFF0027777777777760000477777777777500FFFF
FFFF00AAAAAAAAAAAAA6001AAAAAAAAAAAAA40FFFF
FFFF01AAAAAAAAAAAAA9003AAAAAAAAAAAAA70FFFF
FFFF01AAAAAAAAAAAAA9003AAAAAAAAAAAAA70FFFF
FFFF01AAA77777778AA9003AAA7777777AAA70FFFF
FFFF01AAA00000005AA9003AA900000008AA70FFFF
FFFF01AAAAAAAAAAAAA9003AAAAAAAAAAAAA70FFFF
FFFF01AAAAAAAA84444300144446AAAAAAAA70FFFF
FFFF01AAAAAAA6001111111111102AAAAAAA70FFFF
FFFF01AAAAAAA03AAAAAAAAAAAA807AAAAAA70FFFF
FFFF01AAAAAA90AAAAAAAAAAAAAA03AAAAAA70FFFF
FFFF01AAAAAA90AAAAAAAAAAAAAA03AAAAAA70FFFF
FFFF01AAAAAA90AAAAAAAAAAAAAA03AAAAAA70FFFF
FFFF01AAAAAA90AAA50000000AAA03AAAAAA70FFFF
FFFF01AAAAAA90AAA85555556AAA03AAAAAA70FFFF
FFFF01AAAAAA90AAAAAAAAAAAAAA03AAAAAA70FFFF
FFFF01AAAAAA90AAAAAAAAAAAAAA03AAAAAA70FFFF
FFFF01AAAAAA90AAAAAAAAAAAAAA03AAAAAA70FFFF
FFFF01AAAAAA90AAAAAAAAAAAAAA03AAAAAA70FFFF
FFFF01AAAAAA90AAAAAAAAAAAAAA03AAAAAA70FFFF
FFFF01AAA00000AAAAAAAAAAAAAA000008AA70FFFF
FFFF01AAA44440AAAAAAAAAAAAAA014449AA70FFFF
FFFF01AAAAAA90AAAAAAAAAAAAAA03AAAAAA70FFFF
FFFF01AAA99980AAAAAAAAAAAAAA02999AAA70FFFF
FFFF01AAA00000AAAAAAAAAAAAAA000008AA70FFFF
FFFF01AAA88870AAAAAAAAAAAAAA02888AAA70FFFF
FFFF01AAAAAA90AAAAAAAAAAAAAA03AAAAAA70FFFF
FFFF01AAAAAA90AAAAAAAAAAAAAA03AAAAAA70FFFF
FFFF01AAAAAA90AAA87777777AAA03AAAAAA70FFFF
FFFF0000000000AAA50000001AAA0000000000FFFF
FFFF0000000000AAAAAAAAAAAAAA0000000000FFFF
FFFFFFFFFFFF00AAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFFFFFFFF00AAA63333333AAA00FFFFFFFFFFFF
FFFFFFFFFFFF00AAA62222222AAA00FFFFFFFFFFFF
FFFFFFFFFFFF00AAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFFFFFFFF00AAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFFFFFFFF00AAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFFFFFFFF006666666666666600FFFFFFFFFFFF
FFFFFFFFFFFF000000000000000000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_CLUSTER_SERVER(_alias) ENTITY(rectangle,black,cluster_server,_alias,OFF CLUSTER_SERVER)
!define OFF_CLUSTER_SERVER(_alias,_label) ENTITY(rectangle,black,cluster_server,_label,_alias,OFF CLUSTER_SERVER)
!define OFF_CLUSTER_SERVER(_alias,_label,_shape) ENTITY(_shape,black,cluster_server,_label,_alias,OFF CLUSTER_SERVER)
!define OFF_CLUSTER_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,cluster_server,_label,_alias,OFF CLUSTER_SERVER)
skinparam folderBackgroundColor<<OFF CLUSTER_SERVER>> White