sprite $database_server_orange [40x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF00000000000000000FFFFFFFFFFFFFFFF
FFFFF000000000000000000000FFFFFFFFFFFFFF
FFFFF009AAAAAAAAAAAAAAA900FFFFFFFFFFFFFF
FFFFF05AAAAAAAAAAAAAAAAA40FFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAAA60FFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAAA60FFFFFFFFFFFFFF
FFFFF06AAA55555555555AAA60FFFFFFFFFFFFFF
FFFFF06AAA00000000000AAA60FFFFFFFFFFFFFF
FFFFF06AAA99999999999AAA60FFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAAA60FFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAAA60FFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAAA60FFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAAA60FFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAAA60FFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAAA60FFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAAA60FFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAAA60FFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAAA60FFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAAA60FFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAAA60000000FFFFFFFF
FFFFF06AAAAAAAAAAAAAA74100000000000FFFFF
FFFFF06AAAAAAAAAAAAA2003466776542000FFFF
FFFFF06AAAAAAAAAAAA105999999999998300FFF
FFFFF06AAAAAAAAAAAA029999999999999900FFF
FFFFF06AAAAAAAAAAAA006999999999998400FFF
FFFFF06AAAAAAAAAAAA021146777776530300FFF
FFFFF06AAAAAAAAAAAA049743211112358900FFF
FFFFF06AAA444444444049999999999999900FFF
FFFFF06AAA111111111049999999999999900FFF
FFFFF06AAAAAAAAAAAA049999999999999900FFF
FFFFF06AAAAAAAAAAAA049999999999999900FFF
FFFFF06AAA999999999049999999999999900FFF
FFFFF06AAA000000000049999999999999900FFF
FFFFF06AAA555555555049999999999999900FFF
FFFFF06AAAAAAAAAAAA049999999999999900FFF
FFFFF06AAAAAAAAAAAA049999999999999900FFF
FFFFF06AAAAAAAAAAAA049999999999999900FFF
FFFFF03666666666666029999999999999900FFF
FFFFF00000000000000007999999999998200FFF
FFFFFFFFFFFFFFFFFFFF0006888888873000FFFF
FFFFFFFFFFFFFFFFFFFFF00000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE_SERVER_ORANGE(_alias) ENTITY(rectangle,black,database_server_orange,_alias,OFF DATABASE_SERVER_ORANGE)
!define OFF_DATABASE_SERVER_ORANGE(_alias,_label) ENTITY(rectangle,black,database_server_orange,_label,_alias,OFF DATABASE_SERVER_ORANGE)
!define OFF_DATABASE_SERVER_ORANGE(_alias,_label,_shape) ENTITY(_shape,black,database_server_orange,_label,_alias,OFF DATABASE_SERVER_ORANGE)
!define OFF_DATABASE_SERVER_ORANGE(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_server_orange,_label,_alias,OFF DATABASE_SERVER_ORANGE)
skinparam folderBackgroundColor<<OFF DATABASE_SERVER_ORANGE>> White