sprite $database_server_blue [40x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF00000000000000000FFFFFFFFFFFFFFFF
FFFFF00000000000000000000FFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAA800FFFFFFFFFFFFFF
FFFFF07AAAAAAAAAAAAAAAAA20FFFFFFFFFFFFFF
FFFFF09AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFFF09AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFFF09AAA55555555555AAA30FFFFFFFFFFFFFF
FFFFF09AAA00000000000AAA30FFFFFFFFFFFFFF
FFFFF09AAA99999999999AAA30FFFFFFFFFFFFFF
FFFFF09AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFFF09AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFFF09AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFFF09AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFFF09AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFFF09AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFFF09AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFFF09AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFFF09AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFFF09AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFFF09AAAAAAAAAAAAAAAAA3000000FFFFFFFFF
FFFFF09AAAAAAAAAAAAAA73000000000000FFFFF
FFFFF09AAAAAAAAAAAA91003567777542000FFFF
FFFFF09AAAAAAAAAAAA006999999999998200FFF
FFFFF09AAAAAAAAAAAA059999999999999900FFF
FFFFF09AAAAAAAAAAAA007999999999999300FFF
FFFFF09AAAAAAAAAAAA041146788877520300FFF
FFFFF09AAAAAAAAAAAA069743211112369900FFF
FFFFF09AAA444444444069999999999999900FFF
FFFFF09AAA111111111069999999999999900FFF
FFFFF09AAAAAAAAAAAA069999999999999900FFF
FFFFF09AAAAAAAAAAAA069999999999999900FFF
FFFFF09AAA999999999069999999999999900FFF
FFFFF09AAA000000000069999999999999900FFF
FFFFF09AAA555555555069999999999999900FFF
FFFFF09AAAAAAAAAAAA069999999999999900FFF
FFFFF09AAAAAAAAAAAA069999999999999900FFF
FFFFF09AAAAAAAAAAAA069999999999999900FFF
FFFFF05666666666666059999999999999900FFF
FFFFF0000000000000000899999999999910FFFF
FFFFFFFFFFFFFFFFFFF00016999999983000FFFF
FFFFFFFFFFFFFFFFFFFFF00000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE_SERVER_BLUE(_alias) ENTITY(rectangle,black,database_server_blue,_alias,OFF DATABASE_SERVER_BLUE)
!define OFF_DATABASE_SERVER_BLUE(_alias,_label) ENTITY(rectangle,black,database_server_blue,_label,_alias,OFF DATABASE_SERVER_BLUE)
!define OFF_DATABASE_SERVER_BLUE(_alias,_label,_shape) ENTITY(_shape,black,database_server_blue,_label,_alias,OFF DATABASE_SERVER_BLUE)
!define OFF_DATABASE_SERVER_BLUE(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_server_blue,_label,_alias,OFF DATABASE_SERVER_BLUE)
skinparam folderBackgroundColor<<OFF DATABASE_SERVER_BLUE>> White