sprite $database_server_ghosted [40x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF00000000000000000FFFFFFFFFFFFFFFF
FFFFF000000000000000000000FFFFFFFFFFFFFF
FFFFF007AAAAAAAAAAAAAAA800FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA40FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA40FFFFFFFFFFFFFF
FFFFF01AAA55555555555AAA40FFFFFFFFFFFFFF
FFFFF01AAA00000000000AAA40FFFFFFFFFFFFFF
FFFFF01AAA99999999999AAA40FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA40FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA40FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA40FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA40FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA40FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA40FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA40FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA40FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA40FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA40FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA40000000FFFFFFFF
FFFFF01AAAAAAAAAAAAAA73000000000000FFFFF
FFFFF01AAAAAAAAAAAAA2002234334221000FFFF
FFFFF01AAAAAAAAAAAA303644643643644000FFF
FFFFF01AAAAAAAAAAAA026436436436446400FFF
FFFFF01AAAAAAAAAAAA003364354364364100FFF
FFFFF01AAAAAAAAAAAA010022443442310200FFF
FFFFF01AAAAAAAAAAAA025421110111136400FFF
FFFFF01AAA444444444035355355365364300FFF
FFFFF01AAA111111111023553553553543500FFF
FFFFF01AAAAAAAAAAAA015535535535536400FFF
FFFFF01AAAAAAAAAAAA035355355355354300FFF
FFFFF01AAA999999999023553553553543500FFF
FFFFF01AAA000000000015535535535536400FFF
FFFFF01AAA555555555035355355355355300FFF
FFFFF01AAAAAAAAAAAA023553553553553400FFF
FFFFF01AAAAAAAAAAAA015535535535535400FFF
FFFFF01AAAAAAAAAAAA035355355355355300FFF
FFFFF00666666666666023553553553553400FFF
FFFFF00000000000000004535535535535000FFF
FFFFFFFFFFFFFFFFFFF00013535535531000FFFF
FFFFFFFFFFFFFFFFFFFFF00000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFF000000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE_SERVER_GHOSTED(_alias) ENTITY(rectangle,black,database_server_ghosted,_alias,OFF DATABASE_SERVER_GHOSTED)
!define OFF_DATABASE_SERVER_GHOSTED(_alias,_label) ENTITY(rectangle,black,database_server_ghosted,_label,_alias,OFF DATABASE_SERVER_GHOSTED)
!define OFF_DATABASE_SERVER_GHOSTED(_alias,_label,_shape) ENTITY(_shape,black,database_server_ghosted,_label,_alias,OFF DATABASE_SERVER_GHOSTED)
!define OFF_DATABASE_SERVER_GHOSTED(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_server_ghosted,_label,_alias,OFF DATABASE_SERVER_GHOSTED)
skinparam folderBackgroundColor<<OFF DATABASE_SERVER_GHOSTED>> White