sprite $database_server [40x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF000000000000000000FFFFFFFFFFFFFFFF
FFFFF00000000000000000000FFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAA800FFFFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFF
FFFF00AAAA55555555555AAA10FFFFFFFFFFFFFF
FFFF00AAAA00000000000AAA10FFFFFFFFFFFFFF
FFFF00AAAA99999999999AAA10FFFFFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAAAA1000000FFFFFFFFF
FFFF00AAAAAAAAAAAAAAA63000000000000FFFFF
FFFF00AAAAAAAAAAAAA90014678887641000FFFF
FFFF00AAAAAAAAAAAAA007AAAAAAAAAAA8200FFF
FFFF00AAAAAAAAAAAAA08AAAAAAAAAAAAAA00FFF
FFFF00AAAAAAAAAAAAA018AAAAAAAAAAA9200FFF
FFFF00AAAAAAAAAAAAA051257899987620500FFF
FFFF00AAAAAAAAAAAAA09A84321112347AA00FFF
FFFF00AAAA44444444409AAAAAAAAAAAAAA00FFF
FFFF00AAAA11111111109AAAAAAAAAAAAAA00FFF
FFFF00AAAAAAAAAAAAA09AAAAAAAAAAAAAA00FFF
FFFF00AAAAAAAAAAAAA09AAAAAAAAAAAAAA00FFF
FFFF00AAAA99999999909AAAAAAAAAAAAAA00FFF
FFFF00AAAA00000000009AAAAAAAAAAAAAA00FFF
FFFF00AAAA55555555509AAAAAAAAAAAAAA00FFF
FFFF00AAAAAAAAAAAAA09AAAAAAAAAAAAAA00FFF
FFFF00AAAAAAAAAAAAA09AAAAAAAAAAAAAA00FFF
FFFF00AAAAAAAAAAAAA09AAAAAAAAAAAAAA00FFF
FFFF00666666666666608AAAAAAAAAAAAAA00FFF
FFFF00000000000000000AAAAAAAAAAAAA00FFFF
FFFFFFFFFFFFFFFFFFF00028AAAAAAA83000FFFF
FFFFFFFFFFFFFFFFFFFFF00000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFF000000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE_SERVER(_alias) ENTITY(rectangle,black,database_server,_alias,OFF DATABASE_SERVER)
!define OFF_DATABASE_SERVER(_alias,_label) ENTITY(rectangle,black,database_server,_label,_alias,OFF DATABASE_SERVER)
!define OFF_DATABASE_SERVER(_alias,_label,_shape) ENTITY(_shape,black,database_server,_label,_alias,OFF DATABASE_SERVER)
!define OFF_DATABASE_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_server,_label,_alias,OFF DATABASE_SERVER)
skinparam folderBackgroundColor<<OFF DATABASE_SERVER>> White