sprite $dirsync_server [41x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF000000000000000000FFFFFFFFFFFFFFFFF
FFFFF000000000000000000000FFFFFFFFFFFFFFF
FFFFF008999999999999999600FFFFFFFFFFFFFFF
FFFF008AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAAA50FFFFFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAAA50FFFFFFFFFFFFFFF
FFFF009AAA77777777778AAA50FFFFFFFFFFFFFFF
FFFF009AA900000000001AAA50FFFFFFFFFFFFFFF
FFFF009AAA88888888888AAA50FFFFFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAAA50FFFFFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAAA50FFFFFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAAA50FFFFFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAAA50FFFFFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAAA50FFFFFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAAA50FFFFFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAAA50FFFFFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAAA50FFFFFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAAA50FFFFFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAAA50FFFFFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAAA50FFFFFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAAA500000000FFFFFFFF
FFFF009AAAAAAAAAAAAAAAA500023310000FFFFFF
FFFF009AAAAAAAAAAAAAA91038AAAAAA5000FFFFF
FFFF009AAAAAAAAAAAAA9007AAAAAAAAAA300FFFF
FFFF009AAAAAAAAAAAAA109AAAAAAAAAAAA300FFF
FFFF009AAAAAAAAAAAA407AAAAAA99AAAAAA100FF
FFFF009AAAAAAAAAAA904AAAAA300007AAAAA00FF
FFFF009AAAAAAAAAAA509AAA5A6376003AAAA30FF
FFFF009AA90000000002AAA404AAAAA408AAA900F
FFFF009AAA7777777705AA60006AAAAA01AAAA00F
FFFF009AAAAAAAAAAA06A7000008AAAA50AAAA00F
FFFF009AAAAAAAAAA906AAA40AAAAA321023AA00F
FFFF009AAA4444444405AAA609AAAA800007AA00F
FFFF009AA90000000003AAA902AAAAA7005AAA00F
FFFF009AAA9999999930AAAA6039AA7A53AAA600F
FFFF009AAAAAAAAAAA706AAAA5000007AAAAA00FF
FFFF009AAAAAAAAAAAA21AAAAA96447AAAAA600FF
FFFF009AAAAAAAAAAAA803AAAAAAAAAAAAA800FFF
FFFF0011111111111111003AAAAAAAAAAA8000FFF
FFFF000000000000000000018AAAAAAA94000FFFF
FFFFFFFFFFFFFFFFFFFFFF00015888730000FFFFF
FFFFFFFFFFFFFFFFFFFFFFF00000000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DIRSYNC_SERVER(_alias) ENTITY(rectangle,black,dirsync_server,_alias,OFF DIRSYNC_SERVER)
!define OFF_DIRSYNC_SERVER(_alias,_label) ENTITY(rectangle,black,dirsync_server,_label,_alias,OFF DIRSYNC_SERVER)
!define OFF_DIRSYNC_SERVER(_alias,_label,_shape) ENTITY(_shape,black,dirsync_server,_label,_alias,OFF DIRSYNC_SERVER)
!define OFF_DIRSYNC_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,dirsync_server,_label,_alias,OFF DIRSYNC_SERVER)
skinparam folderBackgroundColor<<OFF DIRSYNC_SERVER>> White