sprite $domain_controller [38x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0000000000000000000FFFFFFFFFFFFF
FFFFF000000000000000000000FFFFFFFFFFFF
FFFFF005AAAAAAAAAAAAAAA500FFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA10FFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA20FFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA20FFFFFFFFFFFF
FFFFF02AAA65555555555AAA20FFFFFFFFFFFF
FFFFF02AAA20000000001AAA20FFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA20FFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA20FFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA20FFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA20FFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA20FFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA20FFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA20FFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA20FFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA20FFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA20FFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA20FFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA2000FFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA20000FFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA03A300FFFFFFFF
FFFFF02AAAAAAAAAAAAAAAA50AA900FFFFFFFF
FFFFF02AAAAAAAAAAAAAAAA04AAA400FFFFFFF
FFFFF02AAAAAAAAAAAAAAA30AAAAA00FFFFFFF
FFFFF02AAAAAAAAAAAAAA905AAAAA500FFFFFF
FFFFF02AAA8888888888820AAAAAAA000FFFFF
FFFFF02AAA1000000000006AAAAAAA600FFFFF
FFFFF02AAAAAAAAAAAAA11AAAAAAAAA100FFFF
FFFFF02AAAAAAAAAAAA808AAAAAAAAA700FFFF
FFFFF02AAAAAAAAAAAA01AAAAAAAAAAA200FFF
FFFFF02AAA20000000009AAAAAAAAAAA800FFF
FFFFF02AAA5444444402AAAAAAAAAAAAA200FF
FFFFF02AAAAAAAAAA50AAAAAAAAAAAAAA900FF
FFFFF02AAAAAAAAAA03AAAAAAAAAAAAAAA300F
FFFFF02AAAAAAAAA40AAAAAAAAAAAAAAAAA00F
FFFFF0044444444405AAAAAAAAAAAAAAAAA400
FFFFF000000000000AAAAAAAAAAAAAAAAAAA00
FFFFF000000000000344444444444444444200
FFFFFFFFFFFFFFFF0000000000000000000000
FFFFFFFFFFFFFFFFF0000000000000000000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DOMAIN_CONTROLLER(_alias) ENTITY(rectangle,black,domain_controller,_alias,OFF DOMAIN_CONTROLLER)
!define OFF_DOMAIN_CONTROLLER(_alias,_label) ENTITY(rectangle,black,domain_controller,_label,_alias,OFF DOMAIN_CONTROLLER)
!define OFF_DOMAIN_CONTROLLER(_alias,_label,_shape) ENTITY(_shape,black,domain_controller,_label,_alias,OFF DOMAIN_CONTROLLER)
!define OFF_DOMAIN_CONTROLLER(_alias,_label,_shape,_color) ENTITY(_shape,_color,domain_controller,_label,_alias,OFF DOMAIN_CONTROLLER)
skinparam folderBackgroundColor<<OFF DOMAIN_CONTROLLER>> White