sprite $file_server [40x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF000000000000000000FFFFFFFFFFFFFFF
FFFFFF00022222222222222100FFFFFFFFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAA200FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFFF05AAA00000000008AA700FFFFFFFFFFFFF
FFFFFF05AAA66666666669AA700FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA700F000000000FFF
FFFFFF05AAAAAAAAAAAAAAAA70000044444200FF
FFFFFF05AAAAAAAAAAAAAAAA700019AAAAAA00FF
FFFFFF05AAAAAAAAA96555554001AAAAAAAA10FF
FFFFFF05AAAAAAAA7000000000000000000000FF
FFFFFF05AAAAAAAA229AAAAAAAAAAAAAAAAA10FF
FFFFFF05AAAAAAAA15AAAAAAAAAAAAAAAAAA10FF
FFFFFF05AAA0000005AAAAAAAAAAAAAAAAAA10FF
FFFFFF05AAA8888805AAAAAAAAAAAAAAAAAA10FF
FFFFFF05AAAAAAAA15AAAAAAAAAAAAAAAAAA10FF
FFFFFF05AAAAAAAA15AAAAAAAAAAAAAAAAAA10FF
FFFFFF05AAA1111105AAAAAAAAAAAAAAAAAA10FF
FFFFFF05AAA1111105AAAAAAAAAAAAAAAAAA10FF
FFFFFF05AAAAAAAA15AAAAAAAAAAAAAAAAAA10FF
FFFFFF05AAAAAAAA15AAAAAAAAAAAAAAAAAA10FF
FFFFFF05AAAAAAAA15AAAAAAAAAAAAAAAAAA10FF
FFFFFF037777777705AAAAAAAAAAAAAAAAAA10FF
FFFFFF000000000005AAAAAAAAAAAAAAAAAA10FF
FFFFFF000000000005AAAAAAAAAAAAAAAAAA10FF
FFFFFFFFFFFFFFFF0000000000000000000000FF
FFFFFFFFFFFFFFFF0000000000000000000000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_FILE_SERVER(_alias) ENTITY(rectangle,black,file_server,_alias,OFF FILE_SERVER)
!define OFF_FILE_SERVER(_alias,_label) ENTITY(rectangle,black,file_server,_label,_alias,OFF FILE_SERVER)
!define OFF_FILE_SERVER(_alias,_label,_shape) ENTITY(_shape,black,file_server,_label,_alias,OFF FILE_SERVER)
!define OFF_FILE_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,file_server,_label,_alias,OFF FILE_SERVER)
skinparam folderBackgroundColor<<OFF FILE_SERVER>> White