sprite $hybrid_server [48x43/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF0000000000000000FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF0000000000000000000FFFFFFFFFFFFFFFFFFFFFF
FFFFFF00588888888888888600FFFFFFFFFFFFFFFFFFFFFF
FFFFFF03AAAAAAAAAAAAAAAA600FFFFFFFFFFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFFFFFF
FFFFFF05AAA66666666669AA800FFFFFFFFFFFFFFFFFFFFF
FFFFFF05AAA00000000007AA800FFFFFFFFFFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA80000000FFFFFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA804885000FFFFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA808AAAA6000FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAA2000000004A800FFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAA204410000002A400FFFFFFFFFFFF
FFFFFF05AAAAAAAAAAA207A7000000006A00FFFFFFFFFFFF
FFFFFF05AAAAAAAAAA307A70000000002A20000FFFFFFFFF
FFFFFF05AAAAAAAAA308AA88888888400A641000FFFFFFFF
FFFFFF05AAAAAAAAA00AAAAAAAAAAA500AAAAA0000FFFFFF
FFFFFF05AAAAAAAAA901AA000000000000001AA000000FFF
FFFFFF05AAAAAAAAAA901AA100000000000000AAAA3000FF
FFFFFF05AAAAAAAAAAA802AA1006A9000000001138A600FF
FFFFFF05AAAAAAAAAAAA300000005A8000000000004A400F
FFFFFF05AAAAAAAAAAAA0000000005A8000000000007900F
FFFFFF05AAAAAAAAAAAA06AAAAAAAAAA700000000003A10F
FFFFFF05AAAAAAAAAAAA06AAAAAAAAAA400000000001A20F
FFFFFF05AAA000000000000000000AA5000000000002A10F
FFFFFF05AAAAAAAAAAAA9AAA70009A60000000000006A00F
FFFFFF05AAAAAAAAAAAAAAAA8006760000000000001A500F
FFFFFF05AAAAAAAAAAAAAAAA800000000000000004A800FF
FFFFFF05AAA00000000006AA808999AAAAAAAAAAAA6000FF
FFFFFF05AAA77777777779AA803333333333333321000FFF
FFFFFF05AAAAAAAAAAAAAAAA8000000000000000000FFFFF
FFFFFF05AAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFFFFFF
FFFFFF001111111111111111000FFFFFFFFFFFFFFFFFFFFF
FFFFFF000000000000000000000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_HYBRID_SERVER(_alias) ENTITY(rectangle,black,hybrid_server,_alias,OFF HYBRID_SERVER)
!define OFF_HYBRID_SERVER(_alias,_label) ENTITY(rectangle,black,hybrid_server,_label,_alias,OFF HYBRID_SERVER)
!define OFF_HYBRID_SERVER(_alias,_label,_shape) ENTITY(_shape,black,hybrid_server,_label,_alias,OFF HYBRID_SERVER)
!define OFF_HYBRID_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,hybrid_server,_label,_alias,OFF HYBRID_SERVER)
skinparam folderBackgroundColor<<OFF HYBRID_SERVER>> White