sprite $mainframe_host [48x45/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF000000000000000000000000000000000000FFFFFF
FFFFF00000000000000000000000000000000000000FFFFF
FFFFF005999999999999998105999999999999998000FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AA633333333333AA200FFFF
FFFFF00AA766666666666AA20AA300000000000AA200FFFF
FFFFF00AA400000000000AA20AA522222222222AA200FFFF
FFFFF00AA400000000000AA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AA644444444444AA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AA300000000000AA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AA522222222222AA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF00AAAAAAAAAAAAAAAA20AAAAAAAAAAAAAAAA200FFFF
FFFFF005555555555555555105555555555555555100FFFF
FFFFF000033333333333333333333333333333320000FFFF
FFFFF0001AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA60000FFFF
FFFFFF000333333333333333333333333333333200FFFFFF
FFFFFF000000000000000000000000000000000000FFFFFF
FFFFFF000000000000000000000000000000000000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_MAINFRAME_HOST(_alias) ENTITY(rectangle,black,mainframe_host,_alias,OFF MAINFRAME_HOST)
!define OFF_MAINFRAME_HOST(_alias,_label) ENTITY(rectangle,black,mainframe_host,_label,_alias,OFF MAINFRAME_HOST)
!define OFF_MAINFRAME_HOST(_alias,_label,_shape) ENTITY(_shape,black,mainframe_host,_label,_alias,OFF MAINFRAME_HOST)
!define OFF_MAINFRAME_HOST(_alias,_label,_shape,_color) ENTITY(_shape,_color,mainframe_host,_label,_alias,OFF MAINFRAME_HOST)
skinparam folderBackgroundColor<<OFF MAINFRAME_HOST>> White