sprite $mainframe [48x37/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFF00000000000000000000000000000000000000FFFFF
FFFFF001111111111110001111100011111111111100FFFF
FFFF008AAAAAAAAAAAA41AAAAAA907AAAAAAAAAAAA50FFFF
FFFF008AAAAAAAAAAAA51AA888A907A8888888888A60FFFF
FFFF008A6666666668A51A8000A907A1000000002A60FFFF
FFFF008A0000000003A51A8000A907A6555555557A60FFFF
FFFF008A7777777778A51A9001A907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907A1000000002A60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907A1000000003A60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF008AAAAAAAAAAAA51AAAAAA907AAAAAAAAAAAA60FFFF
FFFF0034444444444442044444430344444444444420FFFF
FFFF0001888888888888888888888888888888888000FFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF0000000000000000000000000000000000000FFFFF
FFFFFF0000000000000000000000000000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_MAINFRAME(_alias) ENTITY(rectangle,black,mainframe,_alias,OFF MAINFRAME)
!define OFF_MAINFRAME(_alias,_label) ENTITY(rectangle,black,mainframe,_label,_alias,OFF MAINFRAME)
!define OFF_MAINFRAME(_alias,_label,_shape) ENTITY(_shape,black,mainframe,_label,_alias,OFF MAINFRAME)
!define OFF_MAINFRAME(_alias,_label,_shape,_color) ENTITY(_shape,_color,mainframe,_label,_alias,OFF MAINFRAME)
skinparam folderBackgroundColor<<OFF MAINFRAME>> White