sprite $network [30x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0000000000000000000FFFFF
FFFFF00145555555555555200FFFFF
FFFFF008AAAAAAAAAAAAAAA20FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAA7555555555AAA40FFFFF
FFFFF00AAA5222222222AAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAA7555555555AAA40FFFFF
FFFFF00AAA5222222222AAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAA7555555555AAA40FFFFF
FFFFF00AAA5222222222AAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00AAAAAAAAAAAAAAAA40FFFFF
FFFFF00000000000000000000FFFFF
FFFFF000000000AA800000000FFFFF
FFFFFFFFFFFF00AA800FFFFFFFFFFF
FFFFFFFFFFFF00AA800FFFFFFFFFFF
FFFFFFFFFF00008860000FFFFFFFFF
F00000000000000000000000000000
F00000000004AAAAAAA00000000000
F05AAAAAAA34AAAAAAA0AAAAAAAA00
F05AAAAAAA34AAAAAAA0AAAAAAAA00
F05AAAAAAA34AAAAAAA0AAAAAAAA00
F00000000004AAAAAAA00000000000
F00000000000000000000000000000
FFFFFFFFFF00000000000FFFFFFFFF
}

!define OFF_NETWORK(_alias) ENTITY(rectangle,black,network,_alias,OFF NETWORK)
!define OFF_NETWORK(_alias,_label) ENTITY(rectangle,black,network,_label,_alias,OFF NETWORK)
!define OFF_NETWORK(_alias,_label,_shape) ENTITY(_shape,black,network,_label,_alias,OFF NETWORK)
!define OFF_NETWORK(_alias,_label,_shape,_color) ENTITY(_shape,_color,network,_label,_alias,OFF NETWORK)
skinparam folderBackgroundColor<<OFF NETWORK>> White