sprite $office_web_apps_server [44x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000F
FFFFFFFF0000000000000000FFFFF00000489984000F
FFFFFF0000000000000000000000000389999999900F
FFFFF00089999999999999981000178999742999900F
FFFFF007AAAAAAAAAAAAAAAA8000999310001999900F
FFFFF00AAAAAAAAAAAAAAAAAA000998000001999900F
FFFFF00AAAAAAAAAAAAAAAAAA000998000001999900F
FFFFF00AAAA9999999999AAAA000998000001999900F
FFFFF00AAA800000000005AAA000998000001999900F
FFFFF00AAAA88888888889AAA000998000001999900F
FFFFF00AAAAAAAAAAAAAAAAAA000998000001999900F
FFFFF00AAAAAAAAAAAAAAAAAA000998000001999900F
FFFFF00AAAAAAAAAAAAAAAAAA000997000001999900F
FFFFF00AAAAAAAAAAAAAAAAAA000620000001999900F
FFFFF00AAAAAAAAAAAAAAAAAA000025653101999900F
FFFFF00AAAAAAAAAAAAAAAAAA000000148998999900F
FFFFF00AAAAAAAAAAAAAAAAAA00FF00000258742000F
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFF00000000000F
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFF0000FFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFF00AAAA77777777779AAA00FFFFFFFFFFFFFFFFF
FFFFF00AAA800000000005AAA00FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFF00AAA811111111116AAA00FFFFFFFFFFFFFFFFF
FFFFF00AAA922222222226AAA00FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFF0099999999999999999900FFFFFFFFFFFFFFFFF
FFFFF0000000000000000000000FFFFFFFFFFFFFFFFF
FFFFF0000000000000000000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_OFFICE_WEB_APPS_SERVER(_alias) ENTITY(rectangle,black,office_web_apps_server,_alias,OFF OFFICE_WEB_APPS_SERVER)
!define OFF_OFFICE_WEB_APPS_SERVER(_alias,_label) ENTITY(rectangle,black,office_web_apps_server,_label,_alias,OFF OFFICE_WEB_APPS_SERVER)
!define OFF_OFFICE_WEB_APPS_SERVER(_alias,_label,_shape) ENTITY(_shape,black,office_web_apps_server,_label,_alias,OFF OFFICE_WEB_APPS_SERVER)
!define OFF_OFFICE_WEB_APPS_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,office_web_apps_server,_label,_alias,OFF OFFICE_WEB_APPS_SERVER)
skinparam folderBackgroundColor<<OFF OFFICE_WEB_APPS_SERVER>> White