sprite $on_premises_server [41x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF0000000000000000FFFFFFFFFFFFFFFFFFFFF
FFFF0000000000000000FFFFFFFFFFFFFFFFFFFFF
FFFF005AAAAAAAAAA800FFFFFFFFFFFFFFFFFFFFF
FFFF005AAAAAAAAAA900000000FFFFFFFFFFFFFFF
FFFF005AAAAAAAAAA900001100FFFFFFFFFFFFFFF
FFFF005AA12AA516A900006900FFFFFFFFFFFFFFF
FFFF005AA00AA406A900006900FFFFFFFFFFFFFFF
FFFF005AA99AA99AA9000069000FFFFFFFFFFFFFF
FFFF005AAAAAAAAAA9000069000FFFFFFFFFFFFFF
FFFF005AA99AAA9AA90018AA820FFFFFFFFFFFFFF
FFFF005AA00AA406A9001AAAA30FFFFFFFFFFFFFF
FFFF005AA01AA506A9001AAAA3000FFFFFFFFFFFF
FFFF005AAAAAAAAAA9001AAAA3000FFFFFFFFFFFF
FFFF005AAAAAAAAAA9048AAAA8600FFFFFFFFFFFF
FFFF005AA34AA637A906AAAAAA900FFFFFFFFFFFF
FFFF005AA00AA406A906AAAAAA9000FFFFFFFFFFF
FFFF005AA77AA879A906AAAAAA9000FFFFFFFFFFF
FFFF005AAAAAAAAAAA69AAAAAAA610FFFFFFFFFFF
FFFF005AAAAAAAAAAAAAAAAAAAAA20FFFFFFFFFFF
FFFF005AA00AA406AAAA45AAAAAA20FFFFFFFFFFF
FFFF005AA01AA406AAA901AAAAAA20FFFFFFFFFFF
FFFF005AAAAAAAAAAAAA56AAA400000000000FFFF
FFFF005AAAAAAAAAAAAAAAAA60355555555100FFF
FFFF005AA56AA858AAAAAAAA30AAAAAAAAA900FFF
FFFF005AA00AA406AAAAAAAA31AAAAAAAAAA00FFF
FFFF005AA45AA748AAAAAAAA31A9000001AA00FFF
FFFF005AAAAAAAAAAAAA67AA31AAAAAAAAAA00FFF
FFFF005AAAAAAAAAAAA901AA31AAAAAAAAAA00FFF
FFFF005AA01AA506AAA934AA31AAAAAAAAAA00FFF
FFFF005AA00AA406AAAAAAAA31AAAAAAAAAA00FFF
FFFF005AAAAAAAAAAAAAAAAA31AAAAAAAAAA00FFF
FFFF005AAAAAAAAAAAAAAAAA31AAAAAAAAAA00FFF
FFFF005AAAAAAAAAAAAAAAAA31AAAAAAAAAA00FFF
FFFF005AAAAAAAAAAAAAAAAA31AAAAAAAAAA00FFF
FFFF005AAAAAAAAAAAAAAAAA31AAAAAAAAAA00FFF
FFFF005AAAAAAAAAAAAAAAAA31AAAAAAAAAA00FFF
FFFF005AAAAAAAAAAAAAAAAA31AA999999AA00FFF
FFFF005AAAAAAAAAAAAAAAAA31A9111112AA00FFF
FFFF005AAAAAAAAAAAAAAAAA31AAAAAAAAAA00FFF
FFFF0001111111111111111101A9111112AA00FFF
FFFF0000000000000000000001AA999999AA00FFF
FFFFFFFFFFFFFFFFFFFFFFFF01AAAAAAAAAA00FFF
FFFFFFFFFFFFFFFFFFFFFFFF00222222222100FFF
FFFFFFFFFFFFFFFFFFFFFFFF00000000000000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ON_PREMISES_SERVER(_alias) ENTITY(rectangle,black,on_premises_server,_alias,OFF ON_PREMISES_SERVER)
!define OFF_ON_PREMISES_SERVER(_alias,_label) ENTITY(rectangle,black,on_premises_server,_label,_alias,OFF ON_PREMISES_SERVER)
!define OFF_ON_PREMISES_SERVER(_alias,_label,_shape) ENTITY(_shape,black,on_premises_server,_label,_alias,OFF ON_PREMISES_SERVER)
!define OFF_ON_PREMISES_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,on_premises_server,_label,_alias,OFF ON_PREMISES_SERVER)
skinparam folderBackgroundColor<<OFF ON_PREMISES_SERVER>> White