sprite $reverse_proxy [37x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF00000000000000000000FFFFFFFFFFF
FFFFF0001222222222222221000FFFFFFFFFF
FFFFF007AAAAAAAAAAAAAAAA600FFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAAA10FFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFF03AAA655555555557AAA20FFFFFFFFFF
FFFFF03AAA300000000005AAA20FFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAA333000FFFFFFFFF
FFFFF03AAAAAAAAAAAAAA2011000FFFFFFFFF
FFFFF03AAAAAAAAAAAAA206A9100FFFFFFFFF
FFFFF03AAAAAAAAAAAA306A91000000000FFF
FFFFF03AAAAAAAAAAA305AA21111111000FFF
FFFFF03AAAAAAAAAA404AAAAAAAAAAA900FFF
FFFFF03AAAAAAAAAA505AAAAAAAAAAA800FFF
FFFFF03AAAAAAAAAAA405AA10000000000FFF
FFFFF03AAAAAAAAAAAA306AA1000000000FFF
FFFFF03AAA8777777777106AA0004AA100FFF
FFFFF03AAA30000000000000000004AA000FF
FFFFF03AAAAAAAAAAAAA50000000004AA000F
FFFFF03AAAAAAAAAAAAA6089999999AAA9000
FFFFF03AAAAAAAAAAAAA609AAAAAAAAAAA200
FFFFF03AAA422222222210122222223AA400F
FFFFF03AAA422222222211222000019A500FF
FFFFF03AAAAAAAAAAAAAAAAAA20019A500FFF
FFFFF03AAAAAAAAAAAAAAAAAA200233000FFF
FFFFF03AAAAAAAAAAAAAAAAAA20000000FFFF
FFFFF0399999999999999999910FFFFFFFFFF
FFFFF0000000000000000000000FFFFFFFFFF
FFFFF0000000000000000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_REVERSE_PROXY(_alias) ENTITY(rectangle,black,reverse_proxy,_alias,OFF REVERSE_PROXY)
!define OFF_REVERSE_PROXY(_alias,_label) ENTITY(rectangle,black,reverse_proxy,_label,_alias,OFF REVERSE_PROXY)
!define OFF_REVERSE_PROXY(_alias,_label,_shape) ENTITY(_shape,black,reverse_proxy,_label,_alias,OFF REVERSE_PROXY)
!define OFF_REVERSE_PROXY(_alias,_label,_shape,_color) ENTITY(_shape,_color,reverse_proxy,_label,_alias,OFF REVERSE_PROXY)
skinparam folderBackgroundColor<<OFF REVERSE_PROXY>> White