sprite $server_generic [31x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF00000000000000000000FFFFF
FFFFF000566666666666666300FFFFF
FFFFF008AAAAAAAAAAAAAAAA300FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAA511111111118AA800FFFF
FFFFF00AAA744444444449AA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAA9999999999AAA800FFFF
FFFFF00AAA500000000008AA800FFFF
FFFFF00AAA866666666669AA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAA744444444449AA800FFFF
FFFFF00AAA500000000008AA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFF
FFFFF0000000000000000000000FFFF
FFFFF0000000000000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SERVER_GENERIC(_alias) ENTITY(rectangle,black,server_generic,_alias,OFF SERVER_GENERIC)
!define OFF_SERVER_GENERIC(_alias,_label) ENTITY(rectangle,black,server_generic,_label,_alias,OFF SERVER_GENERIC)
!define OFF_SERVER_GENERIC(_alias,_label,_shape) ENTITY(_shape,black,server_generic,_label,_alias,OFF SERVER_GENERIC)
!define OFF_SERVER_GENERIC(_alias,_label,_shape,_color) ENTITY(_shape,_color,server_generic,_label,_alias,OFF SERVER_GENERIC)
skinparam folderBackgroundColor<<OFF SERVER_GENERIC>> White