sprite $sharepoint_server [48x46/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000FFFFFFF
FFFFFFFFF0000000000000000FFF0000000000000FFFFFFF
FFFFFFF00000000000000000000000000002588000FFFFFF
FFFFFF0002333333333333332000047999999980000FFFFF
FFFFFF009AAAAAAAAAAAAAAAA700099999999983500FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAA000999999999879600FFFF
FFFFFF01AAAAAAAAAAAAAAAAAA0009999768998799200FFF
FFFFFF01AAAAAAAAAAAAAAAAAA000999413699823083000F
FFFFFF01AAA200000000005AAA000999159999800009400F
FFFFFF01AAA644444444448AAA0009995039998000099800
FFFFFF01AAAAAAAAAAAAAAAAAA0009999704998000099800
FFFFFF01AAAAAAAAAAAAAAAAAA000999472399800009710F
FFFFFF01AAAAAAAAAAAAAAAAAA000999312999811064000F
FFFFFF01AAAAAAAAAAAAAAAAAA0009999999998799500FFF
FFFFFF01AAAAAAAAAAAAAAAAAA000999999999879600FFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00099999999985700FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00056789999980000FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA000000002457700FFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00FF00000000000FFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00FFFFFFFF00000FFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAA422222222227AAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAA322222222226AAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAA988888888889AAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAA200000000005AAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAA99999999999AAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFF0011111111111111111100FFFFFFFFFFFFFFFFFFFF
FFFFFF0000000000000000000000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SHAREPOINT_SERVER(_alias) ENTITY(rectangle,black,sharepoint_server,_alias,OFF SHAREPOINT_SERVER)
!define OFF_SHAREPOINT_SERVER(_alias,_label) ENTITY(rectangle,black,sharepoint_server,_label,_alias,OFF SHAREPOINT_SERVER)
!define OFF_SHAREPOINT_SERVER(_alias,_label,_shape) ENTITY(_shape,black,sharepoint_server,_label,_alias,OFF SHAREPOINT_SERVER)
!define OFF_SHAREPOINT_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,sharepoint_server,_label,_alias,OFF SHAREPOINT_SERVER)
skinparam folderBackgroundColor<<OFF SHAREPOINT_SERVER>> White