sprite $skype_for_business_server [44x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000FFFFFF
FFFFFF0000000000000000000F00025521100000FFFF
FFFFF000222222222222221000006623666761000FFF
FFFFF009AAAAAAAAAAAAAAA600054000000037300FFF
FFFFF03AAAAAAAAAAAAAAAAA000700003552007200FF
FFFFF04AAAAAAAAAAAAAAAAA100700077568501700FF
FFFFF04AAAAAAAAAAAAAAAAA1006100850035006200F
FFFFF04AAA22222222224AAA1004300775310004400F
FFFFF04AAA33333333335AAA1004200167875003500F
FFFFF04AAAAAAAAAAAAAAAAA1003400100268104400F
FFFFF04AAAAAAAAAAAAAAAAA1000700730058101700F
FFFFF04AAAAAAAAAAAAAAAAA1000720676685000700F
FFFFF04AAAAAAAAAAAAAAAAA1000071013310000700F
FFFFF04AAAAAAAAAAAAAAAAA10F0017500000005400F
FFFFF04AAAAAAAAAAAAAAAAA10FF000477775466000F
FFFFF04AAAAAAAAAAAAAAAAA10FFF0000000331000FF
FFFFF04AAAAAAAAAAAAAAAAA10FFFF00000000000FFF
FFFFF04AAAAAAAAAAAAAAAAA10FFFFFFFFF0000FFFFF
FFFFF04AAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAA44444444446AAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAA21111111114AAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAA88888888889AAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAA00000000003AAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAA87777777778AAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFFFFFF
FFFFF04AAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFFFFFF
FFFFF001111111111111111100FFFFFFFFFFFFFFFFFF
FFFFF000000000000000000000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_SERVER(_alias) ENTITY(rectangle,black,skype_for_business_server,_alias,OFF SKYPE_FOR_BUSINESS_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_SERVER(_alias,_label) ENTITY(rectangle,black,skype_for_business_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_SERVER(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_SERVER)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_SERVER>> White