sprite $skype_for_business_edge_server_pool [48x42/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFF00000000000000000FFFFFFFFFFF000000000FFFFFF
FFFFF029999999999999500FFFFFFFFF00366333000FFFFF
FFFF00BBBBBBBBBBBBBBB00FFFFFFFF00540032476000FFF
FFFF00BBBBBBBBBA87777000000000F00600001002700FFF
FFFF00BBBBBBBB60000000000000000014005788702600FF
FFFF00BBB0000007BBBBBBBBBBBBB70005008300700700FF
FFFF00BBB999970BBBBBBBBBBBBBBB0007007752000420FF
FFFF00BBBBBBB80BBBBBBBBBBBBBBB0007000477800330FF
FFFF00BBBBBBB80BBA888888888BBB0007004000840330FF
FFFF00BBBBBBB80BB9000000000BBB0003307736810060FF
FFFF00BBBBBBB80BBBBBBBBBBBBBBB0000710565100060FF
FFFF00BBBBBBB80BBBBBBBBBBBBBBB00F0074000000620FF
FFFF00BBBBBBB80BBBBBBBBBBBBBBB00FF003777767500FF
FFFF00BBBBBBB80BBBBBBBBBBBBBBB00FFF0000001000FFF
FFFF00BBBBBBB80BBBBBBBBBBBBBBB00FFFFF0000000FFFF
FFFF00BBBBBBB80BBBBBBBBBBBBBBB00FFFFFFFFFFFFFFFF
FFFF00BBBBBBB80BBBBBBBBBBBBBBB00FFFFFFFFFFFFFFFF
FFFF00BBBBBBB80BBBBBBBBBBBBBBB00FFFFFFFFFFFFFFFF
FFFF00BBBBBBB80BBBBBBBBBBBBBBB00FFFFFFFFFFFFFFFF
FFFF00BBBBBBB80BBBBBBBBBBBBBBB00FFFFFFFFFFFFFFFF
FFFF00BBBBBBB80BBBBBBBBBBB900000F000000FFFFFFFFF
FFFF00BBBBBBB80BBBBBBBBBB8039900F0399100FFFFFFFF
FFFF00BBB000000BBBBBBBBB904BA1000004BB100FFFFFFF
FFFF00BBB888860BBBBBBBB705BA200000005BA300FFFFFF
FFFF00BBBBBBB80BBBBBBB607BBAAAAAAAAAABBB300FFFFF
FFFF00BBB999970BBA999903BBBBBBBBBBBBBBBBB00FFFFF
FFFF00BBB000000BB90000004BBA777777777ABB100FFFFF
FFFF00BBBBBBB80BBBBBBBB804BB500000007BA200FFFFFF
FFFF00BBBBBBB80BBBBBBBBB804BB400F007BB200FFFFFFF
FFFF00BBBBBBB80BBA66666665036620F0466100FFFFFFFF
FFFF00444444430BBA11111111111100F000000FFFFFFFFF
FFFF00000000000BBBBBBBBBBBBBBB00FFFFFFFFFFFFFFFF
FFFFFFFFFFFFF00BBBBBBBBBBBBBBB00FFFFFFFFFFFFFFFF
FFFFFFFFFFFFF00BBBBBBBBBBBBBBB00FFFFFFFFFFFFFFFF
FFFFFFFFFFFFF0000000000000000000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFF0000000000000000000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_EDGE_SERVER_POOL(_alias) ENTITY(rectangle,black,skype_for_business_edge_server_pool,_alias,OFF SKYPE_FOR_BUSINESS_EDGE_SERVER_POOL)
!define OFF_SKYPE_FOR_BUSINESS_EDGE_SERVER_POOL(_alias,_label) ENTITY(rectangle,black,skype_for_business_edge_server_pool,_label,_alias,OFF SKYPE_FOR_BUSINESS_EDGE_SERVER_POOL)
!define OFF_SKYPE_FOR_BUSINESS_EDGE_SERVER_POOL(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_edge_server_pool,_label,_alias,OFF SKYPE_FOR_BUSINESS_EDGE_SERVER_POOL)
!define OFF_SKYPE_FOR_BUSINESS_EDGE_SERVER_POOL(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_edge_server_pool,_label,_alias,OFF SKYPE_FOR_BUSINESS_EDGE_SERVER_POOL)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_EDGE_SERVER_POOL>> White