sprite $skype_for_business_persistent_chat_server [45x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000FFFFFFF
FFFFFF0000000000000000000F00025521100000FFFFF
FFFFF00011111111111111100F005633666762000FFFF
FFFFF009AAAAAAAAAAAAAAA8000360000000274000FFF
FFFFF02AAAAAAAAAAAAAAAAA000700003552006300FFF
FFFFF02AAAAAAAAAAAAAAAAA000700057567600700FFF
FFFFF02AAAAAAAAAAAAAAAAA0005200850025005300FF
FFFFF02AAA21111111112AAA0002500775310002600FF
FFFFF02AAA33333333333AAA0002400157885001600FF
FFFFF02AAAAAAAAAAAAAAAAA0001600100268202600FF
FFFFF02AAAAAAAAAAAAAAAAA0000701840048200700FF
FFFFF02AAAAAAAAAAAAAAAAA0000530586676000610FF
FFFFF02AAAAAAAAAAAAAAAAA0000072013320000700FF
FFFFF02AAAAAAAAAAAAAAAAA00F0017510000004600FF
FFFFF02AAAAAAAAAAAAAAAAA00FF000377775467000FF
FFFFF02AAAAAAAAAAAAAAAAA00FFF0000000342000FFF
FFFFF02AAAAAAAAAAAAAAAAA00FFFF00000000000FFFF
FFFFF02AAAAAAAAAAAAAAAAA00FFFFFFFFFF000FFFFFF
FFFFF02AAAAAAAAAAA6555550000000000000FFFFFFFF
FFFFF02AAAAAAAAAA000000000000000000000FFFFFFF
FFFFF02AAAAAAAAA30AAAAAAAAAAAAAAAAAA20FFFFFFF
FFFFF02AAAAAAAAA30AAAAAAAAAAAAAAAAAA30FFFFFFF
FFFFF02AAAAAAAAA30AAAAAAAAAAAAAAAAAA30FFFFFFF
FFFFF02AAAAAAAAA30AAA919AAAAAAA26AAA30FFFFFFF
FFFFF02AAAAAAAAA30AAA000AAAAAA500AAA30FFFFFFF
FFFFF02AAAAAAAAA30AAA303AA54AA702AAA30FFFFFFF
FFFFF02AAAAAAAAA30AA86868A00795977AA30FFFFFFF
FFFFF02AAA44444410AA00000A009300009A30FFFFFFF
FFFFF02AAA11111100AA000055886500007A30FFFFFFF
FFFFF02AAAAAAAAA30AA99999000039999AA30FFFFFFF
FFFFF02AAAAAAAAA30AAAAAA600002AAAAAA30FFFFFFF
FFFFF02AAA88888820AAAAAA988889AAAAAA30FFFFFFF
FFFFF02AAA00000000AAAAAAAAAAAAAAAAAA30FFFFFFF
FFFFF02AAA77777720AAAAAAAAAAAAAAAAAA20FFFFFFF
FFFFF02AAAAAAAAA80233333333AAAA3333200FFFFFFF
FFFFF02AAAAAAAAAA7222222000AAA20000000FFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA000AA400FFFFFFFFFFFFF
FFFFF0022222222222222222000A600FFFFFFFFFFFFFF
FFFFF0000000000000000000000800FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_PERSISTENT_CHAT_SERVER(_alias) ENTITY(rectangle,black,skype_for_business_persistent_chat_server,_alias,OFF SKYPE_FOR_BUSINESS_PERSISTENT_CHAT_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_PERSISTENT_CHAT_SERVER(_alias,_label) ENTITY(rectangle,black,skype_for_business_persistent_chat_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_PERSISTENT_CHAT_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_PERSISTENT_CHAT_SERVER(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_persistent_chat_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_PERSISTENT_CHAT_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_PERSISTENT_CHAT_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_persistent_chat_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_PERSISTENT_CHAT_SERVER)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_PERSISTENT_CHAT_SERVER>> White