sprite $skype_for_business_director_array [48x41/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF00000000000000000FFFFFFFFFF000000000FFFFFF
FFFFF006AAAAAAAAAAAAA10FFFFFFFFF005776651000FFFF
FFFFF00BBBBBBBBBBBBBB90FFFFFFFF00530011247100FFF
FFFFF00BBBBBBBBB53333300000000F00600014200700FFF
FFFFF00BBB777770133333333333310005006756701700FF
FFFFF00BBB000001BBBBBBBBBBBBBA0007007500300600FF
FFFFF00BBBBBBB24BBBBBBBBBBBBBB2007004886200510FF
FFFFF00BBBBBBB24BBBBBBBBBBBBBB2006000016810510FF
FFFFF00BBBBBBB24BB5111111117BB2004107200820250FF
FFFFF00BBBBBBB24BB8666666669BB2000704877600060FF
FFFFF00BBBBBBB24BBBBBBBBBBBBBB20F0260000000340FF
FFFFF00BBBBBBB24BBBBBBBBBBBBBB20F0017656203700FF
FFFFF00BBBBBBB24BBBBBBBBBBBBBB20FF00001146400FFF
FFFFF00BBBBBBB24BBBBBBBBBBBBBB20FFFF00000000FFFF
FFFFF00BBBBBBB24BBBBBBBBBBBBBB20FFFFFFFFFFFFFFFF
FFFFF00BBBBBBB24BBBBBBBBBBBBBB20FFFFFFFFFFFFFFFF
FFFFF00BBBBBBB24BBBBBBBBBBBBBB20FFFFFFFFFFFFFFFF
FFFFF00BBBBBBB24BBBBBBBBBBBBBB2000000FFFFFFFFFFF
FFFFF00BBBBBBB24BBBBBBBBBBBBBB20288700FFFFFFFFFF
FFFFF00BBBBBBB24BBBBBBBBBBBBBB0034BB00FFFFFFFFFF
FFFFF00BBBBBBB24BBBBBBBBBBBBBB100A8B00FFFFFFFFFF
FFFFF00BBB000004BBBBBBBBBBBBBB00A70A00FFFFFFFFFF
FFFFF00BBB888814BBBBBBBBBBBBA10A8000000FFFFFFFFF
FFFFF00BBBBBBB24BBBBBBBBBBBB11A70004A10FFFFFFFFF
FFFFF00BBB999924BBA9999999911A9111117A100FFFFFFF
FFFFF00BBB000004BB30000000007BBBBBBBBB800FFFFFFF
FFFFF00BBBBBBB24BBBBBBBBBBB508A000009900FFFFFFFF
FFFFF00BBBBBBB24BBBBBBBBBBBB608A0003500FFFFFFFFF
FFFFF00BBBBBBB24BB5222222227B508B00300FFFFFFFFFF
FFFFF00111111104BB6444444448BB107A0B00FFFFFFFFFF
FFFFF00000000004BBBBBBBBBBBBBB0007BB00FFFFFFFFFF
FFFFFFFFFFFFFF04BBBBBBBBBBBBBB1099BB00FFFFFFFFFF
FFFFFFFFFFFFFF04AAAAAAAAAAAAAA20021000FFFFFFFFFF
FFFFFFFFFFFFFF000000000000000000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_DIRECTOR_ARRAY(_alias) ENTITY(rectangle,black,skype_for_business_director_array,_alias,OFF SKYPE_FOR_BUSINESS_DIRECTOR_ARRAY)
!define OFF_SKYPE_FOR_BUSINESS_DIRECTOR_ARRAY(_alias,_label) ENTITY(rectangle,black,skype_for_business_director_array,_label,_alias,OFF SKYPE_FOR_BUSINESS_DIRECTOR_ARRAY)
!define OFF_SKYPE_FOR_BUSINESS_DIRECTOR_ARRAY(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_director_array,_label,_alias,OFF SKYPE_FOR_BUSINESS_DIRECTOR_ARRAY)
!define OFF_SKYPE_FOR_BUSINESS_DIRECTOR_ARRAY(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_director_array,_label,_alias,OFF SKYPE_FOR_BUSINESS_DIRECTOR_ARRAY)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_DIRECTOR_ARRAY>> White