sprite $skype_for_business_mediation_server [43x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF000000000FFFFFFF
FFFFFFF0000000000000000FFF000110000000FFFFF
FFFFF0000000000000000000000276676652000FFFF
FFFFF00799999999999999600007100111266000FFF
FFFFF05AAAAAAAAAAAAAAAA20062000022003700FFF
FFFFF06AAAAAAAAAAAAAAAA300700047887304500FF
FFFFF06AAAAAAAAAAAAAAAA300620075006700700FF
FFFFF06AAA3333333333AAA300060077200000520FF
FFFFF06AAA1111111111AAA300150027788200430FF
FFFFF06AAAAAAAAAAAAAAAA3000600000377005200F
FFFFF06AAAAAAAAAAAAAAAA3000701830067003500F
FFFFF06AAAAAAAAAAAAAAAA3000530686685001600F
FFFFF06AAAAAAAAAAAAAAAA30F0072024420002600F
FFFFF06AAAAAAAAAAAAAAAA30F0017400000006200F
FFFFF06AAAAAAAAAAAAAAAA30FF00047777547400FF
FFFFF06AAAAAAAAAAAAAAAA30FFF0000000230000FF
FFFFF06AAAAAAAAAAAAAAAA30FFFFF000000000FFFF
FFFFF06AAAAAAAAAAAAAAAA30FFFFFFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAA30FFFFFFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAA30FFFFFFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAA30FFFFFFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAA30FFFFFFFFFFFFFFFFFF
FFFFF06AAAAAAAAAA4224720000000000000FFFFFFF
FFFFF06AAAAAAAAA004300233333333333200FFFFFF
FFFFF06AAAAAAAA70AAA80AAAAAAAAAAAAA00FFFFFF
FFFFF06AAAAAAAA60AAA90AA766666666AA00FFFFFF
FFFFF06AAAAAAAA60AAA90AA200000001AA00FFFFFF
FFFFF06AAA0000000AAA90AA200000001AA00FFFFFF
FFFFF06AAA6666640AAA90AA311111112AA00FFFFFF
FFFFF06AAAAAAAA70AAA90AAAAAAAAAAAAA00FFFFFF
FFFFF06AAAAAAAA70AAA80AAA9AA9AA9AAA00FFFFFF
FFFFF06AAA3333320AAA80AAA01805508AA00FFFFFF
FFFFF06AAA2222210AAA80AAA89A8AA8AAA00FFFFFF
FFFFF06AAAAAAAA70AAA80AAA13916618AA00FFFFFF
FFFFF06AAAAAAAA60AAA90AAA36937739AA00FFFFFF
FFFFF06AAAAAAAA60AAA90AAA79A7A97AAA00FFFFFF
FFFFF046666666630AAA90AAA01805508AA00FFFFFF
FFFFF000000000000AAA90AAAAAAAAAAAAA00FFFFFF
FFFFFFFFFFFFFFF00AAA80AAAAAAAAAAAAA00FFFFFF
FFFFFFFFFFFFFFF0004400244444444444300FFFFFF
FFFFFFFFFFFFFFFF00000000000000000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_MEDIATION_SERVER(_alias) ENTITY(rectangle,black,skype_for_business_mediation_server,_alias,OFF SKYPE_FOR_BUSINESS_MEDIATION_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_MEDIATION_SERVER(_alias,_label) ENTITY(rectangle,black,skype_for_business_mediation_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_MEDIATION_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_MEDIATION_SERVER(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_mediation_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_MEDIATION_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_MEDIATION_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_mediation_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_MEDIATION_SERVER)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_MEDIATION_SERVER>> White