sprite $skype_for_business_director [46x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000FFFFFFF
FFFFFF0000000000000000000FF00177765530000FFFFF
FFFFF000666666666666666400F017100343676000FFFF
FFFFF00ABBBBBBBBBBBBBBBB500071000000005700FFFF
FFFFF00BBBBBBBBBBBBBBBBBA000800016776005600FFF
FFFFF00BBBBBBBBBBBBBBBBBB000800078238700710FFF
FFFFF00BBBBBBBBBBBBBBBBBB0008000850014003600FF
FFFFF00BBB100000000009BBB0006100886520000800FF
FFFFF00BBB54444444444ABBB0007000157886000800FF
FFFFF00BBBBBBBBBBBBBBBBBB0005200200168100800FF
FFFFF00BBBBBBBBBBBBBBBBBB0001701840058100800FF
FFFFF00BBBBBBBBBBBBBBBBBB0000710686686000710FF
FFFFF00BBBBBBBBBBBBBBBBBB0000170023320000700FF
FFFFF00BBBBBBBBBBBBBBBBBB00F0027400000003700FF
FFFFF00BBBBBBBBBBBBBBBBBB00FF001577674357100FF
FFFFF00BBBBBBBBBBBBBBBBBB00FFF0000111453000FFF
FFFFF00BBBBBBBBBBBBBBBBBB00FFFF00000000000FFFF
FFFFF00BBBBBBBBBBBBBBBBBB00FFFFFFFFFF000FFFFFF
FFFFF00BBBBBBBBBBBBBBBBBB00000000FFFFFFFFFFFFF
FFFFF00BBBBBBBBBBBBBBBBBB00022210FFFFFFFFFFFFF
FFFFF00BBBBBBBBBBBBBBBBBB009BBBA0FFFFFFFFFFFFF
FFFFF00BBBBBBBBBBBBBBBBBB0013BBB00FFFFFFFFFFFF
FFFFF00BBBBBBBBBBBBBBBBBB000AA9B00FFFFFFFFFFFF
FFFFF00BBBBBBBBBBBBBBBBB900AA18A00FFFFFFFFFFFF
FFFFF00BBBBBBBBBBBBBBBB900AA207000FFFFFFFFFFFF
FFFFF00BBBBBBBBBBBBBBB900AA10002200FFFFFFFFFFF
FFFFF00BBBBBBBBBBBBBBA009A200007B300FFFFFFFFFF
FFFFF00BBB99999999999009B31111119B200FFFFFFFFF
FFFFF00BBB0000000000008BBBBBBBBBBBB000FFFFFFFF
FFFFF00BBB6666666666600AB54444449B600FFFFFFFFF
FFFFF00BBBBBBBBBBBBBB800AA000004B700FFFFFFFFFF
FFFFF00BBBBBBBBBBBBBBB801AA00004400FFFFFFFFFFF
FFFFF00BBB54444444444AB701AA006000FFFFFFFFFFFF
FFFFF00BBB100000000009BB701AA08900FFFFFFFFFFFF
FFFFF00BBBBBBBBBBBBBBBBBB001AA8B00FFFFFFFFFFFF
FFFFF00BBBBBBBBBBBBBBBBBB0002BBB00FFFFFFFFFFFF
FFFFF00BBBBBBBBBBBBBBBBBB00ABBBB00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA000655400FFFFFFFFFFFF
FFFFF0000000000000000000000000000FFFFFFFFFFFFF
FFFFF0000000000000000000000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_DIRECTOR(_alias) ENTITY(rectangle,black,skype_for_business_director,_alias,OFF SKYPE_FOR_BUSINESS_DIRECTOR)
!define OFF_SKYPE_FOR_BUSINESS_DIRECTOR(_alias,_label) ENTITY(rectangle,black,skype_for_business_director,_label,_alias,OFF SKYPE_FOR_BUSINESS_DIRECTOR)
!define OFF_SKYPE_FOR_BUSINESS_DIRECTOR(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_director,_label,_alias,OFF SKYPE_FOR_BUSINESS_DIRECTOR)
!define OFF_SKYPE_FOR_BUSINESS_DIRECTOR(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_director,_label,_alias,OFF SKYPE_FOR_BUSINESS_DIRECTOR)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_DIRECTOR>> White