sprite $skype_for_business_edge_server [46x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFF
FFFFFFF00000000000000000FFF0000100000000FFFFFF
FFFFFF00000000000000000000F00687788861000FFFFF
FFFFF003BBBBBBBBBBBBBBB8000064000000277000FFFF
FFFFF00BBBBBBBBBBBBBBBBB5001700000000047000FFF
FFFFF01BBBBBBBBBBBBBBBBB7002500068888105500FFF
FFFFF01BBBBBBBBBBBBBBBBB7002600383007700700FFF
FFFFF01BBB88888888888ABB70007103840000006200FF
FFFFF01BBB100000000009BB70007100788860004400FF
FFFFF01BBBBBBBBBBBBBBBBB70006100004787004400FF
FFFFF01BBBBBBBBBBBBBBBBB70005203600068004600FF
FFFFF01BBBBBBBBBBBBBBBBB70003604861377000700FF
FFFFF01BBBBBBBBBBBBBBBBB70000620378870000700FF
FFFFF01BBBBBBBBBBBBBBBBB70000073000000002700FF
FFFFF01BBBBBBBBBBBBBBBBB700F0006842310027000FF
FFFFF01BBBBBBBBBBBBBBBBB700FF00004657887000FFF
FFFFF01BBBBBBBBBBBBBBBBB700FFFF00000000000FFFF
FFFFF01BBBBBBBBBBBBBBBBB700FFFFFFFFF0000FFFFFF
FFFFF01BBBBBBBBBBBBBBBBB700FFFFFFFFFFFFFFFFFFF
FFFFF01BBBBBBBBBBBBBBBBB700FFFFFFFFFFFFFFFFFFF
FFFFF01BBBBBBBBBBBBBBBBB700FFFFFFFFFFFFFFFFFFF
FFFFF01BBBBBBBBBBBBBA100000F000000FFFFFFFFFFFF
FFFFF01BBBBBBBBBBBBA1022200F01222000FFFFFFFFFF
FFFFF01BBBBBBBBBBBA008BB300F006BB6000FFFFFFFFF
FFFFF01BBBBBBBBBB9009BB300000006BB7000FFFFFFFF
FFFFF01BBBBBBBBB9009BB40000000007BB7000FFFFFFF
FFFFF01BBBBBBBB900ABBBBBBBBBBBBBBBBB8000FFFFFF
FFFFF01BBBBBBB900ABBBBBBBBBBBBBBBBBBB9000FFFFF
FFFFF01BBB10000002BBBBBBBBBBBBBBBBBBA000FFFFFF
FFFFF01BBB422222103BBA10000000004BBB100FFFFFFF
FFFFF01BBBBBBBBBB603BBA100000003BBB100FFFFFFFF
FFFFF01BBBBBBBBBBB603BBA100F003BBB100FFFFFFFFF
FFFFF01BBB88888888840388700F01888100FFFFFFFFFF
FFFFF01BBB10000000000000000F0000000FFFFFFFFFFF
FFFFF01BBBBBBBBBBBBBBBBB700FFFFFFFFFFFFFFFFFFF
FFFFF01BBBBBBBBBBBBBBBBB700FFFFFFFFFFFFFFFFFFF
FFFFF01BBBBBBBBBBBBBBBBB700FFFFFFFFFFFFFFFFFFF
FFFFF01BBBBBBBBBBBBBBBBB700FFFFFFFFFFFFFFFFFFF
FFFFF0000000000000000000000FFFFFFFFFFFFFFFFFFF
FFFFF0000000000000000000000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_EDGE_SERVER(_alias) ENTITY(rectangle,black,skype_for_business_edge_server,_alias,OFF SKYPE_FOR_BUSINESS_EDGE_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_EDGE_SERVER(_alias,_label) ENTITY(rectangle,black,skype_for_business_edge_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_EDGE_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_EDGE_SERVER(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_edge_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_EDGE_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_EDGE_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_edge_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_EDGE_SERVER)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_EDGE_SERVER>> White