sprite $skype_for_business_front_end_pool [48x41/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF00000000000000000FFFFFFFFFF000000000FFFFFF
FFFFF008AAAAAAAAAAAAA10FFFFFFFFF002776441000FFFF
FFFFF01BBBBBBBBBBBBBB80FFFFFFFFF0350012257100FFF
FFFFF02BBBBBBBBA65555400000000F007000032007100FF
FFFFF02BBA999990011111111111100007004767800700FF
FFFFF02BB7000001ABBBBBBBBBBBBA1007008600400520FF
FFFFF02BBBBBBB15BBBBBBBBBBBBBB4006004885100150FF
FFFFF02BBBBBBB15BBBBBBBBBBBBBB4006000136840150FF
FFFFF02BBBBBBB15BB6333333336BB4004308300770060FF
FFFFF02BBBBBBB15BB6333333336BB4000704866710070FF
FFFFF02BBBBBBB15BBBBBBBBBBBBBB4000260010000070FF
FFFFF02BBBBBBB15BBBBBBBBBBBBBB40F0027422100620FF
FFFFF02BBBBBBB15BBBBBBBBBBBBBB40FF000133677100FF
FFFFF02BBBBBBB15BBBBBBBBBBBBBB40FFFF000000000FFF
FFFFF02BBBBBBB15BBBBBBBBBBBBBB40FFFFFFFF000FFFFF
FFFFF02BBBBBBB15BBBBBBBBBBBBBB40FFFFFFFFFFFFFFFF
FFFFF02BBBBBBB15BBBBBBBBBA11110000FFFFFFFFFFFFFF
FFFFF02BBBBBBB15BBBBBBBBB907777730000FFFFFFFFFFF
FFFFF02BBBBBBB15BBBBBBBBB90BBBBB60080FFFFFFFFFFF
FFFFF02BBBBBBB15BBBBBBBBB90B6B7A600A00FFFFFFFFFF
FFFFF02BBBBBBB15BBBBBBBBB90B9B9A609A700FFFFFFFFF
FFFFF02BB9555505BBBBBBBBB90B6B7A60BB900FFFFFFFFF
FFFFF02BB8333305BBBBBBBBB90B9B9A68BBB500FFFFFFFF
FFFFF02BBBBBBB15BBBBBBBBB90B7B8A89BBB800FFFFFFFF
FFFFF02BBBBBBB15BBBBBBBBB90B8B9ABB8BBB10FFFFFFFF
FFFFF02BB7000005BB300000000B7B8ABB4BBB10FFFFFFFF
FFFFF02BB9777705BB877777760B8B8ABBBA4B10FFFFFFFF
FFFFF02BBBBBBB15BBBBBBBBB90B8B8ABBBAAB10FFFFFFFF
FFFFF02BBBBBBB15BB999999980B7B8ABB1BBB10FFFFFFFF
FFFFF01888888805BB300000000BBBBBBBBBBB10FFFFFFFF
FFFFF00000000005BBBBBBBBB90BBBBBBBBBBB10FFFFFFFF
FFFFFFFFFFFFFF05BBBBBBBBB90BBBBBBBBBBB10FFFFFFFF
FFFFFFFFFFFFFF05BBBBBBBBB90BBBBBBBBBBB10FFFFFFFF
FFFFFFFFFFFFFF01222222222202222222222200FFFFFFFF
FFFFFFFFFFFFFF00000000000000000000000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_FRONT_END_POOL(_alias) ENTITY(rectangle,black,skype_for_business_front_end_pool,_alias,OFF SKYPE_FOR_BUSINESS_FRONT_END_POOL)
!define OFF_SKYPE_FOR_BUSINESS_FRONT_END_POOL(_alias,_label) ENTITY(rectangle,black,skype_for_business_front_end_pool,_label,_alias,OFF SKYPE_FOR_BUSINESS_FRONT_END_POOL)
!define OFF_SKYPE_FOR_BUSINESS_FRONT_END_POOL(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_front_end_pool,_label,_alias,OFF SKYPE_FOR_BUSINESS_FRONT_END_POOL)
!define OFF_SKYPE_FOR_BUSINESS_FRONT_END_POOL(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_front_end_pool,_label,_alias,OFF SKYPE_FOR_BUSINESS_FRONT_END_POOL)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_FRONT_END_POOL>> White