sprite $skype_for_business_front_end_server [44x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF000000000FFFFFFFF
FFFFFFF00000000000000000FF000010000000FFFFFF
FFFFF00000000000000000000000576767631000FFFF
FFFFF00599999999999999700005400021257300FFFF
FFFFF04AAAAAAAAAAAAAAAA800160000121006400FFF
FFFFF05AAAAAAAAAAAAAAAAA002500068875007100FF
FFFFF05AAAAAAAAAAAAAAAAA001600482028303500FF
FFFFF05AAA55555555559AAA000700584001000700FF
FFFFF05AAA00000000008AAA000700078875000700FF
FFFFF05AAAAAAAAAAAAAAAAA000700001368500700FF
FFFFF05AAAAAAAAAAAAAAAAA000520560008600610FF
FFFFF05AAAAAAAAAAAAAAAAA0002604864683004300F
FFFFF05AAAAAAAAAAAAAAAAA0000630268610004300F
FFFFF05AAAAAAAAAAAAAAAAA000007500000000710FF
FFFFF05AAAAAAAAAAAAAAAAA00F000477673017400FF
FFFFF05AAAAAAAAAAAAAAAAA00FF0000021576200FFF
FFFFF05AAAAAAAAAAAAAAAAA00FFFF0000000000FFFF
FFFFF05AAAAAAAAAAAAAAAAA00FFFFFFFFF000FFFFFF
FFFFF05AAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFF
FFFFF05AAAAAAAAAAA7777770000FFFFFFFFFFFFFFFF
FFFFF05AAAAAAAAAAA00000000000000FFFFFFFFFFFF
FFFFF05AAAAAAAAAAA06999997000000FFFFFFFFFFFF
FFFFF05AAAAAAAAAAA07AAAAA8004400FFFFFFFFFFFF
FFFFF05AAAAAAAAAAA07A5A6A80055000FFFFFFFFFFF
FFFFF05AAAAAAAAAAA07A5A6A80288200FFFFFFFFFFF
FFFFF05AAAAAAAAAAA07AAAAA804AA400FFFFFFFFFFF
FFFFF05AAAAAAAAAAA07A0A19828AA820FFFFFFFFFFF
FFFFF05AAA3333333307AAAAA83AAAA300FFFFFFFFFF
FFFFF05AAA0000000007A3A4AA8AAAA810FFFFFFFFFF
FFFFF05AAAAAAAAAAA07A8A8AAAAAAAA20FFFFFFFFFF
FFFFF05AAAAAAAAAAA07AAAAAAA65AAA20FFFFFFFFFF
FFFFF05AAA9999999907A1A2AAAAAAAA20FFFFFFFFFF
FFFFF05AAA0000000007AAAAAAAAA57A20FFFFFFFFFF
FFFFF05AAA8888888807A2A3AAAA9AAA20FFFFFFFFFF
FFFFF05AAAAAAAAAAA07A9A9AAA76AAA20FFFFFFFFFF
FFFFF05AAAAAAAAAAA07AAAAAAAAAAAA20FFFFFFFFFF
FFFFF05AAAAAAAAAAA07AAAAAAAAAAAA20FFFFFFFFFF
FFFFF001111111111107AAAAAAAAAAAA20FFFFFFFFFF
FFFFF000000000000007AAAAAAAAAAAA20FFFFFFFFFF
FFFFFFFFFFFFFFFFFF07AAAAAAAAAAAA20FFFFFFFFFF
FFFFFFFFFFFFFFFFFF0000000000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFF0000000000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_FRONT_END_SERVER(_alias) ENTITY(rectangle,black,skype_for_business_front_end_server,_alias,OFF SKYPE_FOR_BUSINESS_FRONT_END_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_FRONT_END_SERVER(_alias,_label) ENTITY(rectangle,black,skype_for_business_front_end_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_FRONT_END_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_FRONT_END_SERVER(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_front_end_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_FRONT_END_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_FRONT_END_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_front_end_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_FRONT_END_SERVER)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_FRONT_END_SERVER>> White