sprite $skype_for_business_back_end_server [45x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000FFFFFFFF
FFFFFFF00000000000000000FFF000000000000FFFFFF
FFFFFF0000000000000000000F00057764431000FFFFF
FFFFF001566666666666666100007400243576000FFFF
FFFFF00ABBBBBBBBBBBBBBBA000350000000047100FFF
FFFFF02BBBBBBBBBBBBBBBBB100610016886203700FFF
FFFFF02BBBBBBBBBBBBBBBBB1006100673268106200FF
FFFFF02BBB99999999999BBB1002500770003002600FF
FFFFF02BBB10000000000ABB1001600487641000700FF
FFFFF02BBB87777777777ABB1001600024687100700FF
FFFFF02BBBBBBBBBBBBBBBBB1001600410038300700FF
FFFFF02BBBBBBBBBBBBBBBBB1000710772158200610FF
FFFFF02BBBBBBBBBBBBBBBBB1000260178874000610FF
FFFFF02BBBBBBBBBBBBBBBBB10F0046000100000700FF
FFFFF02BBBBBBBBBBBBBBBBB10F0004752220006400FF
FFFFF02BBBBBBBBBBBBBBBBB10FF000035667674000FF
FFFFF02BBBBBBBBBBBBBBBBB10FFF0000000010000FFF
FFFFF02BBBBBBBBBBBBBBBBB10FFFFF0000000000FFFF
FFFFF02BBBBBBBBBBBBBBBBB10FFFFFFFFFFFFFFFFFFF
FFFFF02BBBBBBBBBBBBBBBBB10FFFFFFFFFFFFFFFFFFF
FFFFF02BBBBBBBBBBBBBBBBB10FFFFFFFFFFFFFFFFFFF
FFFFF02BBBBBBBBBBBBBBA300000000000FFFFFFFFFFF
FFFFF02BBBBBBBBBBBBA1001478987400000FFFFFFFFF
FFFFF02BBBBBBBBBBBB107BBBBBBBBBBB600FFFFFFFFF
FFFFF02BBBBBBBBBBBB06BBBBBBBBBBBBB50FFFFFFFFF
FFFFF02BBBBBBBBBBBB009ABBBBBBBBBA800FFFFFFFFF
FFFFF02BBBBBBBBBBBB05105899999840120FFFFFFFFF
FFFFF02BBBAAAAAAAAA08B95321112369B40FFFFFFFFF
FFFFF02BBB10000000008BBBBBBBBBBBBB40FFFFFFFFF
FFFFF02BBB65555555508BBBBBBBBBBBBB40FFFFFFFFF
FFFFF02BBBBBBBBBBBB08BBBBBBBBBBBBB40FFFFFFFFF
FFFFF02BBBBBBBBBBBB08BBBBBBBBBBBBB40FFFFFFFFF
FFFFF02BBB65555555508BBBBBBBBBBBBB40FFFFFFFFF
FFFFF02BBB20000000008BBBBBBBBBBBBB40FFFFFFFFF
FFFFF02BBBBBBBBBBBB08BBBBBBBBBBBBB40FFFFFFFFF
FFFFF02BBBBBBBBBBBB08BBBBBBBBBBBBB40FFFFFFFFF
FFFFF02BBBBBBBBBBBB08BBBBBBBBBBBBB40FFFFFFFFF
FFFFF02AAAAAAAAAAAA08BBBBBBBBBBBBB40FFFFFFFFF
FFFFF0000000000000003BBBBBBBBBBBBB20FFFFFFFFF
FFFFF00000000000000003ABBBBBBBBB9200FFFFFFFFF
FFFFFFFFFFFFFFFFFFFF000123454321000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF0000000000000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF0000000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_BACK_END_SERVER(_alias) ENTITY(rectangle,black,skype_for_business_back_end_server,_alias,OFF SKYPE_FOR_BUSINESS_BACK_END_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_BACK_END_SERVER(_alias,_label) ENTITY(rectangle,black,skype_for_business_back_end_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_BACK_END_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_BACK_END_SERVER(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_back_end_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_BACK_END_SERVER)
!define OFF_SKYPE_FOR_BUSINESS_BACK_END_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_back_end_server,_label,_alias,OFF SKYPE_FOR_BUSINESS_BACK_END_SERVER)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_BACK_END_SERVER>> White