sprite $sql_server [39x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0000000000000000000FFFFFFFFFFFFFF
FFFFF000111111111111111000FFFFFFFFFFFFF
FFFFF009AAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA10FFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAA20FFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAA20FFFFFFFFFFFFF
FFFFF03AAA22222222222AAA20FFFFFFFFFFFFF
FFFFF03AAA33333333333AAA20FFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAA20FFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAA20FFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAA20FFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAA20FFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAA20FFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAA20FFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAA20FFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAA20FFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAA20FFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAA20FFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAA20FFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAAA20FFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAA6555510000000000FFFF
FFFFF03AAAAAAAAAA80000000000000000000FF
FFFFF03AAAAAAAAAA01AAAAAAAAAAAAAAA700FF
FFFFF03AAAAAAAAAA07AAAAAAAAAAAAAAAA00FF
FFFFF03AAAAAAAAAA07AAAAAAAAAAAAAAAA10FF
FFFFF03AAAAAAAAAA07AAAAAAAAAAAAAAAA10FF
FFFFF03AAA444444407AAAAAAAAAAAAAAAA10FF
FFFFF03AAA111111107AAA89AA88AA9AAAA10FF
FFFFF03AAAAAAAAAA07AA155A2333A1AAAA10FF
FFFFF03AAAAAAAAAA07AA15A92AA1A1AAAA10FF
FFFFF03AAA999999907AAA4192AA1A1AAAA10FF
FFFFF03AAA000000007AA680A2653A178AA10FF
FFFFF03AAA777777707AA758AA7628778AA10FF
FFFFF03AAAAAAAAAA07AAAAAAAAAAAAAAAA10FF
FFFFF03AAAAAAAAAA07AAAAAAAAAAAAAAAA10FF
FFFFF03AAAAAAAAAA07AAAAAAAAAAAAAAAA10FF
FFFFF00222222222207AAAAAAAAAAAAAAAA10FF
FFFFF00000000000006AAAAAAAAAAAAAAAA00FF
FFFFFFFFFFFFFFFFF00788888888888888300FF
FFFFFFFFFFFFFFFFF00000000000000000000FF
FFFFFFFFFFFFFFFFFF00000000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SQL_SERVER(_alias) ENTITY(rectangle,black,sql_server,_alias,OFF SQL_SERVER)
!define OFF_SQL_SERVER(_alias,_label) ENTITY(rectangle,black,sql_server,_label,_alias,OFF SQL_SERVER)
!define OFF_SQL_SERVER(_alias,_label,_shape) ENTITY(_shape,black,sql_server,_label,_alias,OFF SQL_SERVER)
!define OFF_SQL_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,sql_server,_label,_alias,OFF SQL_SERVER)
skinparam folderBackgroundColor<<OFF SQL_SERVER>> White