sprite $survivable_branch_server [37x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF000000000000000000FFFFFFFFFFFFF
FFFFF00111111111111111000FFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAA10FFFFFFFFFFFF
FFFF008AAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFF009AA622222222229AA60FFFFFFFFFFFF
FFFF009AA733333333339AA60FFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFF009AAAAAAAAAAAAAAAA60FFFFFFFFFFFF
FFFF009AAAAAAAAAAA7666630000FFFFFFFFF
FFFF009AAAAAAAAAAA20000000000000FFFFF
FFFF009AAAAAAAAAAA22AAAAAA000000FFFFF
FFFF009AAAAAAAAAAA22AAAAAA001900FFFFF
FFFF009AAAAAAAAAAA22A6A87A0019000FFFF
FFFF009AAAAAAAAAAA22A6A87A006A400FFFF
FFFF009AAAAAAAAAAA22AAAAAA00AA9000FFF
FFFF009AAAAAAAAAAA22A2974A06AAA4000FF
FFFF009AAAAAAAAAAA22AAAAAA0AAAA9000FF
FFFF009AAAAAAAAAAA22A5A87A6AAAAA400FF
FFFF009AAAAAAAAAAA22A7A98AAAAAAA800FF
FFFF009AA84444444412A9AAAAAA2AAA800FF
FFFF009AA61111111102A2975AAAAA9A800FF
FFFF009AAAAAAAAAAA22AAAAAAAAA92A800FF
FFFF009AAAAAAAAAAA22A5A86AAA9AAA800FF
FFFF009AAA9999999922A7A98AAA2AAA800FF
FFFF009AA60000000002AAAAAAAAAAAA800FF
FFFF009AA97777777722AAAAAAAAAAAA800FF
FFFF009AAAAAAAAAAA22888888888888700FF
FFFF009AAAAAAAAAAA20000003700000000FF
FFFF009AAAAAAAAAAA20000003800000000FF
FFFF0022222222222200222088883122100FF
FFFF0000000000000002AAA0AAAA56AA800FF
FFFFFFFFFFFFFFFFFF00111088883111100FF
FFFFFFFFFFFFFFFFFF00000000000000000FF
FFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SURVIVABLE_BRANCH_SERVER(_alias) ENTITY(rectangle,black,survivable_branch_server,_alias,OFF SURVIVABLE_BRANCH_SERVER)
!define OFF_SURVIVABLE_BRANCH_SERVER(_alias,_label) ENTITY(rectangle,black,survivable_branch_server,_label,_alias,OFF SURVIVABLE_BRANCH_SERVER)
!define OFF_SURVIVABLE_BRANCH_SERVER(_alias,_label,_shape) ENTITY(_shape,black,survivable_branch_server,_label,_alias,OFF SURVIVABLE_BRANCH_SERVER)
!define OFF_SURVIVABLE_BRANCH_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,survivable_branch_server,_label,_alias,OFF SURVIVABLE_BRANCH_SERVER)
skinparam folderBackgroundColor<<OFF SURVIVABLE_BRANCH_SERVER>> White