sprite $survivable_branch_appliance [34x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFF000000000000000FFFFFFFFFFFFFF
FFFFF001111111111100FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAA00F00000FFFFFFFF
FFFFF01AAAAAAAAAAA00F00000FFFFFFFF
FFFFF01AA98AAA89AA00F07800FFFFFFFF
FFFFF01AA10AA804AA00F09A00FFFFFFFF
FFFFF01AA42AA825AA00F09A00FFFFFFFF
FFFFF01AAAAAAAAAAA00009A000FFFFFFF
FFFFF01AAAAAAAAAAA0003AA300FFFFFFF
FFFFF01AA32AA825AA000AAAA00FFFFFFF
FFFFF01AA10AA804AA000AAAA00FFFFFFF
FFFFF01AA99AAA99AA000AAAA0000FFFFF
FFFFF01AAAAAAAAAAA024AAAA4200FFFFF
FFFFF01AA76AA968AA07AAAAAA700FFFFF
FFFFF01AA10AA804AA07AAAAAA700FFFFF
FFFFF01AA54AA946AA07AAAAAA7000FFFF
FFFFF01AAAAAAAAAAA48AAAAAA9400FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF01AA20AA804AAAA55AAAAAA00FFFF
FFFFF01AA10AA804AAAA00AAAAAA00FFFF
FFFFF01AAAAAAAAAAAAA55AAAAAA00FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF01AA65AA957AAAAAAAA02AA00FFFF
FFFFF01AA10AA804AAAAAAAA02AA00FFFF
FFFFF01AA65AA957AAAAAAAAAAAA00FFFF
FFFFF01AAAAAAAAAAAAA44AAAAAA00FFFF
FFFFF01AAAAAAAAAAAAA00AAAAAA00FFFF
FFFFF01AAAAAAAAAAAAA66AAAAAA00FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF0033333333333333333333300FFFF
FFFFF0000000000037700000000000FFFF
FFFFFFFFFFFFFF004AA00FFFFFFFFFFFFF
FFFFFFFFFFFF00004AA0000FFFFFFFFFFF
FFFF0000000000001220000000000000FF
FFFF0000000000288888800000000000FF
FFFF00888888863AAAAAA08888888400FF
FFFF01AAAAAAA83AAAAAA0AAAAAAA500FF
FFFF00888888863AAAAAA08888888400FF
FFFF0000000000288888800000000000FF
FFFF0000000000000000000000000000FF
FFFFFFFFFFFFF0000000000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SURVIVABLE_BRANCH_APPLIANCE(_alias) ENTITY(rectangle,black,survivable_branch_appliance,_alias,OFF SURVIVABLE_BRANCH_APPLIANCE)
!define OFF_SURVIVABLE_BRANCH_APPLIANCE(_alias,_label) ENTITY(rectangle,black,survivable_branch_appliance,_label,_alias,OFF SURVIVABLE_BRANCH_APPLIANCE)
!define OFF_SURVIVABLE_BRANCH_APPLIANCE(_alias,_label,_shape) ENTITY(_shape,black,survivable_branch_appliance,_label,_alias,OFF SURVIVABLE_BRANCH_APPLIANCE)
!define OFF_SURVIVABLE_BRANCH_APPLIANCE(_alias,_label,_shape,_color) ENTITY(_shape,_color,survivable_branch_appliance,_label,_alias,OFF SURVIVABLE_BRANCH_APPLIANCE)
skinparam folderBackgroundColor<<OFF SURVIVABLE_BRANCH_APPLIANCE>> White