sprite $trusted_application_pool [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFF
F00266666666666666666000FFFFFFFFFFFFFFFFFFFFFFFF
F02AAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFFFFFF
F06AAAAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFFFFFFFFFFFF
F06AAAAAAAAAAAAAAAAAAA100000000000FFFFFFFFFFFFFF
F06AAAAAAAAAA9100000000000000000000FFFFFFFFFFFFF
F06AAA433333310577777777777777775000FFFFFFFFFFFF
F06AAA100000006AAAAAAAAAAAAAAAAAA500FFFFFFFFFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
F06AAAAAAAAA20AAAA222222222222AAAA00FFFFFFFFFFFF
F06AAAAAAAAA20AAAA000000000000AAAA00FFFFFFFFFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAAAAA8420000000FFFFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAAA82001233210000FFFFF
F06AAAAAAAAA20AAAAAAAAAAAAAA5003AAAAAAA810000FFF
F06AAAAAAAAA20AAAAAAAAAAAAA202AAAAAAAAAAA7000FFF
F06AAAAAAAAA20AAAAAAAAAAAA503AAAAAAAAAAAAA9000FF
F06AAAAAAAAA20AAAAAAAAAAA802AAAAAAAAAAAAAAA8000F
F06AAA10000000AAAAAAAAAAA20AAAAAAAAAAAA916AA500F
F06AAA32222200AAAAAAAAAA803AAAAAAAAAAAA2009AA10F
F06AAAAAAAAA20AAAAAAAAAA40AAAAAAAAAAAA3004AAA400
F06AAAAAAAAA20AAAAAAAAAA21AAAAAAAAAAA7003AAAA700
F06AAAAAAAAA20AAAAAAAAAA02AAAA87AAAA90019AAAA900
F06AAA10000000AAAA00000003AAA8008AAA2008AAAAAA00
F06AAA32222200AAAA22222203AAA80009A4007AAAAAAA00
F06AAAAAAAAA20AAAAAAAAAA12AAAA80005003AAAAAAA900
F06AAAAAAAAA20AAAAAAAAAA31AAAAA700001AAAAAAAA600
F06AAAAAAAAA20AAAAAAAAAA508AAAAA60019AAAAAAAA300
F06AAAAAAAAA20AAAA000000001AAAAAA407AAAAAAAA900F
F0000000000000AAAA3333333207AAAAAA8AAAAAAAAA200F
F0000000000000AAAAAAAAAAA9009AAAAAAAAAAAAAA500FF
FFFFFFFFFFFF00AAAAAAAAAAAA9008AAAAAAAAAAAA5000FF
FFFFFFFFFFFF00AAAAAAAAAAAAA8005AAAAAAAAA92000FFF
FFFFFFFFFFFF00AAAAAAAAAAAAAA8201479AA9630000FFFF
FFFFFFFFFFFF000000000000000000000000000000FFFFFF
FFFFFFFFFFFF0000000000000000000000000000FFFFFFFF
}

!define OFF_TRUSTED_APPLICATION_POOL(_alias) ENTITY(rectangle,black,trusted_application_pool,_alias,OFF TRUSTED_APPLICATION_POOL)
!define OFF_TRUSTED_APPLICATION_POOL(_alias,_label) ENTITY(rectangle,black,trusted_application_pool,_label,_alias,OFF TRUSTED_APPLICATION_POOL)
!define OFF_TRUSTED_APPLICATION_POOL(_alias,_label,_shape) ENTITY(_shape,black,trusted_application_pool,_label,_alias,OFF TRUSTED_APPLICATION_POOL)
!define OFF_TRUSTED_APPLICATION_POOL(_alias,_label,_shape,_color) ENTITY(_shape,_color,trusted_application_pool,_label,_alias,OFF TRUSTED_APPLICATION_POOL)
skinparam folderBackgroundColor<<OFF TRUSTED_APPLICATION_POOL>> White