sprite $trusted_application_server [40x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF000000000000000000FFFFFFFFFFFFFFF
FFFFFF00011111111111111000FFFFFFFFFFFFFF
FFFFF004AAAAAAAAAAAAAAAA300FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAA722222222227AA900FFFFFFFFFFFFF
FFFFF00AAA711111111117AA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA7000000000FFFFFF
FFFFF00AAAAAAAAAAAAAAA9300245420000FFFFF
FFFFF00AAAAAAAAAAAAAA8005AAAAAAA5000FFFF
FFFFF00AAAAAAAAAAAAA8019AAAAAAAAAA200FFF
FFFFF00AAAAAAAAAAAA901AAAAAAAAAAAAA200FF
FFFFF00AAAAAAAAAAAA309AAAAAAAAAA79AA000F
FFFFF00AAAAAAAAAAA905AAAAAAAAAA900AA600F
FFFFF00AAA6000000000AAAAAAAAAAA100AAA00F
FFFFF00AAA7333333302AAAAAAAAAA4009AAA200
FFFFF00AAAAAAAAAAA05AAAA9AAAA7006AAAA600
FFFFF00AAAAAAAAAAA06AAA308AAA003AAAAA800
FFFFF00AAA9888888706AAA2009A201AAAAAA800
FFFFF00AAA6000000004AAAA1004009AAAAAA500
FFFFF00AAAA999999922AAAA900007AAAAAAA100
FFFFF00AAAAAAAAAAA509AAAA8004AAAAAAAA00F
FFFFF00AAAAAAAAAAA904AAAAA61AAAAAAAA500F
FFFFF00AAAAAAAAAAAA408AAAAAAAAAAAAAA00FF
FFFFF001111111111111009AAAAAAAAAAAA000FF
FFFFF0000000000000000008AAAAAAAAA9000FFF
FFFFFFFFFFFFFFFFFFFFF00029AAAAAA3000FFFF
FFFFFFFFFFFFFFFFFFFFFFF000001000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_TRUSTED_APPLICATION_SERVER(_alias) ENTITY(rectangle,black,trusted_application_server,_alias,OFF TRUSTED_APPLICATION_SERVER)
!define OFF_TRUSTED_APPLICATION_SERVER(_alias,_label) ENTITY(rectangle,black,trusted_application_server,_label,_alias,OFF TRUSTED_APPLICATION_SERVER)
!define OFF_TRUSTED_APPLICATION_SERVER(_alias,_label,_shape) ENTITY(_shape,black,trusted_application_server,_label,_alias,OFF TRUSTED_APPLICATION_SERVER)
!define OFF_TRUSTED_APPLICATION_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,trusted_application_server,_label,_alias,OFF TRUSTED_APPLICATION_SERVER)
skinparam folderBackgroundColor<<OFF TRUSTED_APPLICATION_SERVER>> White