sprite $tunnel_straight [48x10/16] {
000000000000000000000000000000000000000000000000
000032003444444444444444444444444444444444430000
0019AA604AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9100
007AAAA20AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA700
00AAAAA508AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAA508AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
007AAAA20AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA700
0019AA604AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA100
000032003444444444444444444444444444444444430000
000000000000000000000000000000000000000000000000
}

!define OFF_TUNNEL_STRAIGHT(_alias) ENTITY(rectangle,black,tunnel_straight,_alias,OFF TUNNEL_STRAIGHT)
!define OFF_TUNNEL_STRAIGHT(_alias,_label) ENTITY(rectangle,black,tunnel_straight,_label,_alias,OFF TUNNEL_STRAIGHT)
!define OFF_TUNNEL_STRAIGHT(_alias,_label,_shape) ENTITY(_shape,black,tunnel_straight,_label,_alias,OFF TUNNEL_STRAIGHT)
!define OFF_TUNNEL_STRAIGHT(_alias,_label,_shape,_color) ENTITY(_shape,_color,tunnel_straight,_label,_alias,OFF TUNNEL_STRAIGHT)
skinparam folderBackgroundColor<<OFF TUNNEL_STRAIGHT>> White