sprite $tunnel_angled [48x32/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFF00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF00157400000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF0009AAAA40000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF008AAAAAA940000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF01AAAAAAAAA830000FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF02AAAAAAAAAAA820000FFFFFFFFFFFFFFFFFFFFFFFFFFF
FF01AAAAAAAAAAAAA80000FFFFFFFFFFFFFFFFFFFFFFFFFF
FF007AAAAAAAAAAAAAA70000FFFFFFFFFFFFFFFFFFFFFFFF
FF00049AAAAAAAAAAAAAA510000FFFFFFFFFFFFFFFFFFFFF
FFF000049AAAAAAAAAAAAAA400000FFFFFFFFFFFFFFFFFFF
FFFFF00005AAAAAAAAAAAAAAA30000FFFFFFFFFFFFFFFFFF
FFFFFF000016AAAAAAAAAAAAAA930000FFFFFFFFFFFFFFFF
FFFFFFFF000016AAAAAAAAAAAAAA820000FFFFFFFFFFFFFF
FFFFFFFFFF000028AAAAAAAAAAAAAA710000FFFFFFFFFFFF
FFFFFFFFFFFFF00019AAAAAAAAAAAAAA80000FFFFFFFFFFF
FFFFFFFFFFFFF0000039AAAAAAAAAAAAAA60000FFFFFFFFF
FFFFFFFFFFFFFFF0000049AAAAAAAAAAAAA9500000FFFFFF
FFFFFFFFFFFFFFFFFF000059AAAAAAAAAAAAA9300000FFFF
FFFFFFFFFFFFFFFFFFF000006AAAAAAAAAAAAAAA1000FFFF
FFFFFFFFFFFFFFFFFFFFF000017AAAAAAAAAAAA2000000FF
FFFFFFFFFFFFFFFFFFFFFFF000027AAAAAAAAA204996000F
FFFFFFFFFFFFFFFFFFFFFFFFF000028AAAAAA604AAAA300F
FFFFFFFFFFFFFFFFFFFFFFFFFFF00002AAAAA11AAAAA800F
FFFFFFFFFFFFFFFFFFFFFFFFFFFF000004AAA04AAAAA700F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000005A04AAAAA200F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000003AAAA8000F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000006AA7000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000110000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_TUNNEL_ANGLED(_alias) ENTITY(rectangle,black,tunnel_angled,_alias,OFF TUNNEL_ANGLED)
!define OFF_TUNNEL_ANGLED(_alias,_label) ENTITY(rectangle,black,tunnel_angled,_label,_alias,OFF TUNNEL_ANGLED)
!define OFF_TUNNEL_ANGLED(_alias,_label,_shape) ENTITY(_shape,black,tunnel_angled,_label,_alias,OFF TUNNEL_ANGLED)
!define OFF_TUNNEL_ANGLED(_alias,_label,_shape,_color) ENTITY(_shape,_color,tunnel_angled,_label,_alias,OFF TUNNEL_ANGLED)
skinparam folderBackgroundColor<<OFF TUNNEL_ANGLED>> White