sprite $tunnel_straight [48x17/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF00000000000000000000000000000000000FFFFFF
FFFFF000000111111111111111111111111111111000FFFF
FFFF003AA607AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FFFF
FFFF00AAAA12AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA800FFF
FFFF01AAAA51AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFF
FFFF00AAAA41AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA900FFF
FFFF008AAA04AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA600FFF
FFFFF006710788888888888888888888888888888500FFFF
FFFFF000000000000000000000000000000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_TUNNEL_STRAIGHT(_alias) ENTITY(rectangle,black,tunnel_straight,_alias,OFF TUNNEL_STRAIGHT)
!define OFF_TUNNEL_STRAIGHT(_alias,_label) ENTITY(rectangle,black,tunnel_straight,_label,_alias,OFF TUNNEL_STRAIGHT)
!define OFF_TUNNEL_STRAIGHT(_alias,_label,_shape) ENTITY(_shape,black,tunnel_straight,_label,_alias,OFF TUNNEL_STRAIGHT)
!define OFF_TUNNEL_STRAIGHT(_alias,_label,_shape,_color) ENTITY(_shape,_color,tunnel_straight,_label,_alias,OFF TUNNEL_STRAIGHT)
skinparam folderBackgroundColor<<OFF TUNNEL_STRAIGHT>> White