sprite $voicemail_preview_partner [40x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF0000000000000000FFFFFFFFFFFFFFFF
FFFFFF00000000000000000000FFFFFFFFFFFFFF
FFFFFF009AAAAAAAAAAAAAA9100FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAA9999999999AAAA00FFFFFFFFFFFFF
FFFFF00AAA600000000002AAA00FFFFFFFFFFFFF
FFFFF00AAAA88888888889AAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAA300000000000000000000F
FFFFF00AAA977777720333333333333333333300
FFFFF00AAA600000002AAAAAAAAAAAAAAAAAAA00
FFFFF00AAAAAAAAAA02AAAAAAAAAAAAAAAAAAA00
FFFFF00AAAAAAAAAA02AAA5016AAAAA5116AAA00
FFFFF00AAAAAAAAAA02AA100002AAA200002AA00
FFFFF00AAA711111102A803AA10AA902AA10AA00
FFFFF00AAA722222202A40AAA706A60AAA806A00
FFFFF00AAAAAAAAAA02A608AA408A806AA508A00
FFFFF00AAAAAAAAAA02AA004300888003300AA00
FFFFF00AAAAAAAAAA02AA91000000000001AAA00
FFFFF00999999999902AAAAA999999999AAAAA00
FFFFF00000000000002AAAAAAAAAAAAAAAAAAA00
FFFFF00000000000002AAAAAAAAAAAAAAAAAAA00
FFFFFFFFFFFFFFFFF00111111111111111111000
FFFFFFFFFFFFFFFFFF000000000000000000000F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_VOICEMAIL_PREVIEW_PARTNER(_alias) ENTITY(rectangle,black,voicemail_preview_partner,_alias,OFF VOICEMAIL_PREVIEW_PARTNER)
!define OFF_VOICEMAIL_PREVIEW_PARTNER(_alias,_label) ENTITY(rectangle,black,voicemail_preview_partner,_label,_alias,OFF VOICEMAIL_PREVIEW_PARTNER)
!define OFF_VOICEMAIL_PREVIEW_PARTNER(_alias,_label,_shape) ENTITY(_shape,black,voicemail_preview_partner,_label,_alias,OFF VOICEMAIL_PREVIEW_PARTNER)
!define OFF_VOICEMAIL_PREVIEW_PARTNER(_alias,_label,_shape,_color) ENTITY(_shape,_color,voicemail_preview_partner,_label,_alias,OFF VOICEMAIL_PREVIEW_PARTNER)
skinparam folderBackgroundColor<<OFF VOICEMAIL_PREVIEW_PARTNER>> White