sprite $web_server [40x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0000000000000000000FFFFFFFFFFFFFFF
FFFFF000222222222222222000FFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFF003AAA00000000001AAA30FFFFFFFFFFFFFF
FFFF003AAA22222222223AAA30FFFFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FFFF003AAAAAAAAAAAAAAAAA300000000FFFFFFF
FFFF003AAAAAAAAAAAAAAAA500000200000FFFFF
FFFF003AAAAAAAAAAAAAAA10222A28A05000FFFF
FFFF003AAAAAAAAAAAAAA00771AA28AA0A400FFF
FFFF003AAAAAAAAAAAAA100517AA28AA352000FF
FFFF003AAAAAAAAAAAA507A200472552005A300F
FFFF003AAAAAAAAAAAA03AA45A741258A19AA00F
FFFF003AAA88888888408AA28AAA37AAA46AA500
FFFF003AAA00000000008AA1AAAA37AAA73AA600
FFFF003AAAAAAAAAAA020180AAAA37AAAA070200
FFFF003AAAAAAAAAAA05A910169A37A85003AA00
FFFF003AAAAAAAAAAA05AAA194100001590AAA00
FFFF003AAA0000000004AAA0AAAA38AAA91AAA00
FFFF003AAA22222222009AA0AAAA38AAA73AA200
FFFF003AAAAAAAAAAA5002A28AAA38AAA4650000
FFFF003AAAAAAAAAAA90460038AA38AA7002A00F
FFFF003AAAAAAAAAAAA308A80000000040AA500F
FFFF002888888888888700AA18AA28AA34A800FF
FFFF0000000000000000000961AA28AA0A7000FF
FFFFFFFFFFFFFFFFFFFFF000425A28A161000FFF
FFFFFFFFFFFFFFFFFFFFFF0000011300000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFF0000000000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_WEB_SERVER(_alias) ENTITY(rectangle,black,web_server,_alias,OFF WEB_SERVER)
!define OFF_WEB_SERVER(_alias,_label) ENTITY(rectangle,black,web_server,_label,_alias,OFF WEB_SERVER)
!define OFF_WEB_SERVER(_alias,_label,_shape) ENTITY(_shape,black,web_server,_label,_alias,OFF WEB_SERVER)
!define OFF_WEB_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,web_server,_label,_alias,OFF WEB_SERVER)
skinparam folderBackgroundColor<<OFF WEB_SERVER>> White