sprite $windows_server [44x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000
FFFFFF0000000000000000000F000000001356677400
FFFFF000011111111111111000002466646777777400
FFFFF006AAAAAAAAAAAAAAAA20027777746777777400
FFFFF00AAAAAAAAAAAAAAAAA70027777746777777400
FFFFF00AAAAAAAAAAAAAAAAA80027777746777777400
FFFFF00AAAAAAAAAAAAAAAAA80027777746777777400
FFFFF00AAA522222222228AA80026666645666666300
FFFFF00AAA511111111118AA80015555535555555300
FFFFF00AAAAAAAAAAAAAAAAA80027777746777777400
FFFFF00AAAAAAAAAAAAAAAAA80027777746777777400
FFFFF00AAAAAAAAAAAAAAAAA80027777746777777400
FFFFF00AAAAAAAAAAAAAAAAA80027777746777777400
FFFFF00AAAAAAAAAAAAAAAAA80003457746777777400
FFFFF00AAAAAAAAAAAAAAAAA80000000011222222100
FFFFF00AAAAAAAAAAAAAAAAA800F0000000000000000
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFF000000000
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF00AAA400000000008AA800FFFFFFFFFFFFFFFFF
FFFFF00AAA622222222228AA800FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF00AAA98888888888AAA800FFFFFFFFFFFFFFFFF
FFFFF00AAA400000000008AA800FFFFFFFFFFFFFFFFF
FFFFF00AAAA9999999999AAA800FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFF0011111111111111111100FFFFFFFFFFFFFFFFF
FFFFF0000000000000000000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_WINDOWS_SERVER(_alias) ENTITY(rectangle,black,windows_server,_alias,OFF WINDOWS_SERVER)
!define OFF_WINDOWS_SERVER(_alias,_label) ENTITY(rectangle,black,windows_server,_label,_alias,OFF WINDOWS_SERVER)
!define OFF_WINDOWS_SERVER(_alias,_label,_shape) ENTITY(_shape,black,windows_server,_label,_alias,OFF WINDOWS_SERVER)
!define OFF_WINDOWS_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,windows_server,_label,_alias,OFF WINDOWS_SERVER)
skinparam folderBackgroundColor<<OFF WINDOWS_SERVER>> White