sprite $application_android [48x17/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF0000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF6BBBBBBBBBAABB0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF9BBBBBBBBBBBBB0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF9000000000000B0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF900000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF9000000000ABB00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF900000000A9BBB0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF9000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF90000000BABBBB24FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF90000000BABBBB24FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF87777772BABBBB24FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF0000000006BBBB00FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF090B0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF1040FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_APPLICATION_ANDROID(_alias) ENTITY(rectangle,black,application_android,_alias,OFF APPLICATION_ANDROID)
!define OFF_APPLICATION_ANDROID(_alias,_label) ENTITY(rectangle,black,application_android,_label,_alias,OFF APPLICATION_ANDROID)
!define OFF_APPLICATION_ANDROID(_alias,_label,_shape) ENTITY(_shape,black,application_android,_label,_alias,OFF APPLICATION_ANDROID)
!define OFF_APPLICATION_ANDROID(_alias,_label,_shape,_color) ENTITY(_shape,_color,application_android,_label,_alias,OFF APPLICATION_ANDROID)
skinparam folderBackgroundColor<<OFF APPLICATION_ANDROID>> White