sprite $attachment [32x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF00000000FFFFFFFFFFFFFF
FFFFFFFFF0000000000FFFFFFFFFFFFF
FFFFFFFF0006AAAA9100FFFFFFFFFFFF
FFFFFFF0009BBBBBBA300FFFFFFFFFFF
FFFFFFF008BBA658BBA100FFFFFFFFFF
FFFFFF001AB910005AB600FFFFFFFFFF
FFFFFF007BB2000009BA00FFFFFFFFFF
FFFFFF00ABB0000006BB1000FFFFFFFF
FFFFFF00BBA0000005BB100000FFFFFF
FFFFFF00BBA03B4005BB101000FFFFFF
FFFFFF00BBA08B9005BB14BA00FFFFFF
FFFFFF00BBA08B9005BB15BA00FFFFFF
FFFFFF00BBA08B9005BB15BA00FFFFFF
FFFFFF00BBA08B9005BB15BA00FFFFFF
FFFFFF00BBA08B9005BB15BA00FFFFFF
FFFFFF00BBA08B9005BB15BA00FFFFFF
FFFFFF00BBA08B9005BB15BA00FFFFFF
FFFFFF00BBA08B9005BB15BA00FFFFFF
FFFFFF00BBA08B9005BB15BA00FFFFFF
FFFFFF00BBA08B9005BB15BA00FFFFFF
FFFFFF00BBA08B9005BB15BA00FFFFFF
FFFFFF00BBA08B9006BB15BA00FFFFFF
FFFFFF00BBA06BA219BA05BA00FFFFFF
FFFFFF00BBA03ABBBBB605BA00FFFFFF
FFFFFF00BBA005ABBB9005BA00FFFFFF
FFFFFF00BBA00006620005BA00FFFFFF
FFFFFF00ABB00000000006BA00FFFFFF
FFFFFF006BB20000000009B900FFFFFF
FFFFFF000AB8000000004BB500FFFFFF
FFFFFFF008BB60000003AB9000FFFFFF
FFFFFFF000ABB942137ABA300FFFFFFF
FFFFFFFF0019BBBBBBBBA300FFFFFFFF
FFFFFFFFF0006AABBBA8100FFFFFFFFF
FFFFFFFFFF000003310000FFFFFFFFFF
FFFFFFFFFFF0000000000FFFFFFFFFFF
FFFFFFFFFFFFFF00000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ATTACHMENT(_alias) ENTITY(rectangle,black,attachment,_alias,OFF ATTACHMENT)
!define OFF_ATTACHMENT(_alias,_label) ENTITY(rectangle,black,attachment,_label,_alias,OFF ATTACHMENT)
!define OFF_ATTACHMENT(_alias,_label,_shape) ENTITY(_shape,black,attachment,_label,_alias,OFF ATTACHMENT)
!define OFF_ATTACHMENT(_alias,_label,_shape,_color) ENTITY(_shape,_color,attachment,_label,_alias,OFF ATTACHMENT)
skinparam folderBackgroundColor<<OFF ATTACHMENT>> White