sprite $backup_local [43x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF00899300FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF009AA400FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF009AA400FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF009AA400FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF009AA400FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF009AA400FFFFFFFFFFFFFFFFF
FFFFFFFFFFFF0000FF009AA400FF0000FFFFFFFFFFF
FFFFFFFFFFFF00000F009AA400F00000FFFFFFFFFFF
FFFFFFFFFFFF004000009AA400000100FFFFFFFFFFF
FFFFFFFFFFFF009400009AA400007300FFFFFFFFFFF
FFFFFFFFFFFF009A40009AA40007A300FFFFFFFFFFF
FFFFFFFFFFFF009AA4009AA4007AA300FFFFFFFFFFF
FFFFFFFFFFFF009AAA409AA407AAA300FFFFFFFFFFF
FFFFFFFFFFFF000AAAA49AA47AAA7000FFFFFFFFFFF
FFFFFFFFFFFFF0009AAAAAAAAAA7000FFFFFFFFFFFF
FFFFFFFFFFFFFF0019AAAAAAAA7000FFFFFFFFFFFFF
FFFFFFFFFFFFFFF0019AAAAAA6000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF0019AAAA7000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF0019AA7000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF000A7000FFFFFFFFFFFFFFFFF
FFFFF0000000000000000000000000000000000FFFF
FFF0000000000000000000000000000000000000FFF
FFF0049AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9200FF
FFF02AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA89A900FF
FF004AAAAAAAAAAAAAAAAAAAAAAAAAAAAA800AA10FF
FF004AAAAAAAAAAAAAAAAAAAAAAAAAAAAA800AA10FF
FF004AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FF
FF004AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FF
FF004AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FF
FF004AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FF
FF004AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FF
FF004AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FF
FF000111111111111111111111111111111111100FF
FF000000000000000000000000000000000000000FF
FFF00000000000000000000000000000000000000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_BACKUP_LOCAL(_alias) ENTITY(rectangle,black,backup_local,_alias,OFF BACKUP_LOCAL)
!define OFF_BACKUP_LOCAL(_alias,_label) ENTITY(rectangle,black,backup_local,_label,_alias,OFF BACKUP_LOCAL)
!define OFF_BACKUP_LOCAL(_alias,_label,_shape) ENTITY(_shape,black,backup_local,_label,_alias,OFF BACKUP_LOCAL)
!define OFF_BACKUP_LOCAL(_alias,_label,_shape,_color) ENTITY(_shape,_color,backup_local,_label,_alias,OFF BACKUP_LOCAL)
skinparam folderBackgroundColor<<OFF BACKUP_LOCAL>> White