sprite $best_practices [47x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF0000000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0000000386100F0000FFFFFFFFFFFFFF
FFFFFFFFFFFFF000000006BBBA10000000FFFFFFFFFFFFF
FFFFFFFFFFFFF00597448BBBBBA54698200FFFFFFFFFFFF
FFFFFFFFFFFF006BBBBBBBBBBBBBBBBBA00FFFFFFFFFFFF
FFFFFFFFFFFF00ABBBBBBBBBBBBBBBBBB40FFFFFFFFFFFF
FFFFFFFFFF0001ABBBBBA87667ABBBBBB9000FFFFFFFFFF
FFFFFFFF000009BBBB94000000026ABBBA40000FFFFFFFF
FFFFFFFF0037ABBBA400479A9861019BBBB96100FFFFFFF
FFFFFFF006BBBBBA105ABBBBBBBB8106BBBBBA00FFFFFFF
FFFFFFF00ABBBBB108BBBBBBBBBBBA207BBBBB500FFFFFF
FFFFFFF00ABBBB308BBBBBBBBBBBBBA10ABBBB500FFFFFF
FFFFFFF009BBB806BBBBBBBBBBBAABBA01BBBB30FFFFFFF
FFFFFFF007BBB10ABBBBBBBBBBB31ABB709BBB10FFFFFFF
FFFFFFF008BBA07BBBBBBBBBBB6007BBA03BBB300FFFFFF
FFFFFF004ABB60ABBBBBBBBBB9003ABBB31BBB9000FFFFF
FFFFF003ABBB30ABBBBBBBBBA100ABBBB80BBBB800FFFFF
FFFFF009BBBB21BBBB81BBBB3009BBBBB90ABBBB30FFFFF
FFFFF00ABBBB21BBBA001BB6007BBBBBB90ABBBB400FFFF
FFFFF006BBBB20BBBB90029004BBBBBBB90ABBBA10FFFFF
FFFFFF009BBB40ABBBB700001ABBBBBBB50BBBA300FFFFF
FFFFFF000ABB809BBBBB50009BBBBBBBB01BBB500FFFFFF
FFFFFFF007BBB02BBBBBB307BBBBBBBBA06BBB10FFFFFFF
FFFFFFF008BBB509BBBBBA6BBBBBBBBB20BBBB20FFFFFFF
FFFFFFF00ABBBB00ABBBBBBBBBBBBBB706BBBB400FFFFFF
FFFFFFF00BBBBB902ABBBBBBBBBBBB802BBBBB600FFFFFF
FFFFFFF008BBBBB7019BBBBBBBBBA601BBBBBA300FFFFFF
FFFFFFF0018ABBBB80059BBBBBA7103ABBBB9500FFFFFFF
FFFFFFFF00016ABBBA400134420017BBBB820000FFFFFFF
FFFFFFFFF00005BBBBBA63211248ABBBBA00000FFFFFFFF
FFFFFFFFFFFF00ABBBBBBBBBBBBBBBBBB600FFFFFFFFFFF
FFFFFFFFFFFF009BBBBBBBBBBBBBBBBBA00FFFFFFFFFFFF
FFFFFFFFFFFF001ABBA9BBBBBBBAAABB600FFFFFFFFFFFF
FFFFFFFFFFFFF00021002ABBBB600021000FFFFFFFFFFFF
FFFFFFFFFFFFFF000000019BB500000000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF00011000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF000000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_BEST_PRACTICES(_alias) ENTITY(rectangle,black,best_practices,_alias,OFF BEST_PRACTICES)
!define OFF_BEST_PRACTICES(_alias,_label) ENTITY(rectangle,black,best_practices,_label,_alias,OFF BEST_PRACTICES)
!define OFF_BEST_PRACTICES(_alias,_label,_shape) ENTITY(_shape,black,best_practices,_label,_alias,OFF BEST_PRACTICES)
!define OFF_BEST_PRACTICES(_alias,_label,_shape,_color) ENTITY(_shape,_color,best_practices,_label,_alias,OFF BEST_PRACTICES)
skinparam folderBackgroundColor<<OFF BEST_PRACTICES>> White