sprite $book_journal [42x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF000000000000000000000000000FFFFFF
FFFFFFF00000000000000000000000000000FFFFFF
FFFFFF000488408888888888888888888820FFFFFF
FFFFFF007BBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF01BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBBB60BBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFF02BBB9508888888888888888888820FFFFFF
FFFFFF01BB70000000000000000000000000FFFFFF
FFFFFF009B97777777777777777777777720FFFFFF
FFFFFF0029BBBBBBBBBBBBBBBBBBBBBBBB30FFFFFF
FFFFFFF00012222222222222222222222200FFFFFF
FFFFFFFF0000000000000000000000000000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_BOOK_JOURNAL(_alias) ENTITY(rectangle,black,book_journal,_alias,OFF BOOK_JOURNAL)
!define OFF_BOOK_JOURNAL(_alias,_label) ENTITY(rectangle,black,book_journal,_label,_alias,OFF BOOK_JOURNAL)
!define OFF_BOOK_JOURNAL(_alias,_label,_shape) ENTITY(_shape,black,book_journal,_label,_alias,OFF BOOK_JOURNAL)
!define OFF_BOOK_JOURNAL(_alias,_label,_shape,_color) ENTITY(_shape,_color,book_journal,_label,_alias,OFF BOOK_JOURNAL)
skinparam folderBackgroundColor<<OFF BOOK_JOURNAL>> White