sprite $calculator [40x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF000000000000000000000FFFFFFFFF
FFFFFFFF000000000000000000000000FFFFFFFF
FFFFFFF00027888888888888888885000FFFFFFF
FFFFFFF005ABBBBBBBBBBBBBBBBBBB9000FFFFFF
FFFFFFF00ABBBBBBBBBBBBBBBBBBBBB300FFFFFF
FFFFFFF00AB911111111111111115BB400FFFFFF
FFFFFFF00AB700000000000000002BB400FFFFFF
FFFFFFF00AB700000000000000002BB400FFFFFF
FFFFFFF00AB700000000000000002BB400FFFFFF
FFFFFFF00AB700000000000000002BB400FFFFFF
FFFFFFF00AB700000000000000002BB400FFFFFF
FFFFFFF00ABA00000000000000005BB400FFFFFF
FFFFFFF00ABBAAAAAAAAAAAAAAAAABB400FFFFFF
FFFFFFF00ABBBBBBBBBBBBBBBBBBBBB400FFFFFF
FFFFFFF00ABBBBBBBBBBBBBBBBBBBBB400FFFFFF
FFFFFFF00ABBBBBBBBBBBBBBBBBBBBB400FFFFFF
FFFFFFF00ABB9223BB8224BB8225BBB400FFFFFF
FFFFFFF00ABB8000BB6002BB5003BBB400FFFFFF
FFFFFFF00ABB8000BB6002BB5003BBB400FFFFFF
FFFFFFF00ABBA777BBA778BBA779BBB400FFFFFF
FFFFFFF00ABBBBBBBBBBBBBBBBBBBBB400FFFFFF
FFFFFFF00ABBA666BB9667BB9668BBB400FFFFFF
FFFFFFF00ABB8000BB6002BB5003BBB400FFFFFF
FFFFFFF00ABB8000BB6002BB5003BBB400FFFFFF
FFFFFFF00ABB9222BB8224BB7225BBB400FFFFFF
FFFFFFF00ABBBBBBBBBBBBBBBBBBBBB400FFFFFF
FFFFFFF00ABBBBBBBBBBBBBBBBBBBBB400FFFFFF
FFFFFFF00ABB8001BB7002BB6003BBB400FFFFFF
FFFFFFF00ABB8000BB6002BB5003BBB400FFFFFF
FFFFFFF00ABB8000BB7002BB6003BBB400FFFFFF
FFFFFFF00ABBA999BBA99ABBA99ABBB400FFFFFF
FFFFFFF00ABBBBBBBBBBBBBBBBBBBBB400FFFFFF
FFFFFFF00ABBBBBBBBBBBBBBBBBBBBB400FFFFFF
FFFFFFF008BBBBBBBBBBBBBBBBBBBBA000FFFFFF
FFFFFFF0007BBBBBBBBBBBBBBBBBBA200FFFFFFF
FFFFFFFF000000000000000000000000FFFFFFFF
FFFFFFFFF0000000000000000000000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_CALCULATOR(_alias) ENTITY(rectangle,black,calculator,_alias,OFF CALCULATOR)
!define OFF_CALCULATOR(_alias,_label) ENTITY(rectangle,black,calculator,_label,_alias,OFF CALCULATOR)
!define OFF_CALCULATOR(_alias,_label,_shape) ENTITY(_shape,black,calculator,_label,_alias,OFF CALCULATOR)
!define OFF_CALCULATOR(_alias,_label,_shape,_color) ENTITY(_shape,_color,calculator,_label,_alias,OFF CALCULATOR)
skinparam folderBackgroundColor<<OFF CALCULATOR>> White