sprite $connector [48x39/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF0000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF0000000000000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF00003689987510000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF00039BBBBBBBBA71000FFFFFFFFFFF
FFFFFFFFFFFFFFFFF0006BBBBBBBBBBBBB4000FFFFFFFFFF
FFFFFFFFFFFFFFFF0009BBBBBAAAAABBBBB4000FFFFFFFFF
FFFFFFFFFFFFFFF0007BBBB92000014ABB5000FFFFFFFFFF
FFFFFFFFFFFFFFF005BBBA400000000075000FFFFFFFFFFF
FFFFFFFFFFFFFF000ABBA400000000000000FFFFFFFFFFFF
FFFFFFFFF00000004BBB70000011000000000000FFFFFFFF
FFFFFFF000000000ABBA000008BBB500000000000FFFFFFF
FFFFFFF000444445BBB800008BBBBB744444444000FFFFFF
FFFFFFF01ABBBBBBBBB60004BBBBBBBBBBBBBBBA10FFFFFF
FFFFFF005BBBBBBBBBB40006BBBBBBBBBBBBBBBB40FFFFFF
FFFFFFF04BBBBBBBBBB50005BBBBBBBBBBBBBBBB30FFFFFF
FFFFFFF006999999BBB60001ABBBBBA99999999500FFFFFF
FFFFFFF000000000BBB900004ABBBA10000000000FFFFFFF
FFFFFFFF000000008BBA400001674000000000000FFFFFFF
FFFFFFFFFFFFFF001ABB900000000000000FFFFFFFFFFFFF
FFFFFFFFFFFFFFF008BBB800000000003200FFFFFFFFFFFF
FFFFFFFFFFFFFFF001ABBB9300000005BA200FFFFFFFFFFF
FFFFFFFFFFFFFFFF003ABBBB952126ABBBA100FFFFFFFFFF
FFFFFFFFFFFFFFFFF003BBBBBBBBBBBBBB9000FFFFFFFFFF
FFFFFFFFFFFFFFFFF00018BBBBBBBBBBB5000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFF000037ABBBBB951000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF000002343100000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF0000000000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_CONNECTOR(_alias) ENTITY(rectangle,black,connector,_alias,OFF CONNECTOR)
!define OFF_CONNECTOR(_alias,_label) ENTITY(rectangle,black,connector,_label,_alias,OFF CONNECTOR)
!define OFF_CONNECTOR(_alias,_label,_shape) ENTITY(_shape,black,connector,_label,_alias,OFF CONNECTOR)
!define OFF_CONNECTOR(_alias,_label,_shape,_color) ENTITY(_shape,_color,connector,_label,_alias,OFF CONNECTOR)
skinparam folderBackgroundColor<<OFF CONNECTOR>> White