sprite $credit_card [48x37/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF0000000000000000000000000000000000FFFFFFF
FFFFF00000000000000000000000000000000000000FFFFF
FFFF0002444444444444444444444444444444443000FFFF
FFFF004BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFF
FFFF00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF0055555555555555555555555555555555555500FFFF
FFFF0000000000000000000000000000000000000000FFFF
FFFF0000000000000000000000000000000000000000FFFF
FFFF0011111111111111111111111111111111111100FFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFF
FFFF002BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB800FFFF
FFFFF001111111111111111111111111111111111000FFFF
FFFFF00000000000000000000000000000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_CREDIT_CARD(_alias) ENTITY(rectangle,black,credit_card,_alias,OFF CREDIT_CARD)
!define OFF_CREDIT_CARD(_alias,_label) ENTITY(rectangle,black,credit_card,_label,_alias,OFF CREDIT_CARD)
!define OFF_CREDIT_CARD(_alias,_label,_shape) ENTITY(_shape,black,credit_card,_label,_alias,OFF CREDIT_CARD)
!define OFF_CREDIT_CARD(_alias,_label,_shape,_color) ENTITY(_shape,_color,credit_card,_label,_alias,OFF CREDIT_CARD)
skinparam folderBackgroundColor<<OFF CREDIT_CARD>> White