sprite $folder_public [48x41/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF0000000000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF0000000000000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF0009AAAAAAAA900FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF000AAAAAAAAAAA80FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF001AAAAAAAAAAAAA00FFFFFFFFFF
FFFFFFFF000000000000019AAAAAAAAAAAAA00FFFFFFFFFF
FFFFFF00000000000000000000000000000000FFFFFFFFFF
FFFFFF00899999999999999999999999999900FFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAA810000000000000000FFFF
FFFFF00AAAAAAAAAAAAAAAAAAA028888888888888700FFFF
FFFFF00AAAAAAAAAAAAAAAAAA80AAAAAAAAAAAAAAAA00FFF
FFFFF00AAAAAAAAAAAAAAAAAA80AAAAAAAAAAAAAAAA00FFF
FFFFF00AAAAAAAAAAAAAAAAAA80AAAAAAAAAAAAAAAA00FFF
FFFFF00AAAAAAAAAAAAAAAAAA80AAAAAAAAAAAAAAAA00FFF
FFFFF00AAAAAAAAAAAAAAAAAA80AAA446AAAA544AAA00FFF
FFFFF00AAAAAAAAAAAAAAAAAA80AAA026AAA9600AAA00FFF
FFFFF00AAAAAAAAAAAAAAAAAA80AAA006AAAA230AAA00FFF
FFFFF00AAAAAAAAAAAAAAAAAA80AAA0A16AA23A4AAA00FFF
FFFFF00AAAAAAAAAAAAAAAAAA80AAAAAA1003AAAAAA00FFF
FFFFF0066666666666666666640AAAAAA600AAAAAAA00FFF
FFFFF0000000000000000000000AAAAAAA56AAAAAAA00FFF
FFFFF0000000000000000000000AAAAAAAAAAAAAAAA00FFF
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAA00FFF
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAA00FFF
FFFFFFFFFFFFFFFFFFFFFFFFF008AAAAAAAAAAAAAA50FFFF
FFFFFFFFFFFFFFFFFFFFFFFFF0000111111111111000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_FOLDER_PUBLIC(_alias) ENTITY(rectangle,black,folder_public,_alias,OFF FOLDER_PUBLIC)
!define OFF_FOLDER_PUBLIC(_alias,_label) ENTITY(rectangle,black,folder_public,_label,_alias,OFF FOLDER_PUBLIC)
!define OFF_FOLDER_PUBLIC(_alias,_label,_shape) ENTITY(_shape,black,folder_public,_label,_alias,OFF FOLDER_PUBLIC)
!define OFF_FOLDER_PUBLIC(_alias,_label,_shape,_color) ENTITY(_shape,_color,folder_public,_label,_alias,OFF FOLDER_PUBLIC)
skinparam folderBackgroundColor<<OFF FOLDER_PUBLIC>> White