sprite $folder_shared [48x41/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF000000000000000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF0007AAAAAAAAAA00FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF0009AAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFFFFFFFFFFF0009AAAAAAAAAAAAA00FFFFF
FFFFFFFFF00000000000000000AAAAAAAAAAAAAAA00FFFFF
FFFFFFF000000000000000000000000000000000000FFFFF
FFFFFFF002333333333333333333333333333333300FFFFF
FFFFFF009AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAA952000147AA00FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAA930024543001700FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAA8005AAAAAAA71000FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAA8019AAAAAAAAAA400FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAA01AAAAAAAA55AAA500FFFF
FFFFFF00AAAAAAAAAAAAAAAAA10AAAAA4100004AAA200FFF
FFFFFF00AAAAAAAAAAAAAAAAA06AAA901680001AAAA00FFF
FFFFFF00AAAAAAAAAAAAAAAA30AAAA03AAA80094AAA20FFF
FFFFFF00AAAAAAAAAAAAAAAA01AAAA8AAAAAAAA0AAA80FFF
FFFFFF00AAAAAAAAAAAAAAAA05AA203AAAAAAAA05AAA00FF
FFFFFF00AAAAAAAAAAAAAAAA07A8000AAAAAAAA22AAA00FF
FFFFFF00AAAAAAAAAAAAAAAA06AA000AAAAAAAA03AAA00FF
FFFFFF00AAAAAAAAAAAAAAAA03AA811AAAAAAAA08AAA00FF
FFFFFF00AAAAAAAAAAAAAAAA10AAA908AAAA4520AAA40FFF
FFFFFF00AAAAAAAAAAAAAAAA809AAA505AA10009AAA00FFF
FFFFFF000000000000000000000AAAA700A0001AAA600FFF
FFFFFF0000000000000000000005AAAAA89900AAAA00FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF005AAAAAAAAAAAA000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF0001AAAAAAAAA5000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00017AAA930000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000FFFFFFFFFF
}

!define OFF_FOLDER_SHARED(_alias) ENTITY(rectangle,black,folder_shared,_alias,OFF FOLDER_SHARED)
!define OFF_FOLDER_SHARED(_alias,_label) ENTITY(rectangle,black,folder_shared,_label,_alias,OFF FOLDER_SHARED)
!define OFF_FOLDER_SHARED(_alias,_label,_shape) ENTITY(_shape,black,folder_shared,_label,_alias,OFF FOLDER_SHARED)
!define OFF_FOLDER_SHARED(_alias,_label,_shape,_color) ENTITY(_shape,_color,folder_shared,_label,_alias,OFF FOLDER_SHARED)
skinparam folderBackgroundColor<<OFF FOLDER_SHARED>> White