sprite $folders [48x45/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF00000000000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF0001111111000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF0019AAAAAAAA500FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF001AAAAAAAAAAA00FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF001AAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFF000000000000000000000000000000000FFFFFFFFF
FFFFF00022222222222222222210012222222000FFFFFFFF
FFFF003AAAAAAAAAAAAAAAAAA900AAAAAAAAAA00FFFFFFFF
FFFF007AAAAAAAAAAAAAAAAA9019AAAAAAAAAA10FFFFFFFF
FFFF007AAAAAAAAAAAAAAAA8019AAAAAAAAAAA100FFFFFFF
FFFF007AAA7100000000000000000000000000000000FFFF
FFFF007AA90277777777777777777760067777777400FFFF
FFFF007AA10AAAAAAAAAAAAAAAAAAA009AAAAAAAAA500FFF
FFFF007AA02AAAAAAAAAAAAAAAAAA00AAAAAAAAAAA700FFF
FFFF007AA02AAAAAAAAAAAAAAAA900AAAAAAAAAAAA600FFF
FFFF007AA02AAA7000000000000000000000000000000FFF
FFFF007AA02AA902AAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFF007AA02AA60AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFF007AA02AA60AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFF007AA02AA60AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFF007AA02AA60AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFF007AA02AA60AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFF007AA02AA60AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFF007AA02AA60AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFF007AA02AA60AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFF007AA02AA60AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFF0000002AA60AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFF0000002AA60AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFFFFFFF02AA60AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFFFFFFF02AA60AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFFFFFFF02AA60AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFFFFFFF000000AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFFFFFFF000000AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAA700FFF
FFFFFFFFFFFFF00777777777777777777777777777500FFF
FFFFFFFFFFFFF00000000000000000000000000000000FFF
FFFFFFFFFFFFF00000000000000000000000000000000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_FOLDERS(_alias) ENTITY(rectangle,black,folders,_alias,OFF FOLDERS)
!define OFF_FOLDERS(_alias,_label) ENTITY(rectangle,black,folders,_label,_alias,OFF FOLDERS)
!define OFF_FOLDERS(_alias,_label,_shape) ENTITY(_shape,black,folders,_label,_alias,OFF FOLDERS)
!define OFF_FOLDERS(_alias,_label,_shape,_color) ENTITY(_shape,_color,folders,_label,_alias,OFF FOLDERS)
skinparam folderBackgroundColor<<OFF FOLDERS>> White