sprite $get_started [41x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF0FFFFFFF00FFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0000FFFFF00000FFFFFFFFFFFF
FFFFFFFFFFFFF0000000FFFF0040000FFFFFFFFFF
FFFFFFFFFFFFF0039800FFF004BA300FFFFFFFFFF
FFFFFFFFFFFFF008BA200FF009BB20FFFFFFFFFFF
FFFFFFFFFFFFF003BB800F002BBA00FFFFFFFFFFF
FFFFFFFFFFFFFF00ABB300008BB600FFFFFFFFFFF
FFFFFFFFFFFFFF007BB90001ABB300FFFFF00FFFF
FFFFFFF000FFFF003BBB4006BBB00FFF00000FFFF
FFFFFFF000000FF00ABB900ABB80000000400FFFF
FFFFFFF00610000005BBB45BBB4000017AB300FFF
FFFFFF003BA9620002B941126A10059ABBBA00FFF
FFFFFF009BBBBBA7305000000237ABBBBB71000FF
FFFFFF0005ABBBBBB7000100003BBBBB820000FFF
FFFFFF0000049BBBA10009100008BB930000FFFFF
FFFFFFFFF000039B80000A910004A40000FFFFFFF
FFFFFFFFFFF0000250000AB910010000FFFFFFFFF
FFFFFFFFFFFF000140000ABB910000FFFFFFFFFFF
FFFFFFFFFF00006A90000ABBB9100FFFFFFFFFFFF
FFFFFFFF00004ABBB3000ABBBB9000FFFFFFFFFFF
FFFFFF000039BBBBB9000ABBBBB9000FFFFFFFFFF
FFFFFF0028BBBBB951000ABBBBBB8000FFFFFFFFF
FFFFFF002BBBA73000000ABBBBBBB8000FFFFFFFF
FFFFFFF00A9500000FF00ABBBBBBBB8000FFFFFFF
FFFFFFF00000000FFFF00ABBBBBBBBB8000FFFFFF
FFFFFFFF0000FFFFFFF00ABBBBBBBBBB7000FFFFF
FFFFFFFF0FFFFFFFFFF00ABBBBBBBBBBB7000FFFF
FFFFFFFFFFFFFFFFFFF00ABBBBBBAAAAAA6000FFF
FFFFFFFFFFFFFFFFFFF00ABBBABBA0000000000FF
FFFFFFFFFFFFFFFFFFF00ABB93ABB3000000000FF
FFFFFFFFFFFFFFFFFFF00AB9008BB800FFFFFFFFF
FFFFFFFFFFFFFFFFFFF00A90003BBB200FFFFFFFF
FFFFFFFFFFFFFFFFFFF009000009BB700FFFFFFFF
FFFFFFFFFFFFFFFFFFF00000F005BBB100FFFFFFF
FFFFFFFFFFFFFFFFFFF0000FFF00ABB500FFFFFFF
FFFFFFFFFFFFFFFFFFF000FFFF007BBA00FFFFFFF
FFFFFFFFFFFFFFFFFFF00FFFFFF01AA6000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF0030000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_GET_STARTED(_alias) ENTITY(rectangle,black,get_started,_alias,OFF GET_STARTED)
!define OFF_GET_STARTED(_alias,_label) ENTITY(rectangle,black,get_started,_label,_alias,OFF GET_STARTED)
!define OFF_GET_STARTED(_alias,_label,_shape) ENTITY(_shape,black,get_started,_label,_alias,OFF GET_STARTED)
!define OFF_GET_STARTED(_alias,_label,_shape,_color) ENTITY(_shape,_color,get_started,_label,_alias,OFF GET_STARTED)
skinparam folderBackgroundColor<<OFF GET_STARTED>> White