sprite $globe_internet [48x47/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF00000000000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0000000430610000000FFFFFFFFFFFFFF
FFFFFFFFFFFFF000066019A40AA50282000FFFFFFFFFFFFF
FFFFFFFFFFFF0006AA01AAA40AAA604A81000FFFFFFFFFFF
FFFFFFFFFFF0019AA109AAA40AAAA408AA5000FFFFFFFFFF
FFFFFFFFFF0008AA707AAAA40AAAAA01AAA3000FFFFFFFFF
FFFFFFFFF001004900AAAAA40AAAAA7087202000FFFFFFFF
FFFFFFFF00099300049AAAA40AAAAA800016A400FFFFFFFF
FFFFFFFF007AAA90000034520654200006AAAA200FFFFFFF
FFFFFFF003AAAAA0184210000000135806AAAA800FFFFFFF
FFFFFFF008AAAA907AAAAAA409AAAAAA01AAAAA300FFFFFF
FFFFFF003AAAAA60AAAAAAA40AAAAAAA10AAAAA800FFFFFF
FFFFFF006AAAAA30AAAAAAA40AAAAAAA60AAAAAA10FFFFFF
FFFFFF0019AAAA00AAAAAAA40AAAAAAA909AAAA4000FFFFF
FFFFFF011039AA02AAAAAAA40AAAAAAAA08AA700100FFFFF
FFFFFF04A4002803AAAAAAA40AAAAAAAA0550008900FFFFF
FFFFFF05AAA500017AAAAAA40AAAAAA9500017AAA00FFFFF
FFFFFF06AAAAA9000000034204320000002AAAAAA00FFFFF
FFFFFF05AAAAAA05A74100000000036AA05AAAAAA00FFFFF
FFFFFF04AAAAAA04AAAAAAA40AAAAAAAA05AAAAAA00FFFFF
FFFFFF02AAAAAA03AAAAAAA40AAAAAAAA07AAAAA800FFFFF
FFFFFF008AAAAA01AAAAAAA40AAAAAAAA08AAAAA100FFFFF
FFFFFF0003AAAA20AAAAAAA40AAAAAAA809AAA5000FFFFFF
FFFFFF000003AA50AAAAAAA40AAAAAAA40AA610200FFFFFF
FFFFFFF018200250AAAAAAA40AAAAAAA0041017500FFFFFF
FFFFFFF006A83000269AAAA40AAAA96300027AA100FFFFFF
FFFFFFF001AAA9700000122102210000069AAA400FFFFFFF
FFFFFFFF003AAAA608753210012456810AAAA8000FFFFFFF
FFFFFFFFF006AAAA03AAAAA40AAAAA904AAAA100FFFFFFFF
FFFFFFFFF0006AAA309AAAA40AAAAA30AAAA100FFFFFFFFF
FFFFFFFFFF0006AAA02AAAA40AAAA804AA9100FFFFFFFFFF
FFFFFFFFFFF0003AA606AAA40AAAA01AA7000FFFFFFFFFFF
FFFFFFFFFFFF00006A206AA40AA910983000FFFFFFFFFFFF
FFFFFFFFFFFFFF00004003940A700320000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00000000000000000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF000000000000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_GLOBE_INTERNET(_alias) ENTITY(rectangle,black,globe_internet,_alias,OFF GLOBE_INTERNET)
!define OFF_GLOBE_INTERNET(_alias,_label) ENTITY(rectangle,black,globe_internet,_label,_alias,OFF GLOBE_INTERNET)
!define OFF_GLOBE_INTERNET(_alias,_label,_shape) ENTITY(_shape,black,globe_internet,_label,_alias,OFF GLOBE_INTERNET)
!define OFF_GLOBE_INTERNET(_alias,_label,_shape,_color) ENTITY(_shape,_color,globe_internet,_label,_alias,OFF GLOBE_INTERNET)
skinparam folderBackgroundColor<<OFF GLOBE_INTERNET>> White