sprite $help [48x47/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF0000000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF000000000000000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0000158999997510000FFFFFFFFFFFFFF
FFFFFFFFFFFFF000059AAAAAAAAAAA840000FFFFFFFFFFFF
FFFFFFFFFFFF0004AAAAAAAAAAAAAAAA93000FFFFFFFFFFF
FFFFFFFFFFF0007AAAAAAAAAAAAAAAAAAA6000FFFFFFFFFF
FFFFFFFFFF0019AAAAAAAAAAAAAAAAAAAAA8000FFFFFFFFF
FFFFFFFFF0019AAAAAAAAAAAAAAAAAAAAAAA8000FFFFFFFF
FFFFFFFF0008AAAAAAAAA864458AAAAAAAAAA600FFFFFFFF
FFFFFFFF005AAAAAAAA8100000019AAAAAAAAA300FFFFFFF
FFFFFFF001AAAAAAAAA3000000000AAAAAAAAAA00FFFFFFF
FFFFFFF007AAAAAAAAA3049A830004AAAAAAAAA500FFFFFF
FFFFFFF01AAAAAAAAAA49AAAAA4001AAAAAAAAAA00FFFFFF
FFFFFF005AAAAAAAAAAAAAAAAA7002AAAAAAAAAA300FFFFF
FFFFFF008AAAAAAAAAAAAAAAAA5005AAAAAAAAAA600FFFFF
FFFFFF00AAAAAAAAAAAAAAAAA9000AAAAAAAAAAA900FFFFF
FFFFFF02AAAAAAAAAAAAAAAA90006AAAAAAAAAAAA00FFFFF
FFFFFF03AAAAAAAAAAAAAAA90005AAAAAAAAAAAAA10FFFFF
FFFFFF03AAAAAAAAAAAAAAA0007AAAAAAAAAAAAAA10FFFFF
FFFFFF03AAAAAAAAAAAAAA3006AAAAAAAAAAAAAAA10FFFFF
FFFFFF02AAAAAAAAAAAAAA001AAAAAAAAAAAAAAAA00FFFFF
FFFFFF01AAAAAAAAAAAAAA002AAAAAAAAAAAAAAAA00FFFFF
FFFFFF009AAAAAAAAAAAAA100AAAAAAAAAAAAAAA800FFFFF
FFFFFF007AAAAAAAAAAAAAA99AAAAAAAAAAAAAAA500FFFFF
FFFFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FFFFFF
FFFFFFF009AAAAAAAAAAAA824AAAAAAAAAAAAAA800FFFFFF
FFFFFFF004AAAAAAAAAAAA0003AAAAAAAAAAAAA200FFFFFF
FFFFFFFF009AAAAAAAAAAA0002AAAAAAAAAAAA700FFFFFFF
FFFFFFFF002AAAAAAAAAAA5018AAAAAAAAAAAA100FFFFFFF
FFFFFFFFF004AAAAAAAAAAAAAAAAAAAAAAAAA200FFFFFFFF
FFFFFFFFFF005AAAAAAAAAAAAAAAAAAAAAAA300FFFFFFFFF
FFFFFFFFFF0004AAAAAAAAAAAAAAAAAAAAA200FFFFFFFFFF
FFFFFFFFFFF00019AAAAAAAAAAAAAAAAA81000FFFFFFFFFF
FFFFFFFFFFFFF00059AAAAAAAAAAAAA94000FFFFFFFFFFFF
FFFFFFFFFFFFFF0000389AAAAAAA9730000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00000134543000000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF00000000000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_HELP(_alias) ENTITY(rectangle,black,help,_alias,OFF HELP)
!define OFF_HELP(_alias,_label) ENTITY(rectangle,black,help,_label,_alias,OFF HELP)
!define OFF_HELP(_alias,_label,_shape) ENTITY(_shape,black,help,_label,_alias,OFF HELP)
!define OFF_HELP(_alias,_label,_shape,_color) ENTITY(_shape,_color,help,_label,_alias,OFF HELP)
skinparam folderBackgroundColor<<OFF HELP>> White