sprite $home [48x46/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF0001000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF001AA9000FF0000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFF002AAAA9000F00000000FFFFFFFFF
FFFFFFFFFFFFFFFFFF002AAAAAAA00004AAAA60FFFFFFFFF
FFFFFFFFFFFFFFFFF003AAAAAAAAA0005AAAA60FFFFFFFFF
FFFFFFFFFFFFFFFF003AAAAAAAAAAA105AAAA60FFFFFFFFF
FFFFFFFFFFFFFFF004AAAAAAAAAAAAA15AAAA60FFFFFFFFF
FFFFFFFFFFFFFF004AAAAAAAAAAAAAAA7AAAA60FFFFFFFFF
FFFFFFFFFFFFF004AAAAAAAAAAAAAAAAAAAAA60FFFFFFFFF
FFFFFFFFFFFF005AAAAAAAAAAAAAAAAAAAAAA60FFFFFFFFF
FFFFFFFFFFF006AAAAAAAAAAAAAAAAAAAAAAA60FFFFFFFFF
FFFFFFFFFF006AAAAAAAAAAAAAAAAAAAAAAAA60FFFFFFFFF
FFFFFFFFF007AAAAAAAAAAAAAAAAAAAAAAAAA600FFFFFFFF
FFFFFFFF007AAAAAAAAAAAAAAAAAAAAAAAAAAA300FFFFFFF
FFFFFFF008AAAAAAAAAAAAAAAAAAAAAAAAAAAAA300FFFFFF
FFFFFF008AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA400FFFFF
FFFFFF03AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFFF00009AAAAAAAAAAAAAAAAAAAAAAAAAAA7000FFFFFF
FFFFFFFF009AAAAAAAAAAAAAAAAAAAAAAAAAAA70FFFFFFFF
FFFFFFFF009AAAAAAAAAAAAAAAAAAAAAAAAAAA70FFFFFFFF
FFFFFFFF009AAAAAAAAAAAAAAAAAAAAAAAAAAA70FFFFFFFF
FFFFFFFF009AAAAAAAAA80000001AAAAAAAAAA70FFFFFFFF
FFFFFFFF009AAAAAAAAA80000001AAAAAAAAAA70FFFFFFFF
FFFFFFFF009AAAAAAAAA80000001AAAAAAAAAA70FFFFFFFF
FFFFFFFF009AAAAAAAAA80000001AAAAAAAAAA70FFFFFFFF
FFFFFFFF009AAAAAAAAA80000001AAAAAAAAAA70FFFFFFFF
FFFFFFFF009AAAAAAAAA80000001AAAAAAAAAA70FFFFFFFF
FFFFFFFF009AAAAAAAAA80000001AAAAAAAAAA70FFFFFFFF
FFFFFFFF009AAAAAAAAA80000001AAAAAAAAAA70FFFFFFFF
FFFFFFFF009AAAAAAAAA80000001AAAAAAAAAA70FFFFFFFF
FFFFFFFF009AAAAAAAAA80000001AAAAAAAAAA70FFFFFFFF
FFFFFFFF009AAAAAAAAA80000001AAAAAAAAAA70FFFFFFFF
FFFFFFFF009AAAAAAAAA80000001AAAAAAAAAA70FFFFFFFF
FFFFFFFF00000000000000000000000000000000FFFFFFFF
FFFFFFFF00000000000000000000000000000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_HOME(_alias) ENTITY(rectangle,black,home,_alias,OFF HOME)
!define OFF_HOME(_alias,_label) ENTITY(rectangle,black,home,_label,_alias,OFF HOME)
!define OFF_HOME(_alias,_label,_shape) ENTITY(_shape,black,home,_label,_alias,OFF HOME)
!define OFF_HOME(_alias,_label,_shape,_color) ENTITY(_shape,_color,home,_label,_alias,OFF HOME)
skinparam folderBackgroundColor<<OFF HOME>> White