sprite $input_output_filter [46x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF00000000000000000000000000000000000FFFFF
FFFFFF00000000000000000000000000000000000FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAA999AAAAAAA999AAAAAAA99AAAAA00FFFFF
FFFFFF07AAAA000AAAAAAA000AAAAAA3005AAAA00FFFFF
FFFFFF07AAAA000AAAAAAA000AAAAAA3005AAAA00FFFFF
FFFFFF07AAAA000AAAAAAA000AAAAAA4006AAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAA999AAAAAAA999AAAAAA999AAAAA00FFFFF
FFFFFF07AAAA000AAAAAAA000AAAAAA3005AAAA00FFFFF
FFFFFF07AAAA000AAAAAAA000AAAAAA3005AAAA00FFFFF
FFFFFF07AAAA000AAAAAAA000AAAAAA3005AAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAA777AAAAAAA777AAAAAA8779AAAA00FFFFF
FFFFFF07AAAA000AAAAAAA000AAAAAA3005AAAA00FFFFF
FFFFFF07AAAA000AAAAAAA000AAAAAA3005AAAA00FFFFF
FFFFFF07AAAA000AAAAAAA000AAAAAA4006AAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF07AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF03444444444444444444444444444444400FFFFF
FFFFFF00000000000000000000000000000000000FFFFF
FFFFFF00000000000000000000000000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_INPUT_OUTPUT_FILTER(_alias) ENTITY(rectangle,black,input_output_filter,_alias,OFF INPUT_OUTPUT_FILTER)
!define OFF_INPUT_OUTPUT_FILTER(_alias,_label) ENTITY(rectangle,black,input_output_filter,_label,_alias,OFF INPUT_OUTPUT_FILTER)
!define OFF_INPUT_OUTPUT_FILTER(_alias,_label,_shape) ENTITY(_shape,black,input_output_filter,_label,_alias,OFF INPUT_OUTPUT_FILTER)
!define OFF_INPUT_OUTPUT_FILTER(_alias,_label,_shape,_color) ENTITY(_shape,_color,input_output_filter,_label,_alias,OFF INPUT_OUTPUT_FILTER)
skinparam folderBackgroundColor<<OFF INPUT_OUTPUT_FILTER>> White