sprite $install [42x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF0000000000000000000FFFFFF
FFFFFFFFFFFFFFFF00466666666666666500FFFFFF
FFFFFFFFFFFFFFF006AAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF00AAA911111111112AAA00FFFFF
FFFFFFFFFFFFFFF00AAA944444444445AAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFF0000000F0000002AAAAAAAAAAAAAAAAA00FFFFF
FFF0022200F00222201AAAAAAAAAAAAAAAA00FFFFF
FFF00AAA100001AAA801AAAAAAAAAAAAAAA00FFFFF
FFFF07AA9000001AAA702AAAAAAAAAAAAAA00FFFFF
FFFF00AAA6000002AAA702AAAAAAAAAAAAA00FFFFF
FFFF006AAA8322225AAA702AAAAAAAAAAAA00FFFFF
FFFFF008AAAAAAAAAAAAA702AAAAAAAAAAA00FFFFF
FFFFFF006AAAAAAAAAAAAA008AAAAAAAAAA00FFFFF
FFFFFFF0016899999AAAA206AAAAAAAAAAA00FFFFF
FFFFFFFF000000006AAA204999999999AAA00FFFFF
FFFFFFFFFF000005AAA2000000000001AAA00FFFFF
FFFFFFFFFFFF004AAA30566666666667AAA00FFFFF
FFFFFFFFFFF003999305AAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFF00000005AAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFF0000006AA944444444445AAA00FFFFF
FFFFFFFFFFFFFFF00AAA900000000002AAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFFFFFFFFFF0000000000000000000000FFFFF
FFFFFFFFFFFFFFF0000000000000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_INSTALL(_alias) ENTITY(rectangle,black,install,_alias,OFF INSTALL)
!define OFF_INSTALL(_alias,_label) ENTITY(rectangle,black,install,_label,_alias,OFF INSTALL)
!define OFF_INSTALL(_alias,_label,_shape) ENTITY(_shape,black,install,_label,_alias,OFF INSTALL)
!define OFF_INSTALL(_alias,_label,_shape,_color) ENTITY(_shape,_color,install,_label,_alias,OFF INSTALL)
skinparam folderBackgroundColor<<OFF INSTALL>> White