sprite $integration [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF000000000000000000000000000000000000FFFFFF
FFFFFF000000000000000000000000000000000000FFFFFF
FFFFFF006999999999999999999911999999999930FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA21AAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA21AAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA21AAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA21AAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA21AAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA21AAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA21AAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA21AAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAA944444444401AAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAA900000000001AAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAA904999999999AAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAA904AAAAAAAAAAAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAA904AAAAAAAAAAAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAA904AAAAAAAAAAAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAA904AAAAAAAAAAAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAA904AAAAAAAAAAAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAA904AAAAAAAAAAAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAA904AAAAAAAAAAAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAA904AAAAAAAAAAAAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAA9024444444448AAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAA9000000000005AAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAA999999999705AAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA805AAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA805AAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA805AAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA805AAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA805AAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA805AAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA805AAAAAAAAA40FFFFFF
FFFFFF006AAAAAAAAAAAAAAAAAAA805AAAAAAAAA40FFFFFF
FFFFFF003555555555555555555540255555555520FFFFFF
FFFFFF000000000000000000000000000000000000FFFFFF
FFFFFF000000000000000000000000000000000000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_INTEGRATION(_alias) ENTITY(rectangle,black,integration,_alias,OFF INTEGRATION)
!define OFF_INTEGRATION(_alias,_label) ENTITY(rectangle,black,integration,_label,_alias,OFF INTEGRATION)
!define OFF_INTEGRATION(_alias,_label,_shape) ENTITY(_shape,black,integration,_label,_alias,OFF INTEGRATION)
!define OFF_INTEGRATION(_alias,_label,_shape,_color) ENTITY(_shape,_color,integration,_label,_alias,OFF INTEGRATION)
skinparam folderBackgroundColor<<OFF INTEGRATION>> White