sprite $lab [46x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00000000000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF0000000000000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF00233333333000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF004AAAAAAAAA800FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF01AAAAAAAAA500FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF002AAAAAAA6000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00AAAAAAA200FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF009AAAAAA10FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF009AAAAAA10FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF009AAAAAA10FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF009AAAAAA10FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF009AAAAAA10FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF009AAAAAA10FF0000000000000FFFFFF
FFFFFFFFFFFFFF009AAAAAA10FF0022222222100FFFFFF
FFFFFFFFFFFFF000AAAAAAA300001AAAAAAAAA00FFFFFF
FFFFFFFFFFFFF005AAAAAAA8000005AAAAAAA400FFFFFF
FFFFFFFFFFFF001AAAAAAAAA500001AAAAAAA000FFFFFF
FFFFFFFFFFFF008AAAAAAAAAA00001AAAAAAA00FFFFFFF
FFFFFFFFFFF004AAAAAAAAAAA80001AAAAAAA00FFFFFFF
FFFFFFFFFFF00AAAAAAAAAAAAA3001AAAA77700FFFFFFF
FFFFFFFFFF007AAAAAAAAAAAAAA001AAAA22200FFFFFFF
FFFFFFFFF002AAAAAAAAAAAAAAA701AAAAAAA00FFFFFFF
FFFFFFFF0009922222222222226A11AAAAAAA00FFFFFFF
FFFFFFFF006A300000000000000AA2AAAAAAA00FFFFFFF
FFFFFFF000A70000000000000003A6AAAAAA900FFFFFFF
FFFFFF0009A100000000000000009AAAAA00000FFFFFFF
FFFFFF003A3000000000000000000AAAAAAAA00FFFFFFF
FFFFF001AA00000000000000000006AAAAAAA00FFFFFFF
FFFFF007A100000000000000000001AAAAAAA00FFFFFFF
FFFF003A6000000000000000000001AAAAAAA00FFFFFFF
FFFF00990000000000000000000001AAAA33300FFFFFFF
FFFF00A81111111111111111111113AAAA66600FFFFFFF
FFFF007AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFF00046666666666666666666667AAAAAAA00FFFFFFF
FFFFF0000000000000000000000000AAAAAAA00FFFFFFF
FFFFFF0000000000000000000000009AAAAA900FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF002AAAAA000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF002686100FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_LAB(_alias) ENTITY(rectangle,black,lab,_alias,OFF LAB)
!define OFF_LAB(_alias,_label) ENTITY(rectangle,black,lab,_label,_alias,OFF LAB)
!define OFF_LAB(_alias,_label,_shape) ENTITY(_shape,black,lab,_label,_alias,OFF LAB)
!define OFF_LAB(_alias,_label,_shape,_color) ENTITY(_shape,_color,lab,_label,_alias,OFF LAB)
skinparam folderBackgroundColor<<OFF LAB>> White