sprite $learn [44x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF000000000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF00012321000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF0007BBBBB9100FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF0019BBBBBBBB300FFFFFFFFFFFFFFFFFF
FFFFFFFFFFF009BBBBBBBBBA200FFFFFFFFFFFFFFFFF
FFFFFFFFFF006BBBBBBBBBBBA00FFFFFFFFFFFFFFFFF
FFFFFFFFFF00ABBBBBBBBBBBB30FFFFFFFFFFFFFFFFF
FFFFFFFFFF03BBBBBBBBBBBBB800FFFFFFFFFFFFFFFF
FFFFFFFFF006BBBBBBBBBBBBBA00FFFFFFFFFFFFFFFF
FFFFFFFFF007BBBBBBBBBBBBBA00FFFFFFFFFFFFFFFF
FFFFFFFFF006BBBBBBBBBBBBBA00FFFFFFFFFFFFFFFF
FFFFFFFFF005BBBBBBBBBBBBB900FFFFFFFFFFFFFFFF
FFFFFFFFFF02BBBBBBBBBBBBB700FFFFFFFFFFFFFFFF
FFFFFFFFFF008BBBBBBBBBBBA00FFFFFFFFFFFFFFFFF
FFFFFFFFFF002BBBBBBBBBBB700FFFFFFFFFFFFFFFFF
FFFFFFFFFFF005BBBBBBBBBA00FFFFFFFFFFFFFFFFFF
FFFFFFFFFFF0004BBBBBBB8000FFFFFFFFFFFFFFFFFF
FFFFFFFFF00000006ABB81000000FFFFFFFFFFFFFFFF
FFFFFFF00004100000000000031000FFFFFFFFFFFFFF
FFFFF00006ABA300000000009BB90000FFFFFFFFFFFF
FFFF0003BBBBBB910000006BBBBBB7000FFFFFFFFFFF
FFFF005BBBBBBBBBBBAABBBBBBBBBB900FFFFFFFFFFF
FFF001BBBBBBBBBBBBBBBB810000018500000000FFFF
FFF006BBBBBBBBBBBBBBB70111111000111111000FFF
FFF00ABBBBBBBBBBBBBBA00A99999A45A99999A100FF
FFF01BBBBBBBBBBBBBBB4047000000A90000008300FF
FF001BBBBBBBBBBBBBBB01B7000000650000008B10FF
FF004BBBBBBBBBBBBBBB02B7022220540222208B10FF
FF006BBBBBBBBBBBBBBB02B7077770540777608B10FF
FF009BBBBBBBBBBBBBBB02B7000000540000008B10FF
FF00ABBBBBBBBBBBBBBB02B70AAA90541AAA808B10FF
FF00BBBBBBBBBBBBBBBB02B7000000540000008B10FF
FF00BBBBBBBBBBBBBBBB02B7044440540444408B10FF
F000BBBBBBBBBBBBBBBB02B7055550540555408B10FF
F000555555555555555502B7000000540000008B10FF
F000000000000000000002B7000000540000008B10FF
FF00000000000000000002B966666455466666AB10FF
FFFFFFFFFFFFFFFFFFFF02BBBBBBBBAABBBBBBBB10FF
FFFFFFFFFFFFFFFFFFFF0034444447BB6444444300FF
FFFFFFFFFFFFFFFFFFFF0000000000000000000000FF
FFFFFFFFFFFFFFFFFFFFFF000000000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_LEARN(_alias) ENTITY(rectangle,black,learn,_alias,OFF LEARN)
!define OFF_LEARN(_alias,_label) ENTITY(rectangle,black,learn,_label,_alias,OFF LEARN)
!define OFF_LEARN(_alias,_label,_shape) ENTITY(_shape,black,learn,_label,_alias,OFF LEARN)
!define OFF_LEARN(_alias,_label,_shape,_color) ENTITY(_shape,_color,learn,_label,_alias,OFF LEARN)
skinparam folderBackgroundColor<<OFF LEARN>> White