sprite $link [48x24/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF000000000FFFFFFFFFF0000000000FFFFFFFFF
FFFFFFFF00011222210000FFFFF00012222210000FFFFFFF
FFFFFFF0039AAAAAAAA6000FFF0029AAAAAAAA8100FFFFFF
FFFFFF006AAAAAAAAAAAA10FF004AAAAAAAAAAAA200FFFFF
FFFFF004AAA50000008AAA00F01AAA40000007AAA00FFFFF
FFFFF00AAA10000000012200001110000000004AA700FFFF
FFFFF02AA500F0024444444444444444410FF009AA00FFFF
FFFFF03AA00FF01AAAAAAAAAAAAAAAAAAA00FF05AA00FFFF
FFFFF03AA00FF01AAAAAAAAAAAAAAAAAAA00FF06AA00FFFF
FFFFF02AA600F0001111111111111111100FF00AA900FFFF
FFFFF009AA20000000034400003552000000006AA500FFFF
FFFFF002AAA73222249AAA00F00AAA84333359AAA00FFFFF
FFFFFF004AAAAAAAAAAAA00FF001AAAAAAAAAAAA000FFFFF
FFFFFFF0018AAAAAAAA600FFFF0007AAAAAAA95000FFFFFF
FFFFFFFF00001111110000FFFFF00000000000000FFFFFFF
FFFFFFFFFF0000000000FFFFFFFFF0000000000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_LINK(_alias) ENTITY(rectangle,black,link,_alias,OFF LINK)
!define OFF_LINK(_alias,_label) ENTITY(rectangle,black,link,_label,_alias,OFF LINK)
!define OFF_LINK(_alias,_label,_shape) ENTITY(_shape,black,link,_label,_alias,OFF LINK)
!define OFF_LINK(_alias,_label,_shape,_color) ENTITY(_shape,_color,link,_label,_alias,OFF LINK)
skinparam folderBackgroundColor<<OFF LINK>> White