sprite $maintenance [38x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF000000FFFFFFFF00FFF000FFFFFFFFF
FFFFFFF000000FFFFFF0000FFF0000FFFFFFFF
FFFFFFF035510FFFFF00010FFF00000FFFFFFF
FFFFFFF06AA30FFFF000840FFF00A300FFFFFF
FFFFFFF06AA30FFFF009A40FFF00AA200FFFFF
FFFFFFF06AA30FFF005AA40FFF00AAA00FFFFF
FFFFFFF06AA30FFF00AAA40FFF00AAA400FFFF
FFFFFFF04AA10FFF01AAA40FFF00AAA800FFFF
FFFFFFF01AA00FFF04AAA4000000AAA900FFFF
FFFFFFF00AA00FFF04AAAA600019AAA900FFFF
FFFFFFF00AA00FFF03AAAAA916AAAAA900FFFF
FFFFFFF00AA00FFF00AAAAAAAAAAAAA600FFFF
FFFFFFF00AA00FFF009AAAAAAAAAAAA00FFFFF
FFFFFFF00AA00FFFF00AAAAAAAAAAA600FFFFF
FFFFFFF00AA00FFFF001AAAAAAAAA800FFFFFF
FFFFFFF00AA00FFFFF000AAAAAAA600FFFFFFF
FFFFFFF00AA00FFFFFF005AAAAAA00FFFFFFFF
FFFFFFF00AA00FFFFFFF05AAAAAA00FFFFFFFF
FFFFFFF00AA00FFFFFFF05AAAAAA00FFFFFFFF
FFFFFFF00AA00FFFFFFF05AAAAAA00FFFFFFFF
FFFFFFF00AA00FFFFFFF05AAAAAA00FFFFFFFF
FFFFFFF00AA00FFFFFFF05AAAAAA00FFFFFFFF
FFFFFF000AA000FFFFFF05AAAAAA00FFFFFFFF
FFFFF0002AA2000FFFFF05AAAAAA00FFFFFFFF
FFFFF009AAAA800FFFFF05AAAAAA00FFFFFFFF
FFFFF00AAAAA900FFFFF05AAAAAA00FFFFFFFF
FFFFF00AAAAA900FFFFF05AAAAAA00FFFFFFFF
FFFFF00AAAAA900FFFFF05AAAAAA00FFFFFFFF
FFFFF00AAAAA900FFFFF05AAAAAA00FFFFFFFF
FFFFF00AAAAA900FFFFF05AAAAAA00FFFFFFFF
FFFFF00AAAAA900FFFFF05AAAAAA00FFFFFFFF
FFFFF00AAAAA900FFFFF05AAAAAA00FFFFFFFF
FFFFF00AAAAA900FFFFF05AAAAAA00FFFFFFFF
FFFFF00AAAAA900FFFFF05AAAAAA00FFFFFFFF
FFFFF00AAAAA900FFFFF05A925AA00FFFFFFFF
FFFFF00AAAAA900FFFFF05A500AA00FFFFFFFF
FFFFF00AAAAA900FFFFF02A925AA00FFFFFFFF
FFFFF00AAAAA900FFFFF009AAAA20FFFFFFFFF
FFFFF0069999500FFFFF000587200FFFFFFFFF
FFFFF000000000FFFFFFF0000000FFFFFFFFFF
FFFFFF0000000FFFFFFFFFF0000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_MAINTENANCE(_alias) ENTITY(rectangle,black,maintenance,_alias,OFF MAINTENANCE)
!define OFF_MAINTENANCE(_alias,_label) ENTITY(rectangle,black,maintenance,_label,_alias,OFF MAINTENANCE)
!define OFF_MAINTENANCE(_alias,_label,_shape) ENTITY(_shape,black,maintenance,_label,_alias,OFF MAINTENANCE)
!define OFF_MAINTENANCE(_alias,_label,_shape,_color) ENTITY(_shape,_color,maintenance,_label,_alias,OFF MAINTENANCE)
skinparam folderBackgroundColor<<OFF MAINTENANCE>> White