sprite $marketplace_shopping_bag [40x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0000010000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0007AAAA7000FFFFFFFFFFFFFF
FFFFFFFFFFFFFF0088100169000FFFFFFFFFFFFF
FFFFFFFFFFFFF00390000007600FFFFFFFFFFFFF
FFFFFFFFFFFFF009200FF001B00FFFFFFFFFFFFF
FFFFFFFFFFFFF00A00FFFF00B00FFFFFFFFFFFFF
FFFFFFFFFFFFF00A00FFFF00B00FFFFFFFFFFFFF
FFFFFFFF0000000A00000000B0000000FFFFFFFF
FFFFFFF00000000A00000000B0000000FFFFFFFF
FFFFFFF00277777A77777777B7777740FFFFFFFF
FFFFFFF004BBBBBBBBBBBBBBBBBBBB70FFFFFFFF
FFFFFFF006BBBBBBBBBBBBBBBBBBBB800FFFFFFF
FFFFFFF008BBBBBBBBBBBBBBBBBBBB800FFFFFFF
FFFFFFF009BBBBBBBBBBBBBBBBBBBB900FFFFFFF
FFFFFFF009BBBBBBBBBBBBBBBBBBBBA00FFFFFFF
FFFFFFF00ABBBBBBBBBBBBBBBBBBBBA00FFFFFFF
FFFFFFF00ABBBBBBBBBBBBBBBBBBBBA000FFFFFF
FFFFFFF00ABBBBBBBBBBBBBBBBBBBBB100FFFFFF
FFFFFFF00ABBBBBBBBBBBBBBBBBBBBB300FFFFFF
FFFFFF000BBBBBBBBBBBBBBBBBBBBBB500FFFFFF
FFFFFF002BBBBBBBBBBBBBBBBBBBBBB700FFFFFF
FFFFFF004BBBBBBBBBBBBBBBBBBBBBB800FFFFFF
FFFFFF006BBBBBBBBBBBBBBBBBBBBBB900FFFFFF
FFFFFF008BBBBBBBBBBBBBBBBBBBBBB900FFFFFF
FFFFFF009BBBBBBBBBBBBBBBBBBBBBBA00FFFFFF
FFFFFF00BBBBBBBBBBBBBBBBBBBBBBBA00FFFFFF
FFFFFF00BBBBBBBBBBBBBBBBBBBBBBBA00FFFFFF
FFFFFF00BBBBBBBBBBBBBBBBBBBBBBBB000FFFFF
FFFFFF00BBBBBBBBBBBBBBBBBBBBBBBB200FFFFF
FFFFFF01BBBBBBBBBBBBBBBBBBBBBBBB400FFFFF
FFFFF001BBBBBBBBBBBBBBBBBBBBBBBB600FFFFF
FFFFF002BBBBBBBBBBBBBBBBBBBBBBBB800FFFFF
FFFFF004BBBBBBBBBBBBBBBBBBBBBBBBA00FFFFF
FFFFF004999999999999999999999999900FFFFF
FFFFF000000000000000000000000000000FFFFF
FFFFF000000000000000000000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_MARKETPLACE_SHOPPING_BAG(_alias) ENTITY(rectangle,black,marketplace_shopping_bag,_alias,OFF MARKETPLACE_SHOPPING_BAG)
!define OFF_MARKETPLACE_SHOPPING_BAG(_alias,_label) ENTITY(rectangle,black,marketplace_shopping_bag,_label,_alias,OFF MARKETPLACE_SHOPPING_BAG)
!define OFF_MARKETPLACE_SHOPPING_BAG(_alias,_label,_shape) ENTITY(_shape,black,marketplace_shopping_bag,_label,_alias,OFF MARKETPLACE_SHOPPING_BAG)
!define OFF_MARKETPLACE_SHOPPING_BAG(_alias,_label,_shape,_color) ENTITY(_shape,_color,marketplace_shopping_bag,_label,_alias,OFF MARKETPLACE_SHOPPING_BAG)
skinparam folderBackgroundColor<<OFF MARKETPLACE_SHOPPING_BAG>> White