sprite $meets_requirements [45x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF00000000000000000000000000FFFFFFFF
FFFFFFFFF000000000000000000000000000000FFFFFF
FFFFFFFF00058999999999999999999999820000FFFFF
FFFFFFFF008AAAAAAAAAAAAAAAAAAAAAA8003320FFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAAAAA119AA900FFFF
FFFFFFF00AAAAAAAAAAAAAAAAAAAAAAA806AAAA00FFFF
FFFFFFF00AAAAAAAAAAAAAAAAAAAAAAA809AAAA00FFFF
FFFFFFF01AAAAAAAAAAAAAAAAAAAAAAA809AAA80FFFFF
FFFFFFF01AAAAAAAAAAAAAAAAAAAAAAA809AAA00FFFFF
FFFFFFF01AAAAAAAAAAAAAAAAAAAAAAA809A8000FFFFF
FFFFFFF01AAAAAAAAAAAAAAAAAAAAAAA8000000FFFFFF
FFFFFFF01AAAAAAAAAAAAAAAAAAAAAAA8000FFFFFFFFF
FFFFFFF01AAAAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFF
FFFFFFF01AAAAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFF
FFFFFFF01AAAAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFF
FFFFFFF01AAAAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFF
FFFFFFF01AAAAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFF
FFFFFFF01AAAAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFF
FFFFFFF01AAAAAAAAAAAAAAAAAAA632110000FFFFFFFF
FFFFFFF01AAAAAAAAAAAAAAAAA600023320000FFFFFFF
FFFFFFF01AAAAAAAAAAAAAAA92027AAAAAA62000FFFFF
FFFFFFF01AAAAAAAAAAAAAA9106AAAAAAAAAA5000FFFF
FFFFFFF01AAAAAAAAAAAAAA207AAAAAAAAAAAA700FFFF
FFFFFFF01AAAAAAAAAAAAA506AAAAAAAAAAA8AA500FFF
FFFFFFF01AAAAAAAAAAAAA02AAAAAAAAAAA606AA00FFF
FFFFF0000999999999999608AAAAAAAAAA8003AA700FF
FFFF0000000000000000001AAAAAAAAAAA001AAAA00FF
FFF00057888888888888813AAAAAAAAAA200AAAAA00FF
FF002AAAAAAAAAAAAAAAA04AAA807AAA6007AAAAA10FF
FF00AAAAAAAAAAAAAAAAA05AAA2008A8004AAAAAA20FF
FF05AAAAAAAAAAAAAAAAA14AAAA1008002AAAAAAA00FF
FF07AAAAAAAAAAAAAAAAA22AAAA900001AAAAAAAA00FF
FF04AAAAAAAAAAAAAAAAA509AAAA80008AAAAAAA900FF
FF00AAAAAAAAAAAAAAAAA904AAAAA705AAAAAAAA20FFF
FF003AAAAAAAAAAAAAAAAA309AAAAA7AAAAAAAA800FFF
FFF0015666666666666666501AAAAAAAAAAAAA9000FFF
FFFF00000000000000000000029AAAAAAAAAA9000FFFF
FFFFFF0000000000000000000006AAAAAAAA5000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF00004788730000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_MEETS_REQUIREMENTS(_alias) ENTITY(rectangle,black,meets_requirements,_alias,OFF MEETS_REQUIREMENTS)
!define OFF_MEETS_REQUIREMENTS(_alias,_label) ENTITY(rectangle,black,meets_requirements,_label,_alias,OFF MEETS_REQUIREMENTS)
!define OFF_MEETS_REQUIREMENTS(_alias,_label,_shape) ENTITY(_shape,black,meets_requirements,_label,_alias,OFF MEETS_REQUIREMENTS)
!define OFF_MEETS_REQUIREMENTS(_alias,_label,_shape,_color) ENTITY(_shape,_color,meets_requirements,_label,_alias,OFF MEETS_REQUIREMENTS)
skinparam folderBackgroundColor<<OFF MEETS_REQUIREMENTS>> White