sprite $node_generic [43x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF0001881000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF00005AAAA50000FFFFFFFFFFFFFF
FFFFFFFFFFFFFF0003AAAAAAAA3000FFFFFFFFFFFFF
FFFFFFFFFFFF00028AAAAAAAAAA82000FFFFFFFFFFF
FFFFFFFFFF00006AAAAAAAAAAAAAA60000FFFFFFFFF
FFFFFFFF00004AAAAAAAAAAAAAAAAAA40000FFFFFFF
FFFFFFF00029AAAAAAAAAAAAAAAAAAAA92000FFFFFF
FFFFF00017AAAAAAAAAAAAAAAAAAAAAAAA71000FFFF
FFFFF00017AAAAAAAAAAAAAAAAAAAAAAAA71000FFFF
FFFFF0050029AAAAAAAAAAAAAAAAAAAA9200600FFFF
FFFFF009A4004AAAAAAAAAAAAAAAAAA4005A900FFFF
FFFFF009AA92006AAAAAAAAAAAAAA60039AA900FFFF
FFFFF009AAAA80019AAAAAAAAAA91008AAAA900FFFF
FFFFF009AAAAAA5003AAAAAAAA3007AAAAAA900FFFF
FFFFF009AAAAAAAA2005AAAA6004AAAAAAAA900FFFF
FFFFF009AAAAAAAAA9001891019AAAAAAAAA900FFFF
FFFFF009AAAAAAAAAAA600007AAAAAAAAAAA900FFFF
FFFFF009AAAAAAAAAAAAA12AAAAAAAAAAAAA900FFFF
FFFFF009AAAAAAAAAAAAA22AAAAAAAAAAAAA900FFFF
FFFFF009AAAAAAAAAAAAA22AAAAAAAAAAAAA900FFFF
FFFFF009AAAAAAAAAAAAA22AAAAAAAAAAAAA900FFFF
FFFFF009AAAAAAAAAAAAA22AAAAAAAAAAAAA900FFFF
FFFFF009AAAAAAAAAAAAA22AAAAAAAAAAAAA900FFFF
FFFFF009AAAAAAAAAAAAA22AAAAAAAAAAAAA900FFFF
FFFFF009AAAAAAAAAAAAA22AAAAAAAAAAAAA900FFFF
FFFFF008AAAAAAAAAAAAA22AAAAAAAAAAAAA800FFFF
FFFFF0006AAAAAAAAAAAA22AAAAAAAAAAAA6000FFFF
FFFFFF00018AAAAAAAAAA22AAAAAAAAAA82000FFFFF
FFFFFFFF0003AAAAAAAAA22AAAAAAAAA4000FFFFFFF
FFFFFFFFF00005AAAAAAA22AAAAAAA60000FFFFFFFF
FFFFFFFFFFF00017AAAAA22AAAAA71000FFFFFFFFFF
FFFFFFFFFFFFF00029AAA22AAA93000FFFFFFFFFFFF
FFFFFFFFFFFFFFF0004AA22AA4000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF000162271000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF000000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_NODE_GENERIC(_alias) ENTITY(rectangle,black,node_generic,_alias,OFF NODE_GENERIC)
!define OFF_NODE_GENERIC(_alias,_label) ENTITY(rectangle,black,node_generic,_label,_alias,OFF NODE_GENERIC)
!define OFF_NODE_GENERIC(_alias,_label,_shape) ENTITY(_shape,black,node_generic,_label,_alias,OFF NODE_GENERIC)
!define OFF_NODE_GENERIC(_alias,_label,_shape,_color) ENTITY(_shape,_color,node_generic,_label,_alias,OFF NODE_GENERIC)
skinparam folderBackgroundColor<<OFF NODE_GENERIC>> White