sprite $on_premises_directory [43x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF000000000000000FFFFFFFFFFFFFFFFFFFFFF
FFFFFF000000000000000FFFFFFFFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAA00000000FFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAA00000000FFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAA00003400FFFFFFFFFFFFFFFF
FFFFFF01AA209A803AA00007900FFFFFFFFFFFFFFFF
FFFFFF01AA209A803AA00007900FFFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAA000079000FFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAA000079000FFFFFFFFFFFFFFF
FFFFFF01AA64AA946AA000AAAA10FFFFFFFFFFFFFFF
FFFFFF01AA209A803AA000AAAA10FFFFFFFFFFFFFFF
FFFFFF01AA76AAA68AA000AAAA100FFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAA001AAAA200FFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAAA05AAAAAA90FFFFFFFFFFFFFF
FFFFFF01AA209A803AA05AAAAAA90FFFFFFFFFFFFFF
FFFFFF01AA209A803AA05AAAAAA9000FFFFFFFFFFFF
FFFFFF01AAAAAAAAAAA05AAAAAA9000FFFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFF01AA319A814AAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFF01AA209A803AAAA01AAAAAA00FFFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAA01AAAAAA00FFFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAA000FFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAA30000FFFFFFFFFF
FFFFFF01AA209A803AAAAAAAAAAA04A100FFFFFFFFF
FFFFFF01AA319A814AAAAAAAAAA20AA900FFFFFFFFF
FFFFFF01AAAAAAAAAAAAA99AAA906AAA200FFFFFFFF
FFFFFF01AAAAAAAAAAAAA01AAA20AAAA900FFFFFFFF
FFFFFF01AA209A803AAAA23AA807A869A400FFFFFFF
FFFFFF01AA209A803AAAAAAAA11AA000A900FFFFFFF
FFFFFF01AAAAAAAAAAAAAAAA708AA000AA500FFFFFF
FFFFFF01AAAAAAAAAAAAAAAA12AAA415AAA00FFFFFF
FFFFFF01AAAAAAAAAAAAAAA608AA73A19AA600FFFFF
FFFFFF01AAAAAAAAAAAAAAA13AAA0AA72AAA100FFFF
FFFFFF01AAAAAAAAAAAAAA509AA53AAA18AA600FFFF
FFFFFF01AAAAAAAAAAAAAA04AAA0AAAA82AAA100FFF
FFFFFF01AAAAAAAAAAAAA509A537AAAAA538A700FFF
FFFFFF01AAAAAAAAAAAA905A800075558001AA200FF
FFFFFF01AAAAAAAAAAAA40AA800086668001AA800FF
FFFFFF0000000000000005AAA639AAAAA638AAA200F
FFFFFF000000000000000AAAAAAAAAAAAAAAAAA900F
FFFFFFFFFFFFFFFFFFF00244444444444444444200F
FFFFFFFFFFFFFFFFFFF0000000000000000000000FF
FFFFFFFFFFFFFFFFFFFFF0000000000000000000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ON_PREMISES_DIRECTORY(_alias) ENTITY(rectangle,black,on_premises_directory,_alias,OFF ON_PREMISES_DIRECTORY)
!define OFF_ON_PREMISES_DIRECTORY(_alias,_label) ENTITY(rectangle,black,on_premises_directory,_label,_alias,OFF ON_PREMISES_DIRECTORY)
!define OFF_ON_PREMISES_DIRECTORY(_alias,_label,_shape) ENTITY(_shape,black,on_premises_directory,_label,_alias,OFF ON_PREMISES_DIRECTORY)
!define OFF_ON_PREMISES_DIRECTORY(_alias,_label,_shape,_color) ENTITY(_shape,_color,on_premises_directory,_label,_alias,OFF ON_PREMISES_DIRECTORY)
skinparam folderBackgroundColor<<OFF ON_PREMISES_DIRECTORY>> White