sprite $on_premises [36x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF000000000000000FFFFFFFFFFFFFFF
FFFFFF000000000000000FFFFFFFFFFFFFFF
FFFFFF018888888888700FFFFFFFFFFFFFFF
FFFFFF01AAAAAAAAAA90000000FFFFFFFFFF
FFFFFF01AAAAAAAAAA90000210FFFFFFFFFF
FFFFFF01AA32AA726A90000A80FFFFFFFFFF
FFFFFF01AA10AA605A90000A80FFFFFFFFFF
FFFFFF01AA98AAA89A90000A8000FFFFFFFF
FFFFFF01AAAAAAAAAA90000A8000FFFFFFFF
FFFFFF01AA77AA979A90019AA800FFFFFFFF
FFFFFF01AA10AA605A9002AAAA00FFFFFFFF
FFFFFF01AA44AA847A9002AAAA000FFFFFFF
FFFFFF01AAAAAAAAAA9002AAAA000FFFFFFF
FFFFFF01AAAAAAAAAA9079AAAA950FFFFFFF
FFFFFF01AA21AA716A908AAAAAA60FFFFFFF
FFFFFF01AA10AA605A908AAAAAA6000FFFFF
FFFFFF01AAAAAAAAAA908AAAAAA6000FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAA900FFFFF
FFFFFF01AA65AA958AAAAAAAAAAAA00FFFFF
FFFFFF01AA10AA605AAA902AAAAAA00FFFFF
FFFFFF01AA65AA858AAA902AAAAAA00FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF01AAAAAAAAAAAAAAAA957AA00FFFFF
FFFFFF01AA10AA605AAAAAAA804AA00FFFFF
FFFFFF01AA20AA705AAAAAAA957AA00FFFFF
FFFFFF01AAAAAAAAAAAAA9AAAAAAA00FFFFF
FFFFFF01AAAAAAAAAAAA902AAAAAA00FFFFF
FFFFFF01AA54AA847AAA913AAAAAA00FFFFF
FFFFFF01AA10AA605AAAAAAAAAAAA00FFFFF
FFFFFF01AA76AA968AAAAAAAAAAAA00FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF0011111111111111111111100FFFFF
FFFFFF0000000000000000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ON_PREMISES(_alias) ENTITY(rectangle,black,on_premises,_alias,OFF ON_PREMISES)
!define OFF_ON_PREMISES(_alias,_label) ENTITY(rectangle,black,on_premises,_label,_alias,OFF ON_PREMISES)
!define OFF_ON_PREMISES(_alias,_label,_shape) ENTITY(_shape,black,on_premises,_label,_alias,OFF ON_PREMISES)
!define OFF_ON_PREMISES(_alias,_label,_shape,_color) ENTITY(_shape,_color,on_premises,_label,_alias,OFF ON_PREMISES)
skinparam folderBackgroundColor<<OFF ON_PREMISES>> White