sprite $phishing [48x35/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFF0000000000000000000000000000000FFFFFFFFFFFF
FFFFF0000000000000000000000000000000FFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAA900FFFFFFFFFFFF
FFFFF0007AAAAAAAAAAAAAAAAAAAAAAA6000FFFFFFFFFFFF
FFFFF01403AAAAAAAAAAAAAAAAAAAAA10600FFFFFFFFFFFF
FFFFF01A8009AAAAAAAAAAAAAAAAA8009A00FFFFFFFFFFFF
FFFFF01AAA206AAAAAAAAAAAAAAA503AAA00FFFFFFFFFFFF
FFFFF01AAAA502AAAAAAAAAAAAA107AAAA00FFFFFFFFFFFF
FFFFF01AAAAAA009AAAAAAAAA800AAAAAA00FFFFFFFFFFFF
FFFFF01AAAAAAA205AAAAAAA304AAAAAA20000FFFFFFFFFF
FFFFF01AAAAAAAA601AAAA9108AAAAAA2099000FFFFFFFFF
FFFFF01AAAAAAAAAA0059402AAAAAA900AAA9000FFFFFFFF
FFFFF01AAAAAAAAAAA30006AAAAA8102AAAAAA20000FFFFF
FFFFF01AAAAAAAAAAAAAAAAAAAA0039AAAAAAAA93000FFFF
FFFFF01AAAAAAAAAAAAAAAAAAA21AAAAAAAAAAAAAA10FFFF
FFFFF01AAAAAAAAAAAAAAAAAAA02AAAAAAAAAAAAAA30FFFF
FFFFF01AAAAAAAAAAAAAAAAAAA21AAAA33AA16AAAA20FFFF
FFFFF01AAAAAAAAAAAAAAAAAAA51AAAA503008AAAA00FFFF
FFFFF01AAAAAAAAAAAAAAAAAAA90AAAAA6009AAAA900FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAA07AAAA0002AAAA700FFFF
FFFFF001111111111111111111102AAA009604AAA20FFFFF
FFFFF0000000000000000000000009AA99AA8AAA900FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF003AAAAAAAAAA20FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF008AAAAAAAA800FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAA900FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF000AAAAAA00FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF009AA9000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00055000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000FFFFFFFFFF
}

!define OFF_PHISHING(_alias) ENTITY(rectangle,black,phishing,_alias,OFF PHISHING)
!define OFF_PHISHING(_alias,_label) ENTITY(rectangle,black,phishing,_label,_alias,OFF PHISHING)
!define OFF_PHISHING(_alias,_label,_shape) ENTITY(_shape,black,phishing,_label,_alias,OFF PHISHING)
!define OFF_PHISHING(_alias,_label,_shape,_color) ENTITY(_shape,_color,phishing,_label,_alias,OFF PHISHING)
skinparam folderBackgroundColor<<OFF PHISHING>> White