sprite $pin [36x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF000000000000000000FFFFFFFFF
FFFFFFFFF000000000000000000FFFFFFFFF
FFFFFFFFF002AAAAAAAAAAAAA00FFFFFFFFF
FFFFFFFFFF00AAAAAAAAAAAAA00FFFFFFFFF
FFFFFFFFFF007AAAAAAAAAAA400FFFFFFFFF
FFFFFFFFFF0007AAAAAAAAA6000FFFFFFFFF
FFFFFFFFFFF0004AAAAAAA2000FFFFFFFFFF
FFFFFFFFFFFF001AAAAAAA00FFFFFFFFFFFF
FFFFFFFFFFFFF01AAAAAAA00FFFFFFFFFFFF
FFFFFFFFFFFFF01AAAAAAA00FFFFFFFFFFFF
FFFFFFFFFFFFF01AAAAAAA00FFFFFFFFFFFF
FFFFFFFFFFFFF01AAAAAAA00FFFFFFFFFFFF
FFFFFFFFFFFFF01AAAAAAA00FFFFFFFFFFFF
FFFFFFFFFFFFF01AAAAAAA00FFFFFFFFFFFF
FFFFFFFFFFF0001AAAAAAA0000FFFFFFFFFF
FFFFFFFFFF0004AAAAAAAA93000FFFFFFFFF
FFFFFFFFF0008AAAAAAAAAAA6000FFFFFFFF
FFFFFFFFF007AAAAAAAAAAAAA400FFFFFFFF
FFFFFFFF001AAAAAAAAAAAAAAA00FFFFFFFF
FFFFFFFF007AAAAAAAAAAAAAAA400FFFFFFF
FFFFFFFF00AAAAAAAAAAAAAAAA700FFFFFFF
FFFFFFFF003333334AAA333333300FFFFFFF
FFFFFFFF000000000AA9000000000FFFFFFF
FFFFFFFFFFFFFFF00AA800FFFFFFFFFFFFFF
FFFFFFFFFFFFFFF009A800FFFFFFFFFFFFFF
FFFFFFFFFFFFFFF009A700FFFFFFFFFFFFFF
FFFFFFFFFFFFFFF008A600FFFFFFFFFFFFFF
FFFFFFFFFFFFFFF007A50FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF006A40FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF05A30FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF03A10FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF01A00FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00800FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00200FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_PIN(_alias) ENTITY(rectangle,black,pin,_alias,OFF PIN)
!define OFF_PIN(_alias,_label) ENTITY(rectangle,black,pin,_label,_alias,OFF PIN)
!define OFF_PIN(_alias,_label,_shape) ENTITY(_shape,black,pin,_label,_alias,OFF PIN)
!define OFF_PIN(_alias,_label,_shape,_color) ENTITY(_shape,_color,pin,_label,_alias,OFF PIN)
skinparam folderBackgroundColor<<OFF PIN>> White