sprite $script [40x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF000000000000000000000000000FFF
FFFFFFFFF00000000000000000000000000000FF
FFFFFFFF005AAAAAAAAAAAAAAAAAAAAAAA10000F
FFFFFFF006AAAAAAAAAAAAAAAAAAAAAAA0079900
FFFFFFF00AAAAAAAAAAAAAAAAAAAAAAA20AAAA00
FFFFFFF04AAAAAAAAAAAAAAAAAAAAAAA01AAAA10
FFFFFFF06AAAAAAAAAAAAAAAAAAAAAAA03AAAA00
FFFFFFF06AAAAAAAAAAAAAAAAAAAAAAA03AAA900
FFFFFFF06AAAAAAAAAAAAAAAAAAAAAAA03AAA00F
FFFFFFF06AAAAAAAAAAAAAAAAAAAAAAA0163000F
FFFFFFF06AAAAAAAAAAAAAAAAAAAAAAA000000FF
FFFFFFF06AAAA50000000000000AAAAA00FFFFFF
FFFFFFF06AAAA87777777777777AAAAA00FFFFFF
FFFFFFF06AAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFF06AAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFF06AAAA50000000000000AAAAA00FFFFFF
FFFFFFF06AAAA86666666666666AAAAA00FFFFFF
FFFFFFF06AAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFF06AAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFF06AAAA50000000000000AAAAA00FFFFFF
FFFFFFF06AAAA74444444444444AAAAA00FFFFFF
FFFFFFF06AAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFF06AAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFF06AAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFF06AAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFF00000000000000000000007AAAAA00FFFFFF
FFF000233333333333333333000AAAAA00FFFFFF
FF003AAAAAAAAAAAAAAAAAA9019AAAAA00FFFFFF
FF01AAAAAAAAAAAAAAAAAAA10AAAAAAA00FFFFFF
F009AAAAAAAAAAAAAAAAAAA05AAAAAAA00FFFFFF
F00AAAAAAAAAAAAAAAAAAAA09AAAAAAA00FFFFFF
F00AAAAAAAAAAAAAAAAAAAA08AAAAAAA00FFFFFF
FF04AAAAAAAAAAAAAAAAAAA01AAAAAA600FFFFFF
FF008AAAAAAAAAAAAAAAAAA607AAAA900FFFFFFF
FFF00499999999999999999900399400FFFFFFFF
FFFF000000000000000000000000000FFFFFFFFF
FFFFFF00000000000000000000000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SCRIPT(_alias) ENTITY(rectangle,black,script,_alias,OFF SCRIPT)
!define OFF_SCRIPT(_alias,_label) ENTITY(rectangle,black,script,_label,_alias,OFF SCRIPT)
!define OFF_SCRIPT(_alias,_label,_shape) ENTITY(_shape,black,script,_label,_alias,OFF SCRIPT)
!define OFF_SCRIPT(_alias,_label,_shape,_color) ENTITY(_shape,_color,script,_label,_alias,OFF SCRIPT)
skinparam folderBackgroundColor<<OFF SCRIPT>> White