sprite $settings [48x47/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF0000FFFFFF0000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00000000FFFF00000000FFFFFFFFFFFFFF
FFFFFFFFFFFFF000039A10FFFF01A720000FFFFFFFFFFFFF
FFFFFFFFFFFFF004AAAA500FF007AAAA200FFFFFFFFFFFFF
FFFFFFFFFFFFF00AAAAA9000000AAAAAA00FFFFFFFFFFFFF
FFFFFFFFFFFFF004AAAAA400005AAAAA300FFFFFFFFFFFFF
FFFFFFFFFFFFF000AAAAAAAAAAAAAAAA000FFFFFFFFFFFFF
FFFFFFFFFFFFFF008AAAAAAAAAAAAAA700FFFFFFFFFFFFFF
FFFFFFF00000F0009AAAAAAAAAAAAAA8000F0000FFFFFFFF
FFFFFF0001000009AAAAAAA99AAAAAAA8000000000FFFFFF
FFFFFF003A83009AAAAA62000026AAAAA80038A300FFFFFF
FFFFFF00AAAAA9AAAA800000000018AAAA8AAAA900FFFFFF
FFFFF001AAAAAAAAA7000FFFFFF0007AAAAAAAAA000FFFFF
FFFFF008AAAAAAAA9000FFFFFFFF0009AAAAAAAA700FFFFF
FFFFF008AAAAAAAA000FFFFFFFFFF001AAAAAAAA700FFFFF
FFFFF00016AAAAA800FFFFFFFFFFFF00AAAAAA61000FFFFF
FFFFFF000019AAA300FFFFFFFFFFFF004AAA800000FFFFFF
FFFFFFFF0009AAA000FFFFFFFFFFFF000AAA8000FFFFFFFF
FFFFFFFFF009AAA00FFFFFFFFFFFFFF00AAA800FFFFFFFFF
FFFFFFFFF009AAA00FFFFFFFFFFFFF000AAA800FFFFFFFFF
FFFFFF000008AAA100FFFFFFFFFFFF002AAA80000FFFFFFF
FFFFF000016AAAA600FFFFFFFFFFFF007AAAA610000FFFFF
FFFFF002AAAAAAAA000FFFFFFFFFF000AAAAAAA9100FFFFF
FFFFF00AAAAAAAAA500FFFFFFFFF0006AAAAAAAA900FFFFF
FFFFF004AAAAAAAAA100FFFFFFFF003AAAAAAAAA100FFFFF
FFFFF000AAAAAAAAAA30000FF00004AAAAAAAAAA000FFFFF
FFFFFF007AA833AAAAA7100000017AAAAA239AA500FFFFFF
FFFFFF000520003AAAAAA865568AAAAAA200024000FFFFFF
FFFFFFF000000003AAAAAAAAAAAAAAAA200000000FFFFFFF
FFFFFFFFF00FF0007AAAAAAAAAAAAAA5000FF000FFFFFFFF
FFFFFFFFFFFFFF00AAAAAAAAAAAAAAA900FFFFFFFFFFFFFF
FFFFFFFFFFFFF001AAAAA867769AAAAA000FFFFFFFFFFFFF
FFFFFFFFFFFFF008AAAAA100001AAAAA800FFFFFFFFFFFFF
FFFFFFFFFFFFF00AAAAA70000008AAAAA00FFFFFFFFFFFFF
FFFFFFFFFFFFF00029AA300FF003AAA3000FFFFFFFFFFFFF
FFFFFFFFFFFFFF00001200FFFF00320000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0000000FFFF000000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF00FFFFFFFF00FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SETTINGS(_alias) ENTITY(rectangle,black,settings,_alias,OFF SETTINGS)
!define OFF_SETTINGS(_alias,_label) ENTITY(rectangle,black,settings,_label,_alias,OFF SETTINGS)
!define OFF_SETTINGS(_alias,_label,_shape) ENTITY(_shape,black,settings,_label,_alias,OFF SETTINGS)
!define OFF_SETTINGS(_alias,_label,_shape,_color) ENTITY(_shape,_color,settings,_label,_alias,OFF SETTINGS)
skinparam folderBackgroundColor<<OFF SETTINGS>> White