sprite $upgrade_server [37x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF000000000000000000FFFFFFFFFFFF
FFFFFF00000000000000000000FFFFFFFFFFF
FFFFFF008AAAAAAAAAAAAAAA10FFFFFFFFFFF
FFFFF005AAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF006AAA55555555558AAA00FFFFFFFFFF
FFFFF006AAA00000000006AAA00FFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00FFFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA000FFFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA0000FFFFFFFF
FFFFF006AAAAAAAAAAAAAAAAA00200FFFFFFF
FFFFF006AAAAAAAAAAAAAAAA009A200FFFFFF
FFFFF006AAAAAAAAAAAAAAA109AAA200FFFFF
FFFFF006AAAAAAAAAAAAAA109AAAAA200FFFF
FFFFF006AAAAAAAAAAAAA208AAAAAAA200FFF
FFFFF006AAAAAAAAAAAA408AAAAAAAAA200FF
FFFFF006AAAAAAAAAAAA40AAA0AA85AA600FF
FFFFF006AAAAAAAAAAAA40AA00AA805A600FF
FFFFF006AAAAAAAAAAAA409000AA8005600FF
FFFFF006AAA888888888300010AA8000100FF
FFFFF006AAA000000000001A20AA8000000FF
FFFFF006AAAAAAAAAAAAAAAA20AA800F000FF
FFFFF006AAAAAAAAAAAAAAAA00AA800FFFFFF
FFFFF006AAAAAAAAAAAAAAA607AA50FFFFFFF
FFFFF006AAA00000000004203AAA00FFFFFFF
FFFFF006AAA5555555552006AAA600FFFFFFF
FFFFF006AAAAAAAAAAAA40AAAA800FFFFFFFF
FFFFF006AAAAAAAAAAAA40AAA6000FFFFFFFF
FFFFF006AAAAAAAAAAAA40A82000FFFFFFFFF
FFFFF0024444444444442000000FFFFFFFFFF
FFFFF0000000000000000000000FFFFFFFFFF
FFFFFF000000000000000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_UPGRADE_SERVER(_alias) ENTITY(rectangle,black,upgrade_server,_alias,OFF UPGRADE_SERVER)
!define OFF_UPGRADE_SERVER(_alias,_label) ENTITY(rectangle,black,upgrade_server,_label,_alias,OFF UPGRADE_SERVER)
!define OFF_UPGRADE_SERVER(_alias,_label,_shape) ENTITY(_shape,black,upgrade_server,_label,_alias,OFF UPGRADE_SERVER)
!define OFF_UPGRADE_SERVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,upgrade_server,_label,_alias,OFF UPGRADE_SERVER)
skinparam folderBackgroundColor<<OFF UPGRADE_SERVER>> White