sprite $video_play [48x42/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF0000000000000000000000000000000000FFFFFFF
FFFFFF000000000000000000000000000000000000FFFFFF
FFFFFF005BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB9100FFFFF
FFFFFF01BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB800FFFFF
FFFFFF01BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBB73ABBBBBBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBB6004ABBBBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBB600006BBBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBB60000018BBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBB600000002ABBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBB60000000004ABBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBB600000000004BBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBB6000000002ABBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBB600000018BBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBB6000006BBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBB60004ABBBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBB6029BBBBBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBB88BBBBBBBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFF
FFFFFF01BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFF
FFFFFF00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB400FFFFF
FFFFFF0014555555555555555555555555555553000FFFFF
FFFFFFF00000000000000000000000000000000000FFFFFF
FFFFFFFFF0000000000000000000000000000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_VIDEO_PLAY(_alias) ENTITY(rectangle,black,video_play,_alias,OFF VIDEO_PLAY)
!define OFF_VIDEO_PLAY(_alias,_label) ENTITY(rectangle,black,video_play,_label,_alias,OFF VIDEO_PLAY)
!define OFF_VIDEO_PLAY(_alias,_label,_shape) ENTITY(_shape,black,video_play,_label,_alias,OFF VIDEO_PLAY)
!define OFF_VIDEO_PLAY(_alias,_label,_shape,_color) ENTITY(_shape,_color,video_play,_label,_alias,OFF VIDEO_PLAY)
skinparam folderBackgroundColor<<OFF VIDEO_PLAY>> White