sprite $video_play [48x39/16] {
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
0007AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7100
007BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB700
00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB94ABBBBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB8006ABBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB800017BBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB80000028BBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB8000000049BBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB80000000005ABBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB8000000000016ABBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB800000000000028BBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB8000000000000006BBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB800000000000017ABBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB8000000000005ABBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB800000000049BBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB8000000028BBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB80000017BBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB800006ABBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB8004ABBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBB839BBBBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBBABBBBBBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00
00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00
007BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB700
0017AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7100
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
}

!define OFF_VIDEO_PLAY(_alias) ENTITY(rectangle,black,video_play,_alias,OFF VIDEO_PLAY)
!define OFF_VIDEO_PLAY(_alias,_label) ENTITY(rectangle,black,video_play,_label,_alias,OFF VIDEO_PLAY)
!define OFF_VIDEO_PLAY(_alias,_label,_shape) ENTITY(_shape,black,video_play,_label,_alias,OFF VIDEO_PLAY)
!define OFF_VIDEO_PLAY(_alias,_label,_shape,_color) ENTITY(_shape,_color,video_play,_label,_alias,OFF VIDEO_PLAY)
skinparam folderBackgroundColor<<OFF VIDEO_PLAY>> White