sprite $voicemail_preview [48x40/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF0000000000000000000000000000000000FFFFFFF
FFFFFF000000000000000000000000000000000000FFFFFF
FFFFFF03AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA20FFFFFF
FFFFFF09AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA60FFFFFF
FFFFFF09AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA60FFFFFF
FFFFFF09AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA60FFFFFF
FFFFFF09AAAAAA71005AAAAAAAAAA50028AAAAAA60FFFFFF
FFFFFF09AAAAA00000008AAAAAA70000001AAAAA60FFFFFF
FFFFFF09AAAA0001210008AAAA8000221001AAAA60FFFFFF
FFFFFF09AAA4005AAA8002AAAA0009AAA4008AAA60FFFFFF
FFFFFF09AAA101AAAAA6009AA9007AAAAA100AAA60FFFFFF
FFFFFF09AAA005AAAAA9008AA4000013AA300AAA60FFFFFF
FFFFFF09AAA004AAAAA900850038A95003300AAA60FFFFFF
FFFFFF09AAA100AAAAA200304AA999AA70002AAA60FFFFFF
FFFFFF09AAA80018A9300007A5000004A900AAAA60FFFFFF
FFFFFF09AAAA50000000006A2000000019808AAA60FFFFFF
FFFFFF09AAAAA700000001A30000000002A20AAA60FFFFFF
FFFFFF09AAAAAAA9888705A05888888970890AAA60FFFFFF
FFFFFF09AAAAAAAAAAA90860AAAAAAAAA14A07AA60FFFFFF
FFFFFF09AAAAAAAAAAA90950AAAAAAAAA33A06AA60FFFFFF
FFFFFF09AAAAAAAAAAA90950AAAAAAAAA23A06AA60FFFFFF
FFFFFF04AAAAAAAAAAAA07909AAAAAAAA07A09AA30FFFFFF
FFFFFF0023333333333303A10333333320A3033200FFFFFF
FFFFFFF0000000000000008A0000000007A0000000FFFFFF
FFFFFFFFFFFFFFFFFFFFF00AA00000008A90000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF0009A72226A99AA9000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00048AAA8500AAA9000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF00000000008AAA9000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF00000000009AAA900FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000AAAAA00FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF009AAAA00FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF009AAA40FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF008AA20FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0003200FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000FFFFF
}

!define OFF_VOICEMAIL_PREVIEW(_alias) ENTITY(rectangle,black,voicemail_preview,_alias,OFF VOICEMAIL_PREVIEW)
!define OFF_VOICEMAIL_PREVIEW(_alias,_label) ENTITY(rectangle,black,voicemail_preview,_label,_alias,OFF VOICEMAIL_PREVIEW)
!define OFF_VOICEMAIL_PREVIEW(_alias,_label,_shape) ENTITY(_shape,black,voicemail_preview,_label,_alias,OFF VOICEMAIL_PREVIEW)
!define OFF_VOICEMAIL_PREVIEW(_alias,_label,_shape,_color) ENTITY(_shape,_color,voicemail_preview,_label,_alias,OFF VOICEMAIL_PREVIEW)
skinparam folderBackgroundColor<<OFF VOICEMAIL_PREVIEW>> White