sprite $voicemail [48x35/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF000000000000000000000000000000000FFFFFFF
FFFFFF000000000000000000000000000000000000FFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA20FFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA20FFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA20FFFFF
FFFFFF05AAAAAAA6446AAAAAAAAAAA6447AAAAAAA20FFFFF
FFFFFF05AAAAA60000006AAAAAAA50000018AAAAA20FFFFF
FFFFFF05AAAA6000000006AAAAA4000000007AAAA20FFFFF
FFFFFF05AAA90009AA90009AAA8001AAA8000AAAA20FFFFF
FFFFFF05AAA6009AAAA9006AAA300AAAAA7007AAA20FFFFF
FFFFFF05AAA301AAAAAA103AAA003AAAAAA005AAA20FFFFF
FFFFFF05AAA301AAAAAA202AAA003AAAAAA005AAA20FFFFF
FFFFFF05AAA5009AAAA9005AAA200AAAAA8007AAA20FFFFF
FFFFFF05AAA9001AAAA1009AAA8003AAA9000AAAA20FFFFF
FFFFFF05AAAA5000110000699950000110006AAAA20FFFFF
FFFFFF05AAAAA50000000000000000000006AAAAA20FFFFF
FFFFFF05AAAAAAA4111111111111111115AAAAAAA20FFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA20FFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA20FFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA20FFFFF
FFFFFF04AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FFFFF
FFFFFF008AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA700FFFFF
FFFFFFF00000000000000000000000000000000000FFFFFF
FFFFFFFF00000000000000000000000000000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_VOICEMAIL(_alias) ENTITY(rectangle,black,voicemail,_alias,OFF VOICEMAIL)
!define OFF_VOICEMAIL(_alias,_label) ENTITY(rectangle,black,voicemail,_label,_alias,OFF VOICEMAIL)
!define OFF_VOICEMAIL(_alias,_label,_shape) ENTITY(_shape,black,voicemail,_label,_alias,OFF VOICEMAIL)
!define OFF_VOICEMAIL(_alias,_label,_shape,_color) ENTITY(_shape,_color,voicemail,_label,_alias,OFF VOICEMAIL)
skinparam folderBackgroundColor<<OFF VOICEMAIL>> White