sprite $whats_new [48x37/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF000400FFF0FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF00008B10FF000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF00002ABB10F00000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFF0000017BBBB100016000FFFFFF
FFFFFFFFF000000000000000027BBBBBB10003A500FFFFFF
FFFFFFFF0000111111111247ABBBBBBBB100004A100FFFFF
FFFFFFF0003ABBBBBBBBBBBBBBBBBBBBB1027009900FFFFF
FFFFFF0026ABBBBBBBBBBBBBBBBBBBBBB202A302B10FFFFF
FFFFF001BBBBBBBBBBBBBBBBBBBBBBBBBA108A00A200FFFF
FFFFF008BBBBBBBBBBBBBBBBBBBBBBBBBB703B109500FFFF
FFFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBA01B109600FFFF
FFFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBA02B109500FFFF
FFFFF007BBBBBBBBBBBBBBBBBBBBBBBBBB306A00A300FFFF
FFFFF001ABBBBBBBBBBBBBBBBBBBBBBBB400A501A100FFFF
FFFFFF0015ABBBBBBBBBBBBBBBBBBBBBB2019008A00FFFFF
FFFFFFF00029BBBBBBBBBBBBBBBBBBBBB200002A300FFFFF
FFFFFFFFF0004BBBB91011247ABBBBBBB20000A800FFFFFF
FFFFFFFFFF000BBBBA0000000026ABBBB20F005000FFFFFF
FFFFFFFFFFF007BBB600FFF0000017BBB20FF0000FFFFFFF
FFFFFFFFFFF002BBB400FFFFFF00003AB20FF000FFFFFFFF
FFFFFFFFFFFF00ABB700FFFFFFFF0002A10FFF0FFFFFFFFF
FFFFFFFFFFFF005BB800FFFFFFFFFF00000FFFFFFFFFFFFF
FFFFFFFFFFFFF01BB900FFFFFFFFFFF000FFFFFFFFFFFFFF
FFFFFFFFFFFFF00ABB50FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF007A400FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF0000000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_WHATS_NEW(_alias) ENTITY(rectangle,black,whats_new,_alias,OFF WHATS_NEW)
!define OFF_WHATS_NEW(_alias,_label) ENTITY(rectangle,black,whats_new,_label,_alias,OFF WHATS_NEW)
!define OFF_WHATS_NEW(_alias,_label,_shape) ENTITY(_shape,black,whats_new,_label,_alias,OFF WHATS_NEW)
!define OFF_WHATS_NEW(_alias,_label,_shape,_color) ENTITY(_shape,_color,whats_new,_label,_alias,OFF WHATS_NEW)
skinparam folderBackgroundColor<<OFF WHATS_NEW>> White