sprite $windows_powershell [48x45/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF000000000000000000000000000000FFFFFFFFF
FFFFFFFF000000000000000000000000000000000FFFFFFF
FFFFFFFF008AAAAAAAAAAAAAAAAAAAAAAAAAAA300FFFFFFF
FFFFFFF004AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAA848AAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAA0007AAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAA00006AAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAA800006AAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAA900005AAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAAA900004AAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAAAA900004AAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAAAAAA10003AAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAAAAAAA10002AAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAAAAAAAA10005AAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAAAAAAA300009AAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAAAAAA20000AAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAAAAA10001AAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAAA900002AAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAA800004AAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAA700005AAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAA00006AAA200000002AAAAAA00FFFFFFF
FFFFFFF005AAAAAA0007AAA90000000009AAAAA00FFFFFFF
FFFFFFF005AAAAAA959AAAAA744444447AAAAAA00FFFFFFF
FFFFFFF005AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF005AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF002AAAAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFFFF
FFFFFFFF002444444444444444444444444444000FFFFFFF
FFFFFFFF00000000000000000000000000000000FFFFFFFF
FFFFFFFFFF0000000000000000000000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_WINDOWS_POWERSHELL(_alias) ENTITY(rectangle,black,windows_powershell,_alias,OFF WINDOWS_POWERSHELL)
!define OFF_WINDOWS_POWERSHELL(_alias,_label) ENTITY(rectangle,black,windows_powershell,_label,_alias,OFF WINDOWS_POWERSHELL)
!define OFF_WINDOWS_POWERSHELL(_alias,_label,_shape) ENTITY(_shape,black,windows_powershell,_label,_alias,OFF WINDOWS_POWERSHELL)
!define OFF_WINDOWS_POWERSHELL(_alias,_label,_shape,_color) ENTITY(_shape,_color,windows_powershell,_label,_alias,OFF WINDOWS_POWERSHELL)
skinparam folderBackgroundColor<<OFF WINDOWS_POWERSHELL>> White