sprite $writing_pen [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000AA101AA7000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0019AA94AAAA9000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00018A44AAAAAAA200FF
FFFFFFFFFFFFFFFFFFFFFFFFFFF00018A502AAAAAAA400FF
FFFFFFFFFFFFFFFFFFFFFFFFFFF0009A501AAAAAAAA100FF
FFFFFFFFFFFFFFFFFFFFFFFFFF000AA401AAAAAAAA500FFF
FFFFFFFFFFFFFFFFFFFFFFFFF0019A402AAAAAAAA5000FFF
FFFFFFFFFFFFFFFFFFFFFFF00019A403AAAAAAAA5000FFFF
FFFFFFFFFFFFFFFFFFFFFF00019A402AAAAAAAA5000FFFFF
FFFFFFFFFFFFFFFFFFFFFF0009A401AAAAAAAA6000FFFFFF
FFFFFFFFFFFFFFFFFFFFF000AA602AAAAAAAA5000FFFFFFF
FFFFFFFFFFFFFFFFFFFF0008AA13AAAAAAAA5000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFF001613AAAAAAAA5000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF0002AAAAAAAA5000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF001AAAAAAAA5000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF00007AAAAAA5000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF0003007AAAA5000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF0004A8007AA5000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF0004AAA80076000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF0004AAAAA800000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF0004AAAAAA70000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0004AAAAAA70000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0004AAAAAA8000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF0004AAAAAA8000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF0004AAAAAA7000FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF0004AAAAAA7000FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF0004AAAAAA7000FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF0004AAAAAA7000FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF0004AAAAAA7000FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF0004AAAAAA7000FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0004AAAAAA6000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF004AAAAAA7000FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFF0007AAAAA7000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF0006AAAAA7000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF0007AAAAA6000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF007AAAA92000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF001AAAA80000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF003AAA80000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF00AAA8000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
F0039200000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
F00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_WRITING_PEN(_alias) ENTITY(rectangle,black,writing_pen,_alias,OFF WRITING_PEN)
!define OFF_WRITING_PEN(_alias,_label) ENTITY(rectangle,black,writing_pen,_label,_alias,OFF WRITING_PEN)
!define OFF_WRITING_PEN(_alias,_label,_shape) ENTITY(_shape,black,writing_pen,_label,_alias,OFF WRITING_PEN)
!define OFF_WRITING_PEN(_alias,_label,_shape,_color) ENTITY(_shape,_color,writing_pen,_label,_alias,OFF WRITING_PEN)
skinparam folderBackgroundColor<<OFF WRITING_PEN>> White