sprite $administrator [48x44/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF0000000FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0000000000FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF00039AAA5100FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF0019AAAAAAA300FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF001AAAAAAAAAA400FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF009AAAAAAAAAAA10FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF004AAAAAAAAAAAA900FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF009AAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF00AAAAAAAAAAAAAA30FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF02AAAAAAAAAAAAAA60FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF02AAAAAAAAAAAAAA60FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF01AAAAAAAAAAAAAA40FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF009AAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF005AAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAAAA300FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF004AAAAAAAAAA900FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF004AAAAAAAA9000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF0000019AAAAA300000FFFFFFFFFFFFFFFFFFFF
FFFFFFFF0000000000000000000000000000000000FFFFFF
FFFFFF00005AA3000000000009A9000220000000000FFFFF
FFFFF0003AAAAA8000000003AAAAA707800060006100FFFF
FFFF0007AAAAAAAAA63348AAAAAAA9078005A0007A00FFFF
FFFF005AAAAAAAAAAAAAAAAAAAAAA906700AA0007A10FFFF
FFFF00AAAAAAAAAAAAAAAAAAAAAAAA04600AA714AA20FFFF
FFF002AAAAAAAAAAAAAAAAAAAAAAAA046008AAAAAA10FFFF
FFF006AAAAAAAAAAAAAAAAAAAAAAAA046002AAAAA500FFFF
FFF00AAAAAAAAAAAAAAAAAAAAAAAAA0460002AAA500FFFFF
FFF00AAAAAAAAAAAAAAAAAAAAAAAAA0460000AAA300FFFFF
FFF01AAAAAAAAAAAAAAAAAAAAAAAAA0460000AAA30FFFFFF
FF001AAAAAAAAAAAAAAAAAAAAAAAA60460000AAA30FFFFFF
FF002AAAAAAAAAAAAAAAAAAAAAAAA01892000AAA30FFFFFF
FF004AAAAAAAAAAAAAAAAAAAAAAAA04AA5000AAA30FFFFFF
FF006AAAAAAAAAAAAAAAAAAAAAAAA04AA5000AAA30FFFFFF
FF008AAAAAAAAAAAAAAAAAAAAAAAA04AA5000AAA30FFFFFF
FF00788888888888888888888888804AA5000AAA30FFFFFF
FF00000000000000000000000000004AA5000AAA30FFFFFF
FF00000000000000000000000000004AA5000A2830FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF004AA5000A4920FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00288300017300FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000FFFFFFFF
}

!define OFF_ADMINISTRATOR(_alias) ENTITY(rectangle,black,administrator,_alias,OFF ADMINISTRATOR)
!define OFF_ADMINISTRATOR(_alias,_label) ENTITY(rectangle,black,administrator,_label,_alias,OFF ADMINISTRATOR)
!define OFF_ADMINISTRATOR(_alias,_label,_shape) ENTITY(_shape,black,administrator,_label,_alias,OFF ADMINISTRATOR)
!define OFF_ADMINISTRATOR(_alias,_label,_shape,_color) ENTITY(_shape,_color,administrator,_label,_alias,OFF ADMINISTRATOR)
skinparam folderBackgroundColor<<OFF ADMINISTRATOR>> White