sprite $approver [48x46/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000200FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000AB50FFF
FFFFFFFFFFFFFFF000000000FFFFFFFFFFFFFF008BA00FFF
FFFFFFFFFFFFFF00016750000FFFFFF0000FF004BB200FFF
FFFFFFFFFFFFF004ABBBBBA100FFFF000400001BB600FFFF
FFFFFFFFFFFF007BBBBBBBBB300FFF009B6000AB800FFFFF
FFFFFFFFFFF005BBBBBBBBBBB200FF005BB509BA00FFFFFF
FFFFFFFFFFF00ABBBBBBBBBBB900FFF006BB8BA000FFFFFF
FFFFFFFFFF007BBBBBBBBBBBBB30FFF0008BBB300FFFFFFF
FFFFFFFFFF009BBBBBBBBBBBBB600FFF0009B700FFFFFFFF
FFFFFFFFFF00ABBBBBBBBBBBBB900FFFF000800FFFFFFFFF
FFFFFFFFFF00BBBBBBBBBBBBBBA00FFF0000000000FFFFFF
FFFFFFFFFF00BBBBBBBBBBBBBB900FF000300000400FFFFF
FFFFFFFFFF00ABBBBBBBBBBBBB800FF00AB50007B800FFFF
FFFFFFFFFF008BBBBBBBBBBBBB500FF006BB507BB500FFFF
FFFFFFFFFFF04BBBBBBBBBBBBB10FFF0007BBABB500FFFFF
FFFFFFFFFFF009BBBBBBBBBBB600FFFF0007BBB500FFFFFF
FFFFFFFFFFF000ABBBBBBBBB900FFFFF0007BBB600FFFFFF
FFFFFFFFFFFF001ABBBBBBB9000FFFF0007BB9BB500FFFFF
FFFFFFFFFF0000005ABBBA3000000FF007BB506BB600FFFF
FFFFFFFF00000000000000000000000009B40007B800FFFF
FFFFFF00008BB5000000000006BB600000300000300FFFFF
FFFFF0006BBBBBA100000002ABBBBA300000FF0000FFFFFF
FFFFF00ABBBBBBBBB85469BBBBBBBBB800FFFFFFFFFFFFFF
FFFF009BBBBBBBBBBBBBBBBBBBBBBBBB600FFFFFFFFFFFFF
FFFF00ABBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFFFFFFFFFF
FFF006BBBBBBBBBBBBBBBBBBBBBBBBBBB30FFFFFFFFFFFFF
FFF00ABBBBBBBBBBBBBBBBBBBBBBBBBBB700FFFFFFFFFFFF
FFF00ABBBBBBBBBBBBBBBBBBBBBBBBBBB900FFFFFFFFFFFF
FFF00ABBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFFFFFFFFF
FFF01BBBBBBBBBBBBBBBBBBBBBBBBBBBBB00FFFFFFFFFFFF
FFF04BBBBBBBBBBBBBBBBBBBBBBBBBBBBB20FFFFFFFFFFFF
FF007BBBBBBBBBBBBBBBBBBBBBBBBBBBBB50FFFFFFFFFFFF
FF009BBBBBBBBBBBBBBBBBBBBBBBBBBBBB70FFFFFFFFFFFF
FF00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBB800FFFFFFFFFFF
FF00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBB900FFFFFFFFFFF
FF00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBB900FFFFFFFFFFF
FF00000000000000000000000000000000000FFFFFFFFFFF
FF00000000000000000000000000000000000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_APPROVER(_alias) ENTITY(rectangle,black,approver,_alias,OFF APPROVER)
!define OFF_APPROVER(_alias,_label) ENTITY(rectangle,black,approver,_label,_alias,OFF APPROVER)
!define OFF_APPROVER(_alias,_label,_shape) ENTITY(_shape,black,approver,_label,_alias,OFF APPROVER)
!define OFF_APPROVER(_alias,_label,_shape,_color) ENTITY(_shape,_color,approver,_label,_alias,OFF APPROVER)
skinparam folderBackgroundColor<<OFF APPROVER>> White