sprite $call_center_agent [38x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00000000000FFFFFFFFFFFFF
FFFFFFFFFFFF00002578741000FFFFFFFFFFFF
FFFFFFFFFFF0003AAA989AA81000FFFFFFFFFF
FFFFFFFFFF0007A830000049A400FFFFFFFFFF
FFFFFFFFFF008A40147873007A500FFFFFFFFF
FFFFFFFFF006A305AAAAAAA306A300FFFFFFFF
FFFFFFFF002A506AAAAAAAAA408A00FFFFFFFF
FFFFFFFF008904AAAAAAAAAAA11A500FFFFFFF
FFFFFFFF01A40AAAAAAAAAAAA806900FFFFFFF
FFFFFFF005A03AAAAAAAAAAAA902A20FFFFFFF
FFFFFFF0078121AAAAAAAAAA9020A40FFFFFFF
FFFFFFF0099AA19AAAAAAAAA83A9A600FFFFFF
FFFFFFF009AAA19AAAAAAAAA83AAA700FFFFFF
FFFFFFF004AAA19AAAAAAAAA83AAA100FFFFFF
FFFFFFFF01AAA19AAAAAAAAA83AA800FFFFFFF
FFFFFFFF018AA19AAAAAAAAA83AA100FFFFFFF
FFFFFFFF006390AAAAAAAAAA829100FFFFFFFF
FFFFFFFF008002AAAAAAAAAAA0000FFFFFFFFF
FFFFFFFF0043005AAAAAAAAA2000FFFFFFFFFF
FFFFFFFFF0081003AAAAAAA000FFFFFFFFFFFF
FFFFFFFFF000830000000000000000FFFFFFFF
FFFFFFF000030398AAAAA00002830000FFFFFF
FFFFFF0004AAA300688860006AAAA2000FFFFF
FFFFF0019AAAAAAA5100116AAAAAAA8000FFFF
FFFF000AAAAAAAAAAAAAAAAAAAAAAAA900FFFF
FFFF006AAAAAAAAAAAAAAAAAAAAAAAAA300FFF
FFFF00AAAAAAAAAAAAAAAAAAAAAAAAAA800FFF
FFF001AAAAAAAAAAAAAAAAAAAAAAAAAAA00FFF
FFF003AAAAAAAAAAAAAAAAAAAAAAAAAAA20FFF
FFF006AAAAAAAAAAAAAAAAAAAAAAAAAAA300FF
FFF008AAAAAAAAAAAAAAAAAAAAAAAAAAA600FF
FFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAA800FF
FFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FF
FFF01AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FF
FF001AAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FF
FF002AAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FF
FF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAA20FF
FF00011111111111111111111111111111000F
FF00000000000000000000000000000000000F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_CALL_CENTER_AGENT(_alias) ENTITY(rectangle,black,call_center_agent,_alias,OFF CALL_CENTER_AGENT)
!define OFF_CALL_CENTER_AGENT(_alias,_label) ENTITY(rectangle,black,call_center_agent,_label,_alias,OFF CALL_CENTER_AGENT)
!define OFF_CALL_CENTER_AGENT(_alias,_label,_shape) ENTITY(_shape,black,call_center_agent,_label,_alias,OFF CALL_CENTER_AGENT)
!define OFF_CALL_CENTER_AGENT(_alias,_label,_shape,_color) ENTITY(_shape,_color,call_center_agent,_label,_alias,OFF CALL_CENTER_AGENT)
skinparam folderBackgroundColor<<OFF CALL_CENTER_AGENT>> White