sprite $communications [40x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF00000000000000000000FFF
FFFFFFFFFFFFFFFFF01777777777777777710FFF
FFFFFFFFFFFFFFFFF08AAAAAAAAAAAAAAAA900FF
FFFFFFFFFFFFFFFFF08AAAAAAAAAAAAAAAA900FF
FFFFFFFFFFFFFFFFF08AAAAAAAAAAAAAAAA900FF
FFFFFFFFFFFFFFFFF08AAAAAAAAAAAAAAAA900FF
FFFFFFFFFFFFFFFFF08AAA3000008AAAAAA900FF
FFFFFFFFFFFFFFFFF08AAAAAAAAAAAAAAAA900FF
FFFFFFFFFFF00000008AAAAAAAAAAAAAAAA900FF
FFFFFFFFFF00059AA08AAA522222229AAAA900FF
FFFFFFFFF002AAAAA08AAA98888888AAAAA900FF
FFFFFFFF001AAAAAA08AAAAAAAAAAAAAAAA900FF
FFFFFFFF009AAAAAA08AAAAAAAAAAAAAAAA900FF
FFFFFFFF02AAAAAAA08AAAAAAAAAAAAAAAA900FF
FFFFFFF006AAAAAAA0499999999AAAA9999600FF
FFFFFFF007AAAAAAA5000000000AAA4000000FFF
FFFFFFF007AAAAAAAA988600000AA6000000FFFF
FFFFFFF006AAAAAAAAAAA60FF00A800FFFFFFFFF
FFFFFFFF02AAAAAAAAAAA30FF00900FFFFFFFFFF
FFFFFFFF009AAAAAAAAAA00FF0000FFFFFFFFFFF
FFFFFFFF001AAAAAAAAA300FF0000FFFFFFFFFFF
FFFFFFFFF003AAAAAAA400FFFFFFFFFFFFFFFFFF
FFFFFFF0000006AAA7100000FFFFFFFFFFFFFFFF
FFFFF000150000000000041000FFFFFFFFFFFFFF
FFFF0007AAA200000002AAA8000FFFFFFFFFFFFF
FFF001AAAAAAA50005AAAAAAA300FFFFFFFFFFFF
FF001AAAAAAAAAAAAAAAAAAAAA300FFFFFFFFFFF
FF008AAAAAAAAAAAAAAAAAAAAA900FFFFFFFFFFF
FF00AAAAAAAAAAAAAAAAAAAAAAA10FFFFFFFFFFF
FF02AAAAAAAAAAAAAAAAAAAAAAA20FFFFFFFFFFF
F005AAAAAAAAAAAAAAAAAAAAAAA50FFFFFFFFFFF
F006AAAAAAAAAAAAAAAAAAAAAAA70FFFFFFFFFFF
F008AAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFF
F009AAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFF
F00AAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFF
F00AAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFF
F01AAAAAAAAAAAAAAAAAAAAAAAAA10FFFFFFFFFF
F00000000000000000000000000000FFFFFFFFFF
F00000000000000000000000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_COMMUNICATIONS(_alias) ENTITY(rectangle,black,communications,_alias,OFF COMMUNICATIONS)
!define OFF_COMMUNICATIONS(_alias,_label) ENTITY(rectangle,black,communications,_label,_alias,OFF COMMUNICATIONS)
!define OFF_COMMUNICATIONS(_alias,_label,_shape) ENTITY(_shape,black,communications,_label,_alias,OFF COMMUNICATIONS)
!define OFF_COMMUNICATIONS(_alias,_label,_shape,_color) ENTITY(_shape,_color,communications,_label,_alias,OFF COMMUNICATIONS)
skinparam folderBackgroundColor<<OFF COMMUNICATIONS>> White