sprite $conferencing_attendant [42x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF0000000000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF0000467741000FFFFFFFFFFFFFFFFFF
FFFFFFFFFF0018AAA9AAA8100FFFFFFFFFFFFFFFFF
FFFFFFFFF003AA3000003AA400FFFFFFFFFFFFFFFF
FFFFFFFF004A70049A95006A500FFFFFFFFFFFFFFF
FFFFFFF001A603AAAAAAA405A200FFFFFFFFFFFFFF
FFFFFFF00A904AAAAAAAAA508A00FFFFFFFFFFFFFF
FFFFFF003A02AAAAAAAAAAA20A500FFFFFFFFFFFFF
FFFFFF00A908AAAAAAAAAAA908A00FFFFFFFFFFFFF
FFFFFF00A207AAAAAAAAAAA701A00FFFFFFFFFFFFF
FFFFFF02A1518AAAAAAAAA8051A40FFFFFFFFFFFFF
FFFFFF04AAA65AAAAAAAAA54AAA60FFFFFFFFFFFFF
FFFFFF04AAA65AAAAAAAAA54AAA60FFFFFFFFFFFFF
FFFFFF00AAA65AAAAAAAAA54AAA00FFFFFFFFFFFFF
FFFFFF00AAA65AAAAAAAAA54AA500FFFFFFFFFFFFF
FFFFFF00A7A55AAAAAAAAA54A900FFFFFFFFFFFFFF
FFFFFFF080208AAAAAAAAA90200FFFFFFFFFFFFFFF
FFFFFFF014007AAAAAAAAA8000FFFFFFFFFFFFFFFF
FFFFFFF0090007AAAAAAA8000FFFFFFF000FFFFFFF
FFFFFFFF0081003333474000000FFF000000FFFFFF
FFFFFFF0000662477770000020000F0058300FFFFF
FFFFF0003981139AAAA10019A9400005AAA400FFFF
FFFF0019AAAA9600000006AAAAA9202AAAAA00FFFF
FFF002AAAAAAAAAAA89AAAAAAAAA908AAAAA20FFFF
FFF009AAAAAAAAAAAAAAAAAAAAAA908AAAAA50FFFF
FF003AAAAAAAAAAAAAAAAAAAAAAAA208AAAA40FFFF
FF006AAAAAAAAAAAAAAAAAAAAAAAAA209AAA20FFFF
FF009AAAAAAAAAAAAAAAAAAAAAAAAA30AAAA00FFFF
FF00AAAAAAAAAAAAAAAAAAAAAAAAA607AAA600FFFF
FF01AAAAAAAAAAAAAAAAAAAAAAAA903AAAA00FFFFF
F003AAAAAAAAAAAAAAAAAAAAAAAA20AAAA400FFFFF
F004AAAAAAAAAAAAAAAAAA91017507AAAA00FFFFFF
F005AAAAAAAAAAAAAAAAAA0061004AAAA100FFFFFF
F007AAAAAAAAAAAAAAAAA209AA64AAAA400FFFFFFF
F008AAAAAAAAAAAAAAAA706AAAAAAAA700FFFFFFFF
F00AAAAAAAAAAAAAAAAA21AAAAAAAA8000FFFFFFFF
F000000000000000000003AAAAAAA80000FFFFFFFF
F0000000000000000000008AAAAA600000FFFFFFFF
FFFFFFFFFFFFFFFFFFFF00036640000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_CONFERENCING_ATTENDANT(_alias) ENTITY(rectangle,black,conferencing_attendant,_alias,OFF CONFERENCING_ATTENDANT)
!define OFF_CONFERENCING_ATTENDANT(_alias,_label) ENTITY(rectangle,black,conferencing_attendant,_label,_alias,OFF CONFERENCING_ATTENDANT)
!define OFF_CONFERENCING_ATTENDANT(_alias,_label,_shape) ENTITY(_shape,black,conferencing_attendant,_label,_alias,OFF CONFERENCING_ATTENDANT)
!define OFF_CONFERENCING_ATTENDANT(_alias,_label,_shape,_color) ENTITY(_shape,_color,conferencing_attendant,_label,_alias,OFF CONFERENCING_ATTENDANT)
skinparam folderBackgroundColor<<OFF CONFERENCING_ATTENDANT>> White