sprite $credentials [46x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF000000FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF0000000000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF00069AAA6000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF002AAAAAAAA200FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF002AAAAAAAAAA200FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF00AAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFFFFFFFFF007AAAAAAAAAAAA700FFFFFFFFFFFFFFFF
FFFFFFFFFFFF00AAAAAAAAAAAAAA00FFFFFFFFFFFFFFFF
FFFFFFFFFFFF00AAAAAAAAAAAAAA00FFFFFFFFFFFFFFFF
FFFFFFFFFFFF03AAAAAAAAAAAAAA30FFFFFFFFFFFFFFFF
FFFFFFFFFFFF04AAAAAAAAAAAAAA40FFFFFFFFFFFFFFFF
FFFFFFFFFFFF03AAAAAAAAAAAAAA30FFFFFFFFFFFFFFFF
FFFFFFFFFFFF00AAAAAAAAAAAAAA00FFFFFFFFFFFFFFFF
FFFFFFFFFFFF00AAAAAAAAAAAAAA00FFFFFFFFFFFFFFFF
FFFFFFFFFFFF005AAAAAAAAAAAA600FFFFFFFFFFFFFFFF
FFFFFFFFFFFFF00AAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF001AAAAAAAAAA100FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0019AAAAAA9100FFFFFFFFFFFFFFFFFF
FFFFFFFFFFF00000004799740000000FFFFFFFFFFFFFFF
FFFFFFFFF000043000000000000140000FFFFFFFFFFFFF
FFFFFFFF0004AAA600000000004AAA5000FFFFFFFFFFFF
FFFFFFF0029AAAAA9410000038AAAAA6000000FFFFFFFF
FFFFFF002AAAAAAAAAA9778AAAAA940002210000FFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAA70048AAAAA6100FFFFF
FFFFFF03AAAAAAAAAAAAAAAAAA602AAAAAAAAAA400FFFF
FFFFF009AAAAAAAAAAAAAAAAA803AAAAAAAAAAAA600FFF
FFFFF00AAAAAAAAAAAAAAAAAA01AAAAAAAAAAA8AA500FF
FFFFF00AAAAAAAAAAAAAAAAA50AAAAAAAAAAA806AA00FF
FFFFF01AAAAAAAAAAAAAAAAA01AAAAAAAAAAA001AA800F
FFFFF04AAAAAAAAAAAAAAAAA08AAAAAAAAAA100AAAA00F
FFFF007AAAAAAAAAAAAAAAA70AAAAAAAAAA5008AAAA00F
FFFF009AAAAAAAAAAAAAAAA50AAAA15AAA9005AAAAA20F
FFFF00AAAAAAAAAAAAAAAAA40AAA7006AA001AAAAAA20F
FFFF00AAAAAAAAAAAAAAAAA60AAAA3007200AAAAAAA00F
FFFF00AAAAAAAAAAAAAAAAA90AAAAA200009AAAAAAA00F
FFFF00AAAAAAAAAAAAAAAAAA04AAAAA0006AAAAAAAA00F
FFFF0000000000000000000000AAAAAA02AAAAAAAA20FF
FFFF00000000000000000000004AAAAAAAAAAAAAA900FF
FFFFFFFFFFFFFFFFFFFFFFFFF008AAAAAAAAAAAAA00FFF
FFFFFFFFFFFFFFFFFFFFFFFFFF007AAAAAAAAAAA000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF001AAAAAAAA5000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF000046750000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_CREDENTIALS(_alias) ENTITY(rectangle,black,credentials,_alias,OFF CREDENTIALS)
!define OFF_CREDENTIALS(_alias,_label) ENTITY(rectangle,black,credentials,_label,_alias,OFF CREDENTIALS)
!define OFF_CREDENTIALS(_alias,_label,_shape) ENTITY(_shape,black,credentials,_label,_alias,OFF CREDENTIALS)
!define OFF_CREDENTIALS(_alias,_label,_shape,_color) ENTITY(_shape,_color,credentials,_label,_alias,OFF CREDENTIALS)
skinparam folderBackgroundColor<<OFF CREDENTIALS>> White