sprite $meeting [48x37/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF0001000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF004AAA200FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF00AAAAA00FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF04AAAAA00FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF03AAAAA00FFFFFFFFFFFFFFFFFFF
FFFFFFFFF000000FFFFF00AAAAA00FFFFF00000FFFFFFFFF
FFFFFFFF00012000FFF0002AA91000FFF0012000FFFFFFFF
FFFFFFFF008AA910FF0016000005000F005AAA300FFFFFFF
FFFFFFF004AAAA800004AAA767AAA20001AAAAA00FFFFFFF
FFFFFFF008AAAAA0000AAAAAAAAAA80004AAAAA10FFFFFFF
FFFFFFF008AAAAA0001AAAAAAAAAAA0003AAAAA10FFFFFFF
FFFFFFFF02AAAA60F02999999999990000AAAA900FFFFFFF
FFFFFFF0005AA70000000000000000000029A80000FFFFFF
FFFFFF0045000035019999999999996017000016000FFFFF
FFFFF008AAA879A409AAAAAAAAAAAAA20AA878AAA20FFFFF
FFFFF01AAAAAAA906AAAAAAAAAAAAAAA03AAAAAAA80FFFFF
FFFFF02AAAAAAA11AAAAAAAAAAAAAAAA708AAAAAAA00FFFF
FFFFF05AAAAAA40AAAAAAAAAAAAAAAAAA21AAAAAAA00FFFF
FFFFF07AAAAA807AAAAAAAAAAAAAAAAAAA04AAAAAA00FFFF
FFFFF045555503AAAAAAAAAAAAAAAAAAAA6055555500FFFF
FFFFF00000000AAAAAAAAAAAAAAAAAAAAAA200000000FFFF
FFFFFFFFFF008AAAAAAAAAAAAAAAAAAAAAA900FFFFFFFFFF
FFFFFFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFFFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA20FFFFFFFFFF
FFFFFFFFFF0011111111111111111111111100FFFFFFFFFF
FFFFFFFFFF0000000000000000000000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_MEETING(_alias) ENTITY(rectangle,black,meeting,_alias,OFF MEETING)
!define OFF_MEETING(_alias,_label) ENTITY(rectangle,black,meeting,_label,_alias,OFF MEETING)
!define OFF_MEETING(_alias,_label,_shape) ENTITY(_shape,black,meeting,_label,_alias,OFF MEETING)
!define OFF_MEETING(_alias,_label,_shape,_color) ENTITY(_shape,_color,meeting,_label,_alias,OFF MEETING)
skinparam folderBackgroundColor<<OFF MEETING>> White