sprite $mobile_user [48x47/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF000001100000FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF00028BBBB82000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF0005BBBBBBBB5000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF005BBBBBBBBBB500FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF002BBBBBBBBBBBA200FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF008BBBBBBBBBBBB700FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF00BBBBBBBBBBBBBA00FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF02BBBBBBBBBBBBBB30FFFFFFFFFFFFFFFFFFF
FFFFFFFFFF002BBBBBBBBBBBBBB40FFFFFFFFFFFFFFFFFFF
FFFFFFFFFF002BBBBBBBBBBBBBB40FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF02BBBBBBBBBBBBBB20FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF00BBBBBBBBBBBBBA00FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF006BBBBBBBBBBBB700FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF001ABBBBBBBBBBA100FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF003BBBBBBBBBB400FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF003BBBBBBBB300FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF00000006ABBA60000000FFFFFFFFFFFFFFFFFF
FFFFFFFF0000100000000000000000000000000000000FFF
FFFFFFF0001ABA400000000003ABA20017777777777100FF
FFFFFF0009BBBBB9100000019BBBBB907BBBBBBBBBB900FF
FFFFF001BBBBBBBBBBA88ABBBBBBBBA07AAAAAAAAAA900FF
FFFF000ABBBBBBBBBBBBBBBBBBBBBBA07A000000009900FF
FFFF002BBBBBBBBBBBBBBBBBBBBBBBA07A000000009900FF
FFFF008BBBBBBBBBBBBBBBBBBBBBBBA07A000000009900FF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBA07A000000009900FF
FFF000BBBBBBBBBBBBBBBBBBBBBBBBA07A000000009900FF
FFF001BBBBBBBBBBBBBBBBBBBBBBBBA07A000000009900FF
FFF003BBBBBBBBBBBBBBBBBBBBBBBBA07A000000009900FF
FFF006BBBBBBBBBBBBBBBBBBBBBBBBA07A000000009900FF
FFF008BBBBBBBBBBBBBBBBBBBBBBBBA07A000000009900FF
FFF00ABBBBBBBBBBBBBBBBBBBBBBBBA07A000000009900FF
FFF00BBBBBBBBBBBBBBBBBBBBBBBBBA07A000000009900FF
FFF00BBBBBBBBBBBBBBBBBBBBBBBBBA07A000000009900FF
FFF005555555555555555555555555407A000000009900FF
FFF000000000000000000000000000007A99999999A900FF
FFF000000000000000000000000000007BBBA109BBB900FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF007BBBBAAABBB900FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF004444444444100FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_MOBILE_USER(_alias) ENTITY(rectangle,black,mobile_user,_alias,OFF MOBILE_USER)
!define OFF_MOBILE_USER(_alias,_label) ENTITY(rectangle,black,mobile_user,_label,_alias,OFF MOBILE_USER)
!define OFF_MOBILE_USER(_alias,_label,_shape) ENTITY(_shape,black,mobile_user,_label,_alias,OFF MOBILE_USER)
!define OFF_MOBILE_USER(_alias,_label,_shape,_color) ENTITY(_shape,_color,mobile_user,_label,_alias,OFF MOBILE_USER)
skinparam folderBackgroundColor<<OFF MOBILE_USER>> White