sprite $on_premises_user [40x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF00000000000000FFFFFFFFFFFFFFFFFFFF
FFFFFF00000000000000FFFFFFFFFFFFFFFFFFFF
FFFFFF02999999999900FFFFFFFFFFFFFFFFFFFF
FFFFFF03AAAAAAAAAA0000000FFFFFFFFFFFFFFF
FFFFFF03AAAAAAAAAA0000320FFFFFFFFFFFFFFF
FFFFFF03AA01AA01AA0000980FFFFFFFFFFFFFFF
FFFFFF03AA02AA01AA0000980FFFFFFFFFFFFFFF
FFFFFF03AAAAAAAAAA000098000FFFFFFFFFFFFF
FFFFFF03AAAAAAAAAA000198100FFFFFFFFFFFFF
FFFFFF03AA01AA01AA001AAAA00FFFFFFFFFFFFF
FFFFFF03AA01AA01AA001AAAA000FFFFFFFFFFFF
FFFFFF03AAAAAAAAAA001AAAA000FFFFFFFFFFFF
FFFFFF03AAAAAAAAAA026AAAA520FFFFFFFFFFFF
FFFFFF03AA34AA34AA04AAAAAA30FFFFFFFFFFFF
FFFFFF03AA01AA01AA04AAAAAA300FFFFFFFFFFF
FFFFFF03AAAAAAAAAA04AAAAAA300FFFFFFFFFFF
FFFFFF03AAAAAAAAAAAAAAAAAAA90FFFFFFFFFFF
FFFFFF03AA67AA67AAAAAAAAAAA90FFFFFFFFFFF
FFFFFF03AA01AA01AAAA01AAAAA90FFFFFFFFFFF
FFFFFF03AA77AA77AAAA01AAAAA8000FFFFFFFFF
FFFFFF03AAAAAAAAAAAAAAAAAA2000000FFFFFFF
FFFFFF03AAAAAAAAAAAAAAAAA107AA8000FFFFFF
FFFFFF03AA01AA01AAAAAAAA608AAAAA00FFFFFF
FFFFFF03AA34AA34AAAAAAAA04AAAAAA600FFFFF
FFFFFF03AAAAAAAAAAAA56AA08AAAAAAA00FFFFF
FFFFFF03AAAAAAAAAAAA01AA0AAAAAAAA00FFFFF
FFFFFF03AA01AA01AAAA88AA08AAAAAAA00FFFFF
FFFFFF03AA01AA01AAAAAAAA04AAAAAA600FFFFF
FFFFFF03AAAAAAAAAAAAAAAA608AAAAA00FFFFFF
FFFFFF03AAAAAAAAAAAAAAA5000699700000FFFF
FFFFFF03AAAAAAAAAAAAA8004700000066000FFF
FFFFFF03AAAAAAAAAAAAA019AAA63369AAA300FF
FFFFFF03AAAAAAAAAAAA60AAAAAAAAAAAAAA00FF
FFFFFF03AAAAAAAAAAAA21AAAAAAAAAAAAAA50FF
FFFFFF03AAAAAAAAAAAA04AAAAAAAAAAAAAA700F
FFFFFF03AAAAAAAAAAAA07AAAAAAAAAAAAAA900F
FFFFFF0000000000000008AAAAAAAAAAAAAAA00F
FFFFFF0000000000000009AAAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFFF009AAAAAAAAAAAAAAA10F
FFFFFFFFFFFFFFFFFFF00000000000000000000F
FFFFFFFFFFFFFFFFFFF00000000000000000000F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ON_PREMISES_USER(_alias) ENTITY(rectangle,black,on_premises_user,_alias,OFF ON_PREMISES_USER)
!define OFF_ON_PREMISES_USER(_alias,_label) ENTITY(rectangle,black,on_premises_user,_label,_alias,OFF ON_PREMISES_USER)
!define OFF_ON_PREMISES_USER(_alias,_label,_shape) ENTITY(_shape,black,on_premises_user,_label,_alias,OFF ON_PREMISES_USER)
!define OFF_ON_PREMISES_USER(_alias,_label,_shape,_color) ENTITY(_shape,_color,on_premises_user,_label,_alias,OFF ON_PREMISES_USER)
skinparam folderBackgroundColor<<OFF ON_PREMISES_USER>> White