sprite $outlook_user [48x44/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF0000000124600FFFFFFFFF
FFFFFFFFFFFFFFF000000FFFFF0035789999900FFFFFFFFF
FFFFFFFFFFFFF0000000000FFF0099999999900000000FFF
FFFFFFFFFFFF000589985000FF00999999999544444200FF
FFFFFFFFFFF001AAAAAAAA100F00999999999111111800FF
FFFFFFFFFFF00AAAAAAAAAA00F00999100999000006900FF
FFFFFFFFFF00AAAAAAAAAAAA0000994392399800073700FF
FFFFFFFFF004AAAAAAAAAAAA4000992796099270720700FF
FFFFFFFFF00AAAAAAAAAAAAAA000993695199039100700FF
FFFFFFFFF00AAAAAAAAAAAAAA000996150699000000700FF
FFFFFFFFF00AAAAAAAAAAAAAA000999636999000000700FF
FFFFFFFFF00AAAAAAAAAAAAAA000999999999766666700FF
FFFFFFFFF00AAAAAAAAAAAAAA000999999999100000000FF
FFFFFFFFF00AAAAAAAAAAAAAA00099999999900000000FFF
FFFFFFFFFF03AAAAAAAAAAAA300000136999900FFFFFFFFF
FFFFFFFFFF00AAAAAAAAAAAA00F000000000000FFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAA00FFFFFFFF000000FFFFFFFFF
FFFFFFFFFF00009AAAAAA90000FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF00000003788730000000FFFFFFFFFFFFFFFFFFFF
FFFFFF000056000000000000450000FFFFFFFFFFFFFFFFFF
FFFFF0004AAA920000000018AAA5000FFFFFFFFFFFFFFFFF
FFFF0019AAAAAA84000037AAAAAAA300FFFFFFFFFFFFFFFF
FFF001AAAAAAAAAAAAAAAAAAAAAAAA300FFFFFFFFFFFFFFF
FFF007AAAAAAAAAAAAAAAAAAAAAAAA900FFFFFFFFFFFFFFF
FFF00AAAAAAAAAAAAAAAAAAAAAAAAAA20FFFFFFFFFFFFFFF
FF003AAAAAAAAAAAAAAAAAAAAAAAAAA500FFFFFFFFFFFFFF
FF005AAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFFFFFF
FF008AAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFFF
FF00AAAAAAAAAAAAAAAAAAAAAAAAAAAA10FFFFFFFFFFFFFF
FF00AAAAAAAAAAAAAAAAAAAAAAAAAAAA20FFFFFFFFFFFFFF
FF01AAAAAAAAAAAAAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFF
FF01AAAAAAAAAAAAAAAAAAAAAAAAAAAA400FFFFFFFFFFFFF
F002AAAAAAAAAAAAAAAAAAAAAAAAAAAA600FFFFFFFFFFFFF
F003AAAAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFFFFF
F0049999999999999999999999999999800FFFFFFFFFFFFF
F0000000000000000000000000000000000FFFFFFFFFFFFF
F0000000000000000000000000000000000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_OUTLOOK_USER(_alias) ENTITY(rectangle,black,outlook_user,_alias,OFF OUTLOOK_USER)
!define OFF_OUTLOOK_USER(_alias,_label) ENTITY(rectangle,black,outlook_user,_label,_alias,OFF OUTLOOK_USER)
!define OFF_OUTLOOK_USER(_alias,_label,_shape) ENTITY(_shape,black,outlook_user,_label,_alias,OFF OUTLOOK_USER)
!define OFF_OUTLOOK_USER(_alias,_label,_shape,_color) ENTITY(_shape,_color,outlook_user,_label,_alias,OFF OUTLOOK_USER)
skinparam folderBackgroundColor<<OFF OUTLOOK_USER>> White