sprite $response_group_service [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF00000000F0000000000000000000000000FFFFFFF
FFFFFF00001110000011111111111111111111100FFFFFFF
FFFFFF004AAAA9102AAAAAAAAAAAAAAAAAAAAAA400FFFFFF
FFFFFF00AAAAAA708AAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFF01AAAAAA908AAA8888888888888888AAAA00FFFFFF
FFFFFF01AAAAAA908AAA1000000000000000AAAA00FFFFFF
FFFFFF01AAAAAA808AAA1000000000000000AAAA00FFFFFF
FFFFFF01AAAAAA808AAA1000000000000000AAAA00FFFFFF
FFFFFF00AAAAAA808AAA1000000000000000AAAA00FFFFFF
FFFFFF00AAAAAA708AAA1000000000000000AAAA00FFFFFF
FFFFFF00AAAAAA708AAA1000000000000000AAAA00FFFFFF
FFFFFF00AAAAAA708AAA9999999999999999AAAA00FFFFFF
FFFFFF00AAAAAA708AAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFF00AAAAAA708AAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFF00AAAAAA708AAAA7668A7669A7669AAAAA00FFFFFF
FFFFFF00AAAAAA708AAAA1002A0003A0005AAAAA00FFFFFF
FFFFFF00AAAAAA708AAAA6558A5558A5558AAAAA00FFFFFF
FFFFFF00AAAAAA708AAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFF00AAAAAA708AAAA1002A0003A0005AA50000FFFFFF
FFFFFF00AAAAAA708AAAA1002A0003A0005A1013000FFFFF
FFFFFF00AAAAAA708AAAAAAAAAAAAAAAAAA309AAA300FFFF
FFFFFF00AAAAAA708AAAA6558AA92018AAA05AAAAA10FFFF
FFFFFF00AAAAAA808AAAA1002A5001003A809AAAAA200FFF
FFFFFF01AAAAAA808AAAA7668804AAA505809AAAAA200FFF
FFFFFF01AAAAAA808AAAAAAAA01AAAAA21906AAAAA10FFFF
FFFFFF01AAAAAA908AAAAAAAA06AAAAA708209AAA4000FFF
FFFFFF01AAAAAA908AAAAAAAA07AAAAA70000046200000FF
FFFFFF01AAAAAA808AAAAAAAA02AAAAA4039A30017A5000F
FFFFFF006AAAAA203AAAAAAAA308AAA903AAAAAAAAAA800F
FFFFFF00003320000133333310005750039AAAAAAAAAA00F
FFFFFFF00000000F0000000017A40004A718AAAAAAAAA100
FFFFFFFFFFFFFFFFFFFFFF00AAAAA9AAAA91AAAAAAAAA400
FFFFFFFFFFFFFFFFFFFFFF03AAAAAAAAAAA48AAAAAAAA700
FFFFFFFFFFFFFFFFFFFFFF07AAAAAAAAAAA6477777777600
FFFFFFFFFFFFFFFFFFFFFF0AAAAAAAAAAAA7000000000000
FFFFFFFFFFFFFFFFFFFFFF0AAAAAAAAAAAA8000000000000
FFFFFFFFFFFFFFFFFFFFF00888888888888600FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF00000000000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF00000000000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_RESPONSE_GROUP_SERVICE(_alias) ENTITY(rectangle,black,response_group_service,_alias,OFF RESPONSE_GROUP_SERVICE)
!define OFF_RESPONSE_GROUP_SERVICE(_alias,_label) ENTITY(rectangle,black,response_group_service,_label,_alias,OFF RESPONSE_GROUP_SERVICE)
!define OFF_RESPONSE_GROUP_SERVICE(_alias,_label,_shape) ENTITY(_shape,black,response_group_service,_label,_alias,OFF RESPONSE_GROUP_SERVICE)
!define OFF_RESPONSE_GROUP_SERVICE(_alias,_label,_shape,_color) ENTITY(_shape,_color,response_group_service,_label,_alias,OFF RESPONSE_GROUP_SERVICE)
skinparam folderBackgroundColor<<OFF RESPONSE_GROUP_SERVICE>> White