sprite $role_group [48x43/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF0004651000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF003AAAAA600FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF002AAAAAAA600FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAA10FFFFFFFFFF
FFFFFFFFFFFF00000000FFFFF01AAAAAAAAA400FFFFFFFFF
FFFFFFFFFFF0003784000FFFF02AAAAAAAAA600FFFFFFFFF
FFFFFFFFFF0019AAAAA200FFF02AAAAAAAAA600FFFFFFFFF
FFFFFFFFFF009AAAAAAA10FFF01AAAAAAAAA30FFFFFFFFFF
FFFFFFFFF004AAAAAAAA700FF007AAAAAAAA00FFFFFFFFFF
FFFFFFFFF008AAAAAAAAA00FFF00AAAAAAA200FFFFFFFFFF
FFFFFFFFF00AAAAAAAAAA00F000008AAA920000FFFFFFFFF
FFFFFFFFF009AAAAAAAAA00000200001000020000FFFFFFF
FFFFFFFFF006AAAAAAAA800029AA30000029AA4000FFFFFF
FFFFFFFFFF01AAAAAAAA3006AAAAAA7679AAAAA800FFFFFF
FFFFFFFFFF004AAAAAA7002AAAAAAAAAAAAAAAAA60FFFFFF
FFFFFFFFF00002AAAA40006AAAAAAAAAAAAAAAAAA00FFFFF
FFFFFFF000020000000011009AAAAAAAAAAAAAAAA00FFFFF
FFFFFF0007AA81000016AA8106AAAAAAAAAAAAAAA10FFFFF
FFFFF001AAAAAA9779AAAAAA40700000000000000000FFFF
FFFFF009AAAAAAAAAAAAAAAAA00377777777777777300FFF
FFFFF00AAAAAAAAAAAAAAAAAA30AAAAAAAAAAAAAAA900FFF
FFFFF04AAAAAAAAAAAAAAAAAA60AAAAAA4019AAAAAA00FFF
FFFFF07AAAAAAAAAAAAAAAAAA70AAAAA102008AAAAA00FFF
FFFF008AAAAAAAAAAAAAAAAAA70AAAAA01A703AAAAA00FFF
FFFF009AAAAAAAAAAAAAAAAAA70AAAA8004101AAAAA00FFF
FFFF009AAAAAAAAAAAAAAAAAA70AAAAA000004AAAAA00FFF
FFFF00AAAAAAAAAAAAAAAAAAA70AAAAA70001AAAAAA00FFF
FFFF00000000000000000000000AAAAAA500AAAAAAA00FFF
FFFF00000000000000000000000AAAAAA601AAAAAAA00FFF
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAA608AAAAAAA00FFF
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAA600AAAAAAA00FFF
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAA606AAAAAAA00FFF
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAA601AAAAAAA00FFF
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAA28AAAAAAA00FFF
FFFFFFFFFFFFFFFFFFFFFFFFF008AAAAAAAAAAAAAA800FFF
FFFFFFFFFFFFFFFFFFFFFFFFF0000000000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ROLE_GROUP(_alias) ENTITY(rectangle,black,role_group,_alias,OFF ROLE_GROUP)
!define OFF_ROLE_GROUP(_alias,_label) ENTITY(rectangle,black,role_group,_label,_alias,OFF ROLE_GROUP)
!define OFF_ROLE_GROUP(_alias,_label,_shape) ENTITY(_shape,black,role_group,_label,_alias,OFF ROLE_GROUP)
!define OFF_ROLE_GROUP(_alias,_label,_shape,_color) ENTITY(_shape,_color,role_group,_label,_alias,OFF ROLE_GROUP)
skinparam folderBackgroundColor<<OFF ROLE_GROUP>> White