sprite $skype_commercial_user [48x47/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF00056631200000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF0007777777764000FFFF
FFFFFFFFFFFFFFFFF0000000FFFF00677777777776000FFF
FFFFFFFFFFFFFF00000110000FFF00777762112677600FFF
FFFFFFFFFFFFF00038ABBA82000F017777001100677300FF
FFFFFFFFFFFF0007BBBBBBBA500F007775027750577600FF
FFFFFFFFFFFF007BBBBBBBBBB500006776003577777700FF
FFFFFFFFFFF004BBBBBBBBBBBA30006777300002677710FF
FFFFFFFFFFF00ABBBBBBBBBBBB80006777765300377700FF
FFFFFFFFFF002BBBBBBBBBBBBBB1003776167750177730FF
FFFFFFFFFF006BBBBBBBBBBBBBB50007760045103777500F
FFFFFFFFFF009BBBBBBBBBBBBBB70004774100037777500F
FFFFFFFFFF009BBBBBBBBBBBBBB8000057777777777730FF
FFFFFFFFFF008BBBBBBBBBBBBBB70F0004777777777600FF
FFFFFFFFFF005BBBBBBBBBBBBBB40FF000035556765000FF
FFFFFFFFFF002BBBBBBBBBBBBBA00FFFF000000000000FFF
FFFFFFFFFFF009BBBBBBBBBBBB700FFFFFFFF000000FFFFF
FFFFFFFFFFF001ABBBBBBBBBBA10FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF003ABBBBBBBBA300FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF00002ABBBBBBA20000FFFFFFFFFFFFFFFFFFF
FFFFFFFFF000000004AAA9300000000FFFFFFFFFFFFFFFFF
FFFFFFFF000040000000000000030000FFFFFFFFFFFFFFFF
FFFFFF00008ABA200000000003ABA70000FFFFFFFFFFFFFF
FFFFF0006ABBBBA8100000029ABBBBA4000FFFFFFFFFFFFF
FFFFF009BBBBBBBBBA9889AABBBBBBBB8000FFFFFFFFFFFF
FFFF007BBBBBBBBBBBBBBBBBBBBBBBBBB400FFFFFFFFFFFF
FFFF00ABBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFFFFFFFFF
FFF004BBBBBBBBBBBBBBBBBBBBBBBBBBBB100FFFFFFFFFFF
FFF007BBBBBBBBBBBBBBBBBBBBBBBBBBBB400FFFFFFFFFFF
FFF008BBBBBBBBBBBBBBBBBBBBBBBBBBBB800FFFFFFFFFFF
FFF00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFFFFFFFF
FFF00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBB00FFFFFFFFFFF
FFF02BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFFFFFFFFF
FFF04BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFFFFFFFFF
FF006BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB300FFFFFFFFFF
FF007BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB500FFFFFFFFFF
FF008BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB700FFFFFFFFFF
FF009BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFFFFFFF
FF000000000000000000000000000000000000FFFFFFFFFF
FF000000000000000000000000000000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_COMMERCIAL_USER(_alias) ENTITY(rectangle,black,skype_commercial_user,_alias,OFF SKYPE_COMMERCIAL_USER)
!define OFF_SKYPE_COMMERCIAL_USER(_alias,_label) ENTITY(rectangle,black,skype_commercial_user,_label,_alias,OFF SKYPE_COMMERCIAL_USER)
!define OFF_SKYPE_COMMERCIAL_USER(_alias,_label,_shape) ENTITY(_shape,black,skype_commercial_user,_label,_alias,OFF SKYPE_COMMERCIAL_USER)
!define OFF_SKYPE_COMMERCIAL_USER(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_commercial_user,_label,_alias,OFF SKYPE_COMMERCIAL_USER)
skinparam folderBackgroundColor<<OFF SKYPE_COMMERCIAL_USER>> White