sprite $skype_for_business_user [48x47/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF00047741100000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF0007511576774000FFFF
FFFFFFFFFFFFFFFFF0000000FFFF00640000000157100FFF
FFFFFFFFFFFFFF000000100000FF00700002553003700FFF
FFFFFFFFFFFFF00028ABBA83000F007000586677105500FF
FFFFFFFFFFFF0006BBBBBBBA6000007000770017201700FF
FFFFFFFFFFFF006BBBBBBBBBB700005300774200000710FF
FFFFFFFFFFF002BBBBBBBBBBBB40005200278875000620FF
FFFFFFFFFFF009BBBBBBBBBBBB90004300001368400620FF
FFFFFFFFFF001BBBBBBBBBBBBBB30026007200185005400F
FFFFFFFFFF004BBBBBBBBBBBBBB70007007743683002600F
FFFFFFFFFF006BBBBBBBBBBBBBB80003700566630002600F
FFFFFFFFFF007BBBBBBBBBBBBBB80000571000000005400F
FFFFFFFFFF006BBBBBBBBBBBBBB8000004763341014600FF
FFFFFFFFFF003BBBBBBBBBBBBBB600F000025556775000FF
FFFFFFFFFFF01BBBBBBBBBBBBBA20FFFF000000000000FFF
FFFFFFFFFFF007BBBBBBBBBBBB800FFFFFFFF000000FFFFF
FFFFFFFFFFF001ABBBBBBBBBBA200FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF002ABBBBBBBBA400FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF00001ABBBBBBA30000FFFFFFFFFFFFFFFFFFF
FFFFFFFFF0000000039AAA400000000FFFFFFFFFFFFFFFFF
FFFFFFFF000040000000000000030000FFFFFFFFFFFFFFFF
FFFFFF00007ABA300000000002ABA80000FFFFFFFFFFFFFF
FFFFF0005ABBBBA9200000018ABBBBA6000FFFFFFFFFFFFF
FFFFF007BBBBBBBBBA9889AABBBBBBBB9000FFFFFFFFFFFF
FFFF004BBBBBBBBBBBBBBBBBBBBBBBBBB700FFFFFFFFFFFF
FFFF009BBBBBBBBBBBBBBBBBBBBBBBBBBB00FFFFFFFFFFFF
FFFF01ABBBBBBBBBBBBBBBBBBBBBBBBBBB300FFFFFFFFFFF
FFF005BBBBBBBBBBBBBBBBBBBBBBBBBBBB700FFFFFFFFFFF
FFF007BBBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFFFFFFFF
FFF008BBBBBBBBBBBBBBBBBBBBBBBBBBBBB00FFFFFFFFFFF
FFF009BBBBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFFFFFFFFF
FFF00ABBBBBBBBBBBBBBBBBBBBBBBBBBBBB200FFFFFFFFFF
FFF01BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB400FFFFFFFFFF
FFF03BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB600FFFFFFFFFF
FF004BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB800FFFFFFFFFF
FF006BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFFFFFFF
FF008BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB00FFFFFFFFFF
FF000000000000000000000000000000000000FFFFFFFFFF
FF000000000000000000000000000000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_USER(_alias) ENTITY(rectangle,black,skype_for_business_user,_alias,OFF SKYPE_FOR_BUSINESS_USER)
!define OFF_SKYPE_FOR_BUSINESS_USER(_alias,_label) ENTITY(rectangle,black,skype_for_business_user,_label,_alias,OFF SKYPE_FOR_BUSINESS_USER)
!define OFF_SKYPE_FOR_BUSINESS_USER(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_user,_label,_alias,OFF SKYPE_FOR_BUSINESS_USER)
!define OFF_SKYPE_FOR_BUSINESS_USER(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_user,_label,_alias,OFF SKYPE_FOR_BUSINESS_USER)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_USER>> White