sprite $tenant_admin [44x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF000000000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF000257741000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0019AAAAAA6000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFF002AAAAAAAAA800FFFFFFFFFFFFFFFF
FFFFFFFFFFFFF009AAAAAAAAAA600FFFFFFFFFFFFFFF
FFFFFFFFFFFF006AAAAAAAAAAAA10FFFFFFFFFFFFFFF
FFFFFFFFFFFF00AAAAAAAAAAAAA700FFFFFFFFFFFFFF
FFFFFFFFFFFF03AAAAAAAAAAAAA900FFFFFFFFFFFFFF
FFFFFFFFFFFF05AAAAAAAAAAAAAA00FFFFFFFFFFFFFF
FFFFFFFFFFFF05AAAAAAAAAAAAAA00FFFFFFFFFFFFFF
FFFFFFFFFFFF05AAAAAAAAAAAAAA00FFFFFFFFFFFFFF
FFFFFFFFFFFF02AAAAAAAAAAAAA900FFFFFFFFFFFFFF
FFFFFFFFFFFF00AAAAAAAAAAAAA700FFFFFFFFFFFFFF
FFFFFFFFFFFF006AAAAAAAAAAAA10FFFFFFFFFFFFFFF
FFFFFFFFFFFFF009AAAAAAAAAA600FFFFFFFFFFFFFFF
FFFFFFFFFFFFF001AAAAAAAAA800FFFFFFFFFFFFFFFF
FFFFFFFFFFFFF00019AAAAAA6000FFFFFFFFFFFFFFFF
FFFFFFFFFFF00000001688400000000FFFFFFFFFFFFF
FFFFFFFFF000285000000000000760000FFFFFFFFFFF
FFFFFFF00009AAA80000000001AAAA6000FFFFFFFFFF
FFFFFFF005AAAAAAA7100002AAAAAAAA200FFFFFFFFF
FFFFFF005AAAAAAAAAAAAAAAAAAAAAAAA200FFFFFFFF
FFFFF001AAAAAAAAAAAAAAAAAAAAAAAAA900FFFFFFFF
FFFFF005AAAAAAAAAAAAAAAAAAAAAAAAAA20FFFFFFFF
FFFFF009AAAAAAAAAAAAAAAAAAA6000000000FFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAA90266666500FFFFFFF
FFFFF01AAAAAAAAAAAAAAA744440A44444840000000F
FFFF002AAAAAAAAAAAAAA0011111A111116511110000
FFFF004AAAAAAAAAAAAA209AAAAAAAAAAAAAAAAAA300
FFFF006AAAAAAAAAAAAA06AAAA9AAAAAAAAAAAAAAA00
FFFF008AAAAAAAAAAAAA089998099999999940999900
FFFF009AAAAAAAAAAAAA012221012222222200222200
FFFF00AAAAAAAAAAAAAA09AAA90AAAAAAAAA40AAAA10
FFFF00AAAAAAAAAAAAAA09AAAA8AAAAAAAAAA9AAAA10
FFFF002222222222222209AAAAAAAAAAAAAAAAAAAA10
FFFF000000000000000009AAAAAAAAAAAAAAAAAAAA10
FFFFFFFFFFFFFFFFFFFF09AAAAAAAAAAAAAAAAAAAA10
FFFFFFFFFFFFFFFFFFFF09AAAAAAAAAAAAAAAAAAAA10
FFFFFFFFFFFFFFFFFFFF09AAAAAAAAAAAAAAAAAAAA10
FFFFFFFFFFFFFFFFFFFF011111111111111111111100
FFFFFFFFFFFFFFFFFFFF000000000000000000000000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_TENANT_ADMIN(_alias) ENTITY(rectangle,black,tenant_admin,_alias,OFF TENANT_ADMIN)
!define OFF_TENANT_ADMIN(_alias,_label) ENTITY(rectangle,black,tenant_admin,_label,_alias,OFF TENANT_ADMIN)
!define OFF_TENANT_ADMIN(_alias,_label,_shape) ENTITY(_shape,black,tenant_admin,_label,_alias,OFF TENANT_ADMIN)
!define OFF_TENANT_ADMIN(_alias,_label,_shape,_color) ENTITY(_shape,_color,tenant_admin,_label,_alias,OFF TENANT_ADMIN)
skinparam folderBackgroundColor<<OFF TENANT_ADMIN>> White