sprite $um_enabled_user [46x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF0000000FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00000000000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF00027AAA83000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF0005AAAAAAA8000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF006AAAAAAAAA900FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF02AAAAAAAAAAA600FFFFFFFFFFFFFFFFFF
FFFFFFFFFFF009AAAAAAAAAAAA00FFFFFFFFFFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAAAAA500FFFFFFFFFFFFFFFFF
FFFFFFFFFFF03AAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFFFFFFFF06AAAAAAAAAAAAA900FFFFFFFFFFFFFFFFF
FFFFFFFFFFF06AAAAAAAAAAAAA900FFFFFFFFFFFFFFFFF
FFFFFFFFFFF04AAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAAAAA600FFFFFFFFFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF02AAAAAAAAAAA800FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF007AAAAAAAAAA00FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF0007AAAAAAA9000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFF00000038AAA95000000FFFFFFFFFFFFFFFFF
FFFFFFFF00002100000000000010000FFFFFFFFFFFFFFF
FFFFFFF00039AA200000000006AA50000FFFFFFFFFFFFF
FFFFFF0018AAAAA720000004AAAAAA3000FFFFFFFFFFFF
FFFFF002AAAAAAAAA97678AAAAAAAAA600FFFFFFFFFFFF
FFFFF009AAAAAAAAAAAAAAA94347733300000000000FFF
FFFF003AAAAAAAAAAAAAAA9002100111111111111100FF
FFFF006AAAAAAAAAAAAAAA20AAA51AAAAAAAAAAAAA20FF
FFFF009AAAAAAAAAAAAAAA01AAA81AA988888888AA20FF
FFFF00AAAAAAAAAAAAAAAA01AAA81AA200000001AA20FF
FFFF02AAAAAAAAAAAAAAAA10AAA71AA200000001AA20FF
FFF003AAAAAAAAAAAAAAAA10AAA71AA200000001AA20FF
FFF005AAAAAAAAAAAAAAAA20AAA71AAAAAAAAAAAAA20FF
FFF006AAAAAAAAAAAAAAAA20AAA71AAAAAAAAAAAAA20FF
FFF007AAAAAAAAAAAAAAAA20AAA71AA804705606AA20FF
FFF008AAAAAAAAAAAAAAAA20AAA71AAA47948849AA20FF
FFF00AAAAAAAAAAAAAAAAA10AAA71AAA68A59969AA20FF
FFF005555555555555555500AAA71AA804805607AA20FF
FFF000000000000000000000AAA71AAA9AA9AA9AAA20FF
FFFFFFFFFFFFFFFFFFFFFF01AAA71AA803704606AA20FF
FFFFFFFFFFFFFFFFFFFFFF01AAA71AAA68A69969AA20FF
FFFFFFFFFFFFFFFFFFFFFF01AAA71AAAAAAAAAAAAA20FF
FFFFFFFFFFFFFFFFFFFFFF0079820899999999999810FF
FFFFFFFFFFFFFFFFFFFFFF0000000000000000000000FF
FFFFFFFFFFFFFFFFFFFFFFFF0000000000000000000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_UM_ENABLED_USER(_alias) ENTITY(rectangle,black,um_enabled_user,_alias,OFF UM_ENABLED_USER)
!define OFF_UM_ENABLED_USER(_alias,_label) ENTITY(rectangle,black,um_enabled_user,_label,_alias,OFF UM_ENABLED_USER)
!define OFF_UM_ENABLED_USER(_alias,_label,_shape) ENTITY(_shape,black,um_enabled_user,_label,_alias,OFF UM_ENABLED_USER)
!define OFF_UM_ENABLED_USER(_alias,_label,_shape,_color) ENTITY(_shape,_color,um_enabled_user,_label,_alias,OFF UM_ENABLED_USER)
skinparam folderBackgroundColor<<OFF UM_ENABLED_USER>> White