sprite $universal_security_group [48x41/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF000000000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF00015761000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF005AAAAA700FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF003AAAAAAA600FFFFFFFFFF
FFFFFFFFFFFFFFF0FFFFFFFFF00AAAAAAAAA00FFFFFFFFFF
FFFFFFFFFFFF0000000FFFFFF01AAAAAAAAA50FFFFFFFFFF
FFFFFFFFFFF0004762000FFFF04AAAAAAAAA80FFFFFFFFFF
FFFFFFFFFF002AAAAA7000FFF03AAAAAAAAA80FFFFFFFFFF
FFFFFFFFFF01AAAAAAA700FFF01AAAAAAAAA40FFFFFFFFFF
FFFFFFFFF00AAAAAAAAA20FFF00AAAAAAAAA00FFFFFFFFFF
FFFFFFFFF00AAAAAAAAA600FF002AAAAAAA600FFFFFFFFFF
FFFFFFFFF02AAAAAAAAA900FF0004AAAAA7000FFFFFFFFFF
FFFFFFFFF02AAAAAAAAA90000000005761000000FFFFFFFF
FFFFFFFFF00AAAAAAAAA600005A500000004A60000FFFFFF
FFFFFFFFF00AAAAAAAAA2003AAAA9421148AAAA400FFFFFF
FFFFFFFFF002AAAAAAA7002AAAAAAAAAAAAAAAAA400FFFFF
FFFFFFFFF0003AAAAA80009AAAAAAAAAAAAAAAAA900FFFFF
FFFFFFFF000001476200002AAAAAAAAAAAAAAAAAA10FFFFF
FFFFFF0004970000000298003AAAAAAAAAAAAAAAA30FFFFF
FFFFF0019AAAA500028AAAA303AAA500002AAAAAA50FFFFF
FFFFF00AAAAAAAAAAAAAAAAA40AA003884009AAAA700FFFF
FFFF006AAAAAAAAAAAAAAAAAA05109AAAAA10AAAA800FFFF
FFFF009AAAAAAAAAAAAAAAAAA1009A5002AA03AAA900FFFF
FFFF00AAAAAAAAAAAAAAAAAAA401A600003A20AAA900FFFF
FFFF02AAAAAAAAAAAAAAAAAAA803A200000A70000000FFFF
FFFF03AAAAAAAAAAAAAAAAAAAA03A200000A70000000FFFF
FFF004AAAAAAAAAAAAAAAAAAA603A200000A4000000FFFFF
FFF005AAAAAAAAAAAAAAAAAAA049A988888A029A8100FFFF
FFF007AAAAAAAAAAAAAAAAAAA08AAAAAAAA20A91A900FFFF
FFF000000000000000000000008AAAAAAAA01AA7AA10FFFF
FFF000000000000000000000008AAAAAAAA10AAAAA00FFFF
FFFFFFFFFFFFFFFFFFFFFFFFF08AAAAAAAA807AAA400FFFF
FFFFFFFFFFFFFFFFFFFFFFFFF08AAAAAAAAA306A400FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF08AAAAAAAAAA06A20FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF08AAAAAAAAAA06A100FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF07AAAAAAAAAA06A400FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF00222222222206A200FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF00000000000001A100FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000FFFFFFF
}

!define OFF_UNIVERSAL_SECURITY_GROUP(_alias) ENTITY(rectangle,black,universal_security_group,_alias,OFF UNIVERSAL_SECURITY_GROUP)
!define OFF_UNIVERSAL_SECURITY_GROUP(_alias,_label) ENTITY(rectangle,black,universal_security_group,_label,_alias,OFF UNIVERSAL_SECURITY_GROUP)
!define OFF_UNIVERSAL_SECURITY_GROUP(_alias,_label,_shape) ENTITY(_shape,black,universal_security_group,_label,_alias,OFF UNIVERSAL_SECURITY_GROUP)
!define OFF_UNIVERSAL_SECURITY_GROUP(_alias,_label,_shape,_color) ENTITY(_shape,_color,universal_security_group,_label,_alias,OFF UNIVERSAL_SECURITY_GROUP)
skinparam folderBackgroundColor<<OFF UNIVERSAL_SECURITY_GROUP>> White