sprite $user_external [47x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00000000FFFFFFFFFF00000000000FF
FFFFFFFFFFFFFF00001210000FFFFFFFF000000000000FF
FFFFFFFFFFFFF0004ABBBA5000FFFFFF0028877666400FF
FFFFFFFFFFFF0009BBBBBBB9100FFFF002AAAAAAAA800FF
FFFFFFFFFFFF009BBBBBBBBB9000FF00088888AAAA800FF
FFFFFFFFFFF005BBBBBBBBBBB700FF00000003AAAA800FF
FFFFFFFFFFF00ABBBBBBBBBBBB10FFF000003AAAAA800FF
FFFFFFFFFFF02BBBBBBBBBBBBB400FFFF003AAA67A900FF
FFFFFFFFFFF06BBBBBBBBBBBBB800FFF003AAA607A900FF
FFFFFFFFFF008BBBBBBBBBBBBB900FF003AAA7007A900FF
FFFFFFFFFF008BBBBBBBBBBBBB900F000AAA70007A600FF
FFFFFFFFFFF06BBBBBBBBBBBBB800FF004A7000076000FF
FFFFFFFFFFF02BBBBBBBBBBBBB400FFF003000002000FFF
FFFFFFFFFFF00ABBBBBBBBBBBB10FFFF00000F00000FFFF
FFFFFFFFFFF004BBBBBBBBBBB600FFFFF000FFF000FFFFF
FFFFFFFFFFFF008BBBBBBBBB9000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF0008BBBBBBB9000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF0000002ABBBA4000000FFFFFFFFFFFFFFFFFF
FFFFFFFFF0000000000000000000000FFFFFFFFFFFFFFFF
FFFFFFF0002ABA000000000007BB4000FFFFFFFFFFFFFFF
FFFFFF0009BBBBB500000003ABBBBA100FFFFFFFFFFFFFF
FFFFF002BBBBBBBBBA7569BBBBBBBBB500FFFFFFFFFFFFF
FFFF000ABBBBBBBBBBBBBBBBBBBBBBBB10FFFFFFFFFFFFF
FFFF004BBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFFFFFFFFF
FFFF008BBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFFFFFFFFF
FFFF00BBBBBBBBBBBBBBBBBBBBBBBBBBB10FFFFFFFFFFFF
FFF001BBBBBBBBBBBBBBBBBBBBBBBBBBB50FFFFFFFFFFFF
FFF003BBBBBBBBBBBBBBBBBBBBBBBBBBB800FFFFFFFFFFF
FFF004BBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFFFFFFFF
FFF006BBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFFFFFFFF
FFF008BBBBBBBBBBBBBBBBBBBBBBBBBBBA00FFFFFFFFFFF
FFF00ABBBBBBBBBBBBBBBBBBBBBBBBBBBB00FFFFFFFFFFF
FFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBB20FFFFFFFFFFF
FFF00BBBBBBBBBBBBBBBBBBBBBBBBBBBBB50FFFFFFFFFFF
FFF007777777777777777777777777777740FFFFFFFFFFF
FFF000000000000000000000000000000000FFFFFFFFFFF
FFF000000000000000000000000000000000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_USER_EXTERNAL(_alias) ENTITY(rectangle,black,user_external,_alias,OFF USER_EXTERNAL)
!define OFF_USER_EXTERNAL(_alias,_label) ENTITY(rectangle,black,user_external,_label,_alias,OFF USER_EXTERNAL)
!define OFF_USER_EXTERNAL(_alias,_label,_shape) ENTITY(_shape,black,user_external,_label,_alias,OFF USER_EXTERNAL)
!define OFF_USER_EXTERNAL(_alias,_label,_shape,_color) ENTITY(_shape,_color,user_external,_label,_alias,OFF USER_EXTERNAL)
skinparam folderBackgroundColor<<OFF USER_EXTERNAL>> White