sprite $users [48x44/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF00179983000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF002AAAAAA600FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF009AAAAAAA400FFFFFFFFF
FFFFFFFFFFFFF000000FFFFFF005AAAAAAAA900FFFFFFFFF
FFFFFFFFFFFF000000000FFFF008AAAAAAAAA10FFFFFFFFF
FFFFFFFFFFF00049A71000FFF009AAAAAAAAA30FFFFFFFFF
FFFFFFFFFF000AAAAAA500FFF008AAAAAAAAA20FFFFFFFFF
FFFFFFFFFF009AAAAAAA400FF007AAAAAAAAA00FFFFFFFFF
FFFFFFFFF004AAAAAAAA900FFF02AAAAAAAA600FFFFFFFFF
FFFFFFFFF007AAAAAAAAA20FFF005AAAAAA9000FFFFFFFFF
FFFFFFFFF008AAAAAAAAA40FF00005AAAA710000FFFFFFFF
FFFFFFFFF008AAAAAAAAA300000000033100010000FFFFFF
FFFFFFFFF007AAAAAAAAA1000134310000029A71000FFFFF
FFFFFFFFFF02AAAAAAAA70003AAAAA4005AAAAAA300FFFFF
FFFFFFFFFF006AAAAAAA1003AAAAAAA409AAAAAAA100FFFF
FFFFFFFFF00006AAAAA1000AAAAAAAAA01AAAAAAA600FFFF
FFFFFFF0000000134100002AAAAAAAAA309AAAAAAA00FFFF
FFFFFF00059A70000002705AAAAAAAAA609AAAAAAA00FFFF
FFFFF0008AAAAA75468A805AAAAAAAAA709AAAAAAA10FFFF
FFFFF008AAAAAAAAAAAA903AAAAAAAAA409AAAAAAA200FFF
FFFFF01AAAAAAAAAAAAAA21AAAAAAAAA00AAAAAAAA300FFF
FFFF002AAAAAAAAAAAAAA606AAAAAAA707AAAAAAAA500FFF
FFFF005AAAAAAAAAAAAAA9008AAAAA700899999999500FFF
FFFF007AAAAAAAAAAAAA2000028A82000000000000000FFF
FFFF00AAAAAAAAAAAA5006A400000003A400000000000FFF
FFFF00AAAAAAAAAAA5039AAA9300039AAA9200FFFFFFFFFF
FFFF01AAAAAAAAAAA03AAAAAAAAAAAAAAAAA200FFFFFFFFF
FFFF019999999999609AAAAAAAAAAAAAAAAA800FFFFFFFFF
FFFF00000000000000AAAAAAAAAAAAAAAAAAA00FFFFFFFFF
FFFF00000000000001AAAAAAAAAAAAAAAAAAA20FFFFFFFFF
FFFFFFFFFFFFFFF004AAAAAAAAAAAAAAAAAAA50FFFFFFFFF
FFFFFFFFFFFFFFF007AAAAAAAAAAAAAAAAAAA600FFFFFFFF
FFFFFFFFFFFFFFF009AAAAAAAAAAAAAAAAAAA700FFFFFFFF
FFFFFFFFFFFFFFF009AAAAAAAAAAAAAAAAAAA800FFFFFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAAAA900FFFFFFFF
FFFFFFFFFFFFFFF0012222222222222222222100FFFFFFFF
FFFFFFFFFFFFFFF0000000000000000000000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_USERS(_alias) ENTITY(rectangle,black,users,_alias,OFF USERS)
!define OFF_USERS(_alias,_label) ENTITY(rectangle,black,users,_label,_alias,OFF USERS)
!define OFF_USERS(_alias,_label,_shape) ENTITY(_shape,black,users,_label,_alias,OFF USERS)
!define OFF_USERS(_alias,_label,_shape,_color) ENTITY(_shape,_color,users,_label,_alias,OFF USERS)
skinparam folderBackgroundColor<<OFF USERS>> White