sprite $user_store [43x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0000000000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFF0000000000000000000FFFFFFFFFFFFFF
FFFFFFFF00000134678877532100000FFFFFFFFFFFF
FFFFFF000038AAAAAAAAAAAAAAA61000FFFFFFFFFFF
FFFFFF003AAAAAAAAAAAAAAAAAAAA7000FFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAA700FFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAA700FFFFFFFFFF
FFFFFF0039AAAAAAAAAAAAAAAAAAA7000FFFFFFFFFF
FFFFFF000037AAAAAAAAAAAAAA9610100FFFFFFFFFF
FFFFFF029400013456776654200027800FFFFFFFFFF
FFFFFF02AAA85310000000002479AA800FFFFFFFFFF
FFFFFF02AAAAAAAAA99999AAAAAAAA800FFFFFFFFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAA9100000FFFFFFFF
FFFFFF02AAAAAAAAAAAAAAAAAAA800598100FFFFFFF
FFFFFF02AAAAAAAAAAAAAAAAAAA01AAAAA600FFFFFF
FFFFFF02AAAAAAAAAAAAAAAAAA609AAAAAA300FFFFF
FFFFFF02AAAAAAAAAAAAAAAAAA02AAAAAAA700FFFFF
FFFFFF02AAAAAAAAAAAAAAAAAA03AAAAAAAA00FFFFF
FFFFFF02AAAAAAAAAAAAAAAAAA03AAAAAAAA00FFFFF
FFFFFF02AAAAAAAAAAAAAAAAAA12AAAAAAA700FFFFF
FFFFFF02AAAAAAAAAAAAAAAAAA609AAAAAA200FFFFF
FFFFFF02AAAAAAAAAAAAAAAAAA8019AAAA5000FFFFF
FFFFFF02AAAAAAAAAAAAAAAA9300005872000000FFF
FFFFFF02AAAAAAAAAAAAAAA8004A5000001972000FF
FFFFFF01AAAAAAAAAAAAAAA019AAA95447AAAA500FF
FFFFFF006AAAAAAAAAAAAA709AAAAAAAAAAAAAA200F
FFFFFF00049AAAAAAAAAAA10AAAAAAAAAAAAAAA600F
FFFFFFF0000268AAAAAAAA01AAAAAAAAAAAAAAAA00F
FFFFFFFFF000000112222204AAAAAAAAAAAAAAAA00F
FFFFFFFFFFFF000000000007AAAAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFFFFF009AAAAAAAAAAAAAAAA10F
FFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAA200
FFFFFFFFFFFFFFFFFFFFF0011111111111111111000
FFFFFFFFFFFFFFFFFFFFF0000000000000000000000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_USER_STORE(_alias) ENTITY(rectangle,black,user_store,_alias,OFF USER_STORE)
!define OFF_USER_STORE(_alias,_label) ENTITY(rectangle,black,user_store,_label,_alias,OFF USER_STORE)
!define OFF_USER_STORE(_alias,_label,_shape) ENTITY(_shape,black,user_store,_label,_alias,OFF USER_STORE)
!define OFF_USER_STORE(_alias,_label,_shape,_color) ENTITY(_shape,_color,user_store,_label,_alias,OFF USER_STORE)
skinparam folderBackgroundColor<<OFF USER_STORE>> White