sprite $user [38x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF000000000FFFFFFFFFFFFFF
FFFFFFFFFFFFF000013320000FFFFFFFFFFFFF
FFFFFFFFFFFF00038AAAAA5000FFFFFFFFFFFF
FFFFFFFFFFF0005AAAAAAAA8000FFFFFFFFFFF
FFFFFFFFFFF005AAAAAAAAAA9000FFFFFFFFFF
FFFFFFFFFF002AAAAAAAAAAAA600FFFFFFFFFF
FFFFFFFFFF008AAAAAAAAAAAAA100FFFFFFFFF
FFFFFFFFFF01AAAAAAAAAAAAAA400FFFFFFFFF
FFFFFFFFFF03AAAAAAAAAAAAAA800FFFFFFFFF
FFFFFFFFF005AAAAAAAAAAAAAAA00FFFFFFFFF
FFFFFFFFF005AAAAAAAAAAAAAAA00FFFFFFFFF
FFFFFFFFF004AAAAAAAAAAAAAA900FFFFFFFFF
FFFFFFFFFF03AAAAAAAAAAAAAA700FFFFFFFFF
FFFFFFFFFF00AAAAAAAAAAAAAA400FFFFFFFFF
FFFFFFFFFF006AAAAAAAAAAAAA00FFFFFFFFFF
FFFFFFFFFF001AAAAAAAAAAAA400FFFFFFFFFF
FFFFFFFFFFF003AAAAAAAAAA800FFFFFFFFFFF
FFFFFFFFFFFF003AAAAAAAA7000FFFFFFFFFFF
FFFFFFFFF00000007AAAA910000000FFFFFFFF
FFFFFFF000000000000000000000000FFFFFFF
FFFFFF00029AA1000000000006AA50000FFFFF
FFFFF0008AAAAA70000000039AAAA93000FFFF
FFFF003AAAAAAAAA8543479AAAAAAAA700FFFF
FFF001AAAAAAAAAAAAAAAAAAAAAAAAAA600FFF
FFF007AAAAAAAAAAAAAAAAAAAAAAAAAAA00FFF
FFF009AAAAAAAAAAAAAAAAAAAAAAAAAAA500FF
FFF01AAAAAAAAAAAAAAAAAAAAAAAAAAAA800FF
FF005AAAAAAAAAAAAAAAAAAAAAAAAAAAA900FF
FF008AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FF
FF009AAAAAAAAAAAAAAAAAAAAAAAAAAAAA20FF
FF009AAAAAAAAAAAAAAAAAAAAAAAAAAAAA40FF
FF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA60FF
FF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA800F
FF01AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA900F
FF03AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA900F
F005AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00F
F005888888888888888888888888888888800F
F000000000000000000000000000000000000F
F000000000000000000000000000000000000F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_USER(_alias) ENTITY(rectangle,black,user,_alias,OFF USER)
!define OFF_USER(_alias,_label) ENTITY(rectangle,black,user,_label,_alias,OFF USER)
!define OFF_USER(_alias,_label,_shape) ENTITY(_shape,black,user,_label,_alias,OFF USER)
!define OFF_USER(_alias,_label,_shape,_color) ENTITY(_shape,_color,user,_label,_alias,OFF USER)
skinparam folderBackgroundColor<<OFF USER>> White