sprite $users_two [48x40/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF000020000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF0029AAA93000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF003AAAAAAA500FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAA000FFFFFFFFF
FFFFFFFFFFFF00000FFFFFFF006AAAAAAAAA800FFFFFFFFF
FFFFFFFFFF000000000FFFFF009AAAAAAAAAA00FFFFFFFFF
FFFFFFFFF00037762000FFFF00AAAAAAAAAAA00FFFFFFFFF
FFFFFFFF0019AAAAA6000FFF009AAAAAAAAAA00FFFFFFFFF
FFFFFFF000AAAAAAAA500FFF009AAAAAAAAAA00FFFFFFFFF
FFFFFFF005AAAAAAAAA10FFFF04AAAAAAAAA600FFFFFFFFF
FFFFFFF00AAAAAAAAAA600FFF009AAAAAAAA000FFFFFFFFF
FFFFFFF01AAAAAAAAAA800FFF000AAAAAAA100FFFFFFFFFF
FFFFFFF02AAAAAAAAAA800F0000006AAA7000000FFFFFFFF
FFFFFFF01AAAAAAAAAA80000024000000000420000FFFFFF
FFFFFFF00AAAAAAAAAA500019AA810000008AA92000FFFFF
FFFFFFF004AAAAAAAAA0005AAAAAA87578AAAAAA500FFFFF
FFFFFFF0008AAAAAAA4002AAAAAAAAAAAAAAAAAAA300FFFF
FFFFFFF00007AAAAA40007AAAAAAAAAAAAAAAAAAA700FFFF
FFFFF000000025540000005AAAAAAAAAAAAAAAAAAA00FFFF
FFFF000497000000003971019AAAAAAAAAAAAAAAAA20FFFF
FFF0029AAAA4200137AAAA500AAAAAAAAAAAAAAAAA30FFFF
FF002AAAAAAAAAAAAAAAAAA804AAAAAAAAAAAAAAAA500FFF
FF008AAAAAAAAAAAAAAAAAAA10AAAAAAAAAAAAAAAA600FFF
FF00AAAAAAAAAAAAAAAAAAAA709AAAAAAAAAAAAAAA700FFF
FF02AAAAAAAAAAAAAAAAAAAAA07AAAAAAAAAAAAAAA800FFF
FF05AAAAAAAAAAAAAAAAAAAAA02555555555555555400FFF
FF07AAAAAAAAAAAAAAAAAAAAA00000000000000000000FFF
F008AAAAAAAAAAAAAAAAAAAAA10000000000000000000FFF
F009AAAAAAAAAAAAAAAAAAAAA300FFFFFFFFFFFFFFFFFFFF
F009AAAAAAAAAAAAAAAAAAAAA500FFFFFFFFFFFFFFFFFFFF
F00AAAAAAAAAAAAAAAAAAAAAA700FFFFFFFFFFFFFFFFFFFF
F000000000000000000000000000FFFFFFFFFFFFFFFFFFFF
F000000000000000000000000000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_USERS_TWO(_alias) ENTITY(rectangle,black,users_two,_alias,OFF USERS_TWO)
!define OFF_USERS_TWO(_alias,_label) ENTITY(rectangle,black,users_two,_label,_alias,OFF USERS_TWO)
!define OFF_USERS_TWO(_alias,_label,_shape) ENTITY(_shape,black,users_two,_label,_alias,OFF USERS_TWO)
!define OFF_USERS_TWO(_alias,_label,_shape,_color) ENTITY(_shape,_color,users_two,_label,_alias,OFF USERS_TWO)
skinparam folderBackgroundColor<<OFF USERS_TWO>> White