sprite $user_services [46x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF0000000FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0000220000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF001AAAAAA5000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF005AAAAAAAAA00FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF004AAAAAAAAAAA00FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF00AAAAAAAAAAAA400FFFFFFFFFFFFFFFFF
FFFFFFFFFFF008AAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAAAAAA50FFFFFFFFFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAAAAAA80FFFFFFFFFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAAAAAA70FFFFFFFFFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAAAAAA50FFFFFFFFFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFFFFFFFF006AAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFFFFFFFFF00AAAAAAAAAAAA30FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF002AAAAAAAAAA900FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF003AAAAAAAA900FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF0000009AAAAA300000FFFFFFFFFFFFFFFFF
FFFFFFFFF0000000000000000000000FFFFFFFFFFFFFFF
FFFFFFFF0006AA1000000000008AA0000FFFFFFFFFFFFF
FFFFFF0003AAAAA8000000002AAAAA3000F0000FFFFFFF
FFFFFF00AAAAAAAAAA53248AAAAA3002000000000FFFFF
FFFFF008AAAAAAAAAAAAAAAAAAAA05AA30009AA10FFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAA06AAA000AAA10FFFFF
FFFFF05AAAAAAAAAAAAAAAAAAAAA00AAAAAAAAA00F0FFF
FFFF00AAAAAAAAAAAAAAAAAA500001AAAAAAAAA000000F
FFFF00AAAAAAAAAAAAAAAAAA03701AAA71029AAA00800F
FFFF00AAAAAAAAAAAAAAAAA60AAAAAA0000002AAAAA80F
FFFF00AAAAAAAAAAAAAAAAA01AAAAA000000003AAAAA00
FFFF03AAAAAAAAAAAAAAAAA402AAA7000000000AAAA100
FFFF06AAAAAAAAAAAAAAAAAA500AA10000000007AA000F
FFF008AAAAAAAAAAAAAAAAAAA60AA00000000005AA0FFF
FFF00AAAAAAAAAAAAAAAAAAA000AA20000000008AA000F
FFF00AAAAAAAAAAAAAAAAAA207AAA9000000000AAAA500
FFF00AAAAAAAAAAAAAAAAAA10AAAAA100000006AAAAA00
FFF0000000000000000000000AAAAAA2000006AA9AA90F
FFF00000000000000000000001300AAAA657AAAA00000F
FFFFFFFFFFFFFFFFFFFFFFFF000000AAAAAAAAA000000F
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAA00FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF07AAA000AAA40FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF009A20005A800FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF000000F000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000FFF000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_USER_SERVICES(_alias) ENTITY(rectangle,black,user_services,_alias,OFF USER_SERVICES)
!define OFF_USER_SERVICES(_alias,_label) ENTITY(rectangle,black,user_services,_label,_alias,OFF USER_SERVICES)
!define OFF_USER_SERVICES(_alias,_label,_shape) ENTITY(_shape,black,user_services,_label,_alias,OFF USER_SERVICES)
!define OFF_USER_SERVICES(_alias,_label,_shape,_color) ENTITY(_shape,_color,user_services,_label,_alias,OFF USER_SERVICES)
skinparam folderBackgroundColor<<OFF USER_SERVICES>> White