sprite $cd_dvd [48x47/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF00000000000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0000013445432000000FFFFFFFFFFFFFF
FFFFFFFFFFFFF000016AAAAAAAAAA720000FFFFFFFFFFFFF
FFFFFFFFFFFF00019AAAAAAAAAAAAAAA20000FFFFFFFFFFF
FFFFFFFFFFF0007AAAAAAAAAAAAAAAAAA90000FFFFFFFFFF
FFFFFFFFFF0019AAAAAAAAAAAAAAAAAAAAA200FFFFFFFFFF
FFFFFFFFF001AAAAAAAAAAAAAAAAAAAAAAAA300FFFFFFFFF
FFFFFFFF0019AAAAAAAAAAAAAAAAAAAAAAAAA300FFFFFFFF
FFFFFFF0008AAAAAAAAAAAAAAAAAAAAAAAAAA9000FFFFFFF
FFFFFFF006AAAAAAAAAAAAAAAAAAAAAAAAAAAA8000FFFFFF
FFFFFF000AAAAAAAAAAAA975568AAAAAAAAAAAA200FFFFFF
FFFFFF007AAAAAAAAAA9300110028AAAAAAAAAA900FFFFFF
FFFFF000AAAAAAAAAA7017AAAA8205AAAAAAAAAA000FFFFF
FFFFF003AAAAAAAAA803AAAAAAAA605AAAAAAAAA700FFFFF
FFFFF008AAAAAAAAA03AAAAAAAAAA609AAAAAAAAA00FFFFF
FFFFF00AAAAAAAAA40AAAAAAAAAAAA11AAAAAAAAA00FFFFF
FFFFF01AAAAAAAAA04AAAAA98AAAAA70AAAAAAAAA100FFFF
FFFFF01AAAAAAAAA09AAAA5002AAAA909AAAAAAAA200FFFF
FFFFF02AAAAAAAA909AAAA00009AAAA07AAAAAAAA300FFFF
FFFFF01AAAAAAAA909AAAA1000AAAA908AAAAAAAA300FFFF
FFFFF01AAAAAAAAA07AAAA9228AAAA80AAAAAAAAA200FFFF
FFFFF00AAAAAAAAA11AAAAAAAAAAAA50AAAAAAAAA10FFFFF
FFFFF00AAAAAAAAA908AAAAAAAAAA905AAAAAAAAA00FFFFF
FFFFF005AAAAAAAAA209AAAAAAAAA11AAAAAAAAAA00FFFFF
FFFFF001AAAAAAAAAA106AAAAAA800AAAAAAAAAA300FFFFF
FFFFFF00AAAAAAAAAAA4013664102AAAAAAAAAAA000FFFFF
FFFFFF002AAAAAAAAAAA94100038AAAAAAAAAAA600FFFFFF
FFFFFF0009AAAAAAAAAAAAAAAAAAAAAAAAAAAA9000FFFFFF
FFFFFFF001AAAAAAAAAAAAAAAAAAAAAAAAAAAA400FFFFFFF
FFFFFFFF004AAAAAAAAAAAAAAAAAAAAAAAAAA600FFFFFFFF
FFFFFFFFF005AAAAAAAAAAAAAAAAAAAAAAAA700FFFFFFFFF
FFFFFFFFFF005AAAAAAAAAAAAAAAAAAAAAA7000FFFFFFFFF
FFFFFFFFFFF003AAAAAAAAAAAAAAAAAAAA5000FFFFFFFFFF
FFFFFFFFFFF00008AAAAAAAAAAAAAAAAA1000FFFFFFFFFFF
FFFFFFFFFFFF000018AAAAAAAAAAAA920000FFFFFFFFFFFF
FFFFFFFFFFFFFF00001269AAAA97310000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF0000000000000000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF0000000000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_CD_DVD(_alias) ENTITY(rectangle,black,cd_dvd,_alias,OFF CD_DVD)
!define OFF_CD_DVD(_alias,_label) ENTITY(rectangle,black,cd_dvd,_label,_alias,OFF CD_DVD)
!define OFF_CD_DVD(_alias,_label,_shape) ENTITY(_shape,black,cd_dvd,_label,_alias,OFF CD_DVD)
!define OFF_CD_DVD(_alias,_label,_shape,_color) ENTITY(_shape,_color,cd_dvd,_label,_alias,OFF CD_DVD)
skinparam folderBackgroundColor<<OFF CD_DVD>> White