sprite $data_jack [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF00000000000000000000000000000000000FFFFFF
FFFFFF000000000000000000000000000000000000FFFFFF
FFFFF00025555555555555555555555555555554100FFFFF
FFFFF006AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA300FFFF
FFFF001AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA900FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF003AAAAA7555555555555555555555558AAAAA00FFFF
FFFF003AAAAA3000000000000000000000006AAAAA00FFFF
FFFF003AAAAA3088603012040503011088706AAAAA00FFFF
FFFF003AAAAA31AA8040221607040221AA906AAAAA00FFFF
FFFF003AAAAA31AA9575776859585666AA906AAAAA00FFFF
FFFF003AAAAA31AAAAAAAAAAAAAAAAAAAA906AAAAA00FFFF
FFFF003AAAAA31AAAAAAAAAAAAAAAAAAAA906AAAAA00FFFF
FFFF003AAAAA31AAAAAAAAAAAAAAAAAAAA906AAAAA00FFFF
FFFF003AAAAA31AAAAAAAAAAAAAAAAAAAA906AAAAA00FFFF
FFFF003AAAAA31AAAAAAAAAAAAAAAAAAAA906AAAAA00FFFF
FFFF003AAAAA31AAAAAAAAAAAAAAAAAAAA906AAAAA00FFFF
FFFF003AAAAA31AAAAAAAAAAAAAAAAAAAA906AAAAA00FFFF
FFFF003AAAAA31AAAAAAAAAAAAAAAAAAAA906AAAAA00FFFF
FFFF003AAAAA3055555AAAAAAAAAA95555406AAAAA00FFFF
FFFF003AAAAA3000000AAAAAAAAAA80000006AAAAA00FFFF
FFFF003AAAAA9999930778AAAAA776059999AAAAAA00FFFF
FFFF003AAAAAAAAAA40001AAAA900006AAAAAAAAAA00FFFF
FFFF003AAAAAAAAAA866004444402669AAAAAAAAAA00FFFF
FFFF003AAAAAAAAAAAAA100000003AAAAAAAAAAAAA00FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF0009AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF002799999999999999999999999999999996000FFFF
FFFFFF0000000000000000000000000000000000000FFFFF
FFFFFFF00000000000000000000000000000000000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATA_JACK(_alias) ENTITY(rectangle,black,data_jack,_alias,OFF DATA_JACK)
!define OFF_DATA_JACK(_alias,_label) ENTITY(rectangle,black,data_jack,_label,_alias,OFF DATA_JACK)
!define OFF_DATA_JACK(_alias,_label,_shape) ENTITY(_shape,black,data_jack,_label,_alias,OFF DATA_JACK)
!define OFF_DATA_JACK(_alias,_label,_shape,_color) ENTITY(_shape,_color,data_jack,_label,_alias,OFF DATA_JACK)
skinparam folderBackgroundColor<<OFF DATA_JACK>> White