sprite $device_headset [41x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00000000000000FFFFFFFFFFFFF
FFFFFFFFFFFFF0000146776400000FFFFFFFFFFFF
FFFFFFFFFFF000279AAAAAAAA961000FFFFFFFFFF
FFFFFFFFFF0006AAAAA9889AAAAA5000FFFFFFFFF
FFFFFFFFF0019AA96200000027AAA7000FFFFFFFF
FFFFFFFF000AAA50000000000007AA7000FFFFFFF
FFFFFFFF007AA20000FFFFF000004AA400FFFFFFF
FFFFFFF003AA3000FFFFFFFFFF0006AA10FFFFFFF
FFFFFFF008A9000FFFFFFFFFFFF000AA500FFFFFF
FFFFFFF02AA200FFFFFFFFFFFFFF005A900FFFFFF
FFFFFF006A900FFFFFFFFFFFFFFF000AA30FFFFFF
FFFFFF008A700FFFFFFFFFFFFFFFF008A60FFFFFF
FFFFFF009A400FFFFFFFFFFFFFFFF007A800FFFFF
FFFFF000AA300FFFFFFFFFFFFFFFF005A900FFFFF
FFFFF001AA100000FFFFFFFFFF000004A900FFFFF
FFFFF001AA1001000FFFFFFFF0001003AA00FFFFF
FFFFF002AA17AA700FFFFFFFF009AA33AA00FFFFF
FFFFF002AAAAAA900FFFFFFFF00AAAA9AA00FFFFF
FFFFF002AAAAAAA00FFFFFFFF00AAAAAAA00FFFFF
FFFFF002AAAAAAA00FFFFFFFF00AAAAAAA00FFFFF
FFFFF002AAAAAAA00FFFFFFFF00AAAAAAA00FFFFF
FFFFF0009AAAAAA00FFFFFFFF00AAAAAA700FFFFF
FFFFFF000AAAAAA00FFFFFFFF00AAAAA6000FFFFF
FFFFFFF00AAAAAA00FFFFFFFF00AAAAA100FFFFFF
FFFFFFF00A6AAA900FFFFFFFF00AAAA500FFFFFFF
FFFFFFF00A26AA800FFFFFFFF00AAA6000FFFFFFF
FFFFFFF00A2028300FFFFFFFF00582000FFFFFFFF
FFFFFFF008400000FFFFFFFFF0000000FFFFFFFFF
FFFFFFF007600000FFFFFFFFFF00000FFFFFFFFFF
FFFFFFF004800FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF01A100FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF0078000000000000000FFFFFFFFFFFFFF
FFFFFFFF001A500000000000000FFFFFFFFFFFFFF
FFFFFFFFF001A9302AAAAAAA9100FFFFFFFFFFFFF
FFFFFFFFF00016AAAAAAAAAAA600FFFFFFFFFFFFF
FFFFFFFFFF0000014AAAAAAAA200FFFFFFFFFFFFF
FFFFFFFFFFFFF00000222222000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFF00000000000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DEVICE_HEADSET(_alias) ENTITY(rectangle,black,device_headset,_alias,OFF DEVICE_HEADSET)
!define OFF_DEVICE_HEADSET(_alias,_label) ENTITY(rectangle,black,device_headset,_label,_alias,OFF DEVICE_HEADSET)
!define OFF_DEVICE_HEADSET(_alias,_label,_shape) ENTITY(_shape,black,device_headset,_label,_alias,OFF DEVICE_HEADSET)
!define OFF_DEVICE_HEADSET(_alias,_label,_shape,_color) ENTITY(_shape,_color,device_headset,_label,_alias,OFF DEVICE_HEADSET)
skinparam folderBackgroundColor<<OFF DEVICE_HEADSET>> White