sprite $device_bluetooth [42x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF00000000000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFF000011111100000FFFFFFFFFFFFFF
FFFFFFFFFFFF0005AAAAAAAA8200FFFFFFFFFFFFFF
FFFFFFFFFF00009AAAAAAAAAAA3000FFFFFFFFFFFF
FFFFFFF0000007AAA7554569AAA000000FFFFFFFFF
FFFFF00002610AAA000000006AA70620000FFFFFFF
FFF00005AAA04AA1000000000AAA08AA51000FFFFF
FF0004AAAA909AA00004100007AA04AAAA5000FFFF
F0007AAAAA709AA0000A910004AA21AAAAA8000FFF
F007AAAAA820AA80000AA91002AA408AAAAA800FFF
F01AAAA92000AA70200A699001AA50028AAAA500FF
F01AAA600000AA60A80A44A400AA500005AAAA00FF
F00495000F00AA603A9A8A6000AA50F0008AAA10FF
F0000000FF00AA6002AAA50001AA40FF009AAA20FF
FFF0000FFF00AA80009AA30002AA300005AAAA00FF
FFFFFFFFFF00AAA009AAAA4004AA10019AAAA600FF
FFFFFFFFFF009AA0AA1A46A406AA029AAAAAA000FF
FFFFFFFFFF009AA0500A48A208AAAAAAAAAA000FFF
FFFFFFFFFFF08AA0000AAA2009AAAAAAAA7000FFFF
FFFFFFFFFFF05AA6000AA2001AAAAAAA90000FFFFF
FFFFFFFFFFF02AAA000930005AAAAA50000FFFFFFF
FFFFFFFFFFF00AAA100000009AA800000FFFFFFFFF
FFFFFFFFFFF00AAA90000003AAA400FFFFFFFFFFFF
FFFFFFFFFFF00AAAA2000009AAA00FFFFFFFFFFFFF
FFFFFFFFFFFF07AAAA00007AAAA00FFFFFFFFFFFFF
FFFFFFFFFFFF03AAAAA328AAAAA00FFFFFFFFFFFFF
FFFFFFFFFFFF00AAAAAAAAAAAA600FFFFFFFFFFFFF
FFFFFFFFFFFF00AAAAAAAAAAAA20FFFFFFFFFFFFFF
FFFFFFFFFFFFF07AAAAAAAAAAA00FFFFFFFFFFFFFF
FFFFFFFFFFFFF01AAAAAAAAAA900FFFFFFFFFFFFFF
FFFFFFFFFFFFF00AAAAAAAAAA400FFFFFFFFFFFFFF
FFFFFFFFFFFFF008AAAAAAAAA10FFFFFFFFFFFFFFF
FFFFFFFFFFFFFF02AAAAAAAA800FFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00AAAAAAAA300FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF05AAAAAAA00FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF00AAAAAA400FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF004AAAA900FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF009AAA200FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF0008A300FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF000000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DEVICE_BLUETOOTH(_alias) ENTITY(rectangle,black,device_bluetooth,_alias,OFF DEVICE_BLUETOOTH)
!define OFF_DEVICE_BLUETOOTH(_alias,_label) ENTITY(rectangle,black,device_bluetooth,_label,_alias,OFF DEVICE_BLUETOOTH)
!define OFF_DEVICE_BLUETOOTH(_alias,_label,_shape) ENTITY(_shape,black,device_bluetooth,_label,_alias,OFF DEVICE_BLUETOOTH)
!define OFF_DEVICE_BLUETOOTH(_alias,_label,_shape,_color) ENTITY(_shape,_color,device_bluetooth,_label,_alias,OFF DEVICE_BLUETOOTH)
skinparam folderBackgroundColor<<OFF DEVICE_BLUETOOTH>> White