sprite $device_microphone [48x39/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000000FFF
FFFFFFFFFFFFFFFFFFFFFFFFF000000000059AAAAAA20FFF
FFFFFFFFFFFFFFFFFFFFFFF00000123445AAAAAAAAA30FFF
FFFFFFFFFFFFFFFFFFFFF000015AAAAAAAAAAAAAAAA30FFF
FFFFFFFFFFFFFFFFFFFF00007AA94000007AAAAAAAA30FFF
FFFFFFFFFFFFFFFFFFF0003AA60000000000588888810FFF
FFFFFFFFFFFFFFFFFF0004A9000000FFF000000000000FFF
FFFFFFFFFFFFFFFFF0005A70000FFFFFFFF000000000FFFF
FFFFFFFFFFFFFFFF0005A7000FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0005A7000FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0005A7000FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF0005A7000FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF00F0005A7000FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF0000005A8000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF0000005A8000FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0005306A7000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFF0005AA9A6000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF0005AAAA7000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF0005AAAAAA300FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF0004AAAAAAA3000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF0008AAAAAAA30000000000FFFFFFFFFFFFFFFFFFFFFF
FFF0007A7AAAAAAA322221000000FFFFFFFFFFFFFFFFFFFF
FFF0008700AAAAAAAAAAAAA9510000FFFFFFFFFFFFFFFFFF
FFFF0000008AAAAAAAAAAAAAAA91000FFFFFFFFFFFFFFFFF
FFFFF00002AAAAAAAAAAAAAAAAAA400FFFFFFFFFFFFFFFFF
FFFFFF000AAAAAAAAAAAAAAAAAAAA30FFFFFFFFFFFFFFFFF
FFFFFF002AAAAAAAAAAAAAAAAAAAA700FFFFFFFFFFFFFFFF
FFFFFF00000000000000000000000000FFFFFFFFFFFFFFFF
FFFFFF00000000000000000000000000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DEVICE_MICROPHONE(_alias) ENTITY(rectangle,black,device_microphone,_alias,OFF DEVICE_MICROPHONE)
!define OFF_DEVICE_MICROPHONE(_alias,_label) ENTITY(rectangle,black,device_microphone,_label,_alias,OFF DEVICE_MICROPHONE)
!define OFF_DEVICE_MICROPHONE(_alias,_label,_shape) ENTITY(_shape,black,device_microphone,_label,_alias,OFF DEVICE_MICROPHONE)
!define OFF_DEVICE_MICROPHONE(_alias,_label,_shape,_color) ENTITY(_shape,_color,device_microphone,_label,_alias,OFF DEVICE_MICROPHONE)
skinparam folderBackgroundColor<<OFF DEVICE_MICROPHONE>> White