sprite $device_printer [48x41/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF000000000000000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0000000000000000000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAA100FFFFFFFFFFFFF
FFFFFFFFFFFFFF00A977777777777778A00FFFFFFFFFFFFF
FFFFFFFFFFFFFF00A700000000000002A00FFFFFFFFFFFFF
FFFFFFFFFFFFFF00A700000000000002A00FFFFFFFFFFFFF
FFFFFFFFFFFFFF00A700000000000002A00FFFFFFFFFFFFF
FFFFFFFFFFFFFF00A700000000000002A00FFFFFFFFFFFFF
FFFFFFFFFFFFFF00A700000000000002A00FFFFFFFFFFFFF
FFFFFFFFFFFFFF00A700000000000002A00FFFFFFFFFFFFF
FFFFFFFFFFFFFF00A700000000000002A00FFFFFFFFFFFFF
FFFFFFFFFF000000A700000000000002A000000FFFFFFFFF
FFFFFFF000000000A700000000000002A00000000FFFFFFF
FFFFFF0005999999AA9999999999999AA999999400FFFFFF
FFFFF000AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFF00AAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA700FFFF
FFFFF00AA006AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF02AA409AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF02AAAAAAAAAA844444444444446AAAAAAAAAA00FFFF
FFFFF02AAAAAAAAAA700000000000002AAAAAAAAAA00FFFF
FFFFF02AAAAAAAAAA7006AAAAAAA9002AAAAAAAAAA00FFFF
FFFFF00000000000A700000000000002A00000000000FFFF
FFFFF00000000000A7006AAAAAAA8002A00000000000FFFF
FFFFFFFFFFFFFF00A700000000000002A00FFFFFFFFFFFFF
FFFFFFFFFFFFFF00A700000000000002A00FFFFFFFFFFFFF
FFFFFFFFFFFFFF005AAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFFFFFFFFFFFF0002222222222222100FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00000000000000000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DEVICE_PRINTER(_alias) ENTITY(rectangle,black,device_printer,_alias,OFF DEVICE_PRINTER)
!define OFF_DEVICE_PRINTER(_alias,_label) ENTITY(rectangle,black,device_printer,_label,_alias,OFF DEVICE_PRINTER)
!define OFF_DEVICE_PRINTER(_alias,_label,_shape) ENTITY(_shape,black,device_printer,_label,_alias,OFF DEVICE_PRINTER)
!define OFF_DEVICE_PRINTER(_alias,_label,_shape,_color) ENTITY(_shape,_color,device_printer,_label,_alias,OFF DEVICE_PRINTER)
skinparam folderBackgroundColor<<OFF DEVICE_PRINTER>> White