sprite $device_webcam_hd [42x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0000000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF00000000000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFF00018AAAAA81000FFFFFFFFFFFFFFFF
FFFFFFFFFF002AAAAAAAAAAA2000FFFFFFFFFFFFFF
FFFFFFFF0007AAAAAAAAAAAAA700FFFFFFFFFFFFFF
FFFFFFFF008AAAAAAAAAAAAAAA800FFFFFFFFFFFFF
FFFFFFF008AAAAAAAAAAAAAAAAA800FFFFFFFFFFFF
FFFFFF003AAAAAAAAAAAAAAAAAAA300FFFFFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF003AA93333333333333338AA400FFFFFFFFFF
FFFFF008AA00000000000000001AA900FFFFFFFFFF
FFFFF00AAA000000003000000009AA00FFFFFFFFFF
FFFFF01AA70000002AAA20000007AA10FFFFFFFFFF
FFFFF01AA50000007AAA80000005AA20FFFFFFFFFF
FFFFF01AA50000007AAA80000005AA20FFFFFFFFFF
FFFFF01AA70000002AAA20000007AA10FFFFFFFFFF
FFFFF00AAA000000003000000009AA00FFFFFFFFFF
FFFFF008AA00000000000000001AA900FFFFFFFFFF
FFFFF003AA83333333333333338AA400FFFFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFFF004AAAAAAAAAAAAAAAAAAA30FFFFFFFFFFFF
FFFFFFF008AAAAAAAAAAAAAAAAA800FFFFFFFFFFFF
FFFFFFFF009AAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFFFFFF007AAAAAAAAAAAAA700FFFFFFFFFFFFFF
FFFFFFFFFF003AAAAAAAAAAA3000FFFFFFFFFFFFFF
FFFFFFFFFF000027AAAAA8200000FFFFFFFFFFFFFF
FFFFFFFF0008A70000000006A9000FFFFFFFFFFFFF
FFFFFF0001AAAAAA96569AAAAAA1000FFFFFFFFFFF
FFFFF0005AAAAAAAAAAAAAAAAAAA5000FFFFFFFFFF
FFFFF03AAAAAAAAAAAA9999999999820000000FFFF
FFFFF07AAAAAAAAAAAA000000000000000000000FF
FFFFF07AAAAAAAAAAA90998000399999999998200F
FFFFF06AAAAAAAAAAA50AA60006AAAAAAAAAAAA600
FFFFF000000000000000AA30008AA00444002AAA00
FFFFFF00000000000004AAAAAAAAA02AA8000AAA20
FFFFFFFFFFFFFFFFF009AA8888AA404AA3000AAA00
FFFFFFFFFFFFFFFFF00AA70003AA007AA0049AA600
FFFFFFFFFFFFFFFFF00AA50006AA00AAAAAAAA300F
FFFFFFFFFFFFFFFFF01771000677008888861000FF
FFFFFFFFFFFFFFFFF000000000000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DEVICE_WEBCAM_HD(_alias) ENTITY(rectangle,black,device_webcam_hd,_alias,OFF DEVICE_WEBCAM_HD)
!define OFF_DEVICE_WEBCAM_HD(_alias,_label) ENTITY(rectangle,black,device_webcam_hd,_label,_alias,OFF DEVICE_WEBCAM_HD)
!define OFF_DEVICE_WEBCAM_HD(_alias,_label,_shape) ENTITY(_shape,black,device_webcam_hd,_label,_alias,OFF DEVICE_WEBCAM_HD)
!define OFF_DEVICE_WEBCAM_HD(_alias,_label,_shape,_color) ENTITY(_shape,_color,device_webcam_hd,_label,_alias,OFF DEVICE_WEBCAM_HD)
skinparam folderBackgroundColor<<OFF DEVICE_WEBCAM_HD>> White