sprite $device_phone_digital [48x42/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF000000FF0000000000000000000000000FFFFFFF
FFFFFF000000000000000000000000000000000000FFFFFF
FFFFFF0069AA940029AAAAAAAAAAAAAAAAAAAAA9100FFFFF
FFFFF006AAAAAA10AAAAAAAAAAAAAAAAAAAAAAAA700FFFFF
FFFFF008AAAAAA40AAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF008AAAAAA50AAAA21111111111111115AAA800FFFFF
FFFFF008AAAAAA40AAAA10000000000000004AAA800FFFFF
FFFFF008AAAAAA40AAAA10000000000000004AAA800FFFFF
FFFFF007AAAAAA30AAAA10000000000000004AAA800FFFFF
FFFFF007AAAAAA30AAAA10000000000000004AAA800FFFFF
FFFFF007AAAAAA30AAAA10000000000000004AAA800FFFFF
FFFFF007AAAAAA30AAAA43333333333333337AAA800FFFFF
FFFFF007AAAAAA20AAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF006AAAAAA20AAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF006AAAAAA20AAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF006AAAAAA20AAAAA4225A6223A7222AAAAA800FFFFF
FFFFF006AAAAAA20AAAAA1002A3001A50009AAAA800FFFFF
FFFFF006AAAAAA20AAAAA8778A9778AA777AAAAA800FFFFF
FFFFF006AAAAAA30AAAAA9889AA889AA889AAAAA800FFFFF
FFFFF006AAAAAA30AAAAA1002A3001A50009AAAA800FFFFF
FFFFF007AAAAAA30AAAAA3114A5112A6111AAAAA800FFFFF
FFFFF007AAAAAA30AAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF007AAAAAA40AAAAA5446A7445A8444AAAAA800FFFFF
FFFFF007AAAAAA40AAAAA1002A3001A50009AAAA800FFFFF
FFFFF008AAAAAA50AAAAA7557A8556A9556AAAAA800FFFFF
FFFFF008AAAAAA50AAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF008AAAAAA60AAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF008AAAAAA50AAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF008AAAAAA40AAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF003AAAAA9008AAAAAAAAAAAAAAAAAAAAAAA400FFFFF
FFFFFF000465300005666666666666666666666300FFFFFF
FFFFFFF0000000000000000000000000000000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DEVICE_PHONE_DIGITAL(_alias) ENTITY(rectangle,black,device_phone_digital,_alias,OFF DEVICE_PHONE_DIGITAL)
!define OFF_DEVICE_PHONE_DIGITAL(_alias,_label) ENTITY(rectangle,black,device_phone_digital,_label,_alias,OFF DEVICE_PHONE_DIGITAL)
!define OFF_DEVICE_PHONE_DIGITAL(_alias,_label,_shape) ENTITY(_shape,black,device_phone_digital,_label,_alias,OFF DEVICE_PHONE_DIGITAL)
!define OFF_DEVICE_PHONE_DIGITAL(_alias,_label,_shape,_color) ENTITY(_shape,_color,device_phone_digital,_label,_alias,OFF DEVICE_PHONE_DIGITAL)
skinparam folderBackgroundColor<<OFF DEVICE_PHONE_DIGITAL>> White