sprite $device_webcam [39x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0000000000FFFFFFFFFFFFFF
FFFFFFFFFFFFF00000121100000FFFFFFFFFFFF
FFFFFFFFFFF000048AAAAAA72000FFFFFFFFFFF
FFFFFFFFFF0004AAAAAAAAAAA92000FFFFFFFFF
FFFFFFFFF0019AAAAAAAAAAAAAA5000FFFFFFFF
FFFFFFFF001AAAAAAAAAAAAAAAAA700FFFFFFFF
FFFFFFFF009AAAAAAAAAAAAAAAAAA500FFFFFFF
FFFFFFF007AAAAAAAAAAAAAAAAAAAA200FFFFFF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAA900FFFFFF
FFFFFF007AA86666666666666666AAA30FFFFFF
FFFFFF00AAA000000000000000003AA700FFFFF
FFFFFF03AA7000000000000000000AAA00FFFFF
FFFFF006AA30000000599200000009AA10FFFFF
FFFFF007AA10000003AAAA00000007AA20FFFFF
FFFFF007AA10000006AAAA10000006AA30FFFFF
FFFFF007AA10000003AAAA00000006AA20FFFFF
FFFFF006AA200000006AA200000009AA10FFFFF
FFFFFF04AA6000000000000000000AAA00FFFFF
FFFFFF00AAA000000000000000002AA800FFFFF
FFFFFF008AA75555555555555555AAA30FFFFFF
FFFFFFF03AAAAAAAAAAAAAAAAAAAAA900FFFFFF
FFFFFFF008AAAAAAAAAAAAAAAAAAAA300FFFFFF
FFFFFFFF00AAAAAAAAAAAAAAAAAAA700FFFFFFF
FFFFFFFF001AAAAAAAAAAAAAAAAA800FFFFFFFF
FFFFFFFFF001AAAAAAAAAAAAAAA7000FFFFFFFF
FFFFFFFFFF0007AAAAAAAAAAAA4000FFFFFFFFF
FFFFFFFFFF0000179AAAAAA850000FFFFFFFFFF
FFFFFFFFF00067200023320004A3000FFFFFFFF
FFFFFFF00007AAA963212247AAAA5000FFFFFFF
FFFFFF0003AAAAAAAAAAAAAAAAAAA81000FFFFF
FFFFF0028AAAAAAAAAAAAAAAAAAAAAA6000FFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF006888888888888888888888888400FFFF
FFFFF00000000000000000000000000000FFFFF
FFFFFF000000000000000000000000000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DEVICE_WEBCAM(_alias) ENTITY(rectangle,black,device_webcam,_alias,OFF DEVICE_WEBCAM)
!define OFF_DEVICE_WEBCAM(_alias,_label) ENTITY(rectangle,black,device_webcam,_label,_alias,OFF DEVICE_WEBCAM)
!define OFF_DEVICE_WEBCAM(_alias,_label,_shape) ENTITY(_shape,black,device_webcam,_label,_alias,OFF DEVICE_WEBCAM)
!define OFF_DEVICE_WEBCAM(_alias,_label,_shape,_color) ENTITY(_shape,_color,device_webcam,_label,_alias,OFF DEVICE_WEBCAM)
skinparam folderBackgroundColor<<OFF DEVICE_WEBCAM>> White