sprite $device_phone_traditional [48x44/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF000000000000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF000000000000000000000FFFFFFFFFFFFF
FFFFFFFFFFF000000001234444321000000000FFFFFFFFFF
FFFFFFFF0000025789AAAAAAAAAAAAA875200000FFFFFFFF
FFFFFFF000038AAAAAAAAAAAAAAAAAAAAAA940000FFFFFFF
FFFFFF00019AAAAAAAAAAAAAAAAAAAAAAAAAA92000FFFFFF
FFFFFF002AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA300FFFFFF
FFFFF002AAAAAAAAA655555555555569AAAAAAAA300FFFFF
FFFF0008AAAAAAA912444444444444306AAAAAAA900FFFFF
FFFF002AAAAAAAA24AAAAAAAAAAAAAA71AAAAAAAA400FFFF
FFFF006AAAAAAAA08AAAAAAAAAAAAAAA0AAAAAAAA700FFFF
FFFF008AAAAAAAA08AAAAAAAAAAAAAAA0AAAAAAAA900FFFF
FFFF008AAAAAAAA08AAAAAAAAAAAAAAA0AAAAAAAA900FFFF
FFFF003AAAAAAA909AA669966A966AAA16AAAAAAA500FFFF
FFFF000134455405AA800660075008AA70355444200FFFFF
FFFFFF000000048AAA800660075008AAA9400000000FFFFF
FFFFFFFFFFF00AAAAAA669966A966AAAAAA10FFFFFFFFFFF
FFFFFFFFFF003AAAAAA559955A955AAAAAA20FFFFFFFFFFF
FFFFFFFFFF006AAAAA800660075008AAAAA600FFFFFFFFFF
FFFFFFFFF0008AAAAA800660075009AAAAA900FFFFFFFFFF
FFFFFFFFF001AAAAAAA77AA77AA77AAAAAAA20FFFFFFFFFF
FFFFFFFFF005AAAAAA94489449844AAAAAAA500FFFFFFFFF
FFFFFFFFF008AAAAAA800660075008AAAAAA800FFFFFFFFF
FFFFFFFF000AAAAAAA800660075009AAAAAAA000FFFFFFFF
FFFFFFFF002AAAAAAAA99AA99AA99AAAAAAAA400FFFFFFFF
FFFFFFFF007AAAAAAAAAAAAAAAAAAAAAAAAAA700FFFFFFFF
FFFFFFFF009AAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFFFFF
FFFFFFFF009AAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFFFFF
FFFFFFFF009AAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFFFFF
FFFFFFFF008AAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFFFFF
FFFFFFFF002AAAAAAAAAAAAAAAAAAAAAAAAAA300FFFFFFFF
FFFFFFFF00037999999999999999999999973000FFFFFFFF
FFFFFFFFF00000000000000000000000000000FFFFFFFFFF
FFFFFFFFFFF00000000000000000000000000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DEVICE_PHONE_TRADITIONAL(_alias) ENTITY(rectangle,black,device_phone_traditional,_alias,OFF DEVICE_PHONE_TRADITIONAL)
!define OFF_DEVICE_PHONE_TRADITIONAL(_alias,_label) ENTITY(rectangle,black,device_phone_traditional,_label,_alias,OFF DEVICE_PHONE_TRADITIONAL)
!define OFF_DEVICE_PHONE_TRADITIONAL(_alias,_label,_shape) ENTITY(_shape,black,device_phone_traditional,_label,_alias,OFF DEVICE_PHONE_TRADITIONAL)
!define OFF_DEVICE_PHONE_TRADITIONAL(_alias,_label,_shape,_color) ENTITY(_shape,_color,device_phone_traditional,_label,_alias,OFF DEVICE_PHONE_TRADITIONAL)
skinparam folderBackgroundColor<<OFF DEVICE_PHONE_TRADITIONAL>> White