sprite $device_roundtable [35x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF000000000FFFFFFFFFFFFF
FFFFFFFFFFFF000001100000FFFFFFFFFFF
FFFFFFFFFFF006AAAAAAAA10FFFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAA600FFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAA600FFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAA600FFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAA600FFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAA600FFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAA600FFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAA600FFFFFFFFFF
FFFFFFFFFFF008AAAAAAA910FFFFFFFFFFF
FFFFFFFFFFF000AAAAA72000FFFFFFFFFFF
FFFFFFFFFFF001AAA500000FFFFFFFFFFFF
FFFFFFFFFFF00AA80000FFFFFFFFFFFFFFF
FFFFFFFFFF007A6000FFFFFFFFFFFFFFFFF
FFFFFFFFF002A900FFFFFFFFFFFFFFFFFFF
FFFFFFFFF00AA20FFFFFFFFFFFFFFFFFFFF
FFFFFFFF005A700FFFFFFFFFFFFFFFFFFFF
FFFFFFFF00AA00FFFFFFFFFFFFFFFFFFFFF
FFFFFFF006A600FFFFFFFFFFFFFFFFFFFFF
FFFFFFF00AA00FFFFFFFFFFFFFFFFFFFFFF
FFFFFF004A800FFFFFFFFFFFFFFFFFFFFFF
FFFFFF008A00FFFFFFFFFFFFFFFFFFFFFFF
FFFFFF01AA00FFFFFFFFFFFFFFFFFFFFFFF
FFFFFF04A40FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF08A10FFFFFFFFFFFFFFFFFFFFFFFF
FFFFF00AA00FFFFFFFFFFFFFFFFFFFFFFFF
FFFFF01A600FF0000000000FFFFFFFFFFFF
FFFFF04A30000002444300000FFFFFFFFFF
FFFF009A100038AAAAAAA9500000FFFFFFF
FFFF00AA017AAAAAAAAAAAAA9400000FFFF
FF0004AAAAAAAAAAAAAAAAAAAAAA50000FF
F0018AAAAAAAAAAAAAAAAAAAAAAAAAA4000
F04AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
F03AAAAAAAAAAAAAAAAAAAAAAAAAAAAA900
F00159AAAAAAAAAAAAAAAAAAAAAAAA73000
FF00000114679AAAAAAAAA987531000000F
FFFFFF000000000000000000000000FFFFF
FFFFFFFFFFFFFF0000000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DEVICE_ROUNDTABLE(_alias) ENTITY(rectangle,black,device_roundtable,_alias,OFF DEVICE_ROUNDTABLE)
!define OFF_DEVICE_ROUNDTABLE(_alias,_label) ENTITY(rectangle,black,device_roundtable,_label,_alias,OFF DEVICE_ROUNDTABLE)
!define OFF_DEVICE_ROUNDTABLE(_alias,_label,_shape) ENTITY(_shape,black,device_roundtable,_label,_alias,OFF DEVICE_ROUNDTABLE)
!define OFF_DEVICE_ROUNDTABLE(_alias,_label,_shape,_color) ENTITY(_shape,_color,device_roundtable,_label,_alias,OFF DEVICE_ROUNDTABLE)
skinparam folderBackgroundColor<<OFF DEVICE_ROUNDTABLE>> White