sprite $device_stylus [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000024000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00002AA4000F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00062AAAA400F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0006AAAAAAA100
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0006AAAAAAA2000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0006AAAAAAA2000F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0006AAAAAAA2000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0006AAAAAAA2000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0006AAAAAAA2000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF0006AAAAAAA2000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF0006AAAAAAA2000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF002AAAAAAA2000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF001AAAAAA2000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF001AAAAAA2000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF002AAAAAA2000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF0002AAAAAA2000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF0001AAAAAA2000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF001AAAAAA2000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF001AAAAAA3000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF0002AAAAAA2000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF0001AAAAAA2000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF000AAAAAA2000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF000AAAAAA3000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF001AAAAAA3000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00019AAAAA2000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF00019AAAAA3000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF000AA81AA2000FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF0009AAAAA3000FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF0019A93AA3000FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF00019A9AAA3000FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF00019A92AA3000FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF0009AAAAA3000FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF0019A82AA3000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0019AAAAA3000FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF00019AAAAA3000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF0009AAAAA3000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF008AAAAA3000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF002AAAAA3000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF000AAAAA3000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF003AAA82000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
F000AAA20000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
F006A400000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
F00710000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
F000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DEVICE_STYLUS(_alias) ENTITY(rectangle,black,device_stylus,_alias,OFF DEVICE_STYLUS)
!define OFF_DEVICE_STYLUS(_alias,_label) ENTITY(rectangle,black,device_stylus,_label,_alias,OFF DEVICE_STYLUS)
!define OFF_DEVICE_STYLUS(_alias,_label,_shape) ENTITY(_shape,black,device_stylus,_label,_alias,OFF DEVICE_STYLUS)
!define OFF_DEVICE_STYLUS(_alias,_label,_shape,_color) ENTITY(_shape,_color,device_stylus,_label,_alias,OFF DEVICE_STYLUS)
skinparam folderBackgroundColor<<OFF DEVICE_STYLUS>> White