sprite $device_fax [48x40/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF0000000000000000000FFFFFFFFFFFFF
FFFFFFFFFFFFFFF000444444444444444200FFFFFFFFFFFF
FFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAA30FFFFFFFFFFFF
FFFFFFFFFFFFFFF00A000000000000000A800FFFFFFFFFFF
FFFFFFFFFFFFFFF00A000000000000000A800FFFFFFFFFFF
FFFFFFFFFFFFFFF00A001222210000000A800FFFFFFFFFFF
FFFFFFFFFFFFFFF00A003777760000000A800FFFFFFFFFFF
FFFFFFFFFFFFFFF00A000000000000000A800FFFFFFFFFFF
FFFFFFFFFFFFFFF00A004999999999900A800FFFFFFFFFFF
FFFFFF0000000FF00A000000000000000A800FFFFFFFFFFF
FFFFF002564000F00A002666666666600A800FFFFFFFFFFF
FFFFF07AAAAA00F00A001444444444400A800FFFFFFFFFFF
FFFFF08AAAAA10000A000000000000000A8000000FFFFFFF
FFFFF08AAAAA10222A322222222222222A92222000FFFFFF
FFFFF08AAAAA03AAAAAAAAAAAAAAAAAAAAAAAAAA600FFFFF
FFFFF07AAAAA04AAAAAAAAAAAAAAAAAAAAAAAAAAA600FFFF
FFFFF06AAAAA04AAAAAAAAAAAAAAAAAAAAAAAA13AA00FFFF
FFFFF06AAAAA04AAAAAAAAAAAAAAAAAAAAAAAA13AA00FFFF
FFFFF06AAAAA04AAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF06AAAAA05AAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF06AAAAA04AAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF06AAAAA04AAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF06AAAAA04AAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF07AAAAA04AAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF08AAAAA13AAAA000000000000000AAAAAAAAA00FFFF
FFFFF08AAAAA13AAAA000000000000000AAAAAAAAA00FFFF
FFFFF08AAAAA11444A000000000000000A9444444400FFFF
FFFFF03AAAA800000A000000000000000A8000000000FFFF
FFFFF000110000F00A000000000000000A80FFFFFFFFFFFF
FFFFFF0000000FF00A322222222222222A70FFFFFFFFFFFF
FFFFFFFFFFFFFFF008AAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFFFFFFFFFFFF00000000000000000000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFF00000000000000000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DEVICE_FAX(_alias) ENTITY(rectangle,black,device_fax,_alias,OFF DEVICE_FAX)
!define OFF_DEVICE_FAX(_alias,_label) ENTITY(rectangle,black,device_fax,_label,_alias,OFF DEVICE_FAX)
!define OFF_DEVICE_FAX(_alias,_label,_shape) ENTITY(_shape,black,device_fax,_label,_alias,OFF DEVICE_FAX)
!define OFF_DEVICE_FAX(_alias,_label,_shape,_color) ENTITY(_shape,_color,device_fax,_label,_alias,OFF DEVICE_FAX)
skinparam folderBackgroundColor<<OFF DEVICE_FAX>> White