sprite $load_balancer [48x32/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF0000000000000000000000000000000FFFFFFFFF
FFFFFFF000000000000000000000000000000000FFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FFFFFFFF
FFFFFF07922222222222222222222222222227A00FFFFFFF
FFFFFF08600000000000000000000000000004A00FFFFFFF
FFFFFF08605400000004772577167716770004A00FFFFFFF
FFFFFF08606548880007AA38AA29AA1AAA1004A00FFFFFFF
FFFFFF08603336660004A825A815A715A70004A00FFFFFFF
FFFFFF086087000000003200410020002000024000FFFFFF
FFFFFF0860000000000000000000222222222222100FFFFF
FFFFFF088444444444444444410AAAAAAAAAAAAAA20FFFFF
FFFFFF08AAAAAAAAAAAAAAAAA41AAAAAA10AAAAAA40FFFFF
FFFFFF000000000000000000001AAAAAA008AAAAA40FFFFF
FFFFFF000000000000000000001AAAAAA52AAAAAA40FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF01AAAAAA85AAAAAA40FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF01AAAAAA008AAAAA40FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF01AAAAA05408AAAA40FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF01AA1A0985A083AA40FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF01AA018A85AA018A40FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF01AA013A85A5208A40FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF01AA99A4856A99AA40FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF01AAAAA4110AAAAA40FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF01AAAAAA41AAAAAA40FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAA30FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF003666666666666500FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_LOAD_BALANCER(_alias) ENTITY(rectangle,black,load_balancer,_alias,OFF LOAD_BALANCER)
!define OFF_LOAD_BALANCER(_alias,_label) ENTITY(rectangle,black,load_balancer,_label,_alias,OFF LOAD_BALANCER)
!define OFF_LOAD_BALANCER(_alias,_label,_shape) ENTITY(_shape,black,load_balancer,_label,_alias,OFF LOAD_BALANCER)
!define OFF_LOAD_BALANCER(_alias,_label,_shape,_color) ENTITY(_shape,_color,load_balancer,_label,_alias,OFF LOAD_BALANCER)
skinparam folderBackgroundColor<<OFF LOAD_BALANCER>> White