sprite $modem [48x31/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF00000FFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFFF
FFFFFFF00000FFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFFF
FFFFFFF00550FFFFFFFFFFFFFFFFFFFFFFFF00910FFFFFFF
FFFFFFF00550FFFFFFFFFFFFFFFFFFFFFFFF00910FFFFFFF
FFFFFFF00550FFFFFFFFFFFFFFFFFFFFFFFF00910FFFFFFF
FFFFFFF00550FFFFFFFFFFFFFFFFFFFFFFFF00910FFFFFFF
FFFFFFF005500FFFFFFFFFFFFFFFFFFFFFFF009100FFFFFF
FFFFFFF006600FFFFFFFFFFFFFFFFFFFFFFF00A200FFFFFF
FFFFFFF00AA00FFFFFFFFFFFFFFFFFFFFFFF04A600FFFFFF
FFFFFFF00AA00FFFFFFFFFFFFFFFFFFFFFFF04A600FFFFFF
FFFFFFF00AA00FFFFFFFFFFFFFFFFFFFFFFF04A600FFFFFF
FFFFFFF00AA000000000000000000000000004A600FFFFFF
FFFFFFF00AA000000000000111000000000004A600FFFFFF
FFFFF0000AA456789AAAAAAAAAAAAAAAA98656A6000FFFFF
FFFF00038AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6100FFFF
FFFF004AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF005AAAAAAAAAAAAAAAAAAAAAAAAAA7AAAAAAAA00FFFF
FFFF005AAAAAAAAAAAAAAAAAAAAAAAAA205AAAAAAA00FFFF
FFFF005AAAAAAAAAAAAAAAAAAAAAAAAA407AAAAAAA00FFFF
FFFF005AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF005AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF005AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF005AAAA0000000000000000000000000009AAA00FFFF
FFFF004AAA90000000000000000000000000009AAA00FFFF
FFFF000000000FFFFFFFFFFFFFFFFFFFFFFF00000000FFFF
FFFFF0000000FFFFFFFFFFFFFFFFFFFFFFFFF000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_MODEM(_alias) ENTITY(rectangle,black,modem,_alias,OFF MODEM)
!define OFF_MODEM(_alias,_label) ENTITY(rectangle,black,modem,_label,_alias,OFF MODEM)
!define OFF_MODEM(_alias,_label,_shape) ENTITY(_shape,black,modem,_label,_alias,OFF MODEM)
!define OFF_MODEM(_alias,_label,_shape,_color) ENTITY(_shape,_color,modem,_label,_alias,OFF MODEM)
skinparam folderBackgroundColor<<OFF MODEM>> White