sprite $nic [48x35/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF007999910FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF005668A1000000000000000000000000000000000FFFFF
FF000003A1000000000000000000000000000000000FFFFF
FF000003A14AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FFFFF
FFFFFF03A15AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FFFFF
FFFFFF03A15AAAAAAAAAAAAA60000000AAAAAAAAA10FFFFF
FFFFFF03A15AAAAAAAA3333320000000AAAAAAAAA10FFFFF
FFFFFF03A15AAAAAAA91777740000000AAAAAAAAA10FFFFF
FFFFFF03A15AAAAAAA91AAAA72222222AAAAAAAAA10FFFFF
FFFFFF03A13888888871AAAAAAAAAAAAAAAAAAAAA10FFFFF
FFFFFF03A11333333334AAAAAAAAAAAAAAAAAAAAA10FFFFF
FFFFFF03A15AAAAAAAAAAAAAAAAAAAAAAA111114A10FFFFF
FFFFFF03A15AAAAAAAAAAAA70000000000000003A10FFFFF
FFFFFF03A15AAAAAAAAAAAA73AAAAAAAAA000003A10FFFFF
FFFFFF03A1255555555555534AAAAAAAAAAAAAAAA10FFFFF
FFFFFF03A1266666666666644AAAAAAAAAAAAAAAA10FFFFF
FFFFFF03A15AAAAAAAAAAAA74AAAAAA9999999AAA10FFFFF
FFFFFF03A15AAAAAAAAAAAA739999930000002AAA10FFFFF
FFFFFF03A15AAAAAAAAAAAA822222200000002AAA10FFFFF
FFFFFF03A15AAAAAAAAAAAAAAAAAAA52222224AAA10FFFFF
FFFFFF03A15AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FFFFF
FFFFFF03A15AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA10FFFFF
FFFFFF03A10000A0A09182736465400000000000000FFFFF
FFFFFF03A10000A0A09182736455400000000000000FFFFF
FFFFFF01500F0050505041413232200FFFFFFFFFFFFFFFFF
FFFFFF00000F0000000000000000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_NIC(_alias) ENTITY(rectangle,black,nic,_alias,OFF NIC)
!define OFF_NIC(_alias,_label) ENTITY(rectangle,black,nic,_label,_alias,OFF NIC)
!define OFF_NIC(_alias,_label,_shape) ENTITY(_shape,black,nic,_label,_alias,OFF NIC)
!define OFF_NIC(_alias,_label,_shape,_color) ENTITY(_shape,_color,nic,_label,_alias,OFF NIC)
skinparam folderBackgroundColor<<OFF NIC>> White