sprite $router [48x43/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF00A00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF00A00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF00A00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF00A00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF00A00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF00A00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF01A60FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF01A60FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF01A60FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF01A60FF0000000000000FFFFFFFFFFFFFFFFFF
FFFFFFFFF001A60000000000000000000000000FFFFFFFFF
FFFFFFF00001A8567899999999999987531000000FFFFFFF
FFFFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAA600FFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA80FFFFFFF
FFFFFF00AAAAAAAA9AAAA8AAAA8AAAA9AAAAAAA80FFFFFFF
FFFFFF00AAAAAAAA01AAA04AA409AA00AAAAAAA80FFFFFFF
FFFFFF00AAAAAAAA68AAA59AA95AAA86AAAAAAA80FFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA80FFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAA200000000000000000FFFF
FFFFFF00AAAAAAAAAAAAAAAAA2078888888888888600FFFF
FFFFFF00AAA9111111111111107AAAAAAAAAAAAAAA50FFFF
FFFFFF001110000000000000007AAAAAA919AAAAAA60FFFF
FFFFFFF000000FFFFFFFFFFF007AAAAA9000AAAAAA60FFFF
FFFFFFFFFFFFFFFFFFFFFFFF007AAAAA77068AAAAA60FFFF
FFFFFFFFFFFFFFFFFFFFFFFF007AAAAAAA0AAAAAAA60FFFF
FFFFFFFFFFFFFFFFFFFFFFFF007AA93AAA0AAA3AAA60FFFF
FFFFFFFFFFFFFFFFFFFFFFFF007AAA70AAAAA08AAA60FFFF
FFFFFFFFFFFFFFFFFFFFFFFF007A00003AAA20000A60FFFF
FFFFFFFFFFFFFFFFFFFFFFFF007AAA23AA9AA22AAA60FFFF
FFFFFFFFFFFFFFFFFFFFFFFF007AAA9AAA0AAA9AAA60FFFF
FFFFFFFFFFFFFFFFFFFFFFFF007AAAAA9A0AAAAAAA60FFFF
FFFFFFFFFFFFFFFFFFFFFFFF007AAAAA63028AAAAA60FFFF
FFFFFFFFFFFFFFFFFFFFFFFF007AAAAAA304AAAAAA60FFFF
FFFFFFFFFFFFFFFFFFFFFFFF007AAAAAAA6AAAAAAA60FFFF
FFFFFFFFFFFFFFFFFFFFFFFFF05AAAAAAAAAAAAAAA30FFFF
FFFFFFFFFFFFFFFFFFFFFFFFF0001111111111111000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ROUTER(_alias) ENTITY(rectangle,black,router,_alias,OFF ROUTER)
!define OFF_ROUTER(_alias,_label) ENTITY(rectangle,black,router,_label,_alias,OFF ROUTER)
!define OFF_ROUTER(_alias,_label,_shape) ENTITY(_shape,black,router,_label,_alias,OFF ROUTER)
!define OFF_ROUTER(_alias,_label,_shape,_color) ENTITY(_shape,_color,router,_label,_alias,OFF ROUTER)
skinparam folderBackgroundColor<<OFF ROUTER>> White