sprite $video_camera [48x28/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFF
FFFFF000000000000000000000000000FFFF007720FFFFFF
FFFFF000000000000000000000000000FFF008BB30FFFFFF
FFFFF009992099999999999999999600FF009BBB30FFFFFF
FFFFF00ABB30BBBBBBBBBBBBBBBBB700F009BBBB30FFFFFF
FFFFF00ABB30BBBBBBBBBBBBBBBBB700009BBBBB30FFFFFF
FFFFF00ABB30BBBBBBBBBBBBBBBBB70008BBBBBB30FFFFFF
FFFFF00ABB30BBBBBBBBBBBBBBBBB7008BBBBBBB30FFFFFF
FFFFF0066610BBBBBBBBBBBBBBBBB708BBBBBBBB30FFFFFF
FFFFF0000000BBBBBBBBBBBBBBBBB709BBBBBBBB30FFFFFF
FFFFFFFFFF00BBBBBBBBBBBBBBBBB703ABBBBBBB30FFFFFF
FFFFFFFFFF00BBBBBBBBBBBBBBBBB7003ABBBBBB30FFFFFF
FFFFFFFFFF00BBBBBBBBBBBBBBBBB70003ABBBBB30FFFFFF
FFFFFFFFFF00BBBBBBBBBBBBBBBBB700002ABBBB30FFFFFF
FFFFFFFFFF00BBBBBBBBBBBBBBBBB700F002BBBB30FFFFFF
FFFFFFFFFF0011111111111111111000FF002ABB30FFFFFF
FFFFFFFFFF0000000000000000000000FFF002AB30FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_VIDEO_CAMERA(_alias) ENTITY(rectangle,black,video_camera,_alias,OFF VIDEO_CAMERA)
!define OFF_VIDEO_CAMERA(_alias,_label) ENTITY(rectangle,black,video_camera,_label,_alias,OFF VIDEO_CAMERA)
!define OFF_VIDEO_CAMERA(_alias,_label,_shape) ENTITY(_shape,black,video_camera,_label,_alias,OFF VIDEO_CAMERA)
!define OFF_VIDEO_CAMERA(_alias,_label,_shape,_color) ENTITY(_shape,_color,video_camera,_label,_alias,OFF VIDEO_CAMERA)
skinparam folderBackgroundColor<<OFF VIDEO_CAMERA>> White