sprite $address_book_store [43x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF000000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF00000000000000000FFFFFFFFFFFFFFFF
FFFFFFFF0000001223333221000000FFFFFFFFFFFFF
FFFFFFF00025AAAAAAAAAAAAA841000FFFFFFFFFFFF
FFFFFF0029AAAAAAAAAAAAAAAAAA7100FFFFFFFFFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFFF04AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFFF007AAAAAAAAAAAAAAAAAAAA500FFFFFFFFFFF
FFFFFF00037AAAAAAAAAAAAAAAA61000FFFFFFFFFFF
FFFFFF056000246899AA987642001700FFFFFFFFFFF
FFFFFF05AA741000000000000258AA00FFFFFFFFFFF
FFFFFF05AAAAAA9877777889AAAAAA00FFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAA200000060000000000FFF
FFFFFF05AAAAAAAAAAAAA0000000000000000000FFF
FFFFFF05AAAAAAAAAAAA60999999A81A99999A200FF
FFFFFF05AAAAAAAAAAA900A0000009A10000064000F
FFFFFF05AAAAAAAAAAA70AA0029001A0057006AA00F
FFFFFF05AAAAAAAAAAA70AA006A1009009A0065A00F
FFFFFF05AAAAAAAAAAA70AA0045500901453063A00F
FFFFFF05AAAAAAAAAAA70AA05AAA00908AA9064A00F
FFFFFF05AAAAAAAAAAA70AA0477700906776065A00F
FFFFFF04AAAAAAAAAAA70AA0244400904444063A00F
FFFFFF009AAAAAAAAAA70AA0466600906666064A00F
FFFFFF0018AAAAAAAAA70AA0344400904444065A00F
FFFFFFF000269AAAAAA70AA0355500905555063A00F
FFFFFFFF0000012344530AA0000000900000064A00F
FFFFFFFFFF00000000000AA6555550A3555558AA00F
FFFFFFFFFFFFFFFF00000AAAAAAAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFFF0024444444AA94444444200F
FFFFFFFFFFFFFFFFFFF0000000000000000000000FF
FFFFFFFFFFFFFFFFFFFFF0000000000000000000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ADDRESS_BOOK_STORE(_alias) ENTITY(rectangle,black,address_book_store,_alias,OFF ADDRESS_BOOK_STORE)
!define OFF_ADDRESS_BOOK_STORE(_alias,_label) ENTITY(rectangle,black,address_book_store,_label,_alias,OFF ADDRESS_BOOK_STORE)
!define OFF_ADDRESS_BOOK_STORE(_alias,_label,_shape) ENTITY(_shape,black,address_book_store,_label,_alias,OFF ADDRESS_BOOK_STORE)
!define OFF_ADDRESS_BOOK_STORE(_alias,_label,_shape,_color) ENTITY(_shape,_color,address_book_store,_label,_alias,OFF ADDRESS_BOOK_STORE)
skinparam folderBackgroundColor<<OFF ADDRESS_BOOK_STORE>> White