sprite $database_mini_2 [42x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF000000000000FFFFFFFFFFFFFFF
FFFFFFFFFF0000000000000000000000FFFFFFFFFF
FFFFFFFF00000000245566554210000000FFFFFFFF
FFFFFF000003589AAAAAAAAAAAA98630000FFFFFFF
FFFFFF0004AAAAAAAAAAAAAAAAAAAAAA40000FFFFF
FFFFF0009AAAAAAAAAAAAAAAAAAAAAAAA9100FFFFF
FFFFF006AAAAAAAAAAAAAAAAAAAAAAAAAA700FFFFF
FFFFF005AAAAAAAAAAAAAAAAAAAAAAAAAA600FFFFF
FFFFF0007AAAAAAAAAAAAAAAAAAAAAAAA8000FFFFF
FFFFF000037AAAAAAAAAAAAAAAAAAAA730000FFFFF
FFFFF00620014789AAAAAAAAAA98741002500FFFFF
FFFFF008A920000000112211000000029A800FFFFF
FFFFF008AAA98642100000000124689AAA800FFFFF
FFFFF008AAAAAAAAAAA9999AAAAAAAAAAA800FFFFF
FFFFF008AAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF008AAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF008AAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF008AAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF006AAAAAAAAAAAAAAAAAAAAAAAAAA700FFFFF
FFFFF0009AAAAAAAAAAAAAAAAAAAAAAAAA100FFFFF
FFFFF00029AAAAAAAAAAAAAAAAAAAAAA93000FFFFF
FFFFF000005AAAAAAAAAAAAAAAAAAAA500000FFFFF
FFFFF007300024689AAAAAAAA986420003600FFFFF
FFFFF008A931000000011110000000139A800FFFFF
FFFFF008AAAAA8310000000000138AAAAA800FFFFF
FFFFF008AAAAAAAAAA999999AAAAAAAAAA800FFFFF
FFFFF008AAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF008AAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF008AAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF008AAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFF005AAAAAAAAAAAAAAAAAAAAAAAAAA600FFFFF
FFFFF0009AAAAAAAAAAAAAAAAAAAAAAAA9100FFFFF
FFFFFF0028AAAAAAAAAAAAAAAAAAAAAA82000FFFFF
FFFFFF000039AAAAAAAAAAAAAAAAAA94000FFFFFFF
FFFFFFF0000012579AAAAAAAA9752100000FFFFFFF
FFFFFFFFF000000000001100000000000FFFFFFFFF
FFFFFFFFFFFFF0000000000000000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF0000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE_MINI_2(_alias) ENTITY(rectangle,black,database_mini_2,_alias,OFF DATABASE_MINI_2)
!define OFF_DATABASE_MINI_2(_alias,_label) ENTITY(rectangle,black,database_mini_2,_label,_alias,OFF DATABASE_MINI_2)
!define OFF_DATABASE_MINI_2(_alias,_label,_shape) ENTITY(_shape,black,database_mini_2,_label,_alias,OFF DATABASE_MINI_2)
!define OFF_DATABASE_MINI_2(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_mini_2,_label,_alias,OFF DATABASE_MINI_2)
skinparam folderBackgroundColor<<OFF DATABASE_MINI_2>> White