sprite $database_server_green [39x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF00000000000000000FFFFFFFFFFFFFFF
FFFFFF00000000000000000000FFFFFFFFFFFFF
FFFFF008AAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA60FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAA55555555555AAA80FFFFFFFFFFFFF
FFFFF02AAA00000000000AAA80FFFFFFFFFFFFF
FFFFF02AAA99999999999AAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA7000000FFFFFFFF
FFFFF02AAAAAAAAAAAAAA84100000000000FFFF
FFFFF02AAAAAAAAAAAAA3001334444321000FFF
FFFFF02AAAAAAAAAAAA303666666666665200FF
FFFFF02AAAAAAAAAAAA006666666666666600FF
FFFFF02AAAAAAAAAAAA004666666666666300FF
FFFFF02AAAAAAAAAAAA011024455554320100FF
FFFFF02AAAAAAAAAAAA016531100011235600FF
FFFFF02AAA444444444016666666666666600FF
FFFFF02AAA111111111016666666666666600FF
FFFFF02AAAAAAAAAAAA016666666666666600FF
FFFFF02AAAAAAAAAAAA016666666666666600FF
FFFFF02AAA999999999016666666666666600FF
FFFFF02AAA000000000016666666666666600FF
FFFFF02AAA555555555016666666666666600FF
FFFFF02AAAAAAAAAAAA016666666666666600FF
FFFFF02AAAAAAAAAAAA016666666666666600FF
FFFFF02AAAAAAAAAAAA016666666666666600FF
FFFFF01666666666666006666666666666600FF
FFFFF00000000000000005666666666666200FF
FFFFFFFFFFFFFFFFFFFF0004556666552000FFF
FFFFFFFFFFFFFFFFFFFFF00000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE_SERVER_GREEN(_alias) ENTITY(rectangle,black,database_server_green,_alias,OFF DATABASE_SERVER_GREEN)
!define OFF_DATABASE_SERVER_GREEN(_alias,_label) ENTITY(rectangle,black,database_server_green,_label,_alias,OFF DATABASE_SERVER_GREEN)
!define OFF_DATABASE_SERVER_GREEN(_alias,_label,_shape) ENTITY(_shape,black,database_server_green,_label,_alias,OFF DATABASE_SERVER_GREEN)
!define OFF_DATABASE_SERVER_GREEN(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_server_green,_label,_alias,OFF DATABASE_SERVER_GREEN)
skinparam folderBackgroundColor<<OFF DATABASE_SERVER_GREEN>> White