sprite $database [35x48/16] {
00000000000000000000000000000000000
00000000000000000000000000000000000
00000000013567899999876531000000000
00000047AAAAAAAAAAAAAAAAAAA74000000
00006AAAAAAAAAAAAAAAAAAAAAAAAA60000
0019AAAAAAAAAAAAAAAAAAAAAAAAAAA9100
008AAAAAAAAAAAAAAAAAAAAAAAAAAAAA800
009AAAAAAAAAAAAAAAAAAAAAAAAAAAAA900
004AAAAAAAAAAAAAAAAAAAAAAAAAAAAA400
00039AAAAAAAAAAAAAAAAAAAAAAAAA93000
0000037AAAAAAAAAAAAAAAAAAAAA7300000
009300003578AAAAAAAAAAA875300003900
00AA951000000011222110000000159AA00
00AAAAA964210000000000012469AAAAA00
00AAAAAAAAAAAA98888899AAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
009AAAAAAAAAAAAAAAAAAAAAAAAAAAAA900
004AAAAAAAAAAAAAAAAAAAAAAAAAAAAA400
0006AAAAAAAAAAAAAAAAAAAAAAAAAAA6000
000049AAAAAAAAAAAAAAAAAAAAAAA940000
00000037AAAAAAAAAAAAAAAAAAA73000000
00000000024578899999887542000000000
00000000000000000000000000000000000
00000000000000000000000000000000000
}

!define OFF_DATABASE(_alias) ENTITY(rectangle,black,database,_alias,OFF DATABASE)
!define OFF_DATABASE(_alias,_label) ENTITY(rectangle,black,database,_label,_alias,OFF DATABASE)
!define OFF_DATABASE(_alias,_label,_shape) ENTITY(_shape,black,database,_label,_alias,OFF DATABASE)
!define OFF_DATABASE(_alias,_label,_shape,_color) ENTITY(_shape,_color,database,_label,_alias,OFF DATABASE)
skinparam folderBackgroundColor<<OFF DATABASE>> White