sprite $database_availability_group [48x42/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF00000000000000FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF000013566664200000FFFFFFFFFFFFFFFFFFFFFFFF
FFFFF0018AAAAAAAAAAA95000FFFFFFFFFFFFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFFFFF
FFFFF06AAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFFFFF
FFFFF006AAAAAAAAAAAAA9200FFFFFFFFFFFFFFFFFFFFFFF
FFFFF03003579AAA986410000000000FFFFFFFFFFFFFFFFF
FFFFF0896200000000002567776410000FFFFFFFFFFFFFFF
FFFFF08AAAAAA99104AAAAAAAAAAAA9200FFFFFFFFFFFFFF
FFFFF08AAAAAAA70AAAAAAAAAAAAAAAA600FFFFFFFFFFFFF
FFFFF08AAAAAAA60AAAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF08AAAAAAA6018AAAAAAAAAAAAA6000FFFFFFFFFFFFF
FFFFF08AAAAAAA602013589AAA974200000000000FFFFFFF
FFFFF08AAAAAAA60A95000000000003688886300000FFFFF
FFFFF08AAAAAAA60AAAAAAAA8008AAAAAAAAAAAA8000FFFF
FFFFF08AAAAAAA60AAAAAAAA21AAAAAAAAAAAAAAAA10FFFF
FFFFF08AAAAAAA60AAAAAAAA13AAAAAAAAAAAAAAAA20FFFF
FFFFF08AAAAAAA60AAAAAAAA1039AAAAAAAAAAAA9300FFFF
FFFFF08AAAAAAA60AAAAAAAA13001369AAAA86310010FFFF
FFFFF08AAAAAAA60AAAAAAAA15A92000000000029A20FFFF
FFFFF08AAAAAAA60AAAAAAAA15AAAAAAAAAAAAAAAA20FFFF
FFFFF08AAAAAAA60AAAAAAAA15AAAAAAAAAAAAAAAA20FFFF
FFFFF05AAAAAAA60AAAAAAAA15AAAAAAAAAAAAAAAA20FFFF
FFFFF009AAAAAA60AAAAAAAA15AAAAAAAAAAAAAAAA20FFFF
FFFFF00029AAAA60AAAAAAAA15AAAAAAAAAAAAAAAA20FFFF
FFFFFFF000000000AAAAAAAA15AAAAAAAAAAAAAAAA20FFFF
FFFFFFFFF0000000AAAAAAAA15AAAAAAAAAAAAAAAA20FFFF
FFFFFFFFFFFFFF00AAAAAAAA15AAAAAAAAAAAAAAAA20FFFF
FFFFFFFFFFFFFF00AAAAAAAA15AAAAAAAAAAAAAAAA20FFFF
FFFFFFFFFFFFFF001AAAAAAA15AAAAAAAAAAAAAAAA20FFFF
FFFFFFFFFFFFFFF00049AAAA15AAAAAAAAAAAAAAAA20FFFF
FFFFFFFFFFFFFFFFF000000105AAAAAAAAAAAAAAAA20FFFF
FFFFFFFFFFFFFFFFFFF0000005AAAAAAAAAAAAAAAA20FFFF
FFFFFFFFFFFFFFFFFFFFFFFF05AAAAAAAAAAAAAAAA20FFFF
FFFFFFFFFFFFFFFFFFFFFFFF03AAAAAAAAAAAAAAAA10FFFF
FFFFFFFFFFFFFFFFFFFFFFFF007AAAAAAAAAAAAAA500FFFF
FFFFFFFFFFFFFFFFFFFFFFFFF00069AAAAAAAA96000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF0000001111000000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE_AVAILABILITY_GROUP(_alias) ENTITY(rectangle,black,database_availability_group,_alias,OFF DATABASE_AVAILABILITY_GROUP)
!define OFF_DATABASE_AVAILABILITY_GROUP(_alias,_label) ENTITY(rectangle,black,database_availability_group,_label,_alias,OFF DATABASE_AVAILABILITY_GROUP)
!define OFF_DATABASE_AVAILABILITY_GROUP(_alias,_label,_shape) ENTITY(_shape,black,database_availability_group,_label,_alias,OFF DATABASE_AVAILABILITY_GROUP)
!define OFF_DATABASE_AVAILABILITY_GROUP(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_availability_group,_label,_alias,OFF DATABASE_AVAILABILITY_GROUP)
skinparam folderBackgroundColor<<OFF DATABASE_AVAILABILITY_GROUP>> White