sprite $database_public_folder [47x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF00000000000000000FFFFFFFFFFFFFFFFFFFF
FFFFFFF0000001122333221000000FFFFFFFFFFFFFFFFFF
FFFFFF000148AAAAAAAAAAAA9520000FFFFFFFFFFFFFFFF
FFFFF0017AAAAAAAAAAAAAAAAAA9200FFFFFFFFFFFFFFFF
FFFFF009AAAAAAAAAAAAAAAAAAAAA200FFFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAA400FFFFFFFFFFFFFFF
FFFFF005AAAAAAAAAAAAAAAAAAAA8000FFFFFFFFFFFFFFF
FFFFF00016AAAAAAAAAAAAAAAA830000FFFFFFFFFFFFFFF
FFFFF027200246899AAA987530005500FFFFFFFFFFFFFFF
FFFFF02AA852000000000000147AA500FFFFFFFFFFFFFFF
FFFFF02AAAAAA9877777789AAAAAA500FFFFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAA500FFFFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAA500FFFFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAA500FFFFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAA500FFFFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAA500FFFFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAA500FFFFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAA500FFFFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAA5000000000000FFFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAA50001AAAAA9100FFFF
FFFFF02AAAAAAAAAAAAAAAAAAAAAA5002AAAAAAA700FFFF
FFFFF02AAAAAAAAAAAAAA62222222002AAAAAAAA600FFFF
FFFFF02AAAAAAAAAAAAA30111111111111111111000FFFF
FFFFF02AAAAAAAAAAAA905AAAAAAAAAAAAAAAAAA700FFFF
FFFFF02AAAAAAAAAAAA907AAAAAAAAAAAAAAAAAA700FFFF
FFFFF02AAAAAAAAAAAA907AAAAAAAAAAAAAAAAAA700FFFF
FFFFF02AAAAAAAAAAAA907AAA9889AAAA888AAAA700FFFF
FFFFF02AAAAAAAAAAAA907AAA7012AAAA2107AAA700FFFF
FFFFF02AAAAAAAAAAAA907AAA7109AAAA8017AAA700FFFF
FFFFF01AAAAAAAAAAAA907AAA83709AA80838AAA700FFFF
FFFFF007AAAAAAAAAAA907AAAA9A703308A9AAAA700FFFF
FFFFF0006AAAAAAAAAA907AAAAAAA5005AAAAAAA700FFFF
FFFFFF000259AAAAAAA907AAAAAAA9009AAAAAAA700FFFF
FFFFFFF000000234555407AAAAAAAAAAAAAAAAAA700FFFF
FFFFFFFFFF000000000007AAAAAAAAAAAAAAAAAA700FFFF
FFFFFFFFFFFFFFFF000007AAAAAAAAAAAAAAAAAA700FFFF
FFFFFFFFFFFFFFFFFFF007AAAAAAAAAAAAAAAAAA700FFFF
FFFFFFFFFFFFFFFFFFF000000000000000000000000FFFF
FFFFFFFFFFFFFFFFFFF000000000000000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE_PUBLIC_FOLDER(_alias) ENTITY(rectangle,black,database_public_folder,_alias,OFF DATABASE_PUBLIC_FOLDER)
!define OFF_DATABASE_PUBLIC_FOLDER(_alias,_label) ENTITY(rectangle,black,database_public_folder,_label,_alias,OFF DATABASE_PUBLIC_FOLDER)
!define OFF_DATABASE_PUBLIC_FOLDER(_alias,_label,_shape) ENTITY(_shape,black,database_public_folder,_label,_alias,OFF DATABASE_PUBLIC_FOLDER)
!define OFF_DATABASE_PUBLIC_FOLDER(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_public_folder,_label,_alias,OFF DATABASE_PUBLIC_FOLDER)
skinparam folderBackgroundColor<<OFF DATABASE_PUBLIC_FOLDER>> White