sprite $database_partition_3 [48x46/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF000000000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF000000000000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0000158A87A96100000FFFFFFFFFFFFFFF
FFFFFFFFFFFF00005AAAAA20AAAAA71000FFFFFFFFFFFFFF
FFFFFFFFFFF0004AAAAAAAAAAAAAAAA7000FFFFFFFFFFFFF
FFFFFFFFFF0009AAAAAAAA76AAAAAAAAA100FFFFFFFFFFFF
FFFFFFFFF000AAAAAAAAAA30AAAAAAAAAA200FFFFFFFFFFF
FFFFFFFF000AAAAAAAAAAAAAAAAAAAAAAAA200FFFFFFFFFF
FFFFFFFF00AAAAAAAAAAAA76AAAAAAAAAAAA000FFFFFFFFF
FFFFFFF006AAAAAAAAAAAA30AAAAAAAAAAAAA00FFFFFFFFF
FFFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAA300FFFFFFFF
FFFFFF008AAAAAAAAAAAAA75AAAAAAAAAAAAAA00FFFFFFFF
FFFFFF00AAAAAAAAAAAAAA30AAAAAAAAAAAAAA10FFFFFFFF
FFFFFF03AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA900FFFFFFF
FFFFF009AAAAAAAAAAAAAA65AAAAAAAAAAAAAAA00FFFFFFF
FFFFF00AAAAAAAAAAAAAAA31AAAAAAAAAAAAAAA00FFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFF00AAAAAAAAAAAAAA5AA39AAAAAAAAAAAAA10FFFFFFF
FFFFF00AAAAAAAAAAAA9A06A08AAAAAAAAAAAAA20FFFFFFF
FFFFF00AAAAAAAAAAA10A9AAAA40AAAAAAAAAAA10FFFFFFF
FFFFF00AAAAAAAA92A88AAAAAA95A37AAAAA99900FFFFFFF
FFFFF00AAAAAAAA909AAAAAAAAAAA169520000000000FFFF
FFFFFF05AAAAA02AAAAAAAAAAAAAAA3002466766530000FF
FFFFFF00AA62A6AAAAAAAAAAAAAAA106AAAAAAAAAAA700FF
FFFFFF007A72AAAAAAAAAAAAAAAAA06AAAAAAAAAAAAAA00F
FFFFFFF007AAAAAAAAAAAAAAAAAAA019AAAAAAAAAAAA300F
FFFFFFF009AAAAAAAAAAAAAAAAAAA0502479AAA97520600F
FFFFFFFF00AAAAAAAAAAAAAAAAAAA08A85311001357AA00F
FFFFFFFF002AAAAAAAAAAAAAAAAAA08AAAAAAAAAAAAAA00F
FFFFFFFFF003AAAAAAAAAAAAAAAAA08AAAAAAAAAAAAAA00F
FFFFFFFFFF002AAAAAAAAAAAAAAAA08AAAAAAAAAAAAAA00F
FFFFFFFFFFF0018AAAAAAAAAAAAAA08AAAAAAAAAAAAAA00F
FFFFFFFFFFFF00029AAAAAAAAAAAA08AAAAAAAAAAAAAA00F
FFFFFFFFFFFFF000015AAAAAAAA6208AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFF0000001111000008AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFF0000000000008AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF08AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF08AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF04AAAAAAAAAAAAA700F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF005AAAAAAAAAAA600FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000467876410000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFF
}

!define OFF_DATABASE_PARTITION_3(_alias) ENTITY(rectangle,black,database_partition_3,_alias,OFF DATABASE_PARTITION_3)
!define OFF_DATABASE_PARTITION_3(_alias,_label) ENTITY(rectangle,black,database_partition_3,_label,_alias,OFF DATABASE_PARTITION_3)
!define OFF_DATABASE_PARTITION_3(_alias,_label,_shape) ENTITY(_shape,black,database_partition_3,_label,_alias,OFF DATABASE_PARTITION_3)
!define OFF_DATABASE_PARTITION_3(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_partition_3,_label,_alias,OFF DATABASE_PARTITION_3)
skinparam folderBackgroundColor<<OFF DATABASE_PARTITION_3>> White