sprite $database [39x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF00000000000FFFFFFFFFFFFF
FFFFFFFFFF00000000000000000000FFFFFFFFF
FFFFFFFF000002356788887653200000FFFFFFF
FFFFFFF00027AAAAAAAAAAAAAAAA830000FFFFF
FFFFFF0018AAAAAAAAAAAAAAAAAAAAA200FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA10FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA20FFFFF
FFFFFF003AAAAAAAAAAAAAAAAAAAAAA500FFFFF
FFFFFF00005AAAAAAAAAAAAAAAAAA71000FFFFF
FFFFFF0181001369AAAAAAAA9741000630FFFFF
FFFFFF01AA84000000011000000038AA30FFFFF
FFFFFF01AAAAA98765444456789AAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAA30FFFFF
FFFFFF009AAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF002AAAAAAAAAAAAAAAAAAAAAA400FFFFF
FFFFFFF0017AAAAAAAAAAAAAAAAAA82000FFFFF
FFFFFFF00001379AAAAAAAAAAA7410000FFFFFF
FFFFFFFFF0000000122332210000000FFFFFFFF
FFFFFFFFFFFF0000000000000000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE(_alias) ENTITY(rectangle,black,database,_alias,OFF DATABASE)
!define OFF_DATABASE(_alias,_label) ENTITY(rectangle,black,database,_label,_alias,OFF DATABASE)
!define OFF_DATABASE(_alias,_label,_shape) ENTITY(_shape,black,database,_label,_alias,OFF DATABASE)
!define OFF_DATABASE(_alias,_label,_shape,_color) ENTITY(_shape,_color,database,_label,_alias,OFF DATABASE)
skinparam folderBackgroundColor<<OFF DATABASE>> White