sprite $database_cube [43x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF00040000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00019AA6000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00008AAAAAA3000FFFFFFFFFFFFFF
FFFFFFFFFFFFF000403AAAAA8100000FFFFFFFFFFFF
FFFFFFFFFFF00029A9206AA207AA7000FFFFFFFFFFF
FFFFFFFFF00008AAAAA80104AAAAAA5000FFFFFFFFF
FFFFFFF0000205AAAAA60202AAAAA9102000FFFFFFF
FFFFF000049A8018A8108AA504AA305AA80000FFFFF
FFFF00028AAAAA70206AAAAA921029AAAAA6000FFFF
FFFF00029AAAAA50204AAAAA810029AAAAA5000FFFF
FFFF00A403AA8118A8217AA306AA503AA711820FFFF
FFFF00AA920207AAAAA702039AAAA930206AA20FFFF
FFFF00AAAA0017AAAAA81103AAAAAA4008AAA20FFFF
FFFF00AAAA0A503AAA306A9305AA602819AAA20FFFF
FFFF008AAA0AA930405AAAAA811207AA19AAA10FFFF
FFFF0003AA0AAAA7007AAAAAA300AAAA19A7000FFFF
FFFF00A4060AAAAA06029AA50390AAAA1721720FFFF
FFFF00AA9207AAAA0AA404117AA0AAAA006AA20FFFF
FFFF00AAAA0029AA0AAA806AAAA0AA5009AAA20FFFF
FFFF00AAAA0A50490AAAA0AAAAA0712819AAA20FFFF
FFFF009AAA0AA9300AAAA0AAAA9006AA19AAA10FFFF
FFFF0004AA0AAAA7029AA0AAA600AAAA19A7100FFFF
FFFF0092060AAAAA0505A0A71290AAAA1730520FFFF
FFFF00AA6008AAAA0AA300217AA0AAAA003AA20FFFF
FFFF00AAAA004AAA0AAA805AAAA0AA7007AAA20FFFF
FFFF00AAAA0A206A0AAAA0AAAAA0821619AAA20FFFF
FFFF00AAAA0AA7100AAAA0AAAAA004AA19AAA10FFFF
FFFF0007AA0AAAA4039AA0AAA600AAAA19A9200FFFF
FFFFF000180AAAAA0305A0A81180AAAA185000FFFFF
FFFFFFF00009AAAA0A9200305AA0AAAA1000FFFFFFF
FFFFFFFF00006AAA0AAA603AAAA0AA91000FFFFFFFF
FFFFFFFFFF00008A0AAAA0AAAAA093000FFFFFFFFFF
FFFFFFFFFFFF00020AAAA0AAAAA0000FFFFFFFFFFFF
FFFFFFFFFFFFFF0005AAA0AAA80000FFFFFFFFFFFFF
FFFFFFFFFFFFFFF00008A0A92000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF000105000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF000000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE_CUBE(_alias) ENTITY(rectangle,black,database_cube,_alias,OFF DATABASE_CUBE)
!define OFF_DATABASE_CUBE(_alias,_label) ENTITY(rectangle,black,database_cube,_label,_alias,OFF DATABASE_CUBE)
!define OFF_DATABASE_CUBE(_alias,_label,_shape) ENTITY(_shape,black,database_cube,_label,_alias,OFF DATABASE_CUBE)
!define OFF_DATABASE_CUBE(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_cube,_label,_alias,OFF DATABASE_CUBE)
skinparam folderBackgroundColor<<OFF DATABASE_CUBE>> White