sprite $database_server_orange [39x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF00000000000000000FFFFFFFFFFFFFFF
FFFFFF00000000000000000000FFFFFFFFFFFFF
FFFFF008AAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA60FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAA55555555555AAA80FFFFFFFFFFFFF
FFFFF02AAA00000000000AAA80FFFFFFFFFFFFF
FFFFF02AAA99999999999AAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA80FFFFFFFFFFFFF
FFFFF02AAAAAAAAAAAAAAAAA7000000FFFFFFFF
FFFFF02AAAAAAAAAAAAAA84100000000000FFFF
FFFFF02AAAAAAAAAAAAA3002456766542000FFF
FFFFF02AAAAAAAAAAAA304999999999998300FF
FFFFF02AAAAAAAAAAAA009999999999999900FF
FFFFF02AAAAAAAAAAAA006999999999999400FF
FFFFF02AAAAAAAAAAAA011046778877530200FF
FFFFF02AAAAAAAAAAAA029742111112358900FF
FFFFF02AAA444444444029999999999999900FF
FFFFF02AAA111111111029999999999999900FF
FFFFF02AAAAAAAAAAAA029999999999999900FF
FFFFF02AAAAAAAAAAAA029999999999999900FF
FFFFF02AAA999999999029999999999999900FF
FFFFF02AAA000000000029999999999999900FF
FFFFF02AAA555555555029999999999999900FF
FFFFF02AAAAAAAAAAAA029999999999999900FF
FFFFF02AAAAAAAAAAAA029999999999999900FF
FFFFF02AAAAAAAAAAAA029999999999999900FF
FFFFF01666666666666019999999999999900FF
FFFFF00000000000000007999999999999300FF
FFFFFFFFFFFFFFFFFFFF0006888888884000FFF
FFFFFFFFFFFFFFFFFFFFF00000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE_SERVER_ORANGE(_alias) ENTITY(rectangle,black,database_server_orange,_alias,OFF DATABASE_SERVER_ORANGE)
!define OFF_DATABASE_SERVER_ORANGE(_alias,_label) ENTITY(rectangle,black,database_server_orange,_label,_alias,OFF DATABASE_SERVER_ORANGE)
!define OFF_DATABASE_SERVER_ORANGE(_alias,_label,_shape) ENTITY(_shape,black,database_server_orange,_label,_alias,OFF DATABASE_SERVER_ORANGE)
!define OFF_DATABASE_SERVER_ORANGE(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_server_orange,_label,_alias,OFF DATABASE_SERVER_ORANGE)
skinparam folderBackgroundColor<<OFF DATABASE_SERVER_ORANGE>> White