sprite $database_partition_4 [48x46/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF000000000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF000000000000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0000048A97AA6200000FFFFFFFFFFFFFFF
FFFFFFFFFFFF00004AAAAA50AAAAA81000FFFFFFFFFFFFFF
FFFFFFFFFFF0002AAAAAAAAAAAAAAAA8000FFFFFFFFFFFFF
FFFFFFFFFF0008AAAAAAAA86AAAAAAAAA200FFFFFFFFFFFF
FFFFFFFFF000AAAAAAAAAA50AAAAAAAAAA400FFFFFFFFFFF
FFFFFFFFF00AAAAAAAAAAAAAAAAAAAAAAAA300FFFFFFFFFF
FFFFFFFF009AAAAAAAAAAA86AAAAAAAAAAAA100FFFFFFFFF
FFFFFFF004AAAAAAAAAAAA50AAAAAAAAAAAAA00FFFFFFFFF
FFFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAA600FFFFFFFF
FFFFFF006AAAAAAAAAAAAA85AAAAAAAAAAAAAA00FFFFFFFF
FFFFFF00AAAAAAAAAAAAAA50AAAAAAAAAAAAAA40FFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFF06AAAAAAAAAAAAAA85AAAAAAAAAAAAAAA00FFFFFFF
FFFFF00AAAAAAAAAAAAAAA61AAAAAAAAAAAAAAA00FFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA30FFFFFFF
FFFFF0074A74A74A74A74A53A74A74A74A74A7440FFFFFFF
FFFFF0061A61A61A61A61A30A61A61A61A61A6150FFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA30FFFFFFF
FFFFF00AAAAAAAAAAAAAAA74AAAAAAAAAAAAA9910FFFFFFF
FFFFFF08AAAAAAAAAAAAAA61AAAAAAA9531000000000FFFF
FFFFFF02AAAAAAAAAAAAAAAAAAAAAA3002466766530000FF
FFFFFF00AAAAAAAAAAAAAA73AAAAA205AAAAAAAAAAA8100F
FFFFFF008AAAAAAAAAAAAA61AAAAA03AAAAAAAAAAAAAA00F
FFFFFFF00AAAAAAAAAAAAAAAAAAAA008AAAAAAAAAAAA400F
FFFFFFF007AAAAAAAAAAAA63AAAAA0312478AAA98530400F
FFFFFFFF00AAAAAAAAAAAA61AAAAA05A864210012579A00F
FFFFFFFF001AAAAAAAAAAAAAAAAAA05AAAAAAAAAAAAAA00F
FFFFFFFFF002AAAAAAAAAA62AAAAA05AAAAAAAAAAAAAA00F
FFFFFFFFFF001AAAAAAAAA61AAAAA05AAAAAAAAAAAAAA00F
FFFFFFFFFFF0007AAAAAAAAAAAAAA05AAAAAAAAAAAAAA00F
FFFFFFFFFFFF00029AAAAA62AAAAA05AAAAAAAAAAAAAA00F
FFFFFFFFFFFFF0000159AA62AAA7205AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFF0000001111000005AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFF0000000000005AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF05AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF05AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF01AAAAAAAAAAAAA900F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF003AAAAAAAAAAA800FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000367876410000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFF
}

!define OFF_DATABASE_PARTITION_4(_alias) ENTITY(rectangle,black,database_partition_4,_alias,OFF DATABASE_PARTITION_4)
!define OFF_DATABASE_PARTITION_4(_alias,_label) ENTITY(rectangle,black,database_partition_4,_label,_alias,OFF DATABASE_PARTITION_4)
!define OFF_DATABASE_PARTITION_4(_alias,_label,_shape) ENTITY(_shape,black,database_partition_4,_label,_alias,OFF DATABASE_PARTITION_4)
!define OFF_DATABASE_PARTITION_4(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_partition_4,_label,_alias,OFF DATABASE_PARTITION_4)
skinparam folderBackgroundColor<<OFF DATABASE_PARTITION_4>> White