sprite $database_server_ghosted [39x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF00000000000000000FFFFFFFFFFFFFFF
FFFFFF00000000000000000000FFFFFFFFFFFFF
FFFFF007AAAAAAAAAAAAAAA900FFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA70FFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA90FFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA90FFFFFFFFFFFFF
FFFFF01AAA55555555555AAA90FFFFFFFFFFFFF
FFFFF01AAA00000000000AAA90FFFFFFFFFFFFF
FFFFF01AAA99999999999AAA90FFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA90FFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA90FFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA90FFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA90FFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA90FFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA90FFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA90FFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA90FFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA90FFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA90FFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAA80000000FFFFFFF
FFFFF01AAAAAAAAAAAAAA84100000000000FFFF
FFFFF01AAAAAAAAAAAAA4001124334211000FFF
FFFFF01AAAAAAAAAAAA402553653553553200FF
FFFFF01AAAAAAAAAAAA005535535535535500FF
FFFFF01AAAAAAAAAAAA004355355355355200FF
FFFFF01AAAAAAAAAAAA001022453453320100FF
FFFFF01AAAAAAAAAAAA015421110011125500FF
FFFFF01AAA444444444005355355355355300FF
FFFFF01AAA111111111013553553553553500FF
FFFFF01AAAAAAAAAAAA015535535535535500FF
FFFFF01AAAAAAAAAAAA015355355355355300FF
FFFFF01AAA999999999013553563453553500FF
FFFFF01AAA000000000014635634634535500FF
FFFFF01AAA555555555016346346346356300FF
FFFFF01AAAAAAAAAAAA013463463463563500FF
FFFFF01AAAAAAAAAAAA014634634634634600FF
FFFFF01AAAAAAAAAAAA016346346346346300FF
FFFFF01666666666666003463463463463400FF
FFFFF00000000000000003634634634634200FF
FFFFFFFFFFFFFFFFFFFF0003533533533000FFF
FFFFFFFFFFFFFFFFFFFFF00000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE_SERVER_GHOSTED(_alias) ENTITY(rectangle,black,database_server_ghosted,_alias,OFF DATABASE_SERVER_GHOSTED)
!define OFF_DATABASE_SERVER_GHOSTED(_alias,_label) ENTITY(rectangle,black,database_server_ghosted,_label,_alias,OFF DATABASE_SERVER_GHOSTED)
!define OFF_DATABASE_SERVER_GHOSTED(_alias,_label,_shape) ENTITY(_shape,black,database_server_ghosted,_label,_alias,OFF DATABASE_SERVER_GHOSTED)
!define OFF_DATABASE_SERVER_GHOSTED(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_server_ghosted,_label,_alias,OFF DATABASE_SERVER_GHOSTED)
skinparam folderBackgroundColor<<OFF DATABASE_SERVER_GHOSTED>> White