sprite $database_mirror [48x42/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF00000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF00000001110000000FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFF00038AAAAAAAAAA72000FFFFFFFFFFFFFFFFFFFFFFF
FFFFF009AAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFFFFFFFF
FFFFF03AAAAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFFFFFFFF
FFFFF005AAAAAAAAAAAAAA300FFFFFFFFFFFFFFFFFFFFFFF
FFFFF01003689AAAA98620000FFFFFFFFFFFFFFFFFFFFFFF
FFFFF03A62000000000037A10FFFFFFFF00FFFFFFFFFFFFF
FFFFF03AAAAA99999AAAAAA10FF00000000000000FFFFFFF
FFFFF03AAAAAAAAAAAAAAAA100000368AAAA8520000FFFFF
FFFFF03AAAAAAAAAAAAAAAA10039AAAAAAAAAAAA8100FFFF
FFFFF03AAAAAAAAAAAAAAAA103AAAAAAAAAAAAAAAA00FFFF
FFFFF03AAAAAAAAAAAAAAAA101AAAAAAAAAAAAAAA900FFFF
FFFFF03AAAAAAAAAAAAAAAA100079AAAAAAAAAA95000FFFF
FFFFF03AAAAAAAAAAAAAAAA105400024555532000610FFFF
FFFFF03AAAAAAAAAAAAAAAA105AA864100012479AA10FFFF
FFFFF03AAAAAAAAAAAAAAAA105AAAAAAAAAAAAAAAA10FFFF
FFFFF03AAAAAAAAAAAAAAAA105AAAAAAAAAAAAAAAA10FFFF
FFFFF03AAAAAAAAAAAAAAAA105AAAAAAAAAAAAAAAA10FFFF
FFFFF03AAAAAAAAAAAAAAAA105AAAAAAAAAAAAAAAA10FFFF
FFFFF03AAAAAAAAAAAAAAAA105AAAAAAAAAAAAAAAA10FFFF
FFFFF03AAAAAAAAAAAAAAAA105AAAAAAAAAAAAAAAA10FFFF
FFFFF01AAAAAAAAAAAAAAAA005AAAAAAAAAAAAAAAA10FFFF
FFFFF0019AAAAAAAAAAAA70005AAAAAAAAAAAAAAAA10FFFF
FFFFFF0000268AAAA851000F05AAAAAAAAAAAAAAAA10FFFF
FFFFFFF000000000000000FF05AAAAAAAAAAAAAAAA10FFFF
FFFFFFF005550000155500FF05AAAAAAAAAAAAAAAA10FFFF
FFFFFFF007AA10F006AA900F05AAAAAAAAAAAAAAAA10FFFF
FFFFFFFF00AAA000006AAA0005AAAAAAAAAAAAAAAA10FFFF
FFFFFFFF007AA9100006AAA004AAAAAAAAAAAAAAAA00FFFF
FFFFFFFFF009AAAAAAAAAAA9008AAAAAAAAAAAAAA400FFFF
FFFFFFFFF0008AAAAAAAAAAA70018AAAAAAAAAA6000FFFFF
FFFFFFFFFFF001799999AAA8000000000110000000FFFFFF
FFFFFFFFFFFF00000007AA8000FF00000000000FFFFFFFFF
FFFFFFFFFFFFFF00008AA7000FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF008AA700FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00122200FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE_MIRROR(_alias) ENTITY(rectangle,black,database_mirror,_alias,OFF DATABASE_MIRROR)
!define OFF_DATABASE_MIRROR(_alias,_label) ENTITY(rectangle,black,database_mirror,_label,_alias,OFF DATABASE_MIRROR)
!define OFF_DATABASE_MIRROR(_alias,_label,_shape) ENTITY(_shape,black,database_mirror,_label,_alias,OFF DATABASE_MIRROR)
!define OFF_DATABASE_MIRROR(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_mirror,_label,_alias,OFF DATABASE_MIRROR)
skinparam folderBackgroundColor<<OFF DATABASE_MIRROR>> White