sprite $database_partition_5 [48x46/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF000000000FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF000000000000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0000048AA7AA7200000FFFFFFFFFFFFFFF
FFFFFFFFFFFFF0003AAAAA80AAAAA91000FFFFFFFFFFFFFF
FFFFFFFFFFF0002AAAAAAAAAAAAAAAA9100FFFFFFFFFFFFF
FFFFFFFFFF0006AAAAAAAA96AAAAAAAAA300FFFFFFFFFFFF
FFFFFFFFF0009AAAAAAAAA80AAAAAAAAAA500FFFFFFFFFFF
FFFFFFFFF009AAAAAAAAAAAAAAAAAAAAAAA500FFFFFFFFFF
FFFFFFFF007AAAAAAAAAAA96AAAAAAAAAAAA200FFFFFFFFF
FFFFFFF002AAAAAAAAAAAA80AAAAAAAAAAAAA00FFFFFFFFF
FFFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAA800FFFFFFFF
FFFFFFF03AAAAAAAAAAAAA95AAAAAAAAAAAAAA00FFFFFFFF
FFFFFF00AAAAAAAAAAAAAA80AAAAAAAAAAAAAA600FFFFFFF
FFFFFF0058AAAAAAAAAAAAAAAAAAAAAAAAAAA7700FFFFFFF
FFFFFF0403A15A9AAAAAAA95AAAAAAAA9A33A0200FFFFFFF
FFFFFF08AAA26A05A7AAAA81AAAA97A00A23AAA20FFFFFFF
FFFFF00AAAAAAA59A07A4AAAA73A20A66AAAAAA60FFFFFFF
FFFFF00AAAAAAAAAA8AA0A81A61A99AAAAAAAAA70FFFFFFF
FFFFF00AAAAAAAAAAAAAAA71AAAAAAAAAAAAAAA70FFFFFFF
FFFFF00AAAAAAAAAAAAAA4AAA5AAAAAAAAAAAAA60FFFFFFF
FFFFF009AAAAAAAAAAAA908A40AAAAAAAAAAA9930FFFFFFF
FFFFFF05AAAAAAAAAAA9A8AAAAAAAAAA6310000000000FFF
FFFFFF00AAAAAAAAAAA04AAAAA22AA4001456766531000FF
FFFFFF00AAAAAAAAAAA6AAAAAA77A4049AAAAAAAAAA8200F
FFFFFF006AAAAAAAA56AAAAAAAAA401AAAAAAAAAAAAAA00F
FFFFFFF00AAAAAAAA33AAAAAAAAA0007AAAAAAAAAAAA500F
FFFFFFF005AAAAAA8AAAAAAAAAAAA01114689AA98630300F
FFFFFFFF009AAAA30AAAAAAAAAAAA02A864210012479A00F
FFFFFFFF000AAAAA7AAAAAAAAAAAA02AAAAAAAAAAAAAA00F
FFFFFFFFF001AA09AAAAAAAAAAAAA02AAAAAAAAAAAAAA00F
FFFFFFFFFF00191AAAAAAAAAAAAAA02AAAAAAAAAAAAAA00F
FFFFFFFFFFF0006AAAAAAAAAAAAAA02AAAAAAAAAAAAAA00F
FFFFFFFFFFFF00017AAAAAAAAAAAA02AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFF000149AAAAAAA7302AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFF0000001111000002AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFF0000000000002AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF02AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF02AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAA00F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF002AAAAAAAAAAA9000F
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000357876510000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFF
}

!define OFF_DATABASE_PARTITION_5(_alias) ENTITY(rectangle,black,database_partition_5,_alias,OFF DATABASE_PARTITION_5)
!define OFF_DATABASE_PARTITION_5(_alias,_label) ENTITY(rectangle,black,database_partition_5,_label,_alias,OFF DATABASE_PARTITION_5)
!define OFF_DATABASE_PARTITION_5(_alias,_label,_shape) ENTITY(_shape,black,database_partition_5,_label,_alias,OFF DATABASE_PARTITION_5)
!define OFF_DATABASE_PARTITION_5(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_partition_5,_label,_alias,OFF DATABASE_PARTITION_5)
skinparam folderBackgroundColor<<OFF DATABASE_PARTITION_5>> White