sprite $database_mini_1 [48x39/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF00000000000000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFF000000000000000000000000FFFFFFFFFFFF
FFFFFFFFFF0000000001344444432100000000FFFFFFFFFF
FFFFFFFF0000012579AAAAAAAAAAAAA863100000FFFFFFFF
FFFFFFFF00017AAAAAAAAAAAAAAAAAAAAAA930000FFFFFFF
FFFFFFF0006AAAAAAAAAAAAAAAAAAAAAAAAAA8200FFFFFFF
FFFFFFF006AAAAAAAAAAAAAAAAAAAAAAAAAAAA900FFFFFFF
FFFFFFF009AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF004AAAAAAAAAAAAAAAAAAAAAAAAAAAA700FFFFFFF
FFFFFFF00029AAAAAAAAAAAAAAAAAAAAAAAAA5000FFFFFFF
FFFFFFF00100379AAAAAAAAAAAAAAAAAA98510000FFFFFFF
FFFFFFF00A400001469AAAAAAAAAAA85200002900FFFFFFF
FFFFFFF00AA96310000001111111000000258AA00FFFFFFF
FFFFFFF00AAAAAA964211111111112358AAAAAA00FFFFFFF
FFFFFFF00AAAAAAAAAAAAA99999AAAAAAAAAAAA00FFFFFFF
FFFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF009AAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF004AAAAAAAAAAAAAAAAAAAAAAAAAAAA700FFFFFFF
FFFFFFF0006AAAAAAAAAAAAAAAAAAAAAAAAAA9100FFFFFFF
FFFFFFFF00049AAAAAAAAAAAAAAAAAAAAAAA61000FFFFFFF
FFFFFFFFF000037AAAAAAAAAAAAAAAAAA8400000FFFFFFFF
FFFFFFFFF000000012456778877654321000000FFFFFFFFF
FFFFFFFFFFFF000000000000000000000000FFFFFFFFFFFF
FFFFFFFFFFFFFF00000000000000000000FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE_MINI_1(_alias) ENTITY(rectangle,black,database_mini_1,_alias,OFF DATABASE_MINI_1)
!define OFF_DATABASE_MINI_1(_alias,_label) ENTITY(rectangle,black,database_mini_1,_label,_alias,OFF DATABASE_MINI_1)
!define OFF_DATABASE_MINI_1(_alias,_label,_shape) ENTITY(_shape,black,database_mini_1,_label,_alias,OFF DATABASE_MINI_1)
!define OFF_DATABASE_MINI_1(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_mini_1,_label,_alias,OFF DATABASE_MINI_1)
skinparam folderBackgroundColor<<OFF DATABASE_MINI_1>> White