sprite $database_partition_2 [48x46/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF000000000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF000000000000000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF00000169A78A8510000FFFFFFFFFFFFFFFF
FFFFFFFFFFFF00017AAAAA02AAAAA50000FFFFFFFFFFFFFF
FFFFFFFFFFF0006AAAAAAAAAAAAAAAA4000FFFFFFFFFFFFF
FFFFFFFFFF001AAAAAAAAA67AAAAAAAA9000FFFFFFFFFFFF
FFFFFFFFF002AAAAAAAAAA03AAAAAAAAAA000FFFFFFFFFFF
FFFFFFFF002AAAAAAAAAAAAAAAAAAAAAAAA000FFFFFFFFFF
FFFFFFF000AAAAAAAAAAAA67AAAAAAAAAAAA00FFFFFFFFFF
FFFFFFF00AAAAAAAAAAAAA03AAAAAAAAAAAA600FFFFFFFFF
FFFFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFF
FFFFFF00AAAAAAAAAAAAAA57AAAAAAAAAAAAA800FFFFFFFF
FFFFFF01AAAAAAAAAAAAAA03AAAAAAAAAAAAAA00FFFFFFFF
FFFFF009AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA30FFFFFFFF
FFFFF00AAAAAAAAAAAAAAA56AAAAAAAAAAAAAA900FFFFFFF
FFFFF00AAAAAAAAAAAAAAA13AAAAAAAAAAAAAAA00FFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFF02AAAAAAAAAAAAAAA46AAAAAAAAAAAAAAA00FFFFFFF
FFFFF02AAAAAAAAAAAAAAA13AAAAAAAAAAAAAAA00FFFFFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFF00AAAAAAAAAAAAAAA45AAAAAAAAAAAA99900FFFFFFF
FFFFF00AAAAAAAAAAAAAAA13AAAAAAA7420000000000FFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAA91003566766420000FF
FFFFFF04AAAAAAAAAAAAAA35AAAAA007AAAAAAAAAAA600FF
FFFFFF00AAAAAAAAAAAAAA13AAAA80AAAAAAAAAAAAAA60FF
FFFFFF006AAAAAAAAAAAAAAAAAAA803AAAAAAAAAAAA910FF
FFFFFFF00AAAAAAAAAAAAA35AAAA80502579AAA9742030FF
FFFFFFF002AAAAAAAAAAAA14AAAA80AA75310011368A60FF
FFFFFFFF005AAAAAAAAAAAAAAAAA80AAAAAAAAAAAAAA60FF
FFFFFFFFF006AAAAAAAAAA24AAAA80AAAAAAAAAAAAAA60FF
FFFFFFFFFF005AAAAAAAAA14AAAA80AAAAAAAAAAAAAA60FF
FFFFFFFFFFF002AAAAAAAAAAAAAA80AAAAAAAAAAAAAA60FF
FFFFFFFFFFFF0004AAAAAA24AAAA80AAAAAAAAAAAAAA60FF
FFFFFFFFFFFFF000026AAA24AAA510AAAAAAAAAAAAAA60FF
FFFFFFFFFFFFFFF000000111100000AAAAAAAAAAAAAA60FF
FFFFFFFFFFFFFFFFF0000000000000AAAAAAAAAAAAAA60FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAA60FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAA60FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF009AAAAAAAAAAAAA20FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF007AAAAAAAAAAA400FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF00001467876300000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFF
}

!define OFF_DATABASE_PARTITION_2(_alias) ENTITY(rectangle,black,database_partition_2,_alias,OFF DATABASE_PARTITION_2)
!define OFF_DATABASE_PARTITION_2(_alias,_label) ENTITY(rectangle,black,database_partition_2,_label,_alias,OFF DATABASE_PARTITION_2)
!define OFF_DATABASE_PARTITION_2(_alias,_label,_shape) ENTITY(_shape,black,database_partition_2,_label,_alias,OFF DATABASE_PARTITION_2)
!define OFF_DATABASE_PARTITION_2(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_partition_2,_label,_alias,OFF DATABASE_PARTITION_2)
skinparam folderBackgroundColor<<OFF DATABASE_PARTITION_2>> White