sprite $database_server_blue [39x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFF00000000000000000FFFFFFFFFFFFFFF
FFFFF00000000000000000000FFFFFFFFFFFFFF
FFFFF009AAAAAAAAAAAAAAA700FFFFFFFFFFFFF
FFFFF08AAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF0AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF0AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF0AAAA55555555555AAA00FFFFFFFFFFFFF
FFFFF0AAAA00000000000AAA00FFFFFFFFFFFFF
FFFFF0AAAA99999999999AAA00FFFFFFFFFFFFF
FFFFF0AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF0AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF0AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF0AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF0AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF0AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF0AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF0AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF0AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF0AAAAAAAAAAAAAAAAAA00FFFFFFFFFFFFF
FFFFF0AAAAAAAAAAAAAAAAAA0000000FFFFFFFF
FFFFF0AAAAAAAAAAAAAAA63000000000000FFFF
FFFFF0AAAAAAAAAAAAA91013567776531000FFF
FFFFF0AAAAAAAAAAAAA00799999999999700FFF
FFFFF0AAAAAAAAAAAAA07999999999999980FFF
FFFFF0AAAAAAAAAAAAA01899999999999810FFF
FFFFF0AAAAAAAAAAAAA04025778887752040FFF
FFFFF0AAAAAAAAAAAAA09963211111237980FFF
FFFFF0AAAA44444444409999999999999980FFF
FFFFF0AAAA11111111109999999999999980FFF
FFFFF0AAAAAAAAAAAAA09999999999999980FFF
FFFFF0AAAAAAAAAAAAA09999999999999980FFF
FFFFF0AAAA99999999909999999999999980FFF
FFFFF0AAAA00000000009999999999999980FFF
FFFFF0AAAA55555555509999999999999980FFF
FFFFF0AAAAAAAAAAAAA09999999999999980FFF
FFFFF0AAAAAAAAAAAAA09999999999999980FFF
FFFFF0AAAAAAAAAAAAA09999999999999980FFF
FFFFF0666666666666608999999999999970FFF
FFFFF0000000000000000999999999999900FFF
FFFFFFFFFFFFFFFFFFF00028999999972000FFF
FFFFFFFFFFFFFFFFFFFFF00000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFFF000000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE_SERVER_BLUE(_alias) ENTITY(rectangle,black,database_server_blue,_alias,OFF DATABASE_SERVER_BLUE)
!define OFF_DATABASE_SERVER_BLUE(_alias,_label) ENTITY(rectangle,black,database_server_blue,_label,_alias,OFF DATABASE_SERVER_BLUE)
!define OFF_DATABASE_SERVER_BLUE(_alias,_label,_shape) ENTITY(_shape,black,database_server_blue,_label,_alias,OFF DATABASE_SERVER_BLUE)
!define OFF_DATABASE_SERVER_BLUE(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_server_blue,_label,_alias,OFF DATABASE_SERVER_BLUE)
skinparam folderBackgroundColor<<OFF DATABASE_SERVER_BLUE>> White