sprite $database_mini_3 [35x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF000000000000000FFFFFFFFFF
FFFFFFF000000001111100000000FFFFFFF
FFFFF00001369AAAAAAAAAA7310000FFFFF
FFFFF0028AAAAAAAAAAAAAAAAA93000FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAA600FFFF
FFFF008AAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAA500FFFF
FFFF00017AAAAAAAAAAAAAAAAA83000FFFF
FFFF006100368AAAAAAAAA864100600FFFF
FFFF009A7300000111110000036AA00FFFF
FFFF009AAAA9765443445679AAAAA00FFFF
FFFF009AAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF009AAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF009AAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF009AAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF005AAAAAAAAAAAAAAAAAAAAA800FFFF
FFFF0009AAAAAAAAAAAAAAAAAAAA100FFFF
FFFF00004AAAAAAAAAAAAAAAAA60000FFFF
FFFF008100047AAAAAAAAA841000800FFFF
FFFF009AA300000000000000029AA00FFFF
FFFF009AAAAAA964323359AAAAAAA00FFFF
FFFF009AAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF009AAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF009AAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF009AAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF004AAAAAAAAAAAAAAAAAAAAA700FFFF
FFFF0007AAAAAAAAAAAAAAAAAAA9000FFFF
FFFF000038AAAAAAAAAAAAAAA940000FFFF
FFFF008300035788999887630002900FFFF
FFFF009AA531000000000000259AA00FFFF
FFFF009AAAAAA976555678AAAAAAA00FFFF
FFFF009AAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF009AAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF009AAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF008AAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAA600FFFF
FFFFF005AAAAAAAAAAAAAAAAAAA7000FFFF
FFFFF00016AAAAAAAAAAAAAAA72000FFFFF
FFFFFF00000124678887642100000FFFFFF
FFFFFFFF0000000000000000000FFFFFFFF
FFFFFFFFFFFF00000000000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_DATABASE_MINI_3(_alias) ENTITY(rectangle,black,database_mini_3,_alias,OFF DATABASE_MINI_3)
!define OFF_DATABASE_MINI_3(_alias,_label) ENTITY(rectangle,black,database_mini_3,_label,_alias,OFF DATABASE_MINI_3)
!define OFF_DATABASE_MINI_3(_alias,_label,_shape) ENTITY(_shape,black,database_mini_3,_label,_alias,OFF DATABASE_MINI_3)
!define OFF_DATABASE_MINI_3(_alias,_label,_shape,_color) ENTITY(_shape,_color,database_mini_3,_label,_alias,OFF DATABASE_MINI_3)
skinparam folderBackgroundColor<<OFF DATABASE_MINI_3>> White