sprite $mailbox_database [45x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF0000000000FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF0000000000000000000FFFFFFFFFFFFFFFFF
FFFFFFF00000124577776532100000FFFFFFFFFFFFFFF
FFFFFF00027AAAAAAAAAAAAAA951000FFFFFFFFFFFFFF
FFFFF0029AAAAAAAAAAAAAAAAAAA600FFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAA60FFFFFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAA60FFFFFFFFFFFFFF
FFFFF0029AAAAAAAAAAAAAAAAAAA700FFFFFFFFFFFFFF
FFFFF000037AAAAAAAAAAAAAA961020FFFFFFFFFFFFFF
FFFFF01A50001346777765421002790FFFFFFFFFFFFFF
FFFFF01AAA85310000000002469AA90FFFFFFFFFFFFFF
FFFFF01AAAAAAAAA99999AAAAAAAA90FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAA90FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAA90FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAA90FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAA90FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAA90FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAAAAAAAA90FFFFFFFFFFFFFF
FFFFF01AAAAAAAAAAAAAAAA66666650000000000FFFFF
FFFFF01AAAAAAAAAAAAAAA900000000000000000FFFFF
FFFFF01AAAAAAAAAAAAAAA907AAAAAAAAAAAAA40FFFFF
FFFFF01AAAAAAAAAAAAAAA4031000000000002200FFFF
FFFFF01AAAAAAAAAAAAAAA4055555555555555500FFFF
FFFFF01AAAAAAAAAAAAAAA41A5555555555555A00FFFF
FFFFF01AAAAAAAAAAAAAAA4190000000001550A00FFFF
FFFFF01AAAAAAAAAAAAAAA3190000000003AA0A00FFFF
FFFFF01AAAAAAAAAAAAAAA0190000000003AA0A000FFF
FFFFF01AAAAAAAAAAAAAA80890000000001440A600FFF
FFFFF01AAAAAAAAAAAAAA60A90066666400000A900FFF
FFFFF01AAAAAAAAAAAAAA22A90044444300000AA10FFF
FFFFF00AAAAAAAAAAAAAA05A90066666660000AA200FF
FFFFF004AAAAAAAAAAAA808A90033333330000AA500FF
FFFFFF0039AAAAAAAAAA60AA91111111111112AA900FF
FFFFFF0000268AAAAAAA50AAAAAAAAAAAAAAAAAAA00FF
FFFFFFFF00000012223210AAAAAAAAAAAAAAAAAAA00FF
FFFFFFFFFFF00000000000AAAAAAAAAAAAAAAAAAA00FF
FFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAAA00FF
FFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAAAAAAA00FF
FFFFFFFFFFFFFFFFFFFF00222222222222222222100FF
FFFFFFFFFFFFFFFFFFFF00000000000000000000000FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_MAILBOX_DATABASE(_alias) ENTITY(rectangle,black,mailbox_database,_alias,OFF MAILBOX_DATABASE)
!define OFF_MAILBOX_DATABASE(_alias,_label) ENTITY(rectangle,black,mailbox_database,_label,_alias,OFF MAILBOX_DATABASE)
!define OFF_MAILBOX_DATABASE(_alias,_label,_shape) ENTITY(_shape,black,mailbox_database,_label,_alias,OFF MAILBOX_DATABASE)
!define OFF_MAILBOX_DATABASE(_alias,_label,_shape,_color) ENTITY(_shape,_color,mailbox_database,_label,_alias,OFF MAILBOX_DATABASE)
skinparam folderBackgroundColor<<OFF MAILBOX_DATABASE>> White