sprite $monitoring_store [48x45/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFF0000000000000000000000000000000000000FFFFFF
FFFFF0000000000000000000000000000000000000FFFFFF
FFFFF0288888888888888888888888888888888600FFFFFF
FFFFF03A777777777777777777777777777777A700FFFFFF
FFFFF03A1344444444444444444444444444409700FFFFFF
FFFFF03A19AAAAAAAAAAAAAAAAAAAAAAAAAAA19700FFFFFF
FFFFF03A19AAAAAAAAAAAAAAAAAAAAAAAAAAA19700FFFFFF
FFFFF03A19AAAAAAAAAAAAAAAAAAAAAAAAAAA19700FFFFFF
FFFFF03A19AAAAAAAAAAAAAAAAAAAAAAAAAAA19700FFFFFF
FFFFF03A19AAAAAA08AAAAAAAAA9AAAAAAAAA19700FFFFFF
FFFFF03A19AAAAAA03AAAAAAAA40AAAAAAAAA19700FFFFFF
FFFFF03A19AAAAA270AAAAAAAA009AAAAAAAA19700FFFFFF
FFFFF03A19AAAAA0A0AAAAAAA5428AAAAAAAA19700FFFFFF
FFFFF03A18999955A17AAA9990964AAAAAAAA19700FFFFFF
FFFFF03A1111111AA73AA01115AA0A111111109700FFFFFF
FFFFF03A19AAAAAAAA0A92AAAAAA190AAAAAA19700FFFFFF
FFFFF03A19AAAAAAAA0A56AAAAAA225AAAAAA19700FFFFFF
FFFFF03A19AAAAAAAA270AAAAAAA609AAAAAA19700FFFFFF
FFFFF03A19AAAAAAAA712AAAAAAAA1AAAAAAA19700FFFFFF
FFFFF03A19AAAAAAAA906AAAAAAAAAAAA986615500FFFFFF
FFFFF03A19AAAAAAAAA0AAAAAAAAAA83000000000000FFFF
FFFFF03A19AAAAAAAAAAAAAAAAAAA3005799AA99750000FF
FFFFF03A19AAAAAAAAAAAAAAAAAA706AAAAAAAAAAAA600FF
FFFFF03A19AAAAAAAAAAAAAAAAAA40AAAAAAAAAAAAAA00FF
FFFFF03A19AAAAAAAAAAAAAAAAAA4007AAAAAAAAAA7000FF
FFFFF03A10000000000000000000009200134431002900FF
FFFFF03AAAAAAAAAAAAAAAAAAAAA40AAAA987789AAAA00FF
FFFFF0033333333333333333333310AAAAAAAAAAAAAA00FF
FFFFF0000000000000000000000000AAAAAAAAAAAAAA00FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAA00FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAA00FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAA00FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAA00FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAA00FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAA00FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAA00FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAAAAA00FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF003AAAAAAAAAAAA200FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF00037AAAAA972000FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000FFFFFF
}

!define OFF_MONITORING_STORE(_alias) ENTITY(rectangle,black,monitoring_store,_alias,OFF MONITORING_STORE)
!define OFF_MONITORING_STORE(_alias,_label) ENTITY(rectangle,black,monitoring_store,_label,_alias,OFF MONITORING_STORE)
!define OFF_MONITORING_STORE(_alias,_label,_shape) ENTITY(_shape,black,monitoring_store,_label,_alias,OFF MONITORING_STORE)
!define OFF_MONITORING_STORE(_alias,_label,_shape,_color) ENTITY(_shape,_color,monitoring_store,_label,_alias,OFF MONITORING_STORE)
skinparam folderBackgroundColor<<OFF MONITORING_STORE>> White