sprite $web_store [43x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF0000000000000FFFFFFFFFFFFFFFFFF
FFFFFFFF000000000111000000000FFFFFFFFFFFFFF
FFFFFF0000059AAAAAAAAAAA9610000FFFFFFFFFFFF
FFFFF00039AAAAAAAAAAAAAAAAA94000FFFFFFFFFFF
FFFFF007AAAAAAAAAAAAAAAAAAAAA700FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA10FFFFFFFFFFF
FFFFF007AAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFFF
FFFFF0003AAAAAAAAAAAAAAAAAAA4000FFFFFFFFFFF
FFFFF00400259AAAAAAAAAAA95200310FFFFFFFFFFF
FFFFF00A950000112222211000048A10FFFFFFFFFFF
FFFFF00AAAA975421101123579AAAA10FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA10FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA10FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA10FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA10FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA10FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAA10FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAA8650000FFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA61000000000FFFFFFF
FFFFF00AAAAAAAAAAAAAAAA810105738100000FFFFF
FFFFF00AAAAAAAAAAAAAAA701725A83A9083000FFFF
FFFFF00AAAAAAAAAAAAAA800671AA83AA53A100FFFF
FFFFF00AAAAAAAAAAAAAA1161038A83A97004400FFF
FFFFF00AAAAAAAAAAAAA507AA04200001326AA100FF
FFFFF00AAAAAAAAAAAAA02AA73AAA82AAA81AA800FF
FFFFF00AAAAAAAAAAAA806AA55AAA82AAAA0AAA00FF
FFFFF00AAAAAAAAAAAA5016A37AAA82AAAA1A82000F
FFFFF00AAAAAAAAAAAA3193006AAA82AAA91117400F
FFFFF00AAAAAAAAAAAA31AAA1100220210108AA500F
FFFFF00AAAAAAAAAAAA31AAA28AA85178AA19AA500F
FFFFF00AAAAAAAAAAAA50AAA37AAA83AAAA0AAA200F
FFFFF006AAAAAAAAAAA7018A45AAA83AAAA0A8100FF
FFFFF0007AAAAAAAAAAA011143AAA83AAA9010500FF
FFFFFF000189AAAAAAAA40972003552651016A100FF
FFFFFFF0000003578999702AA25532046919A600FFF
FFFFFFFFFF00000000000003A72AA83AA61A8000FFF
FFFFFFFFFFFFFFFF00000F002926A83AA086000FFFF
FFFFFFFFFFFFFFFFFFFFFFF00030773A120000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFF000000000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_WEB_STORE(_alias) ENTITY(rectangle,black,web_store,_alias,OFF WEB_STORE)
!define OFF_WEB_STORE(_alias,_label) ENTITY(rectangle,black,web_store,_label,_alias,OFF WEB_STORE)
!define OFF_WEB_STORE(_alias,_label,_shape) ENTITY(_shape,black,web_store,_label,_alias,OFF WEB_STORE)
!define OFF_WEB_STORE(_alias,_label,_shape,_color) ENTITY(_shape,_color,web_store,_label,_alias,OFF WEB_STORE)
skinparam folderBackgroundColor<<OFF WEB_STORE>> White