sprite $3rd_party_service [47x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF0FFFFFFF00FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF000000FFFF00000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF0000300FFF00120000FFFFFFFFFFFFFFFF
FFFFFFFFFFFF0016AA700FF008AA4000FFFFFFFFFFFFFFF
FFFFFFFFFFFF00AAAAA000002AAAAA00FFFFFFFFFFFFFFF
FFFFFFFFFFFF00AAAAA400006AAAA800FFFFFFFFFFFFFFF
FFFFFFFFFFFFF04AAAAA9AA8AAAAA100FFFFFFFFFFFFFFF
FFFFFFFFFFFFF00AAAAAAAAAAAAAA00FFFFFFFFFFFFFFFF
FFFFFFF0000F001AAAAAAAAAAAAA9000F0000FFFFFFFFFF
FFFFFF00000002AAAAAAA99AAAAAA900000000FFFFFFFFF
FFFFFF01A9501AAAAA62000027AAAA9006A900FFFFFFFFF
FFFFF005AAAAAAAAA1000000003AAAA9AAAA30FFFFFFFFF
FFFFF009AAAAAAAA000FFFFF0001AAAAAAAA800FFFFFFFF
FFFFF02AAAAAAAA100FFFFFFFF003AAAAAAAA00FFFFFFFF
FFFFF007AAAAAA700FFFFFFFFFF009AAAAAA500FFFFFFFF
FFFFF00004AAAA10FFFFFFFFFFF004AAAA30000FFFFFFFF
FFFFFF00008AAA00FFFFFFFFFFFF00AAA60000FFFFFFFFF
FFFFFFFF008AAA00FFFFFFFFFFFF00AAA70FFFFFFFFFFFF
FFFFFFFF008AAA00FFFFFFFFFFFF00AAA70FFFFFFFFFFFF
FFFFFFF0008AAA00FFFFFFFFFFFF00AAA600FFFFFFFFFFF
FFFFF00003AAAA00FFFFFFF0000000000000000000FFFFF
FFFFF006AAAAAA600FFFFFF007AAAAAAAAAAAAAA300FFFF
FFFFF02AAAAAAAA000FFFFF04AAAAAAAAAAAAAAAA00FFFF
FFFFF00AAAAAAAAA000FFFF04AAAAAAAAAAAAAAAA00FFFF
FFFFF005AAAAAAAAA00000004AAAAAAAAAAAAAAAA00FFFF
FFFFFF01AA601AAAAA5100004AAA9769AAAAAAAAA00FFFF
FFFFFF00000002AAAAAAA9904AAA20005AAAA4AAA00FFFF
FFFFFFF0000F002AAAAAAAA04AAA8AA00A1743AAA00FFFF
FFFFFFFFFFFFF00AAAAAAAA04AAAAA902A3893AAA00FFFF
FFFFFFFFFFFF004AAAAA9AA04AAAA001AA8A89AAA00FFFF
FFFFFFFFFFFF009AAAA500004AAAA6401AAAAAAAA00FFFF
FFFFFFFFFFFF00AAAAA000004AAAAAA10AAAAAAAA00FFFF
FFFFFFFFFFFF0027AA800FF04AAA46600AAAAAAAA00FFFF
FFFFFFFFFFFFF0001500FFF04AAA20028AAAAAAAA00FFFF
FFFFFFFFFFFFFF000000FFF04AAAAAAAAAAAAAAAA00FFFF
FFFFFFFFFFFFFFFFF00FFFF04AAAAAAAAAAAAAAAA00FFFF
FFFFFFFFFFFFFFFFFFFFFFF04AAAAAAAAAAAAAAAA00FFFF
FFFFFFFFFFFFFFFFFFFFFFF019AAAAAAAAAAAAAA600FFFF
FFFFFFFFFFFFFFFFFFFFFFF00000000000000000000FFFF
FFFFFFFFFFFFFFFFFFFFFFFF000000000000000000FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_3RD_PARTY_SERVICE(_alias) ENTITY(rectangle,black,3rd_party_service,_alias,OFF 3RD_PARTY_SERVICE)
!define OFF_3RD_PARTY_SERVICE(_alias,_label) ENTITY(rectangle,black,3rd_party_service,_label,_alias,OFF 3RD_PARTY_SERVICE)
!define OFF_3RD_PARTY_SERVICE(_alias,_label,_shape) ENTITY(_shape,black,3rd_party_service,_label,_alias,OFF 3RD_PARTY_SERVICE)
!define OFF_3RD_PARTY_SERVICE(_alias,_label,_shape,_color) ENTITY(_shape,_color,3rd_party_service,_label,_alias,OFF 3RD_PARTY_SERVICE)
skinparam folderBackgroundColor<<OFF 3RD_PARTY_SERVICE>> White