sprite $access_services [48x43/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00000FFFF00000000FFFFFFFFF
FFFFFFFFFFFFFF000FFFF001100000000002520000FFFFFF
FFFFFFFFFFFFF00000FFF00AAAA00259AABBB30000000FFF
FFFFFFFFFFF0005A400FF02AAAA08BBBBBBBBA999A6000FF
FFFFFFFFFF002AAAA100004AAAA08BBBBBBBB300000800FF
FFFFFFFFFF00AAAAA802349AAAA08BBBBBBBB300002900FF
FFFFFFFFFF002AAAAAAAAAAAAAA08BBA16BBB878775600FF
FFFFFFFFFFF007AAAAAAAAAAAAA08BB803BBB300000600FF
FFFFFFFFFFF001AAAAAAAAAAAAA08BB460ABB500027900FF
FFFFFFFFFFF008AAAAA300003AA08BA0818BB456520600FF
FFFFFF0000004AAAA300000000408BA0204BB300000800FF
FFFFF0047311AAAA200FFFFF00008B74B71BB854578700FF
FFFFF009AAAAAAA400FFFFFFFF008BBBBBBBB301000600FF
FFFFF00AAAAAAA900FFFFFFFFFF08BBBBBBBB300003800FF
FFFFF03AAAAAAA400FFFFFFFFFF08BBBBBBBB878773000FF
FFFFF02AAAAAAA10FFFFFFFFFFF001247ABBB30000000FFF
FFFFF000029AAA00FFFFFFFFFFF0000000001000000FFFFF
FFFFFF00004AAA00FFFFFFFFFFFF00AAAA61000FFFFFFFFF
FFFFFFFFF01AAA20FFFFFFFFFFFF00AAAAAAA10FFFFFFFFF
FFFFFFFFF00AAA500FFFFFFFFFF006AAAAAAA10FFFFFFFFF
FFFFFFFF000AAAA000FFFFFFFFF00AAAAAAAA00FFFFFFFFF
FFFFFF00029AAAA6000FFFFFFF007AAAAAAA800FFFFFFFFF
FFFFFF007AAAAAAA5000FFFF0006AAA90024100FFFFFFFFF
FFFFFF00AAAAAAAAA8000000008AAAA1000000FFFFFFFFFF
FFFFFF004AAAAAAAAAA930039AAAAA300FFFFFFFFFFFFFFF
FFFFFFF009AA504AAAAAAAAAAAAAAA000FFFFFFFFFFFFFFF
FFFFFFFF007000019AAAAAAAAAAAAA800FFFFFFFFFFFFFFF
FFFFFFFF00000F000AAAAAAAA8AAAAA300FFFFFFFFFFFFFF
FFFFFFFFFF0FFFF01AAAA921007AAAA800FFFFFFFFFFFFFF
FFFFFFFFFFFFFF005AAAA400000AAA7000FFFFFFFFFFFFFF
FFFFFFFFFFFFFF008AAAA00FF003A1000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0017AAA00FFF00000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF00000000FFFFF0FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_ACCESS_SERVICES(_alias) ENTITY(rectangle,black,access_services,_alias,OFF ACCESS_SERVICES)
!define OFF_ACCESS_SERVICES(_alias,_label) ENTITY(rectangle,black,access_services,_label,_alias,OFF ACCESS_SERVICES)
!define OFF_ACCESS_SERVICES(_alias,_label,_shape) ENTITY(_shape,black,access_services,_label,_alias,OFF ACCESS_SERVICES)
!define OFF_ACCESS_SERVICES(_alias,_label,_shape,_color) ENTITY(_shape,_color,access_services,_label,_alias,OFF ACCESS_SERVICES)
skinparam folderBackgroundColor<<OFF ACCESS_SERVICES>> White