sprite $business_connectivity_services [36x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFF000000000FFFFFFFFFFFFF
FFFFFFFFFFFFF00069A95000FFFFFFFFFFFF
FFFFFFFFFFFF000AAAAAA900FFFFFFFFFFFF
FFFFFFFFFFFF00AAAAAAAA900FFFFFFFFFFF
FFFFFFFFFFFF04AAAAAAAAA10FFFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAA800FFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAAA00FFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAAA00FFFFFFFFFF
FFFFFFFFFFF00AAAAAAAAAAA00FFFFFFFFFF
FFFFFFFFFFF008AAAAAAAAA400FFFFFFFFFF
FFFFFFFFFFFF00AAAAAAAAA00FFFFFFFFFFF
FFFFFFFFFFFF004AAAAAAA200FFFFFFFFFFF
FFFFFFFFFFF00003AAAAA20000FFFFFFFFFF
FFFFFFFFF0000100023200010000FFFFFFFF
FFFFFFFF0006AA500000006AA4000FFFFFFF
FFFFFFF002AAAAA953236AAAAA8000FFFFFF
FFFFFFF00AAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFF005AAAAAAAAAAAAAAAAAAA20FFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAA800FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF03AAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAA20FFFFF
FFFFF007AAAAAAAAAAAAAAAAAAAAA40FFFFF
FFFFF00788888888888888888888840FFFFF
FFFFF00000000000011000000000000FFFFF
FFFFF000000000000AA7000000000000FFFF
FFFFFFFFFFFFFFF00AA70FFFFFFFFFFFFFFF
FFFFFFFFFFFFF0000996000FFFFFFFFFFFFF
FFFFF00000000001111110000000000FFFFF
FFFFF0000000000AAAAAA7000000000FFFFF
FFFFF00AAAAAAA0AAAAAA73AAAAAA70FFFFF
FFFFF00AAAAAAA0AAAAAA73AAAAAA70FFFFF
FFFFF0066666660AAAAAA7266666630FFFFF
FFFFF00000000006666664000000000FFFFF
FFFFFFFFFFFFF0000000000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_BUSINESS_CONNECTIVITY_SERVICES(_alias) ENTITY(rectangle,black,business_connectivity_services,_alias,OFF BUSINESS_CONNECTIVITY_SERVICES)
!define OFF_BUSINESS_CONNECTIVITY_SERVICES(_alias,_label) ENTITY(rectangle,black,business_connectivity_services,_label,_alias,OFF BUSINESS_CONNECTIVITY_SERVICES)
!define OFF_BUSINESS_CONNECTIVITY_SERVICES(_alias,_label,_shape) ENTITY(_shape,black,business_connectivity_services,_label,_alias,OFF BUSINESS_CONNECTIVITY_SERVICES)
!define OFF_BUSINESS_CONNECTIVITY_SERVICES(_alias,_label,_shape,_color) ENTITY(_shape,_color,business_connectivity_services,_label,_alias,OFF BUSINESS_CONNECTIVITY_SERVICES)
skinparam folderBackgroundColor<<OFF BUSINESS_CONNECTIVITY_SERVICES>> White