sprite $central_management_service [45x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF00000000000000FFFFFFFFFFFFFFFFFFF
FFFFFFFFF000000001232100000000FFFFFFFFFFFFFFF
FFFFFFF0000389AAAAAAAAAAA961000FFFFFFFFFFFFFF
FFFFFF0008AAAAAAAAAAAAAAAAAAA500FFFFFFFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAA800FFFFFFFFFFFF
FFFFFF04AAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFF00AAAAAAAAAAAAAAAAAAAAAA700FFFFFFFFFFFF
FFFFFF0005AAAAAAAAAAAAAAAAAA92000FFFFFFFFFFFF
FFFFFF04100258AAAAAAAAAAA74100500FFFFFFFFFFFF
FFFFFF05A840000112222110000169A00FFFFFFFFFFFF
FFFFFF05AAAA986432212235789AAAA00FFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAAAA6116000000FFFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAA9002200004100FFFFFFF
FFFFFF05AAAAAAAAAAAAAAAAA109AA0000AA700FFFFFF
FFFFFF05AAAAAAAAAAAAAAAAA20AAA2218AAA00FFFFFF
FFFFFF05AAAAAAAAAAAAAAA8A909AAAAAAAA20F000FFF
FFFFFF05AAAAAAAAAAAAAA000109AAAAAAAA400000FFF
FFFFFF05AAAAAAAAAAAAA307208AA95336AAA504600FF
FFFFFF05AAAAAAAAAAAAA05AA9AA60000008AAAAA00FF
FFFFFF05AAAAAAAAAAAA90AAAAA700000000AAAAA70FF
FFFFFF05AAAAAAAAAAAAA028AAA0000000002AAA710FF
FFFFFF05AAAAAAAAAAAAA7107AA0000000000AA2000FF
FFFFFF05AAAAAAAAAAAAAAA07AA0000000000AA200FFF
FFFFFF05AAAAAAAAAAAAA7008AA0000000000AA2000FF
FFFFFF03AAAAAAAAAAAAA028AAA0000000003AAA610FF
FFFFFF00AAAAAAAAAAAA90AAAAA800000000AAAAA80FF
FFFFFF0009AAAAAAAAAAA05AAAAA60000009AA9AA10FF
FFFFFFF00038AAAAAAAAA408309AAA4226AAA501700FF
FFFFFFFFF0000035788887000008AAAAAAAA500000FFF
FFFFFFFFFFF00000000000000007AAAAAAAA40FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF00AAA1006AAA00FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF009AA0000AA800FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF000010F003000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF0000FF0000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_CENTRAL_MANAGEMENT_SERVICE(_alias) ENTITY(rectangle,black,central_management_service,_alias,OFF CENTRAL_MANAGEMENT_SERVICE)
!define OFF_CENTRAL_MANAGEMENT_SERVICE(_alias,_label) ENTITY(rectangle,black,central_management_service,_label,_alias,OFF CENTRAL_MANAGEMENT_SERVICE)
!define OFF_CENTRAL_MANAGEMENT_SERVICE(_alias,_label,_shape) ENTITY(_shape,black,central_management_service,_label,_alias,OFF CENTRAL_MANAGEMENT_SERVICE)
!define OFF_CENTRAL_MANAGEMENT_SERVICE(_alias,_label,_shape,_color) ENTITY(_shape,_color,central_management_service,_label,_alias,OFF CENTRAL_MANAGEMENT_SERVICE)
skinparam folderBackgroundColor<<OFF CENTRAL_MANAGEMENT_SERVICE>> White