sprite $excel_services [48x40/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF000000000000000000000FFFFFF
FFFFFFFFFFFFF0000FFFF05630000013579600000000FFFF
FFFFFFFFFFFF001200FF00AAA908ABBBBBBA88888800FFFF
FFFFFFFFFFF005AA00FF01AAA90ABBBBBBB600000320FFFF
FFFFFFFFFF00AAAAA00004AAA90ABBBBBBBBB5BB5320FFFF
FFFFFFFFFF00AAAAA779AAAAA80AB89B4BB952552320FFFF
FFFFFFFFFF000AAAAAAAAAAAA90AB8272BBBB5BB5320FFFF
FFFFFFFFFFF006AAAAAAAAAAA90ABB00BBB600000320FFFF
FFFFFFFFFFF008AAAA963258A90ABB30BBBBB5BB5320FFFF
FFFFFF0000005AAAA2000000060AB9128BB952552320FFFF
FFFFFF026101AAA90000FFF0000AB2680BBBA5AA4320FFFF
FFFFF008AAAAAAA00FFFFFFFF00ABBBBBBBBB5BB5320FFFF
FFFFF00AAAAAAA50FFFFFFFFF00ABBBBBBBA83883320FFFF
FFFFF01AAAAAAA00FFFFFFFFF00ABBBBBBB733333520FFFF
FFFFF01AAAAAA900FFFFFFFFF00012369BB722222200FFFF
FFFFF000009AA800FFFFFFFFFFF0220000000000000FFFFF
FFFFFFF0006AA900FFFFFFFFFFF04AAAA6200FFFFFFFFFFF
FFFFFFFFF04AAA00FFFFFFFFFF008AAAAAA40FFFFFFFFFFF
FFFFFFFFF02AAA20FFFFFFFFFF00AAAAAAA20FFFFFFFFFFF
FFFFFFFF002AAA800FFFFFFFF005AAAAAAA00FFFFFFFFFFF
FFFFFF0007AAAAA4000FFFFF001AAA969A900FFFFFFFFFFF
FFFFFF00AAAAAAAA5000000002AAAA100000FFFFFFFFFFFF
FFFFFF008AAAAAAAA92000018AAAA3000000FFFFFFFFFFFF
FFFFFFF00AAA92AAAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFFFF004930019AAAAAAAAAAAAA000FFFFFFFFFFFFFFFF
FFFFFFFF000000008AAAAAAAAAAAA800FFFFFFFFFFFFFFFF
FFFFFFFFF000FF009AAAA5320AAAAA20FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00AAAA800002AAA700FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00AAAA30FF00790000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0068AA00FFF00000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF00000100FFFF000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_EXCEL_SERVICES(_alias) ENTITY(rectangle,black,excel_services,_alias,OFF EXCEL_SERVICES)
!define OFF_EXCEL_SERVICES(_alias,_label) ENTITY(rectangle,black,excel_services,_label,_alias,OFF EXCEL_SERVICES)
!define OFF_EXCEL_SERVICES(_alias,_label,_shape) ENTITY(_shape,black,excel_services,_label,_alias,OFF EXCEL_SERVICES)
!define OFF_EXCEL_SERVICES(_alias,_label,_shape,_color) ENTITY(_shape,_color,excel_services,_label,_alias,OFF EXCEL_SERVICES)
skinparam folderBackgroundColor<<OFF EXCEL_SERVICES>> White