sprite $network_file_share_service [48x42/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF0018999999999300FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF001AAAAAAAAAAAA00FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF002AAAAAAAAAAAAA00FFFFFF
FFFFFFFFFFFFFFFFFFFFFFF002AAAAAAAAAAAAAA00FFFFFF
FFFFFFFF0000000000000000000000000000000000FFFFFF
FFFFFFF00377777777777777777777777777777700FFFFFF
FFFFFFF02AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFF05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFF05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFF05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFF05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFF05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFF05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFF05AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFF
FFFFFFF05AAAAAAAAAAAAAAAAAAAA83007A7002800FFFFFF
FFFFFFF05AAAAAAAAAAAAAAAAAAA601631A1261000FFFFFF
FFFFFFF05AAAAAAAAAAAAAAAAAAA11AA80008AA200FFFFFF
FFFFFFF05AAAAAAAAAAAAAAAAAAA40AAA666AAA000FFFFFF
FFFFFFF05AAAAAAAAAAAAAAAA624608AAAAAAA900000FFFF
FFFFFFF05AAAAAAAAAAAAAAA801004AAAA8AAAA500000FFF
FFFFFFF05AAAAAAAAAAAAAAA31AA5AA9000008AA7AA30FFF
FFFFFFF05AAAAAAAAAAAAAAA07AAAA900000008AAAA700FF
FFFFFFF05AAAAAAAAAAAAAAA049AAA000000000AAAA600FF
FFFFFFF05AAAAAAAAAAAAAAA7107AA0000000008A8000FFF
FFFFFFF05AAAAAAAAAAAAAAAAA17A90000000006A800FFFF
FFFFFFF05AAAAAAAAAAAAAAA8207AA0000000008A8000FFF
FFFFFFF05AAAAAAAAAAAAAAA028AAA000000000AAA8300FF
FFFFFFF05AAAAAAAAAAAAAAA07AAAA800000006AAAA900FF
FFFFFFF0377777777777777722AAAAA7000006AA8AA40FFF
FFFFFFF00000000000000000003007AAA968AAA800000FFF
FFFFFFFFFFFFFFFFFFFFFFFFF000006AAAAAAAA00000FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00AAA888AAA00FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF00AA90008AA30FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF0027400038300FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000F00000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000FFF00FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_NETWORK_FILE_SHARE_SERVICE(_alias) ENTITY(rectangle,black,network_file_share_service,_alias,OFF NETWORK_FILE_SHARE_SERVICE)
!define OFF_NETWORK_FILE_SHARE_SERVICE(_alias,_label) ENTITY(rectangle,black,network_file_share_service,_label,_alias,OFF NETWORK_FILE_SHARE_SERVICE)
!define OFF_NETWORK_FILE_SHARE_SERVICE(_alias,_label,_shape) ENTITY(_shape,black,network_file_share_service,_label,_alias,OFF NETWORK_FILE_SHARE_SERVICE)
!define OFF_NETWORK_FILE_SHARE_SERVICE(_alias,_label,_shape,_color) ENTITY(_shape,_color,network_file_share_service,_label,_alias,OFF NETWORK_FILE_SHARE_SERVICE)
skinparam folderBackgroundColor<<OFF NETWORK_FILE_SHARE_SERVICE>> White