sprite $powerpoint_automation_services [48x41/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00000FFFFF00000000FFFFFFFF
FFFFFFFFFFFFFF0000FFFF01500000000000220000000FFF
FFFFFFFFFFFF0000000FF009AAA1013578888411111000FF
FFFFFFFFFFF0005AA00FF00AAAA1288888888644444600FF
FFFFFFFFFFF019AAA700001AAAA1288888888402000400FF
FFFFFFFFFFF03AAAAA34789AAAA1288887888738700400FF
FFFFFFFFFFF008AAAAAAAAAAAAA1288500188838850400FF
FFFFFFFFFFFF00AAAAAAAAAAAAA1288507088833320400FF
FFFFFFFFFFFF008AAAAAA989AAA1288505088888800400FF
FFFFFFF0000005AAAA7200000491288502688888600400FF
FFFFFF0000002AAAA30000000001288508888653000400FF
FFFFFF00A9859AAA2000FFFFF000288608888400000400FF
FFFFFF04AAAAAAA600FFFFFFFF00288888888777760400FF
FFFFF009AAAAAAA00FFFFFFFFFF0288888888400000400FF
FFFFF00AAAAAAA800FFFFFFFFFF0278888888777777600FF
FFFFF00479AAAA40FFFFFFFFFFF0000235678400000000FF
FFFFFF00002AAA30FFFFFFFFFFF000431000000000000FFF
FFFFFFFF000AAA50FFFFFFFFFFFF009AAA986000FFFFFFFF
FFFFFFFFF009AA800FFFFFFFFFFF00AAAAAAA400FFFFFFFF
FFFFFFFFF006AAA00FFFFFFFFFF005AAAAAAA20FFFFFFFFF
FFFFFFF00008AAA600FFFFFFFF000AAAAAAAA00FFFFFFFFF
FFFFFFF004AAAAAA3000FFFFF0008AAA568A700FFFFFFFFF
FFFFFFF06AAAAAAAA40000000008AAA80000000FFFFFFFFF
FFFFFFF01AAAAAAAAA82000005AAAAA0000000FFFFFFFFFF
FFFFFFF007AAA66AAAAAAAAAAAAAAA100FFFFFFFFFFFFFFF
FFFFFFFF00A91003AAAAAAAAAAAAAA600FFFFFFFFFFFFFFF
FFFFFFFFF000000009AAAAAAAAAAAAA100FFFFFFFFFFFFFF
FFFFFFFFF0000FF009AAAA87527AAAAA00FFFFFFFFFFFFFF
FFFFFFFFFFFFFFF00AAAA900000AAAA500FFFFFFFFFFFFFF
FFFFFFFFFFFFFFF00AAAA500F004A9100FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF00AAAA30FFF000000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF00002500FFFF0000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF000000FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_POWERPOINT_AUTOMATION_SERVICES(_alias) ENTITY(rectangle,black,powerpoint_automation_services,_alias,OFF POWERPOINT_AUTOMATION_SERVICES)
!define OFF_POWERPOINT_AUTOMATION_SERVICES(_alias,_label) ENTITY(rectangle,black,powerpoint_automation_services,_label,_alias,OFF POWERPOINT_AUTOMATION_SERVICES)
!define OFF_POWERPOINT_AUTOMATION_SERVICES(_alias,_label,_shape) ENTITY(_shape,black,powerpoint_automation_services,_label,_alias,OFF POWERPOINT_AUTOMATION_SERVICES)
!define OFF_POWERPOINT_AUTOMATION_SERVICES(_alias,_label,_shape,_color) ENTITY(_shape,_color,powerpoint_automation_services,_label,_alias,OFF POWERPOINT_AUTOMATION_SERVICES)
skinparam folderBackgroundColor<<OFF POWERPOINT_AUTOMATION_SERVICES>> White