sprite $push_notification_service [44x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF000147741000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF0006AAAAAA5000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF007AAAA9AAA600FFFFFFF
FFFFFFFF00000000000000003AAA710AAAA200FFFFFF
FFFFFFF000000000000000008AAA220AAAA700FFFFFF
FFFFFF002788888888888840AAAAA40AAAA900FFFFFF
FFFFFF00AAAAAAAAAAAAAA40AAAAA40AAAAA00FFFFFF
FFFFFF01AAAAAAAAAAAAAA50AAAAA40AAAA900FFFFFF
FFFFFF01AAAAAAAAAAAAAA708AAAA40AAAA700FFFFFF
FFFFFF01AAAAAAAAAAAAAAA13AAAA99AAAA10FFFFFFF
FFFFFF01AAAAAAAAAAAAAAA606AAAAAAAA500FFFFFFF
FFFFFF01AAAAAAAAAAAAAAAA305AAAAAA400FFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAA40135530000FFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAA93000000FFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAAAA69AA000FFFFFFFFFF
FFFFFF01AAAAAAAAAAAAAAAAA20006A000000FFFFFFF
FFFFFF01AAAAAAAAAAAAAAAA206A10A05A400FFFFFFF
FFFFFF01AAAAAAAAAAAAAAAA06AA9000AAA30FFFFFFF
FFFFFF01AAAAAAAAAAAAAAAA31AAA9A9AA900F00FFFF
FFFFFF01AAAAAAAAAAAAA204209AAAAAAA8000000FFF
FFFFFF01AAAAAAAAAAAA502008AAA878AAA600200FFF
FFFFFF01AAAAAAAAAAAA05AA8AA6000007AA8AA300FF
FFFFFF01AAAAAAAAAAA80AAAAA500000007AAAA800FF
FFFFFF01AAAAAAAAAAA806AAAA000000000AAAA600FF
FFFFFF00AAAAAAAAAAAA4009A50000000007A8000FFF
FFFFFF002899999999999708A40000000006A700FFFF
FFFFFFF00000000000000008A50000000007A7000FFF
FFFFFFFF000000000000038AA9000000000AAA6200FF
FFFFFFFFFFFFFFFFFFF00AAAAA300000005AAAAA00FF
FFFFFFFFFFFFFFFFFFF006AAAAA3000004AA9AA500FF
FFFFFFFFFFFFFFFFFFFF016219AA84358AA801400FFF
FFFFFFFFFFFFFFFFFFFF0000019AAAAAAA9000000FFF
FFFFFFFFFFFFFFFFFFFFF000009AAAAAAA900000FFFF
FFFFFFFFFFFFFFFFFFFFFFFF04AAA000AAA30FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF018A40006A710FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF000100F001000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF00000F0000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_PUSH_NOTIFICATION_SERVICE(_alias) ENTITY(rectangle,black,push_notification_service,_alias,OFF PUSH_NOTIFICATION_SERVICE)
!define OFF_PUSH_NOTIFICATION_SERVICE(_alias,_label) ENTITY(rectangle,black,push_notification_service,_label,_alias,OFF PUSH_NOTIFICATION_SERVICE)
!define OFF_PUSH_NOTIFICATION_SERVICE(_alias,_label,_shape) ENTITY(_shape,black,push_notification_service,_label,_alias,OFF PUSH_NOTIFICATION_SERVICE)
!define OFF_PUSH_NOTIFICATION_SERVICE(_alias,_label,_shape,_color) ENTITY(_shape,_color,push_notification_service,_label,_alias,OFF PUSH_NOTIFICATION_SERVICE)
skinparam folderBackgroundColor<<OFF PUSH_NOTIFICATION_SERVICE>> White