sprite $response_group_service [48x46/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF00000000000000000000000000000000FFFFFFFF
FFFFFFF0003552000055555555555555555555200FFFFFFF
FFFFFFF00AAAAA900AAAAAAAAAAAAAAAAAAAAAA40FFFFFFF
FFFFFFF04AAAAAA22AAAAAAAAAAAAAAAAAAAAAA90FFFFFFF
FFFFFFF04AAAAAA32AAA9333333333333335AAA90FFFFFFF
FFFFFFF04AAAAAA32AAA7000000000000000AAA90FFFFFFF
FFFFFFF03AAAAAA22AAA7000000000000000AAA90FFFFFFF
FFFFFFF03AAAAAA22AAA7000000000000000AAA90FFFFFFF
FFFFFFF02AAAAAA22AAA7000000000000000AAA90FFFFFFF
FFFFFFF02AAAAAA22AAA7000000000000000AAA90FFFFFFF
FFFFFFF01AAAAAA22AAAA666666666666667AAA90FFFFFFF
FFFFFFF01AAAAAA12AAAAAAAAAAAAAAAAAAAAAA90FFFFFFF
FFFFFFF01AAAAAA12AAAAAAAAAAAAAAAAAAAAAA90FFFFFFF
FFFFFFF01AAAAAA12AAAAA889A988AA988AAAAA90FFFFFFF
FFFFFFF01AAAAAA12AAAA6001A2002A0006AAAA90FFFFFFF
FFFFFFF01AAAAAA12AAAA8335A5336A4338AAAA90FFFFFFF
FFFFFFF01AAAAAA12AAAAAAAAAAAAAAAAAAAAAA90FFFFFFF
FFFFFFF01AAAAAA12AAAA7002A3003A0007AA41000FFFFFF
FFFFFFF01AAAAAA12AAAA6001A2002A0006A0023000FFFFF
FFFFFFF02AAAAAA22AAAAAAAAAAAAAAAAAA20AAAA100FFFF
FFFFFFF02AAAAAA22AAAA9445AA82016AA908AAAA900FFFF
FFFFFFF03AAAAAA22AAAA6001A5013202A70AAAAAA00FFFF
FFFFFFF03AAAAAA22AAAAA888805AAA705709AAAAA00FFFF
FFFFFFF04AAAAAA32AAAAAAAA31AAAAA30A07AAAA800FFFF
FFFFFFF04AAAAAA32AAAAAAAA14AAAAA706009AA9000FFFF
FFFFFFF04AAAAAA32AAAAAAAA24AAAAA70010000001000FF
FFFFFFF01AAAAAA11AAAAAAAA40AAAAA208AA7117AA800FF
FFFFFFF0049A993006AAAAAA9303AAA605AAAAAAAAAA500F
FFFFFFFF000000000000000000300200316AAAAAAAAA900F
FFFFFFFFFF0000FFF00000003AAA5359AA45AAAAAAAAA00F
FFFFFFFFFFFFFFFFFFFFFF00AAAAAAAAAAA1AAAAAAAAA10F
FFFFFFFFFFFFFFFFFFFFFF02AAAAAAAAAAA39AAAAAAAA20F
FFFFFFFFFFFFFFFFFFFFFF04AAAAAAAAAAA500000000000F
FFFFFFFFFFFFFFFFFFFFFF06AAAAAAAAAAA600000000000F
FFFFFFFFFFFFFFFFFFFFF007AAAAAAAAAAA700FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF00000000000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF00000000000000000FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_RESPONSE_GROUP_SERVICE(_alias) ENTITY(rectangle,black,response_group_service,_alias,OFF RESPONSE_GROUP_SERVICE)
!define OFF_RESPONSE_GROUP_SERVICE(_alias,_label) ENTITY(rectangle,black,response_group_service,_label,_alias,OFF RESPONSE_GROUP_SERVICE)
!define OFF_RESPONSE_GROUP_SERVICE(_alias,_label,_shape) ENTITY(_shape,black,response_group_service,_label,_alias,OFF RESPONSE_GROUP_SERVICE)
!define OFF_RESPONSE_GROUP_SERVICE(_alias,_label,_shape,_color) ENTITY(_shape,_color,response_group_service,_label,_alias,OFF RESPONSE_GROUP_SERVICE)
skinparam folderBackgroundColor<<OFF RESPONSE_GROUP_SERVICE>> White