sprite $skype_for_business_storage_service [46x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000FFFFF
FFFFFFFFFFFFFFFF00FFFFFFFFFFFF0015763430000FFF
FFFFFFFFF0000000000000000FFFF002710143476000FF
FFFFFFF00000357899986300000FF0061000000027100F
FFFFF00019AAAAAAAAAAAAAAA30000070004888401700F
FFFF000AAAAAAAAAAAAAAAAAAAA2000700184047204300
FFFF009AAAAAAAAAAAAAAAAAAAAA000610283002001600
FFFF007AAAAAAAAAAAAAAAAAAAA9000600078863000700
FFFF0005AAAAAAAAAAAAAAAAAA60000500002478400700
FFFF00400369AAAAAAAAAAA74002000430250007700700
FFFF00A95000011222221000049A000070286368200520
FFFF00AAAAA964210012369AAAAA000055016862000520
FFFF00AAAAAAAAAAAAAAAAAAAAAA00F007600000000700
FFFF00AAAAAAAAAAAAAAAAAAAAAA00FF00377673027300
FFFF00AAAAAAAAAAAAAAAAAAAAAA00FFF000011465100F
FFFF00AAAAAAAAAAAAAAAAAAAAAA00FFFF0000000000FF
FFFF00AAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFF000FFFF
FFFF00AAAAAAAAAAAAAAAAAAA86A00000FFFFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAAA610010000000FFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAA803990003A700FFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAA70AAA0008AA30FFFFFFFFFFF
FFFF00AAAAAAAAAAAAAAAAA07AAAAAAAA00000FFFFFFFF
FFFF00AAAAAAAAAAAAA700206AAAAAAAA000000FFFFFFF
FFFF00AAAAAAAAAAAAA04305AA95347AA902600FFFFFFF
FFFF00AAAAAAAAAAAA70AAAAA6000002AAAAA400FFFFFF
FFFF00AAAAAAAAAAAA34AAAA800000001AAAA900FFFFFF
FFFF00AAAAAAAAAAAA703AAA2000000009AA5100FFFFFF
FFFF00AAAAAAAAAAAAA901AA0000000005A8000FFFFFFF
FFFF00AAAAAAAAAAAAAA41AA0000000004A800FFFFFFFF
FFFF00AAAAAAAAAAAA9003AA1000000008A90000FFFFFF
FFFF008AAAAAAAAAAA31AAAA600000000AAAA800FFFFFF
FFFFF009AAAAAAAAAA50AAAAA30000008AAAA700FFFFFF
FFFFF00049AAAAAAAAA08948AA620039AA34820FFFFFFF
FFFFFF0000135799AAA300008AAAAAAAA300000FFFFFFF
FFFFFFFF00000000000000003AAAAAAAA00000FFFFFFFF
FFFFFFFFFFF00000000000008AA3108AA20FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF008AA0004AA20FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF000010F001000FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF0000FF000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_SKYPE_FOR_BUSINESS_STORAGE_SERVICE(_alias) ENTITY(rectangle,black,skype_for_business_storage_service,_alias,OFF SKYPE_FOR_BUSINESS_STORAGE_SERVICE)
!define OFF_SKYPE_FOR_BUSINESS_STORAGE_SERVICE(_alias,_label) ENTITY(rectangle,black,skype_for_business_storage_service,_label,_alias,OFF SKYPE_FOR_BUSINESS_STORAGE_SERVICE)
!define OFF_SKYPE_FOR_BUSINESS_STORAGE_SERVICE(_alias,_label,_shape) ENTITY(_shape,black,skype_for_business_storage_service,_label,_alias,OFF SKYPE_FOR_BUSINESS_STORAGE_SERVICE)
!define OFF_SKYPE_FOR_BUSINESS_STORAGE_SERVICE(_alias,_label,_shape,_color) ENTITY(_shape,_color,skype_for_business_storage_service,_label,_alias,OFF SKYPE_FOR_BUSINESS_STORAGE_SERVICE)
skinparam folderBackgroundColor<<OFF SKYPE_FOR_BUSINESS_STORAGE_SERVICE>> White