sprite $user_services [48x47/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF000000000FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00012431000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0018AAAAA9100FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF002AAAAAAAAA300FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF001AAAAAAAAAAA200FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF008AAAAAAAAAAAA00FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF02AAAAAAAAAAAAA30FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF006AAAAAAAAAAAAA800FFFFFFFFFFFFFFFFF
FFFFFFFFFFFF008AAAAAAAAAAAAA900FFFFFFFFFFFFFFFFF
FFFFFFFFFFFF008AAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFFFFFFFFF008AAAAAAAAAAAAAA00FFFFFFFFFFFFFFFFF
FFFFFFFFFFFF006AAAAAAAAAAAAA900FFFFFFFFFFFFFFFFF
FFFFFFFFFFFF003AAAAAAAAAAAAA500FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF009AAAAAAAAAAAA00FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF003AAAAAAAAAAA500FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF006AAAAAAAAA800FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0004AAAAAAA6000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF0000000049A9500000000FFFFFFFFFFFFFFFF
FFFFFFFFFF00016100000000000053000FFFFFFFFFFFFFFF
FFFFFFFF00019AAA40000000000AAAA2000FF00FFFFFFFFF
FFFFFFF0007AAAAAAA30000019AAAA500000000000FFFFFF
FFFFFFF008AAAAAAAAAAAAAAAAAAA302A50002A4000FFFFF
FFFFFF003AAAAAAAAAAAAAAAAAAAA03AA90007AA600FFFFF
FFFFFF009AAAAAAAAAAAAAAAAAAAA40AAA898AAA20F0FFFF
FFFFFF01AAAAAAAAAAAAAAAAAA305408AAAAAAAA000000FF
FFFFF002AAAAAAAAAAAAAAAAA502005AAA888AAA700100FF
FFFFF004AAAAAAAAAAAAAAAAA03AA6AA7000006AA79A700F
FFFFF006AAAAAAAAAAAAAAAA90AAAAA700000005AAAAA00F
FFFFF009AAAAAAAAAAAAAAAA9069AAA0000000009AAA800F
FFFFF00AAAAAAAAAAAAAAAAAA3008A80000000005AA1000F
FFFFF00AAAAAAAAAAAAAAAAAAA908A70000000003AA00FFF
FFFFF01AAAAAAAAAAAAAAAAAA7208A80000000004AA0000F
FFFF001AAAAAAAAAAAAAAAAAA027AA90000000007AA7300F
FFFF002AAAAAAAAAAAAAAAAA80AAAAA500000002AAAAA10F
FFFF00022222222222222222205AAAAA40000029AAAAA00F
FFFF000000000000000000000007209AA85347AAA103200F
FFFFFFFFFFFFFFFFFFFFFFFFF0000008AAAAAAAA100000FF
FFFFFFFFFFFFFFFFFFFFFFFFFF000008AAAAAAAA10F00FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF001AAA0008AA600FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF007A70003A9200FFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000F000000FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000F00000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_USER_SERVICES(_alias) ENTITY(rectangle,black,user_services,_alias,OFF USER_SERVICES)
!define OFF_USER_SERVICES(_alias,_label) ENTITY(rectangle,black,user_services,_label,_alias,OFF USER_SERVICES)
!define OFF_USER_SERVICES(_alias,_label,_shape) ENTITY(_shape,black,user_services,_label,_alias,OFF USER_SERVICES)
!define OFF_USER_SERVICES(_alias,_label,_shape,_color) ENTITY(_shape,_color,user_services,_label,_alias,OFF USER_SERVICES)
skinparam folderBackgroundColor<<OFF USER_SERVICES>> White