sprite $verification_service [48x47/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF0000000FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF0002AA8000FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0005AAAAA000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF0007AAAAAAA1000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF00009AAAAAAAAA3000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFF0002AAAAAAAAAAAA80000FFFFFFFFFFFFFFFF
FFFFFFFFF00006AAAAAAAAAAAAAAA20000FFFFFFFFFFFFFF
FFFFFFF00004AAAAAAAAAAAAAAAAAA920000FFFFFFFFFFFF
FFFFFF0015AAAAAAAAAAAAAAAAAAAAAA93000FFFFFFFFFFF
FFFFF005AAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAA60FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAAA71AAAAAAA80FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA9001AAAAAA60FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAAA000AAAAAAA40FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAAA2008AAAAAAA10FFFFFFFFFFF
FFFFF00AAAAAAAAAAAAAAAA6005AAAAAAAA00FFFFFFFFFFF
FFFFFF06AAAAAAA69AAAAA9002AAAAAAAAA00FFFFFFFFFFF
FFFFFF01AAAAAA5009AAAA000AAAAAAAAAA00FFFFFFFFFFF
FFFFFF00AAAAAA7000AAA2009AAAAAAAAA60FFFFFFFFFFFF
FFFFFF00AAAAAAA6000A5006AAAAAA6218000000FFFFFFFF
FFFFFFF04AAAAAAA5001003AAAAA8002100004000FFFFFFF
FFFFFFF00AAAAAAAA30001AAAAAA019A90002AA600FFFFFF
FFFFFFF009AAAAAAAA200AAAAAAA00AAA1219AA800FFFFFF
FFFFFFFF01AAAAAAAAA18AAAAA7A70AAAAAAAAA00F00FFFF
FFFFFFFF009AAAAAAAAAAAAA900000AAAAAAAAA400000FFF
FFFFFFFFF01AAAAAAAAAAAAA10820AAA73225AAA406700FF
FFFFFFFFF007AAAAAAAAAAAA07AAAAA30000008AAAAA00FF
FFFFFFFFFF00AAAAAAAAAAA80AAAAA4000FF000AAAAA40FF
FFFFFFFFFF002AAAAAAAAAAA016AAA00FFFFF004AAA400FF
FFFFFFFFFFF005AAAAAAAAAA8209A900FFFFFF00AA0000FF
FFFFFFFFFFFF008AAAAAAAAAAA09A80FFFFFFF00AA00FFFF
FFFFFFFFFFFF0009AAAAAAAA2009AA00FFFFFF00AA0000FF
FFFFFFFFFFFFF0009AAAAAA906AAAA00FFFFF008AAA810FF
FFFFFFFFFFFFFF0008AAAAA90AAAAA9000F0001AAAAA30FF
FFFFFFFFFFFFFFF0005AAAAA04AA8AA9000004AAA7AA00FF
FFFFFFFFFFFFFFFF00017840003006AAA9889AAA00010FFF
FFFFFFFFFFFFFFFFFF0000000000006AAAAAAAA000000FFF
FFFFFFFFFFFFFFFFFFF0000FFF0F00AAA9A9AAA40FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF01AAA0006AAA0FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF003A80000A700FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF000000F000000FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FF000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_VERIFICATION_SERVICE(_alias) ENTITY(rectangle,black,verification_service,_alias,OFF VERIFICATION_SERVICE)
!define OFF_VERIFICATION_SERVICE(_alias,_label) ENTITY(rectangle,black,verification_service,_label,_alias,OFF VERIFICATION_SERVICE)
!define OFF_VERIFICATION_SERVICE(_alias,_label,_shape) ENTITY(_shape,black,verification_service,_label,_alias,OFF VERIFICATION_SERVICE)
!define OFF_VERIFICATION_SERVICE(_alias,_label,_shape,_color) ENTITY(_shape,_color,verification_service,_label,_alias,OFF VERIFICATION_SERVICE)
skinparam folderBackgroundColor<<OFF VERIFICATION_SERVICE>> White