sprite $word_automation_services [48x41/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00000FFFFF0000000FFFFFFFFF
FFFFFFFFFFFFF0000FFFF006400000000000410000000FFF
FFFFFFFFFFFF000100FFF00AAA901258CCCCC311111000FF
FFFFFFFFFF00029A600F004AAA909CCCCCCCC877777920FF
FFFFFFFFFF006AAAA200008AAA909CCCCCCCC533331430FF
FFFFFFFFFF007AAAAA2688AAAA909CCCCCCCC533331430FF
FFFFFFFFFF001AAAAAAAAAAAAA909B7C2C1BC655552430FF
FFFFFFFFFFF005AAAAAAAAAAAA909C0B0B1CC300000430FF
FFFFFFFFFFF002AAAAAA9889AA909C16162CC877773430FF
FFFFFF0000000AAAAA40000005909C20816CC300000430FF
FFFFFF0000008AAA8000000000009C51C0BCC999994430FF
FFFFF008A977AAA9000FFFFFF0009CBBCACCC200000430FF
FFFFF00AAAAAAAA000FFFFFFFF009CCCCCCCCBBBBB5430FF
FFFFF00AAAAAAA600FFFFFFFFF009CCCCCCCC200000430FF
FFFFF04AAAAAAA20FFFFFFFFFF008CCCCCCCCAAAAAAA10FF
FFFFF0057AAAAA00FFFFFFFFFF00001468ABC200000000FF
FFFFF000005AAA00FFFFFFFFFF0001420000100000000FFF
FFFFFFF0003AAA10FFFFFFFFFFFF03AAA987400FFFFFFFFF
FFFFFFFFF02AAA20FFFFFFFFFFF006AAAAAAA10FFFFFFFFF
FFFFFFFF000AAA700FFFFFFFFFF009AAAAAAA00FFFFFFFFF
FFFFFFF0003AAAA100FFFFFFFF004AAAAAAA700FFFFFFFFF
FFFFFF0018AAAAAA000FFFFFF002AAAA368A300FFFFFFFFF
FFFFFF00AAAAAAAAA1000000003AAAA3000000FFFFFFFFFF
FFFFFF008AAAAAAAAA71000028AAAA60000000FFFFFFFFFF
FFFFFFF00AAAA19AAAAAAAAAAAAAA900FFFFFFFFFFFFFFFF
FFFFFFF003A50007AAAAAAAAAAAAAA200FFFFFFFFFFFFFFF
FFFFFFFF000000002AAAAAAAAAAAAAA00FFFFFFFFFFFFFFF
FFFFFFFFF000FFF00AAAA96631AAAAA40FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF03AAAA300003AAA910FFFFFFFFFFFFFFF
FFFFFFFFFFFFFF009AAAA100F008A5000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFF006AAAA00FFF000000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF00003200FFFF000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_WORD_AUTOMATION_SERVICES(_alias) ENTITY(rectangle,black,word_automation_services,_alias,OFF WORD_AUTOMATION_SERVICES)
!define OFF_WORD_AUTOMATION_SERVICES(_alias,_label) ENTITY(rectangle,black,word_automation_services,_label,_alias,OFF WORD_AUTOMATION_SERVICES)
!define OFF_WORD_AUTOMATION_SERVICES(_alias,_label,_shape) ENTITY(_shape,black,word_automation_services,_label,_alias,OFF WORD_AUTOMATION_SERVICES)
!define OFF_WORD_AUTOMATION_SERVICES(_alias,_label,_shape,_color) ENTITY(_shape,_color,word_automation_services,_label,_alias,OFF WORD_AUTOMATION_SERVICES)
skinparam folderBackgroundColor<<OFF WORD_AUTOMATION_SERVICES>> White