sprite $azure [48x34/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF000000000FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF000013420000FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF0005BBBBBB8100FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF001ABA8558ABA300FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF0000AB80000006AB2000000FFFFFFFFFFFFFFFF
FFFFFFF000006B80000000045001000000FFFFFFFFFFFFFF
FFFFFF000268BA000000000038BBBA72000FFFFFFFFFFFFF
FFFFF002ABBBB80000000029BBBBBBBB8000FFFFFFFFFFFF
FFFF002BA8322100000003ABBBBBBBBBBA100FFFFFFFFFFF
FFFF00AA4000000000002ABBBBBBBBBBBB900000FFFFFFFF
FFF003B80000000000008BBBBBBBBBBBBBB5200000FFFFFF
FFF008B1000000000002BBBBBBBBBBBBBBBBBB82000FFFFF
FFF00AA0000000000027BBBBBBBBBBBBBBBBBBBB5000FFFF
FFF009B10000000039BBBBBBBBBBBBBBBBBBBBBBB400FFFF
FFF004B700000006BBBBBBBBB93014ABBBBBBBBBBB100FFF
FFFF00AA30000014444444444015401ABBBBBBBBBB800FFF
FFFF003BA62100000000000002ABB806BBBBBBBBBBB00FFF
FFFFF004ABBBBBBBBBBBBBBBBBBBBB23BBBBBBBBBBB00FFF
FFFFF0001589AAAAAAAAAAAAAABBBB23BBBBBBBBBBB10FFF
FFFFFFF00000000000000000008BB607BBBBBBBBBBB00FFF
FFFFFFFFF0000488888888888102103ABBBBBBBBBBB00FFF
FFFFFFFFFFF002BBBBBBBBBBBA6337ABBBBBBBBBBB500FFF
FFFFFFFFFFFF00ABBBBBBBBBBBBBBBBBBBBBBBBBBA000FFF
FFFFFFFFFFFF003BBBBBBBBBBBBBBBBBBBBBBBBBB200FFFF
FFFFFFFFFFFFF004BBBBBBBBBBBBBBBBBBBBBBBA200FFFFF
FFFFFFFFFFFFF00018BBBBBBBBBBBBBBBBBBBA50000FFFFF
FFFFFFFFFFFFFF000001111111111111111100000FFFFFFF
FFFFFFFFFFFFFFFF000000000000000000000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_AZURE(_alias) ENTITY(rectangle,black,azure,_alias,OFF AZURE)
!define OFF_AZURE(_alias,_label) ENTITY(rectangle,black,azure,_label,_alias,OFF AZURE)
!define OFF_AZURE(_alias,_label,_shape) ENTITY(_shape,black,azure,_label,_alias,OFF AZURE)
!define OFF_AZURE(_alias,_label,_shape,_color) ENTITY(_shape,_color,azure,_label,_alias,OFF AZURE)
skinparam folderBackgroundColor<<OFF AZURE>> White