sprite $private_cloud [48x33/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF000000000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF000147863000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF0005AAAAAA81000000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF006AAAAAAAAA10000000FFFFFFFFFFF
FFFFFFFFFFFFFFFF003AAAAAAAAAA9367740000FFFFFFFFF
FFFFFFFFFFFFFFFF009AAAAAAAAAAAAAAAAA400FFFFFFFFF
FFFFFFFFFFFFFF0001AAAAAAAAAAAAAAAAAAA500FFFFFFFF
FFFFFFFFFFFF000013AAAAAAAAAAAAAAAAAAAA100FFFFFFF
FFFFFFFFFF00008AAAAAAAAAAAAAAAAAAAAAAA800FFFFFFF
FFFFFFFF00001AAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFFFF
FFFFFFF0008AAAAAAAAAAAAAAAAAAAAAAAAAAAA10FFFFFFF
FFFFFF004AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA100FFFFFF
FFFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA100FFFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFFF
FFFF001AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA500FFFF
FFFF005AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF005AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFF003AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00FFFF
FFFFF00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA800FFFF
FFFFF007AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA200FFFF
FFFFF0008AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA600FFFFF
FFFFFF0005AAAAAAAAAAAAAAAAAAAAAAAAAAAAA4000FFFFF
FFFFFFF00002222222222222222222222222220000FFFFFF
FFFFFFFFF0000000000000000000000000000000FFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define OFF_PRIVATE_CLOUD(_alias) ENTITY(rectangle,black,private_cloud,_alias,OFF PRIVATE_CLOUD)
!define OFF_PRIVATE_CLOUD(_alias,_label) ENTITY(rectangle,black,private_cloud,_label,_alias,OFF PRIVATE_CLOUD)
!define OFF_PRIVATE_CLOUD(_alias,_label,_shape) ENTITY(_shape,black,private_cloud,_label,_alias,OFF PRIVATE_CLOUD)
!define OFF_PRIVATE_CLOUD(_alias,_label,_shape,_color) ENTITY(_shape,_color,private_cloud,_label,_alias,OFF PRIVATE_CLOUD)
skinparam folderBackgroundColor<<OFF PRIVATE_CLOUD>> White